// 国会で審議中の議題・法案データ
// 2026年4月時点（第221回特別国会）
// ソース: clb.go.jp, sangiin.go.jp, shugiin.go.jp

export type DebateStatus = "審議中" | "可決" | "否決" | "継続審議";

export interface Debate {
  slug: string;
  title: string;
  titleEn: string;
  committee: string;
  committeeEn?: string;
  status: DebateStatus;
  statusColor: string;
  impact: string;
  impactEn?: string;
  summary: string;
  summaryEn?: string;
  detail: string;
  detailEn?: string;
  keyPoints: string[];
  keyPointsEn?: string[];
  parties: { name: string; nameEn?: string; position: string; positionEn?: string }[];
  timeline: { date: string; event: string; eventEn?: string }[];
  lastUpdated: string;
}

// Shared English lookups for repetitive strings.
export const STATUS_EN: Record<DebateStatus, string> = {
  審議中: "Under Deliberation",
  可決: "Passed",
  否決: "Rejected",
  継続審議: "Carried Over",
};

export const COMMITTEE_EN: Record<string, string> = {
  予算委員会: "Budget Committee",
  財務金融委員会: "Finance and Financial Affairs Committee",
  内閣委員会: "Cabinet Committee",
  経済産業委員会: "Economy, Trade and Industry Committee",
  国土交通委員会: "Land, Infrastructure, Transport and Tourism Committee",
  環境委員会: "Environment Committee",
  安全保障委員会: "Security Committee",
  法務委員会: "Judicial Affairs Committee",
  外務委員会: "Foreign Affairs Committee",
  厚生労働委員会: "Health, Labour and Welfare Committee",
  農林水産委員会: "Agriculture, Forestry and Fisheries Committee",
  総務委員会: "General Affairs Committee",
  地方創生特別委員会: "Special Committee on Regional Revitalization",
  文部科学委員会: "Education, Culture, Sports, Science and Technology Committee",
  "政治倫理・選挙制度特別委員会": "Special Committee on Political Ethics and Election Law",
  災害対策特別委員会: "Special Committee on Disaster Countermeasures",
  財政金融委員会: "Financial Affairs Committee",
};

export const PARTY_EN: Record<string, string> = {
  自由民主党: "Liberal Democratic Party",
  日本維新の会: "Japan Innovation Party",
  中道改革連合: "Centrist Reform Coalition",
  国民民主党: "Democratic Party for the People",
  日本共産党: "Japanese Communist Party",
};

export function getCommitteeEn(ja: string): string {
  return COMMITTEE_EN[ja] ?? ja;
}

export function getPartyNameEn(ja: string): string {
  return PARTY_EN[ja] ?? ja;
}

export function getStatusEn(ja: DebateStatus): string {
  return STATUS_EN[ja] ?? ja;
}

export const debates: Debate[] = [
  // ──────────────────────────────────────────
  // 予算案
  // ──────────────────────────────────────────
  {
    slug: "budget-fy2026",
    title: "令和8年度予算案",
    titleEn: "FY2026 Budget",
    committee: "予算委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "国民生活に直結する年間122.3兆円の支出計画。防衛・社会保障・教育の優先順位が決まる。",
    impactEn: "A 122.3 trillion yen annual spending plan that directly affects daily life. Sets priorities for defense, social security and education.",
    summary: "一般会計総額122.3兆円の過去最大規模の予算案。暫定予算で4月1日〜11日を手当てし、本予算は4月11日に自然成立の見込み。",
    summaryEn: "A record 122.3 trillion yen general account budget. An interim budget covers April 1-11, and the main budget is expected to take effect automatically on April 11.",
    detail: "令和8年度（2026年度）予算案は、一般会計総額122兆3,000億円と2年連続で過去最大を更新。防衛費は8.5兆円規模、少子化対策やデジタル投資も重点配分。1月23日に衆議院が解散され、2月8日の総選挙を経て第221回特別国会が2月18日に召集。2月20日に予算案が国会に提出され、3月13日に衆議院を通過。参議院での議決が年度内に間に合わず、4月1日〜11日の暫定予算が3月30日に成立。憲法の30日ルールにより4月11日に本予算が自然成立の見込み。",
    detailEn: "The FY2026 budget totals 122.3 trillion yen in the general account, a record for the second consecutive year. Defense spending is around 8.5 trillion yen, with priority allocations for child-rearing measures and digital investment. After the House of Representatives was dissolved on January 23 and the February 8 general election, the 221st Extraordinary Diet convened on February 18. The budget was submitted on February 20 and passed the Lower House on March 13. With the Upper House unable to vote before the fiscal year began, a stopgap budget covering April 1-11 was enacted on March 30. Under the Constitution's 30-day rule, the main budget is expected to take effect automatically on April 11.",
    keyPoints: [
      "一般会計総額122.3兆円（2年連続過去最大）",
      "防衛費8.5兆円（GDP比2%目標に向けた増額）",
      "暫定予算（4月1日〜11日）が3月30日に成立",
      "4月11日に本予算が自然成立の見込み（30日ルール）",
      "衆院での審議時間は約59時間（過去20年で最短）",
    ],
    keyPointsEn: [
      "General account total of 122.3 trillion yen (record high for second straight year)",
      "Defense spending of 8.5 trillion yen (increase toward the 2% of GDP target)",
      "Stopgap budget (April 1-11) enacted on March 30",
      "Main budget expected to pass automatically on April 11 (30-day rule)",
      "Lower House deliberations totaled about 59 hours (shortest in 20 years)",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（与党として提出）", positionEn: "In favor (submitted as ruling party)" },
      { name: "日本維新の会", position: "条件付き賛成（連立パートナーとして協力）", positionEn: "Conditional support (cooperating as coalition partner)" },
      { name: "中道改革連合", position: "反対（防衛費財源の不透明さを批判）", positionEn: "Opposed (criticizes opacity of defense funding sources)" },
      { name: "国民民主党", position: "修正要求（教育予算の増額を主張）", positionEn: "Demands amendments (calls for increased education budget)" },
      { name: "日本共産党", position: "反対（防衛費増と社会保障費圧縮を批判）", positionEn: "Opposed (criticizes defense increases and social security cuts)" },
    ],
    timeline: [
      { date: "2026-01-23", event: "第220回通常国会召集、即日衆議院解散", eventEn: "220th Ordinary Diet convened; House of Representatives dissolved the same day" },
      { date: "2026-02-08", event: "第51回衆議院総選挙", eventEn: "51st House of Representatives general election" },
      { date: "2026-02-18", event: "第221回特別国会召集", eventEn: "221st Extraordinary Diet convened" },
      { date: "2026-02-20", event: "予算案を国会に提出", eventEn: "Budget submitted to the Diet" },
      { date: "2026-03-13", event: "衆議院本会議で可決、参議院に送付", eventEn: "Passed House of Representatives plenary and sent to House of Councillors" },
      { date: "2026-03-30", event: "暫定予算（4/1〜4/11）が成立", eventEn: "Stopgap budget (April 1-11) enacted" },
      { date: "2026-04-05", event: "参議院予算委でトランプ関税の経済影響を緊急質疑", eventEn: "Emergency questioning on economic impact of Trump tariffs at Upper House Budget Committee" },
    ],
    lastUpdated: "2026-04-06",
  },

  // ──────────────────────────────────────────
  // 閣法（内閣提出法律案）— 審議中
  // ──────────────────────────────────────────
  {
    slug: "financial-function-strengthening",
    title: "金融機能強化特別措置法等改正案",
    titleEn: "Financial Function Strengthening Act Amendment",
    committee: "財務金融委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "地域金融機関の経営基盤強化に関わり、地方経済に影響。",
    impactEn: "Concerns the financial foundation of regional financial institutions and affects local economies.",
    summary: "金融機関の経営基盤強化のための公的資金注入制度の延長・拡充を盛り込んだ改正案。",
    summaryEn: "An amendment extending and expanding the public capital injection scheme to strengthen the financial base of financial institutions.",
    detail: "金融機能の強化のための特別措置に関する法律等の一部を改正する法律案。地域金融機関の経営統合や資本増強を支援する公的資金注入スキームの期限延長・適用要件の見直しを行う。地方銀行の経営環境悪化やマイナス金利解除後の金融再編を見据えた制度整備。",
    detailEn: "A bill amending the Act on Special Measures for Strengthening Financial Functions and related laws. It extends the deadline and revises the eligibility criteria for the public capital injection scheme that supports regional financial institutions' consolidation and capital reinforcement. The reform anticipates deteriorating conditions for regional banks and financial restructuring following the exit from negative interest rates.",
    keyPoints: [
      "公的資金注入制度の期限延長",
      "地域金融機関の経営統合支援の拡充",
      "金融機関の資本増強手続きの簡素化",
      "金融システムの安定性確保",
    ],
    keyPointsEn: [
      "Extension of the public capital injection scheme",
      "Expanded support for consolidation among regional financial institutions",
      "Simplified procedures for capital reinforcement at financial institutions",
      "Ensuring the stability of the financial system",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）", positionEn: "In favor (cabinet-submitted bill)" },
      { name: "日本維新の会", position: "賛成（金融安定化を支持）", positionEn: "In favor (supports financial stability)" },
      { name: "中道改革連合", position: "条件付き賛成（モラルハザード防止を要求）", positionEn: "Conditional support (demands moral hazard prevention)" },
      { name: "国民民主党", position: "賛成", positionEn: "In favor" },
      { name: "日本共産党", position: "反対（公的資金による救済に批判的）", positionEn: "Opposed (critical of public funds bailouts)" },
    ],
    timeline: [
      { date: "2026-02-20", event: "法案を閣議決定・国会提出", eventEn: "Bill approved by Cabinet and submitted to the Diet" },
      { date: "2026-03-25", event: "財務金融委員会で審議開始", eventEn: "Deliberations begin in Finance and Financial Affairs Committee" },
    ],
    lastUpdated: "2026-04-06",
  },
  {
    slug: "disaster-prevention-agency",
    title: "防災庁設置法案",
    titleEn: "Disaster Prevention Agency Establishment",
    committee: "内閣委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "南海トラフ・首都直下地震に備え、3,000万人以上の被災想定地域に影響。",
    impactEn: "Addresses preparations for Nankai Trough and Tokyo inland earthquakes, affecting projected disaster zones with over 30 million residents.",
    summary: "内閣府防災担当を発展させ、独立した「防災庁」を新設する法案。2026年秋の発足を目指す。",
    summaryEn: "A bill elevating the Cabinet Office's disaster management unit into a standalone Disaster Prevention Agency, targeted to launch in autumn 2026.",
    detail: "南海トラフ地震や首都直下地震への備えを強化するため、現在の内閣府防災担当を独立した「防災庁」に格上げする法案。防災庁長官に他省庁への勧告権限を付与し、災害対応の司令塔機能を強化。平時から災害に備えた体制を構築するとともに、被災者支援や復旧・復興の一元的な管理を行う。能登半島地震（2024年1月）の教訓を踏まえ、初動対応の迅速化と自治体支援の強化も盛り込む。",
    detailEn: "To strengthen preparedness for a Nankai Trough or Tokyo inland earthquake, the bill upgrades the Cabinet Office's disaster management section into a standalone Disaster Prevention Agency. The agency's director would gain authority to issue recommendations to other ministries, reinforcing the command role during disasters. A permanent readiness structure and unified management of victim support, recovery and reconstruction are also included. Drawing on lessons from the January 2024 Noto Peninsula earthquake, faster initial response and enhanced municipal support are also part of the bill.",
    keyPoints: [
      "内閣府防災担当を「防災庁」に格上げ",
      "防災庁長官に他省庁への勧告権限を付与",
      "平時からの防災体制の常設化",
      "被災者支援・復旧復興の一元管理",
      "2026年秋の発足を目指す",
    ],
    keyPointsEn: [
      "Upgrade Cabinet Office disaster management into a Disaster Prevention Agency",
      "Grant the agency head authority to issue recommendations to other ministries",
      "Establish a permanent peacetime disaster preparedness structure",
      "Centralized management of victim support, recovery and reconstruction",
      "Target launch in autumn 2026",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）", positionEn: "In favor (cabinet-submitted bill)" },
      { name: "日本維新の会", position: "賛成（防災体制の強化を支持）", positionEn: "In favor (supports strengthening disaster preparedness)" },
      { name: "中道改革連合", position: "賛成（能登半島地震の教訓を重視）", positionEn: "In favor (emphasizes lessons from the Noto Peninsula earthquake)" },
      { name: "国民民主党", position: "賛成（地方自治体支援の拡充を要望）", positionEn: "In favor (urges expanded support for local governments)" },
      { name: "日本共産党", position: "条件付き賛成（予算の十分な確保を要求）", positionEn: "Conditional support (demands sufficient budget allocation)" },
    ],
    timeline: [
      { date: "2025-12-26", event: "防災庁設置の基本方針を閣議決定", eventEn: "Cabinet approved the basic policy to establish the Disaster Prevention Agency" },
      { date: "2026-03-06", event: "設置法案・関連法案を閣議決定・国会提出", eventEn: "Establishment bill and related bills approved by Cabinet and submitted to the Diet" },
      { date: "2026-03-20", event: "衆議院内閣委員会で審議開始", eventEn: "Deliberations begin in the House of Representatives Cabinet Committee" },
    ],
    lastUpdated: "2026-04-06",
  },
  {
    slug: "disaster-prevention-agency-related",
    title: "防災庁設置法施行関連法整備案",
    titleEn: "Disaster Prevention Agency Related Laws Amendment",
    committee: "内閣委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "防災庁設置に伴い関連する既存法律の整備。災害対策基本法など多数の法律に影響。",
    impactEn: "Harmonizes existing laws to accompany the establishment of the Disaster Prevention Agency, affecting the Disaster Countermeasures Basic Act and many others.",
    summary: "防災庁設置法の施行に伴い、災害対策基本法等の関連法律を一括整備する法案。",
    summaryEn: "A bill comprehensively updating related laws, including the Disaster Countermeasures Basic Act, in conjunction with the Disaster Prevention Agency Establishment Act.",
    detail: "防災庁設置法の施行に伴う関係法律の整備等に関する法律案。防災庁の新設に合わせ、災害対策基本法、災害救助法、被災者生活再建支援法等の関連法律における「内閣府防災担当」の規定を「防災庁」に改めるとともに、防災庁長官の権限・所掌事務に関する規定を整備する。",
    detailEn: "A bill adjusting related laws in step with the enforcement of the Disaster Prevention Agency Establishment Act. References to the Cabinet Office disaster management unit in the Disaster Countermeasures Basic Act, Disaster Relief Act, Act on Support for Reconstructing Livelihoods of Disaster Victims and other laws are changed to the Disaster Prevention Agency, and provisions on the agency head's authority and responsibilities are added.",
    keyPoints: [
      "災害対策基本法等の関連法律における所管変更",
      "防災庁長官の権限に関する規定の整備",
      "防災庁設置法と一体で審議",
    ],
    keyPointsEn: [
      "Change of jurisdiction in the Disaster Countermeasures Basic Act and related laws",
      "Provisions on the powers of the Disaster Prevention Agency head",
      "Deliberated jointly with the Disaster Prevention Agency Establishment Act",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）", positionEn: "In favor (cabinet-submitted bill)" },
      { name: "日本維新の会", position: "賛成", positionEn: "In favor" },
      { name: "中道改革連合", position: "賛成", positionEn: "In favor" },
      { name: "国民民主党", position: "賛成", positionEn: "In favor" },
      { name: "日本共産党", position: "条件付き賛成", positionEn: "Conditional support" },
    ],
    timeline: [
      { date: "2026-03-06", event: "防災庁設置法案と同時に国会提出", eventEn: "Submitted to the Diet alongside the Disaster Prevention Agency Establishment Act" },
      { date: "2026-03-20", event: "内閣委員会で防災庁設置法案と一括審議開始", eventEn: "Deliberated jointly with the establishment bill in the Cabinet Committee" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "industrial-competitiveness",
    title: "産業競争力強化法等改正案",
    titleEn: "Industrial Competitiveness Enhancement Act Amendment",
    committee: "経済産業委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "スタートアップ支援や事業再編に関わり、産業界全体に影響。",
    summary: "経済社会情勢の変化を踏まえ、企業の事業活動の持続的発展を図るための産業競争力強化法等の改正案。",
    detail: "産業競争力強化法、中小企業等経営強化法等を一括改正し、スタートアップの創出支援、事業再編の促進、中小企業のDX推進支援を強化する。GX（グリーントランスフォーメーション）投資の加速に向けた規制緩和措置も盛り込む。",
    keyPoints: [
      "スタートアップ創出支援の拡充",
      "事業再編・M&Aの手続き簡素化",
      "中小企業のDX推進支援",
      "GX投資に向けた規制緩和",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成（産業競争力強化を支持）" },
      { name: "中道改革連合", position: "条件付き賛成（中小企業保護を重視）" },
      { name: "国民民主党", position: "賛成（労働者の処遇改善を併せて要望）" },
      { name: "日本共産党", position: "反対（大企業優遇を批判）" },
    ],
    timeline: [
      { date: "2026-03-06", event: "法案を閣議決定・国会提出" },
      { date: "2026-03-28", event: "経済産業委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "logistics-efficiency",
    title: "物資流通効率化法改正案",
    titleEn: "Logistics Efficiency Act Amendment",
    committee: "国土交通委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "物流業界全体と消費者に影響。2024年問題への追加対応。",
    summary: "物流の2024年問題への追加対策として、物資の流通効率化を推進するための法改正案。",
    detail: "トラックドライバーの時間外労働規制強化（2024年問題）への追加対応として、物流の効率化を一層推進する改正案。共同配送の促進、中継物流拠点の整備支援、荷主への規制強化（荷待ち時間の制限等）を盛り込む。",
    keyPoints: [
      "共同配送・モーダルシフトの促進",
      "中継物流拠点の整備支援",
      "荷主企業への規制強化",
      "物流DXの推進",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成" },
      { name: "中道改革連合", position: "賛成（ドライバーの処遇改善を重視）" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "条件付き賛成（ドライバーの労働環境改善を要求）" },
    ],
    timeline: [
      { date: "2026-03-06", event: "法案を閣議決定・国会提出" },
      { date: "2026-04-01", event: "国土交通委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "environment-ministry-reform",
    title: "環境省設置法改正案",
    titleEn: "Ministry of Environment Reform Act",
    committee: "環境委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "環境行政の体制変更。GX推進に向けた組織再編。",
    summary: "GX推進や脱炭素政策の強化に対応するため、環境省の組織体制を見直す設置法改正案。",
    detail: "環境省の組織体制を見直し、GX（グリーントランスフォーメーション）推進部門の新設や、気候変動適応策を担う部局の強化を行う。脱炭素社会の実現に向けた政策立案・実施体制の整備を図る。",
    keyPoints: [
      "GX推進部門の新設",
      "気候変動適応策の体制強化",
      "脱炭素社会実現に向けた組織再編",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成" },
      { name: "中道改革連合", position: "賛成（脱炭素政策の加速を支持）" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "条件付き賛成（原発依存からの脱却を要求）" },
    ],
    timeline: [
      { date: "2026-03-06", event: "法案を閣議決定・国会提出" },
      { date: "2026-04-03", event: "環境委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "defense-ministry-reform",
    title: "防衛省設置法等改正案",
    titleEn: "Ministry of Defense Establishment Act Amendment",
    committee: "安全保障委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "自衛隊の組織体制変更。防衛力強化計画に直結。",
    summary: "防衛力の抜本的強化に向けた防衛省・自衛隊の組織改編を含む設置法等の改正案。",
    detail: "2022年に閣議決定された防衛力整備計画に基づき、防衛省・自衛隊の組織体制を改編する法案。統合作戦司令部の新設、サイバー防衛部隊の拡充、宇宙領域を担当する部隊の体制強化などを含む。防衛費のGDP比2%目標に向けた人的基盤の整備も柱の一つ。",
    keyPoints: [
      "統合作戦司令部の体制強化",
      "サイバー防衛部隊の拡充",
      "宇宙領域作戦部隊の新設",
      "防衛装備品の効率的な調達体制の構築",
      "自衛官の定員増と処遇改善",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成（防衛力強化を支持）" },
      { name: "中道改革連合", position: "慎重（文民統制の徹底を要求）" },
      { name: "国民民主党", position: "賛成（現実的な安全保障政策を支持）" },
      { name: "日本共産党", position: "反対（軍拡路線に反対）" },
    ],
    timeline: [
      { date: "2026-03-06", event: "法案を閣議決定・国会提出" },
      { date: "2026-03-25", event: "安全保障委員会で審議開始" },
      { date: "2026-04-03", event: "参考人質疑（安全保障専門家）" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "court-staff-quota",
    title: "裁判所職員定員法改正案",
    titleEn: "Court Staff Quota Act Amendment",
    committee: "法務委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "裁判所の人員体制に関わり、司法アクセスの改善に影響。",
    summary: "裁判所の適正な人員体制を確保するため、判事・判事補・裁判所職員の定員を見直す法案。",
    detail: "民事訴訟のIT化（2026年5月全面施行）や家事事件・少年事件の増加に対応するため、裁判所の人的体制を整備する。判事補の増員や書記官のデジタル対応要員の確保が柱。",
    keyPoints: [
      "判事補の増員",
      "裁判所書記官のIT対応要員の確保",
      "家庭裁判所の体制強化",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成" },
      { name: "中道改革連合", position: "賛成" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "賛成" },
    ],
    timeline: [
      { date: "2026-03-06", event: "法案を閣議決定・国会提出" },
      { date: "2026-03-28", event: "法務委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "immigration-reform",
    title: "出入国管理及び難民認定法等改正案",
    titleEn: "Immigration Control and Refugee Recognition Act Amendment",
    committee: "法務委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "外国人労働者・技能実習生・難民申請者など約330万人の在留外国人に影響。",
    summary: "育成就労制度の本格施行に向けた入管法の改正。外国人材の受け入れ体制整備と在留管理の厳格化を両立。",
    detail: "2024年に成立した技能実習制度廃止・育成就労制度創設に続く追加的な入管法改正。育成就労制度の円滑な実施に向けた在留資格の整理、不法滞在への対応強化、難民認定手続きの迅速化を図る。外国人材の適正な受け入れと共生社会の実現に向けた施策を法的に整備する。",
    keyPoints: [
      "育成就労制度の本格施行に向けた在留資格の整理",
      "不法滞在への対応強化",
      "難民認定手続きの迅速化",
      "外国人の生活支援体制の法的整備",
      "在留カードとマイナンバーカードの一体化推進",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成（外国人材の適正管理を支持）" },
      { name: "中道改革連合", position: "慎重（外国人の人権保護を重視）" },
      { name: "国民民主党", position: "条件付き賛成" },
      { name: "日本共産党", position: "反対（送還規定の人権侵害を懸念）" },
    ],
    timeline: [
      { date: "2026-03-13", event: "法案を閣議決定・国会提出" },
      { date: "2026-04-02", event: "法務委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "passport-reform",
    title: "旅券法改正案",
    titleEn: "Passport Act Amendment",
    committee: "外務委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "パスポートの電子化。海外渡航する全国民に影響。",
    summary: "パスポートの電子申請・更新のオンライン化やICチップ高度化に向けた旅券法の改正案。",
    detail: "旅券（パスポート）の発給手続きの電子化・オンライン化を推進する改正案。マイナンバーカードを活用した本人確認のオンライン化、IC旅券の次世代チップへの移行を規定。海外在留邦人の利便性向上も図る。",
    keyPoints: [
      "パスポート申請のオンライン化",
      "マイナンバーカードを活用した本人確認",
      "IC旅券の次世代チップ移行",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成" },
      { name: "中道改革連合", position: "賛成" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "賛成" },
    ],
    timeline: [
      { date: "2026-03-13", event: "法案を閣議決定・国会提出" },
      { date: "2026-04-01", event: "外務委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "urban-regeneration",
    title: "都市再生特別措置法等改正案",
    titleEn: "Urban Regeneration Special Measures Act Amendment",
    committee: "国土交通委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "都市のコンパクト化・防災まちづくりに影響。地方自治体のまちづくり政策に直結。",
    summary: "人口減少時代の都市再生に向け、立地適正化計画の強化や防災まちづくりの推進を図る改正案。",
    detail: "人口減少・高齢化に対応したコンパクトシティの実現に向け、都市再生特別措置法等を改正。立地適正化計画の実効性強化、災害リスクの高い区域からの居住誘導、空き地・空き家対策の推進を盛り込む。",
    keyPoints: [
      "立地適正化計画の実効性強化",
      "災害リスク区域からの居住誘導",
      "空き地・空き家対策の推進",
      "コンパクトシティの実現支援",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成" },
      { name: "中道改革連合", position: "賛成（居住の自由との調整を要望）" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "条件付き賛成（住民の意見反映を要求）" },
    ],
    timeline: [
      { date: "2026-03-13", event: "法案を閣議決定・国会提出" },
      { date: "2026-04-01", event: "国土交通委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "regional-public-transport",
    title: "地域公共交通活性化法改正案",
    titleEn: "Regional Public Transport Revitalization Act Amendment",
    committee: "国土交通委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "過疎地域のバス・鉄道路線維持に関わり、地方在住者の移動手段に直結。",
    summary: "地方の公共交通路線の維持・再編を支援するための改正案。自治体主導の再編計画を国が財政支援。",
    detail: "人口減少により採算が悪化する地方のバス・鉄道路線の維持・再編を支援する改正案。地方自治体が主導する地域公共交通計画の策定を義務化するとともに、国の財政支援を拡充。AIオンデマンド交通や自動運転バスの導入支援も盛り込む。",
    keyPoints: [
      "地域公共交通計画の策定義務化",
      "国の財政支援の拡充",
      "AIオンデマンド交通の導入支援",
      "自動運転バスの社会実装促進",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成（民間参入の促進を主張）" },
      { name: "中道改革連合", position: "賛成（地方の足の確保を重視）" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "賛成（路線維持の国の責任を強調）" },
    ],
    timeline: [
      { date: "2026-03-13", event: "法案を閣議決定・国会提出" },
      { date: "2026-04-01", event: "国土交通委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "national-intelligence-agency",
    title: "国家情報会議設置法案（国家情報局新設）",
    titleEn: "National Intelligence Agency Establishment",
    committee: "内閣委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "日本初の本格的情報機関の誕生。外交・安全保障の情報収集力が大幅に強化される。",
    summary: "内閣情報調査室を改組し「国家情報局」を新設。首相直属の国家情報会議を設置し、インテリジェンス機能を集約する法案。",
    detail: "現行の内閣情報調査室（CIRO）を発展的に改組し、独立した「国家情報局」を内閣府の外局として新設する法案。首相を議長とする「国家情報会議」を設置し、各省庁に分散するインテリジェンス機能を一元的に統括。外交・安全保障・経済安全保障に関する情報収集・分析能力を抜本的に強化する。2026年7月の発足を目指す。野党の一部は情報機関の権限拡大に対する国会の監視体制の不十分さを指摘している。",
    keyPoints: [
      "内閣情報調査室を「国家情報局」に改組・格上げ",
      "首相直属の「国家情報会議」を新設",
      "各省庁の情報機能を一元的に統括",
      "経済安全保障分野の情報収集を強化",
      "2026年7月の発足を目指す",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成（情報機能の強化を支持）" },
      { name: "国民民主党", position: "賛成（スパイ防止法案も併せて提出）" },
      { name: "中道改革連合", position: "慎重（国会による監視体制の強化を要求）" },
      { name: "日本共産党", position: "反対（情報機関の権限拡大に懸念）" },
    ],
    timeline: [
      { date: "2026-03-13", event: "法案を閣議決定・国会提出" },
      { date: "2026-03-25", event: "衆議院内閣委員会で審議開始" },
      { date: "2026-04-02", event: "参考人質疑（安全保障・情報の専門家）" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "health-insurance-reform",
    title: "健康保険法等改正案",
    titleEn: "Health Insurance Act Amendment",
    committee: "厚生労働委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "医療保険制度の持続性に関わり、全国民に影響。後期高齢者の負担増が焦点。",
    summary: "医療保険制度の持続可能性を確保するため、後期高齢者医療の窓口負担見直しや保険料の適正化を図る改正案。",
    detail: "少子高齢化の進展に伴う医療費の増大に対応するため、健康保険法等を改正。後期高齢者の窓口負担割合の段階的引き上げ、現役世代の保険料負担の軽減、オンライン診療の推進、予防医療への保険適用拡大などを盛り込む。世代間の負担の公平化と医療の質の確保を両立させることが目的。",
    keyPoints: [
      "後期高齢者の窓口負担の段階的見直し",
      "現役世代の保険料負担の軽減",
      "オンライン診療の推進",
      "予防医療への保険適用拡大",
      "医療DX推進基盤の整備",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成（制度の持続可能性を重視）" },
      { name: "中道改革連合", position: "反対（高齢者の負担増に反対）" },
      { name: "国民民主党", position: "条件付き賛成（低所得者への配慮を要求）" },
      { name: "日本共産党", position: "反対（窓口負担増に反対）" },
    ],
    timeline: [
      { date: "2026-03-13", event: "法案を閣議決定・国会提出" },
      { date: "2026-04-01", event: "厚生労働委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "industrial-technology",
    title: "産業技術力強化法改正案",
    titleEn: "Industrial Technology Enhancement Act Amendment",
    committee: "経済産業委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "大学発ベンチャーや産学連携に関わり、研究開発型企業に影響。",
    summary: "大学等の研究成果の社会実装を加速するため、産学連携体制の強化と技術移転の促進を図る改正案。",
    detail: "産業技術力強化法を改正し、大学等の研究成果の事業化支援を拡充。TLO（技術移転機関）の機能強化、大学発スタートアップへの出資規制の緩和、産学連携型の研究開発プロジェクトへの支援拡大を盛り込む。",
    keyPoints: [
      "TLO（技術移転機関）の機能強化",
      "大学発スタートアップへの出資規制緩和",
      "産学連携研究開発プロジェクト支援の拡大",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成" },
      { name: "中道改革連合", position: "賛成" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "条件付き賛成（軍事研究への流用懸念）" },
    ],
    timeline: [
      { date: "2026-03-19", event: "法案を閣議決定・国会提出" },
      { date: "2026-04-03", event: "経済産業委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "foreign-exchange-reform",
    title: "外国為替及び外国貿易法改正案",
    titleEn: "Foreign Exchange and Foreign Trade Act Amendment",
    committee: "財務金融委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "輸出管理・対内投資規制に関わり、国際取引を行う企業に影響。",
    summary: "経済安全保障の観点から、先端技術の輸出管理と対内直接投資の事前届出制度を強化する改正案。",
    detail: "半導体製造装置等の先端技術の輸出管理を強化するとともに、安全保障上重要な企業への外国資本による投資を規制する対内直接投資の事前届出制度を見直す。米中対立を背景とした経済安全保障体制の強化が目的。",
    keyPoints: [
      "先端技術の輸出管理強化",
      "対内直接投資の事前届出制度の見直し",
      "経済安全保障上重要な技術の流出防止",
      "制裁違反に対する罰則強化",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成" },
      { name: "中道改革連合", position: "条件付き賛成（過度な規制による経済への悪影響を懸念）" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "慎重（米国追従の懸念）" },
    ],
    timeline: [
      { date: "2026-03-19", event: "法案を閣議決定・国会提出" },
      { date: "2026-04-03", event: "財務金融委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "norin-chukin-reform",
    title: "農林中央金庫法改正案",
    titleEn: "Norinchukin Bank Act Amendment",
    committee: "農林水産委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "農協系統金融の再建に関わり、JA組合員・農業関係者に影響。",
    summary: "巨額損失を計上した農林中央金庫の経営再建とガバナンス強化に向けた法改正案。",
    detail: "2024年に外国債券投資の含み損が約2兆円に達した農林中央金庫について、JAグループによる資本増強の枠組み整備、リスク管理体制の強化、経営の透明性向上を図る改正案。金融庁の監督権限の強化も盛り込む。",
    keyPoints: [
      "農林中央金庫のガバナンス強化",
      "JAグループによる資本増強の枠組み整備",
      "リスク管理体制の抜本的見直し",
      "金融庁の監督権限強化",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成（ガバナンス改革を支持）" },
      { name: "中道改革連合", position: "賛成（経営責任の明確化を要求）" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "条件付き賛成（組合員負担の軽減を要求）" },
    ],
    timeline: [
      { date: "2026-03-19", event: "法案を閣議決定・国会提出" },
      { date: "2026-04-01", event: "農林水産委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "agricultural-modernization-finance",
    title: "農業近代化資金融通法改正案",
    titleEn: "Agricultural Modernization Financing Act Amendment",
    committee: "農林水産委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "農業者の設備投資・近代化に関わる融資制度に影響。",
    summary: "農業の近代化投資を促進するため、融資制度の拡充と利子補給制度の見直しを行う改正案。",
    detail: "スマート農業や環境配慮型農業への投資を後押しするため、農業近代化資金の融資対象・限度額を拡充。利子補給制度の見直しや手続きの簡素化も盛り込む。",
    keyPoints: [
      "スマート農業投資への融資対象拡大",
      "融資限度額の引き上げ",
      "利子補給制度の見直し",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成" },
      { name: "中道改革連合", position: "賛成" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "賛成" },
    ],
    timeline: [
      { date: "2026-03-19", event: "法案を閣議決定・国会提出" },
      { date: "2026-04-01", event: "農林水産委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "economic-security",
    title: "経済安全保障推進法改正案",
    titleEn: "Economic Security Enhancement",
    committee: "内閣委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "半導体・AI等の重要技術を持つ企業や研究機関に影響。技術流出防止が強化される。",
    summary: "重要企業の海外活動支援や、サプライチェーン保護の強化を盛り込んだ経済安全保障推進法の改正案。",
    detail: "2022年成立の経済安全保障推進法を改正し、重要物資のサプライチェーン強靱化をさらに推進する法案。政府の有識者会議が2026年1月30日に提言をまとめ、3月19日に閣議決定・国会提出。重要な事業を行う企業の海外展開を支援する新たな制度の創設、サプライチェーンの脆弱性把握のための調査権限強化、特定重要技術の研究開発支援の拡充を柱とする。",
    keyPoints: [
      "重要企業の海外活動支援制度の新設",
      "サプライチェーン脆弱性調査の権限強化",
      "特定重要技術の研究開発支援の拡充",
      "重要インフラへの外国資本投資審査の強化",
      "技術流出防止の罰則強化",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成（国際競争力強化の観点から支持）" },
      { name: "国民民主党", position: "賛成（国内産業保護を支持）" },
      { name: "中道改革連合", position: "条件付き賛成（学術研究への影響に懸念）" },
      { name: "日本共産党", position: "反対（軍事技術開発への傾斜を批判）" },
    ],
    timeline: [
      { date: "2026-01-30", event: "有識者会議が改正に向けた提言を取りまとめ" },
      { date: "2026-03-19", event: "改正法案を閣議決定・国会提出" },
      { date: "2026-03-28", event: "衆議院内閣委員会で審議開始" },
    ],
    lastUpdated: "2026-04-06",
  },
  {
    slug: "drone-no-fly-zone",
    title: "重要施設周辺小型無人機飛行禁止法改正案",
    titleEn: "Critical Facilities Drone No-Fly Zone Act Amendment",
    committee: "内閣委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "原発・自衛隊施設等の重要インフラの安全確保。ドローン利用者にも影響。",
    summary: "重要施設の周辺上空における小型無人機等の飛行禁止区域の拡大・規制強化を図る改正案。",
    detail: "テロリスクの高まりを踏まえ、原子力発電所、自衛隊施設、空港等の重要施設周辺における小型無人機（ドローン）の飛行禁止区域を拡大し、違反に対する罰則を強化する。重要施設の管理者が迅速にドローンを排除できる権限も付与。",
    keyPoints: [
      "飛行禁止区域の対象施設の拡大",
      "違反に対する罰則の強化",
      "施設管理者によるドローン排除権限の付与",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成" },
      { name: "中道改革連合", position: "賛成" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "条件付き賛成" },
    ],
    timeline: [
      { date: "2026-03-19", event: "法案を閣議決定・国会提出" },
      { date: "2026-04-03", event: "内閣委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "overseas-telecom-support",
    title: "海外通信・放送・郵便事業支援機構法改正案",
    titleEn: "Overseas Telecom Support Organization Act Amendment",
    committee: "総務委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "日本企業の海外通信インフラ事業展開に影響。",
    summary: "海外における通信・放送・郵便事業への日本企業の参入を支援する機構の機能拡充に向けた改正案。",
    detail: "海外通信・放送・郵便事業支援機構の支援対象を拡大し、デジタルインフラ輸出を推進。新興国における5Gネットワークや海底ケーブル敷設などへの日本企業の参入を後押しする。",
    keyPoints: [
      "支援対象事業の拡大",
      "デジタルインフラ輸出の推進",
      "5G・海底ケーブル事業への支援強化",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成" },
      { name: "中道改革連合", position: "賛成" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "条件付き賛成" },
    ],
    timeline: [
      { date: "2026-03-19", event: "法案を閣議決定・国会提出" },
      { date: "2026-04-01", event: "総務委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "mobile-identity-verification",
    title: "携帯音声通信事業者本人確認法改正案",
    titleEn: "Mobile Carrier Identity Verification Act Amendment",
    committee: "総務委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "携帯電話の不正利用対策。全携帯電話利用者に影響。",
    summary: "特殊詐欺等への対策として、携帯電話契約時の本人確認の厳格化とSIM不正利用への罰則強化を図る改正案。",
    detail: "特殊詐欺や闇バイトの連絡手段として不正に取得された携帯電話が使われる問題に対応するため、携帯電話契約時の本人確認手続きを厳格化。マイナンバーカードによる本人確認の義務化、不正なSIM取得への罰則強化を盛り込む。",
    keyPoints: [
      "携帯電話契約時のマイナンバーカード確認義務化",
      "不正SIM取得への罰則強化",
      "レンタル携帯の規制強化",
      "特殊詐欺対策としての通信事業者の義務拡大",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成" },
      { name: "中道改革連合", position: "賛成" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "条件付き賛成（プライバシー保護を要求）" },
    ],
    timeline: [
      { date: "2026-03-19", event: "法案を閣議決定・国会提出" },
      { date: "2026-04-01", event: "総務委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "postal-law-reform",
    title: "郵便法及び信書送達法改正案",
    titleEn: "Postal Act and Letter Delivery Act Amendment",
    committee: "総務委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "郵便サービスの維持に関わり、全国民・企業に影響。",
    summary: "郵便物の減少に対応し、ユニバーサルサービスの維持と配達体制の効率化を図る改正案。",
    detail: "郵便物の取扱量が年々減少するなか、全国一律の郵便サービス（ユニバーサルサービス）の維持と経営の効率化の両立を図る改正。土曜日配達の見直し拡大、翌日配達義務の緩和、信書の定義の見直し等を含む。",
    keyPoints: [
      "ユニバーサルサービスの維持方策",
      "配達頻度・速度基準の見直し",
      "信書の定義の現代化",
      "郵便料金制度の弾力化",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成（経営効率化を支持）" },
      { name: "中道改革連合", position: "条件付き賛成（過疎地域サービス維持を要求）" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "反対（サービス低下を懸念）" },
    ],
    timeline: [
      { date: "2026-03-19", event: "法案を閣議決定・国会提出" },
      { date: "2026-04-01", event: "総務委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "livestock-disease-prevention",
    title: "家畜伝染病予防法改正案",
    titleEn: "Act on Domestic Animal Infectious Diseases Control Amendment",
    committee: "農林水産委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "畜産業者・食肉業界に影響。鳥インフルエンザ・豚熱等への対応強化。",
    summary: "鳥インフルエンザや豚熱（CSF）等の家畜伝染病への対応を強化するための改正案。",
    detail: "近年の高病原性鳥インフルエンザの大規模発生を踏まえ、家畜伝染病の予防・まん延防止対策を強化。殺処分の迅速化、畜産農家への補償制度の拡充、ワクチン接種体制の整備を盛り込む。",
    keyPoints: [
      "殺処分の迅速化と体制強化",
      "畜産農家への補償制度の拡充",
      "ワクチン接種体制の整備",
      "農場のバイオセキュリティ基準の強化",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成" },
      { name: "中道改革連合", position: "賛成" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "賛成" },
    ],
    timeline: [
      { date: "2026-03-19", event: "法案を閣議決定・国会提出" },
      { date: "2026-04-01", event: "農林水産委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "electricity-business-reform",
    title: "電気事業法改正案",
    titleEn: "Electricity Business Act Amendment",
    committee: "経済産業委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "電力会社・再エネ事業者・全電力消費者に影響。",
    summary: "再生可能エネルギーの主力電源化と電力供給の安定確保に向けた電気事業法の改正案。",
    detail: "再生可能エネルギーの大量導入に対応するため、送配電網の増強・運用の効率化、容量市場制度の見直し、小売電気事業者の規制強化を盛り込む改正案。電力システム改革の次のステップとして位置づけられる。",
    keyPoints: [
      "送配電網の増強・運用効率化",
      "容量市場制度の見直し",
      "再エネ出力制御の最小化策",
      "小売電気事業者の財務規制強化",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成（電力自由化の推進を支持）" },
      { name: "中道改革連合", position: "条件付き賛成（原発依存の低減を要求）" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "反対（原発再稼働前提を批判）" },
    ],
    timeline: [
      { date: "2026-03-19", event: "法案を閣議決定・国会提出" },
      { date: "2026-04-03", event: "経済産業委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "decentralization-omnibus",
    title: "地方分権一括法案",
    titleEn: "Decentralization Omnibus Act",
    committee: "地方創生特別委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "地方自治体の権限強化に関わり、全自治体に影響。",
    summary: "地方の自主性・自立性を高めるため、国から地方への権限移譲や規制緩和を一括して行う法案。",
    detail: "地方分権改革推進の一環として、関係法律を一括改正する法案。地方自治体からの提案に基づき、農地転用許可権限の移譲、保育所等の設置基準の条例委任拡大などを含む。",
    keyPoints: [
      "国から地方への権限移譲の推進",
      "義務付け・枠付けの見直し",
      "地方の裁量権の拡大",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成（地方分権を強く支持）" },
      { name: "中道改革連合", position: "賛成" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "条件付き賛成（ナショナルミニマムの確保を要求）" },
    ],
    timeline: [
      { date: "2026-03-19", event: "法案を閣議決定・国会提出" },
      { date: "2026-04-01", event: "地方創生特別委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "sewerage-reform",
    title: "下水道法等改正案",
    titleEn: "Sewerage Act Amendment",
    committee: "国土交通委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "老朽化する下水道インフラの更新。自治体の財政負担に影響。",
    summary: "老朽化が進む下水道施設の計画的な更新と、広域化・共同化の推進を図る改正案。",
    detail: "全国の下水道管路の約25%が法定耐用年数を超過するなか、計画的な施設更新を義務化。自治体間の広域連携による管理の効率化、民間資金・技術の活用（コンセッション方式等）を推進する規定を整備。",
    keyPoints: [
      "下水道施設の計画的更新の義務化",
      "自治体間の広域連携推進",
      "民間資金・技術の活用促進",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成" },
      { name: "中道改革連合", position: "賛成" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "条件付き賛成（民営化への懸念）" },
    ],
    timeline: [
      { date: "2026-03-19", event: "法案を閣議決定・国会提出" },
      { date: "2026-04-03", event: "国土交通委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "building-energy-efficiency",
    title: "建築物エネルギー消費性能向上法改正案",
    titleEn: "Building Energy Efficiency Act Amendment",
    committee: "国土交通委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "住宅・建築物の省エネ基準強化。建設業界・住宅購入者に影響。",
    summary: "2050年カーボンニュートラルに向け、新築住宅・建築物の省エネ基準をさらに強化する改正案。",
    detail: "2025年4月から義務化された省エネ基準適合義務をさらに強化し、ZEH（ネット・ゼロ・エネルギー・ハウス）水準への段階的な引き上げを規定。既存建築物の省エネ改修促進策も盛り込む。",
    keyPoints: [
      "新築建築物の省エネ基準の段階的強化",
      "ZEH水準への引き上げロードマップ",
      "既存建築物の省エネ改修促進",
      "建築物の省エネ性能表示制度の拡充",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成" },
      { name: "中道改革連合", position: "賛成（脱炭素政策を支持）" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "条件付き賛成（コスト増への対策を要求）" },
    ],
    timeline: [
      { date: "2026-03-19", event: "法案を閣議決定・国会提出" },
      { date: "2026-04-03", event: "国土交通委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "space-activities-reform",
    title: "人工衛星打上げ・管理法等改正案",
    titleEn: "Space Activities Act Amendment",
    committee: "内閣委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "宇宙産業の振興に関わり、宇宙スタートアップに影響。",
    summary: "宇宙産業の振興と安全保障上の宇宙利用を推進するため、人工衛星の打上げ・管理に関する規制を見直す改正案。",
    detail: "民間宇宙ビジネスの成長に対応し、人工衛星等の打上げ・管理に関する許認可手続きの迅速化、スペースデブリ（宇宙ゴミ）対策の義務化、安全保障上の衛星利用の法的枠組み整備を行う。",
    keyPoints: [
      "打上げ許認可手続きの迅速化",
      "スペースデブリ対策の義務化",
      "安全保障上の宇宙利用の法整備",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成" },
      { name: "中道改革連合", position: "賛成" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "条件付き賛成（宇宙の軍事利用に懸念）" },
    ],
    timeline: [
      { date: "2026-03-19", event: "法案を閣議決定・国会提出" },
      { date: "2026-04-03", event: "内閣委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "science-technology-innovation",
    title: "科学技術・イノベーション活性化法改正案",
    titleEn: "Science, Technology and Innovation Promotion Act Amendment",
    committee: "文部科学委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "研究者・大学・研究機関に影響。研究環境の改善に直結。",
    summary: "研究力の強化に向け、研究者の処遇改善や研究開発環境の整備を推進する改正案。",
    detail: "国際的に低下する日本の研究力を回復するため、若手研究者の安定的なポスト確保、研究費の弾力的な運用、国際共同研究の推進に向けた制度整備を行う。10兆円規模の大学ファンドの運用強化も盛り込む。",
    keyPoints: [
      "若手研究者の安定雇用促進",
      "研究費の弾力的運用の推進",
      "国際共同研究の制度整備",
      "大学ファンドの運用強化",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成" },
      { name: "中道改革連合", position: "賛成（研究者の処遇改善を重視）" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "条件付き賛成（軍事研究との切り離しを要求）" },
    ],
    timeline: [
      { date: "2026-03-19", event: "法案を閣議決定・国会提出" },
      { date: "2026-04-03", event: "文部科学委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "dangerous-driving-reform",
    title: "自動車運転死傷行為処罰法及び道路交通法改正案",
    titleEn: "Dangerous Driving Punishment and Road Traffic Act Amendment",
    committee: "法務委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "全ドライバーに影響。悪質運転への厳罰化と自動運転の法整備。",
    summary: "悪質な危険運転への厳罰化と、自動運転車（レベル4以上）の公道走行に関する法整備を含む改正案。",
    detail: "あおり運転や飲酒運転等の悪質な交通犯罪への罰則を強化するとともに、自動運転車（レベル4・レベル5）の公道走行に関する法的枠組みを整備。自動運転システムの安全基準、事故時の責任の所在、運行データの保存義務等を規定する。",
    keyPoints: [
      "悪質な危険運転に対する罰則強化",
      "自動運転レベル4・5の法的枠組み整備",
      "自動運転事故時の責任の明確化",
      "運行データの保存義務",
      "電動キックボード等の規制見直し",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成" },
      { name: "中道改革連合", position: "賛成（被害者保護の強化を要望）" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "条件付き賛成（自動運転の安全基準を慎重に検討すべき）" },
    ],
    timeline: [
      { date: "2026-03-19", event: "法案を閣議決定・国会提出" },
      { date: "2026-04-02", event: "法務委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "civil-code-reform",
    title: "民法等改正案（共有制度・相隣関係等）",
    titleEn: "Civil Code Amendment",
    committee: "法務委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "不動産所有者・共有者に影響。所有者不明土地問題への対応。",
    summary: "所有者不明土地問題への追加的な対応として、共有制度の見直しや相隣関係の規定整備を行う民法改正案。",
    detail: "所有者不明土地の増加への対応として2021年に成立した民法改正に続く追加措置。共有物の管理・変更に関する規定の見直し、隣地使用権の拡充、ライフライン設置のための隣地通過権の整備などを含む。",
    keyPoints: [
      "共有物の管理・変更手続きの見直し",
      "隣地使用権の拡充",
      "ライフライン設置のための隣地通過権の整備",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成" },
      { name: "中道改革連合", position: "賛成" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "賛成" },
    ],
    timeline: [
      { date: "2026-03-19", event: "法案を閣議決定・国会提出" },
      { date: "2026-04-02", event: "法務委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "civil-code-reform-related",
    title: "民法等改正施行関連法整備案",
    titleEn: "Civil Code Amendment Related Laws",
    committee: "法務委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "民法改正に伴う関連法律の整備。",
    summary: "民法等の一部を改正する法律の施行に伴い、不動産登記法等の関係法律を一括整備する法案。",
    detail: "民法等改正案と一体で審議される関連法整備案。不動産登記法、借地借家法等の関連規定を改正し、民法改正の実効性を確保する。",
    keyPoints: [
      "不動産登記法の関連規定改正",
      "借地借家法等の整合性確保",
      "民法改正と一体での審議",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成" },
      { name: "中道改革連合", position: "賛成" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "賛成" },
    ],
    timeline: [
      { date: "2026-03-19", event: "民法改正案と同時に国会提出" },
      { date: "2026-04-02", event: "法務委員会で一括審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "social-welfare-reform",
    title: "社会福祉法等改正案",
    titleEn: "Social Welfare Act Amendment",
    committee: "厚生労働委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "社会福祉施設・介護施設の運営に影響。福祉人材の処遇改善に直結。",
    summary: "福祉人材の確保・処遇改善と社会福祉法人のガバナンス強化を柱とする改正案。",
    detail: "深刻化する福祉人材不足に対応するため、介護職員・保育士等の処遇改善策を法定化。社会福祉法人の会計基準の透明化やガバナンス強化、複数法人間の連携促進も盛り込む。",
    keyPoints: [
      "福祉人材の処遇改善策の法定化",
      "社会福祉法人のガバナンス強化",
      "複数法人間の連携促進",
      "福祉サービスの質の評価制度導入",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成" },
      { name: "中道改革連合", position: "賛成（処遇改善の十分な財源確保を要求）" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "条件付き賛成（公的福祉の充実を求める）" },
    ],
    timeline: [
      { date: "2026-03-19", event: "法案を閣議決定・国会提出" },
      { date: "2026-04-01", event: "厚生労働委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "important-crop-varieties",
    title: "重要品種育成・種苗生産振興法案",
    titleEn: "Important Crop Varieties Promotion Act",
    committee: "農林水産委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "農業の知的財産保護と食料安全保障に影響。",
    summary: "日本発の優良品種の育成と種苗の国内生産体制の強化を図る新法案。",
    detail: "シャインマスカット等の日本発優良品種の海外流出問題を踏まえ、重要品種の育成支援と種苗の国内生産体制の強化を図る新法。品種の知的財産保護の強化と、種苗の安定供給体制の構築が柱。",
    keyPoints: [
      "重要品種の育成支援制度の創設",
      "種苗の国内生産体制の強化",
      "品種の海外流出防止策の強化",
      "種苗の安定供給体制の構築",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成" },
      { name: "中道改革連合", position: "賛成" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "条件付き賛成（農家の自家増殖権への配慮を要求）" },
    ],
    timeline: [
      { date: "2026-03-19", event: "法案を閣議決定・国会提出" },
      { date: "2026-04-01", event: "農林水産委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "seed-seedling-reform",
    title: "種苗法改正案",
    titleEn: "Plant Variety Protection and Seed Act Amendment",
    committee: "農林水産委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "農業者・種苗メーカーに影響。品種登録制度の見直し。",
    summary: "品種登録制度の迅速化と品種の知的財産保護の強化を図る種苗法改正案。",
    detail: "品種登録の審査期間短縮、登録品種の海外への持ち出し制限の実効性強化、品種の権利侵害に対する罰則強化を盛り込む。重要品種育成法案と一体で審議。",
    keyPoints: [
      "品種登録審査の迅速化",
      "品種の海外持ち出し制限の強化",
      "権利侵害に対する罰則強化",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成" },
      { name: "中道改革連合", position: "賛成" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "条件付き賛成" },
    ],
    timeline: [
      { date: "2026-03-19", event: "法案を閣議決定・国会提出" },
      { date: "2026-04-01", event: "農林水産委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "staple-food-supply",
    title: "主要食糧需給・価格安定法改正案",
    titleEn: "Staple Food Supply and Price Stabilization Act Amendment",
    committee: "農林水産委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "米・麦の流通制度に関わり、農業者・消費者に影響。",
    summary: "コメの需給安定と食料安全保障の観点から、主要食糧の流通・備蓄制度を見直す改正案。",
    detail: "2024年のコメ不足問題を踏まえ、コメの備蓄量の引き上げ、緊急時の流通規制の整備、米価の急激な変動を抑制する仕組みの導入を盛り込む。食料安全保障の強化が目的。",
    keyPoints: [
      "コメの備蓄量の引き上げ",
      "緊急時の流通規制の整備",
      "米価安定のための仕組み導入",
      "食料安全保障の強化",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成" },
      { name: "中道改革連合", position: "賛成（消費者価格への配慮を要求）" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "賛成（食料自給率向上を支持）" },
    ],
    timeline: [
      { date: "2026-03-19", event: "法案を閣議決定・国会提出" },
      { date: "2026-04-01", event: "農林水産委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "solar-panel-recycling",
    title: "太陽電池廃棄物再資源化推進法案",
    titleEn: "Solar Panel Waste Recycling Promotion Act",
    committee: "環境委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "太陽光発電事業者・廃棄物処理業者に影響。環境問題への対応。",
    summary: "大量廃棄が見込まれる太陽光パネルの適正処理・リサイクル体制を構築する新法案。",
    detail: "FIT制度導入初期（2012年頃）に設置された太陽光パネルの大量廃棄が2030年代に見込まれるなか、パネルの適正処理・リサイクルの義務化と処理費用の積立制度の創設を柱とする新法。有害物質の適正管理と資源の有効利用を両立させる。",
    keyPoints: [
      "太陽光パネルのリサイクル義務化",
      "処理費用の積立制度の創設",
      "有害物質の適正管理規定",
      "リサイクル技術の開発支援",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成" },
      { name: "中道改革連合", position: "賛成" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "賛成" },
    ],
    timeline: [
      { date: "2026-03-19", event: "法案を閣議決定・国会提出" },
      { date: "2026-04-03", event: "環境委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "reservist-dual-employment",
    title: "予備自衛官等兼業特例法案",
    titleEn: "Reserve Self-Defense Force Dual Employment Special Measures Act",
    committee: "安全保障委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "国家公務員・地方公務員の予備自衛官への就任を可能にし、防衛力の人的基盤を強化。",
    summary: "国家公務員・地方公務員が予備自衛官等を兼業できるよう、特例措置を設ける新法案。",
    detail: "自衛隊の人的基盤の強化に向け、国家公務員及び地方公務員が予備自衛官、即応予備自衛官等の職務を兼業できるようにする特例法。現行の兼業禁止規定の例外措置を設け、有事の際の動員体制を強化する。",
    keyPoints: [
      "公務員の予備自衛官兼業を可能にする特例措置",
      "有事の動員体制の強化",
      "予備自衛官の確保・充足率向上",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成" },
      { name: "中道改革連合", position: "慎重（公務との両立に懸念）" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "反対（軍事力強化に反対）" },
    ],
    timeline: [
      { date: "2026-03-19", event: "法案を閣議決定・国会提出" },
      { date: "2026-04-01", event: "安全保障委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "anti-money-laundering",
    title: "犯罪収益移転防止法改正案",
    titleEn: "Act on Prevention of Transfer of Criminal Proceeds Amendment",
    committee: "内閣委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "金融機関・仮想通貨交換業者・不動産業者等に影響。マネーロンダリング対策の国際基準対応。",
    summary: "FATF（金融活動作業部会）の対日審査を踏まえ、マネーロンダリング対策を強化する改正案。",
    detail: "FATF第4次対日審査で指摘された不備に対応するため、犯罪収益移転防止法を改正。特定事業者の取引時確認義務の強化、疑わしい取引の届出制度の拡充、暗号資産関連のマネロン規制の強化を盛り込む。",
    keyPoints: [
      "取引時確認義務の強化",
      "疑わしい取引の届出制度の拡充",
      "暗号資産関連のマネロン規制強化",
      "FATF対日審査への対応",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成" },
      { name: "中道改革連合", position: "賛成" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "賛成" },
    ],
    timeline: [
      { date: "2026-03-19", event: "法案を閣議決定・国会提出" },
      { date: "2026-04-03", event: "内閣委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "antarctic-environment",
    title: "南極地域環境保護法改正案",
    titleEn: "Antarctic Region Environment Protection Act Amendment",
    committee: "環境委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "南極観測・研究活動に関わる規制の見直し。",
    summary: "南極地域の環境保護に関する国際条約の改正に対応するため、国内法を整備する改正案。",
    detail: "南極条約環境保護議定書の附属書の改正に対応し、南極地域における活動の環境影響評価手続きの見直しや廃棄物管理規定の強化を行う。",
    keyPoints: [
      "環境影響評価手続きの見直し",
      "廃棄物管理規定の強化",
      "国際条約改正への対応",
    ],
    parties: [
      { name: "自由民主党", position: "賛成（政府提出法案）" },
      { name: "日本維新の会", position: "賛成" },
      { name: "中道改革連合", position: "賛成" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "賛成" },
    ],
    timeline: [
      { date: "2026-03-19", event: "法案を閣議決定・国会提出" },
      { date: "2026-04-03", event: "環境委員会で審議開始" },
    ],
    lastUpdated: "2026-04-04",
  },

  // ──────────────────────────────────────────
  // 衆法（衆議院議員提出法律案）— 審議中
  // ──────────────────────────────────────────
  {
    slug: "political-funds-reform-member-bill",
    title: "政治資金規正法改正案（議員立法）",
    titleEn: "Political Funds Control Act Amendment (Member Bill)",
    committee: "政治倫理・選挙制度特別委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "政治資金の透明性に関わり、全政党・政治家に影響。",
    summary: "企業・団体献金の全面禁止を含む、政治資金規正法のさらなる改正を求める議員立法。",
    detail: "中道改革連合が提出した政治資金規正法の追加改正案。2024年に成立した改正法をさらに踏み込み、企業・団体献金の全面禁止や、政治資金パーティーの開催規制の強化を盛り込む。",
    keyPoints: [
      "企業・団体献金の全面禁止",
      "政治資金パーティーの開催規制強化",
      "政治資金の透明性のさらなる向上",
    ],
    parties: [
      { name: "中道改革連合", position: "提出（議員立法として推進）" },
      { name: "日本共産党", position: "賛成" },
      { name: "自由民主党", position: "反対（既存改正で十分と主張）" },
      { name: "日本維新の会", position: "慎重" },
      { name: "国民民主党", position: "慎重" },
    ],
    timeline: [
      { date: "2026-03-05", event: "中道改革連合が法案を衆議院に提出" },
      { date: "2026-03-28", event: "特別委員会で趣旨説明" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "single-year-deficit-bonds",
    title: "令和八年度公債発行特例法案（議員立法）",
    titleEn: "FY2026 Single-Year Deficit Bond Bill",
    committee: "財務金融委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "財政規律と国会の予算統制に関わる。",
    summary: "赤字国債の発行を令和8年度の単年度に限定する対案。政府の5年延長法案に対抗。",
    detail: "政府が提出した特例公債法改正案（5年延長）に対し、中道改革連合・国民民主党が提出した対案。赤字国債の発行根拠を令和8年度限りとし、毎年度国会の議決を経る原則を堅持する。",
    keyPoints: [
      "赤字国債発行を単年度に限定",
      "毎年度の国会議決の原則を維持",
      "政府の5年一括延長に対する対案",
    ],
    parties: [
      { name: "中道改革連合", position: "提出（財政規律の確保を主張）" },
      { name: "国民民主党", position: "賛成（国会の予算統制を重視）" },
      { name: "自由民主党", position: "反対（安定的な財政運営のため5年延長を支持）" },
      { name: "日本維新の会", position: "条件付き反対" },
      { name: "日本共産党", position: "賛成" },
    ],
    timeline: [
      { date: "2026-03-10", event: "中道改革連合・国民民主党が対案を提出" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "intelligence-infrastructure",
    title: "インテリジェンス態勢整備推進法案（議員立法）",
    titleEn: "Intelligence Infrastructure Promotion Act",
    committee: "内閣委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "情報機関の法的基盤整備。国家情報局設置法案と連動。",
    summary: "政府の国家情報会議設置法案を補完する形で、インテリジェンス態勢の整備を推進する議員立法。",
    detail: "日本維新の会が提出したインテリジェンス関連の議員立法。国家情報会議設置法案を補完し、情報コミュニティ全体の能力向上、人材育成、国際連携の枠組みを定める。",
    keyPoints: [
      "情報コミュニティ全体の能力向上",
      "インテリジェンス人材の育成",
      "Five Eyes等との国際情報連携の強化",
    ],
    parties: [
      { name: "日本維新の会", position: "提出（議員立法）" },
      { name: "自由民主党", position: "前向き" },
      { name: "国民民主党", position: "賛成" },
      { name: "中道改革連合", position: "慎重" },
      { name: "日本共産党", position: "反対" },
    ],
    timeline: [
      { date: "2026-03-10", event: "日本維新の会が法案を提出" },
      { date: "2026-03-28", event: "内閣委員会で趣旨説明" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "earthquake-disaster-prevention",
    title: "地震防災対策特別措置法改正案（議員立法）",
    titleEn: "Earthquake Disaster Prevention Special Measures Act Amendment",
    committee: "災害対策特別委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "地震防災対策の強化。全国の自治体・住民に影響。",
    summary: "南海トラフ地震に備え、地震防災対策の緊急整備事業に係る国の財政支援を拡充する改正案。",
    detail: "地震防災対策強化地域における緊急整備事業について、国の補助率の引き上げや事業期間の延長を盛り込む議員立法。防災庁設置法案と連動した議論が見込まれる。",
    keyPoints: [
      "国の補助率の引き上げ",
      "緊急整備事業の期間延長",
      "南海トラフ地震への備えの強化",
    ],
    parties: [
      { name: "自由民主党", position: "賛成" },
      { name: "日本維新の会", position: "賛成" },
      { name: "中道改革連合", position: "賛成" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "賛成" },
    ],
    timeline: [
      { date: "2026-03-15", event: "超党派で法案を提出" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "disability-support-comprehensive",
    title: "障害者及びその家族福祉・教育支援施策推進法案（議員立法）",
    titleEn: "Comprehensive Disability Support Act",
    committee: "厚生労働委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "障害者及びその家族約960万人に影響。包括的な支援体制の構築。",
    summary: "障害者とその家族に対する福祉・教育等の支援に関する施策を総合的に推進する新法案。",
    detail: "障害者基本法を補完し、障害者とその家族に対する福祉、教育、就労支援等を包括的に推進する新法案。インクルーシブ教育の推進、障害者雇用の質の向上、家族介護者（ケアラー）支援の法定化を含む。",
    keyPoints: [
      "インクルーシブ教育の推進",
      "障害者雇用の質の向上",
      "家族介護者（ケアラー）支援の法定化",
      "障害者の地域生活支援の強化",
    ],
    parties: [
      { name: "中道改革連合", position: "提出（議員立法）" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "賛成" },
      { name: "自由民主党", position: "前向き（一部修正を検討）" },
      { name: "日本維新の会", position: "前向き" },
    ],
    timeline: [
      { date: "2026-03-18", event: "中道改革連合が法案を提出" },
      { date: "2026-04-01", event: "厚生労働委員会で趣旨説明" },
    ],
    lastUpdated: "2026-04-04",
  },

  // ──────────────────────────────────────────
  // 参法（参議院議員提出法律案）— 審議中
  // ──────────────────────────────────────────
  {
    slug: "party-subsidy-transparency",
    title: "政党交付金透明性・公正性向上法案（参法）",
    titleEn: "Party Subsidy Transparency Act",
    committee: "政治倫理・選挙制度特別委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "政党交付金の使途透明化に関わり、全政党に影響。",
    summary: "政党交付金を受ける政党の組織運営の透明性・公正性を向上させる制度を導入する参議院発の法案。",
    detail: "政党交付金（年間約315億円）を受ける政党に対し、外部監査の義務化、使途の詳細公開、ガバナンス体制の整備を求める。政党の組織運営の透明性を高め、国民の信頼回復を目指す。",
    keyPoints: [
      "政党交付金の使途の詳細公開義務化",
      "外部監査の義務化",
      "政党のガバナンス体制の整備要求",
    ],
    parties: [
      { name: "中道改革連合", position: "提出（参議院会派として推進）" },
      { name: "日本共産党", position: "賛成（そもそも政党交付金制度に反対だが透明化は支持）" },
      { name: "自由民主党", position: "反対（政党の自律性を尊重すべき）" },
      { name: "日本維新の会", position: "前向き" },
      { name: "国民民主党", position: "前向き" },
    ],
    timeline: [
      { date: "2026-03-05", event: "参議院に法案提出" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "special-child-allowance-reform",
    title: "特別児童扶養手当等支給法改正案（参法）",
    titleEn: "Special Child Allowance Act Amendment",
    committee: "厚生労働委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "障害のある子どもの家庭約25万世帯に影響。所得制限の見直し。",
    summary: "障害のある子どもに対する特別児童扶養手当の所得制限を撤廃する参議院発の議員立法。",
    detail: "障害児の療育に要する費用が所得に関係なく発生することを踏まえ、特別児童扶養手当の所得制限の撤廃を求める。児童手当の所得制限撤廃（2024年実施）との整合性も主張。",
    keyPoints: [
      "特別児童扶養手当の所得制限撤廃",
      "障害児療育の経済的負担軽減",
      "児童手当との制度的整合性の確保",
    ],
    parties: [
      { name: "中道改革連合", position: "提出" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "賛成" },
      { name: "自由民主党", position: "慎重（財源を懸念）" },
      { name: "日本維新の会", position: "前向き" },
    ],
    timeline: [
      { date: "2026-03-05", event: "参議院に法案提出" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "income-tax-reform-opposition",
    title: "所得税法改正案（参法・野党対案）",
    titleEn: "Income Tax Act Amendment (Opposition)",
    committee: "財政金融委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "103万円の壁のさらなる引き上げ。給与所得者全体に影響。",
    summary: "政府案を上回る基礎控除の引き上げ（178万円）を求める野党の所得税法改正案。",
    detail: "政府が提出した所得税法改正案（基礎控除引き上げ123万円）に対し、中道改革連合が提出した対案。基礎控除を178万円に引き上げ、いわゆる「103万円の壁」を抜本的に解消することを目指す。",
    keyPoints: [
      "基礎控除の178万円への引き上げ",
      "103万円の壁の抜本的解消",
      "政府案を上回る減税規模",
    ],
    parties: [
      { name: "中道改革連合", position: "提出" },
      { name: "国民民主党", position: "賛成（当初から178万円を主張）" },
      { name: "日本共産党", position: "賛成" },
      { name: "自由民主党", position: "反対（財源問題を指摘）" },
      { name: "日本維新の会", position: "慎重（段階的引き上げを主張）" },
    ],
    timeline: [
      { date: "2026-03-10", event: "参議院に法案提出" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "local-tax-reform-opposition",
    title: "地方税法改正案（参法・野党対案）",
    titleEn: "Local Tax Act Amendment (Opposition)",
    committee: "総務委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "住民税の負担軽減に関わり、全納税者に影響。",
    summary: "住民税の基礎控除引き上げを含む、所得税法改正案と連動した地方税法の改正案。",
    detail: "所得税法改正案（参法）と連動し、住民税の基礎控除の引き上げや非課税限度額の見直しを盛り込む対案。",
    keyPoints: [
      "住民税の基礎控除引き上げ",
      "非課税限度額の見直し",
      "所得税法改正案との連動",
    ],
    parties: [
      { name: "中道改革連合", position: "提出" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "賛成" },
      { name: "自由民主党", position: "反対" },
      { name: "日本維新の会", position: "慎重" },
    ],
    timeline: [
      { date: "2026-03-10", event: "参議院に法案提出" },
    ],
    lastUpdated: "2026-04-06",
  },
  {
    slug: "counterintelligence",
    title: "スパイ防止法案（防諜施策推進法案）",
    titleEn: "Counterintelligence Bill",
    committee: "法務委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "主要先進国で唯一スパイ防止法がない日本。報道の自由との均衡が最大の争点。",
    summary: "国民民主党が提出したスパイ活動防止のための議員立法。国家情報局新設と連動した議論が進む。",
    detail: "国民民主党が参議院に議員立法として提出したスパイ活動防止法案。国家機密の漏洩やスパイ活動に対する処罰規定を新設し、カウンターインテリジェンス体制を法的に整備する。日本は主要先進国で唯一、包括的なスパイ防止法を持たないことが長年指摘されてきた。衆議院から提出されたインテリジェンス態勢整備推進法案や、政府の国家情報局設置法案と並行して審議が進む見通し。",
    keyPoints: [
      "スパイ活動に対する刑事罰の新設",
      "国家機密の漏洩に対する処罰規定の整備",
      "カウンターインテリジェンス体制の法的基盤",
      "国家情報局設置法案と連動した審議",
      "表現の自由・報道の自由との均衡が争点",
    ],
    parties: [
      { name: "国民民主党", position: "提出（議員立法として推進）" },
      { name: "自由民主党", position: "前向き（国家情報局と連動して検討）" },
      { name: "日本維新の会", position: "賛成（安全保障強化の観点から支持）" },
      { name: "中道改革連合", position: "慎重（運用面での人権保障を要求）" },
      { name: "日本共産党", position: "反対（治安維持法の再来を懸念）" },
    ],
    timeline: [
      { date: "2026-03-10", event: "国民民主党がスパイ防止法案を参議院に提出" },
      { date: "2026-03-28", event: "法務委員会で趣旨説明" },
    ],
    lastUpdated: "2026-04-06",
  },
  {
    slug: "secrecy-protection-reform",
    title: "特定秘密保護法及び重要経済安保情報保護法改正案（参法）",
    titleEn: "Secrecy Protection Act Amendment",
    committee: "内閣委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "国家機密の取り扱いと情報保全に関わる。公務員・防衛産業関係者に影響。",
    summary: "特定秘密保護法と重要経済安保情報保護法を一体的に改正し、情報保全体制を強化する参議院発の法案。",
    detail: "国家情報局の設置を見据え、特定秘密保護法と2024年に成立した重要経済安保情報保護法の運用を一体的に見直す改正案。セキュリティクリアランスの適用範囲拡大や、秘密指定の適正性を監視する仕組みの強化を含む。",
    keyPoints: [
      "セキュリティクリアランス制度の拡充",
      "秘密指定の適正性監視の強化",
      "2法の一体的運用の推進",
    ],
    parties: [
      { name: "自由民主党", position: "前向き" },
      { name: "日本維新の会", position: "賛成" },
      { name: "国民民主党", position: "提出" },
      { name: "中道改革連合", position: "慎重（過度な秘密指定を懸念）" },
      { name: "日本共産党", position: "反対" },
    ],
    timeline: [
      { date: "2026-03-10", event: "参議院に法案提出" },
    ],
    lastUpdated: "2026-04-04",
  },
  {
    slug: "criminal-code-reform",
    title: "刑法改正案（参法）",
    titleEn: "Criminal Code Amendment",
    committee: "法務委員会",
    status: "審議中",
    statusColor: "#e53e3e",
    impact: "性犯罪やサイバー犯罪等の刑罰体系に影響。",
    summary: "性犯罪の厳罰化やサイバー犯罪への対応強化を含む刑法改正案。",
    detail: "性犯罪に対する量刑の引き上げ、フェイクポルノ（AI生成を含む）の生成・頒布の処罰規定の新設、サイバー犯罪の構成要件の見直しを含む刑法改正案。",
    keyPoints: [
      "性犯罪の量刑引き上げ",
      "AIフェイクポルノの処罰規定新設",
      "サイバー犯罪の構成要件見直し",
    ],
    parties: [
      { name: "中道改革連合", position: "提出" },
      { name: "国民民主党", position: "賛成" },
      { name: "日本共産党", position: "条件付き賛成" },
      { name: "自由民主党", position: "前向き（部分的に賛同）" },
      { name: "日本維新の会", position: "前向き" },
    ],
    timeline: [
      { date: "2026-03-15", event: "参議院に法案提出" },
    ],
    lastUpdated: "2026-04-04",
  },
];
