import type { Competitor } from "./competitors";

export const diningCompanies: Competitor[] = [
  {
    slug: "zensho-hd",
    name: "ゼンショーHD",
    nameEn: "Zensho Holdings",
    logo: "善",
    color: "#ef4444",
    stockCode: "7550",
    overview:
      "国内外食業界売上高首位。すき家・はま寿司・ココス・ジョリーパスタ等を展開し、2025年3月期に国内外食初の売上高1兆円を達成。M&Aによる規模拡大と海外展開を積極化し、グループ全体で約15,400店舗を運営。食材の一括調達やサプライチェーン構築により高い原価管理力を持つ。",
    financials: {
      revenue: "1兆1,366億円",
      revenueYoy: "+17.7%",
      operatingProfit: "751億円",
      opMargin: "6.6%",
      keyMetric: "約15,400店",
      keyMetricLabel: "店舗数",
      fiscalYear: "2025年3月期",
    },
    pl: {
      revenue: "1兆1,366億円",
      cogs: "4,660億円",
      grossProfit: "6,706億円",
      grossMargin: "59.0%",
      sga: "5,955億円",
      rd: "—",
      operatingProfit: "751億円",
      opMargin: "6.6%",
      netIncome: "392億円",
      netMargin: "3.5%",
      fiscalYear: "2025年3月期",
    },
    bs: {
      totalAssets: "8,131億円",
      currentAssets: "2,100億円",
      cash: "950億円",
      fixedAssets: "6,031億円",
      totalLiab: "5,727億円",
      currentLiab: "2,500億円",
      fixedLiab: "3,227億円",
      interestBearingDebt: "2,997億円",
      equity: "2,403億円",
      equityRatio: "27.2%",
      fiscalYear: "2025年3月期",
    },
    cf: {
      operatingCF: "+789億円",
      investingCF: "-664億円",
      financingCF: "-162億円",
      freeCF: "+125億円",
      capex: "600億円",
      dividends: "70円/株",
      fiscalYear: "2025年3月期",
    },
    strategy: {
      title: "成長戦略",
      summary:
        "M&Aを活用したグローバル展開を加速。海外3,000店舗新規出店を計画し、テイクアウト寿司「ZENSHI」等の新業態で米国市場を開拓。国内ではすき家・はま寿司の既存店強化とDX推進による効率化を推進。",
      keyPoints: [
        "海外3,000店舗出店計画（2028年3月期目標）",
        "M&Aによる業態多角化・規模拡大",
        "サプライチェーン一体経営による原価低減",
        "DX推進（モバイルオーダー・省人化）",
      ],
      target: "2028年3月期 売上高1兆4,810億円・営業利益1,165億円",
    },
    strengths: [
      "国内外食業界売上高No.1、初の1兆円達成",
      "垂直統合型サプライチェーンによるコスト優位性",
      "M&A実績豊富（ロッテリア等）でスケール拡大",
      "海外展開の加速（すき家・はま寿司のグローバル化）",
    ],
    challenges: [
      "すき家の異物混入問題による一時的な信頼低下",
      "有利子負債約3,000億円と財務レバレッジの高さ",
      "人手不足・人件費上昇への対応",
      "海外事業の収益化と為替リスク",
    ],
    latestNews: [
      { date: "2025-05-13", headline: "2025年3月期決算発表、国内外食初の売上高1兆円達成" },
      { date: "2025-05-13", headline: "新中期経営計画策定、2028年3月期に売上高1.48兆円目標" },
      { date: "2025-01-31", headline: "すき家で異物混入事案が複数発生、全店清掃対策を実施" },
      { date: "2026-02-17", headline: "2026年3月期Q3累計は増収増益、はま寿司が好調" },
    ],
  },
  {
    slug: "skylark-hd",
    name: "すかいらーくHD",
    nameEn: "Skylark Holdings",
    logo: "す",
    color: "#3b82f6",
    stockCode: "3197",
    overview:
      "国内最大級のファミリーレストランチェーン。ガスト・バーミヤン・しゃぶ葉・ジョナサン等を展開し、約3,000店舗を運営。2024年12月期は価格改定と既存店売上増により営業利益が倍増。M&A（資さんうどん買収等）やアジア展開により成長を加速。",
    financials: {
      revenue: "4,011億円",
      revenueYoy: "+13.0%",
      operatingProfit: "241億円",
      opMargin: "6.0%",
      keyMetric: "約3,000店",
      keyMetricLabel: "店舗数",
      fiscalYear: "2024年12月期",
    },
    pl: {
      revenue: "4,011億円",
      cogs: "1,284億円",
      grossProfit: "2,727億円",
      grossMargin: "68.0%",
      sga: "2,485億円",
      rd: "—",
      operatingProfit: "241億円",
      opMargin: "6.0%",
      netIncome: "139億円",
      netMargin: "3.5%",
      fiscalYear: "2024年12月期",
    },
    bs: {
      totalAssets: "4,700億円",
      currentAssets: "750億円",
      cash: "350億円",
      fixedAssets: "3,950億円",
      totalLiab: "3,000億円",
      currentLiab: "1,100億円",
      fixedLiab: "1,900億円",
      interestBearingDebt: "1,200億円",
      equity: "1,700億円",
      equityRatio: "36.2%",
      fiscalYear: "2024年12月期",
    },
    cf: {
      operatingCF: "+520億円",
      investingCF: "-280億円",
      financingCF: "-364億円",
      freeCF: "+240億円",
      capex: "250億円",
      dividends: "14円/株",
      fiscalYear: "2024年12月期",
    },
    strategy: {
      title: "成長戦略",
      summary:
        "「店舗中心経営」に舵を切り、国内では3年間で300店舗の新規出店を計画。M&Aにより資さんうどん・マレーシアのSuki-Yaを傘下に加え、業態多様化と海外成長を推進。DX・人的資本投資で生産性向上を図る。",
      keyPoints: [
        "3ヶ年で国内300店舗出店計画",
        "M&A活用（資さんうどん・海外ブランド）",
        "業態転換による高収益化（しゃぶ葉等）",
        "DX推進・配膳ロボット導入",
      ],
      target: "2027年12月期 売上高約4,600億円",
    },
    strengths: [
      "ガストを中核とした圧倒的な店舗ネットワーク",
      "業態転換の柔軟性（不採算店→しゃぶ葉等へ転換）",
      "セントラルキッチンによるコスト管理と品質均一化",
      "配膳ロボット等DXによる生産性向上",
    ],
    challenges: [
      "原材料費・人件費の上昇圧力",
      "既存店の老朽化と改装投資の必要性",
      "消費者の外食離れ・中食シフトへの対応",
      "M&A統合リスク（資さんうどん等のPMI）",
    ],
    latestNews: [
      { date: "2025-02-13", headline: "2024年12月期決算発表、営業利益が前年比2倍の241億円" },
      { date: "2025-01-15", headline: "マレーシアしゃぶしゃぶチェーンSuki-Yaの買収完了" },
      { date: "2025-05-01", headline: "資さんうどんの関東出店を本格化、東京都心にも展開" },
      { date: "2025-09-20", headline: "業態転換戦略が奏功し最高益更新ペース" },
    ],
  },
  {
    slug: "mcdonalds-japan",
    name: "日本マクドナルドHD",
    nameEn: "McDonald's Holdings Japan",
    logo: "M",
    color: "#f59e0b",
    stockCode: "2702",
    overview:
      "マクドナルドの日本法人。全国約2,988店舗を展開し、全店売上高は過去最高の8,291億円を達成。既存店売上高は37四半期連続プラスを継続。フランチャイズモデル主体で高い収益性を維持し、デジタル・モバイルオーダーの普及率も業界トップクラス。",
    financials: {
      revenue: "4,054億円",
      revenueYoy: "+6.1%",
      operatingProfit: "480億円",
      opMargin: "11.8%",
      keyMetric: "約2,988店",
      keyMetricLabel: "店舗数",
      fiscalYear: "2024年12月期",
    },
    pl: {
      revenue: "4,054億円",
      cogs: "2,350億円",
      grossProfit: "1,704億円",
      grossMargin: "42.0%",
      sga: "1,224億円",
      rd: "—",
      operatingProfit: "480億円",
      opMargin: "11.8%",
      netIncome: "319億円",
      netMargin: "7.9%",
      fiscalYear: "2024年12月期",
    },
    bs: {
      totalAssets: "3,113億円",
      currentAssets: "1,000億円",
      cash: "550億円",
      fixedAssets: "2,113億円",
      totalLiab: "1,600億円",
      currentLiab: "900億円",
      fixedLiab: "700億円",
      interestBearingDebt: "—",
      equity: "1,513億円",
      equityRatio: "48.6%",
      fiscalYear: "2024年12月期",
    },
    cf: {
      operatingCF: "+600億円",
      investingCF: "-250億円",
      financingCF: "-200億円",
      freeCF: "+350億円",
      capex: "230億円",
      dividends: "49円/株",
      fiscalYear: "2024年12月期",
    },
    strategy: {
      title: "成長戦略",
      summary:
        "2025-2027年度中期経営計画で「メニュー・バリュー」「店舗ポートフォリオ・デジタル」「サステナビリティ・ピープル」の3領域に注力。3年間で100店舗以上の純増と、モバイルオーダー・タッチパネル注文の全店導入を推進。",
      keyPoints: [
        "3年間で100店舗以上の純増",
        "モバイルオーダー・デジタル投資の加速",
        "メニューイノベーションとバリュー戦略",
        "株主資本配当率（DOE）3%目標",
      ],
      target: "2027年12月期 全店売上高1兆円・営業利益率10%以上維持",
    },
    strengths: [
      "37四半期連続既存店プラスの圧倒的ブランド力",
      "フランチャイズモデルによる高い営業利益率（11.8%）",
      "デジタル・モバイルオーダーの業界最高水準の普及",
      "無借金経営に近い強固な財務基盤",
    ],
    challenges: [
      "原材料費（牛肉・小麦等）の国際価格上昇",
      "フランチャイジーの人材確保難",
      "国内市場の成熟化と出店余地の限界",
      "健康志向の高まりへの対応",
    ],
    latestNews: [
      { date: "2025-02-06", headline: "2024年12月期決算発表、営業利益480億円で2期連続最高益" },
      { date: "2025-02-06", headline: "2025-2027年度中期経営計画を発表、100店舗純増目標" },
      { date: "2025-09-30", headline: "店舗数3,000店を突破、マイルストーン達成" },
      { date: "2026-02-06", headline: "2025年12月期決算、既存店41四半期連続プラス達成" },
    ],
  },
  {
    slug: "toridoll-hd",
    name: "トリドールHD",
    nameEn: "Toridoll Holdings",
    logo: "丸",
    color: "#10b981",
    stockCode: "3397",
    overview:
      "讃岐うどん「丸亀製麺」を主力ブランドとする外食チェーン。国内外約2,050店舗を展開し、29の国と地域で約20ブランドを運営。2025年3月期は全セグメントで過去最高売上を達成も、海外不採算店の減損計上により減益。丸亀製麺は事業利益208億円で過去最高。",
    financials: {
      revenue: "2,682億円",
      revenueYoy: "+15.6%",
      operatingProfit: "86億円",
      opMargin: "3.2%",
      keyMetric: "約2,050店",
      keyMetricLabel: "店舗数",
      fiscalYear: "2025年3月期",
    },
    pl: {
      revenue: "2,682億円",
      cogs: "800億円",
      grossProfit: "1,882億円",
      grossMargin: "70.2%",
      sga: "1,714億円",
      rd: "—",
      operatingProfit: "86億円",
      opMargin: "3.2%",
      netIncome: "18億円",
      netMargin: "0.7%",
      fiscalYear: "2025年3月期",
    },
    bs: {
      totalAssets: "3,800億円",
      currentAssets: "600億円",
      cash: "300億円",
      fixedAssets: "3,200億円",
      totalLiab: "2,700億円",
      currentLiab: "800億円",
      fixedLiab: "1,900億円",
      interestBearingDebt: "1,500億円",
      equity: "1,100億円",
      equityRatio: "28.9%",
      fiscalYear: "2025年3月期",
    },
    cf: {
      operatingCF: "+380億円",
      investingCF: "-300億円",
      financingCF: "-50億円",
      freeCF: "+80億円",
      capex: "280億円",
      dividends: "26円/株",
      fiscalYear: "2025年3月期",
    },
    strategy: {
      title: "成長戦略",
      summary:
        "国内丸亀製麺の収益力強化を軸に、海外展開を「MARUGAME UDON」ブランドで加速。2028年3月期までに海外3,000店舗を目標。不採算海外事業は売却・FC化で効率化し、国内の繁盛店モデルを海外に展開する戦略。",
      keyPoints: [
        "海外3,000店舗目標（2028年3月期）",
        "丸亀製麺の国内既存店強化と過去最高利益の継続",
        "不採算海外事業の整理・FC化（英国事業売却等）",
        "多ブランド戦略（ずんどう屋等の海外展開）",
      ],
      target: "2028年3月期 海外3,000店舗・グローバル外食企業へ",
    },
    strengths: [
      "丸亀製麺の圧倒的ブランド力と高収益性（事業利益208億円）",
      "製麺から調理まで店内一貫製造によるライブ感と品質",
      "29ヶ国・20ブランドの多角的海外展開",
      "海外MARUGAME UDONが300店舗突破、高い成長性",
    ],
    challenges: [
      "海外事業の減損リスク（80億円の減損損失を計上）",
      "英国等一部地域の市況悪化への対応",
      "有利子負債が大きく財務レバレッジが高い",
      "原材料費・人件費上昇による利益圧迫",
    ],
    latestNews: [
      { date: "2025-05-15", headline: "2025年3月期決算発表、売上過去最高も海外減損で減益" },
      { date: "2025-03-31", headline: "英国丸亀事業をローカル企業に売却しFC化" },
      { date: "2025-04-30", headline: "海外MARUGAME UDONが300店舗を突破" },
      { date: "2025-05-22", headline: "丸亀製麺の事業利益208億円で過去最高を更新" },
    ],
  },
  {
    slug: "colowide",
    name: "コロワイド",
    nameEn: "Colowide",
    logo: "コ",
    color: "#8b5cf6",
    stockCode: "7616",
    overview:
      "牛角・かっぱ寿司・大戸屋・フレッシュネスバーガー・ステーキ宮等を傘下に持つ総合外食グループ。国内外約2,600店舗を展開。2025年3月期は増収も農畜産物高騰と人件費上昇でコスト増、税引前利益は減益。M&Aで事業領域を拡大し、フードコート業態「牛角焼肉食堂」が急成長中。",
    financials: {
      revenue: "2,691億円",
      revenueYoy: "+11.6%",
      operatingProfit: "93億円",
      opMargin: "3.5%",
      keyMetric: "約2,600店",
      keyMetricLabel: "店舗数",
      fiscalYear: "2025年3月期",
    },
    pl: {
      revenue: "2,691億円",
      cogs: "850億円",
      grossProfit: "1,841億円",
      grossMargin: "68.4%",
      sga: "1,748億円",
      rd: "—",
      operatingProfit: "93億円",
      opMargin: "3.5%",
      netIncome: "12億円",
      netMargin: "0.5%",
      fiscalYear: "2025年3月期",
    },
    bs: {
      totalAssets: "3,500億円",
      currentAssets: "550億円",
      cash: "250億円",
      fixedAssets: "2,950億円",
      totalLiab: "2,600億円",
      currentLiab: "900億円",
      fixedLiab: "1,700億円",
      interestBearingDebt: "1,400億円",
      equity: "900億円",
      equityRatio: "25.7%",
      fiscalYear: "2025年3月期",
    },
    cf: {
      operatingCF: "+200億円",
      investingCF: "-120億円",
      financingCF: "-100億円",
      freeCF: "+80億円",
      capex: "100億円",
      dividends: "5円/株",
      fiscalYear: "2025年3月期",
    },
    strategy: {
      title: "成長戦略",
      summary:
        "国内ではフードコート業態「牛角焼肉食堂」「とんかつ神楽坂さくら」の出店を加速。海外は中東エリアへの新規進出とインドネシアでの牛角・温野菜の拡大を推進。グループ内で原材料共通化を進めコスト効率を向上。",
      keyPoints: [
        "牛角焼肉食堂（FC専門店）の全国展開加速",
        "海外新規エリア（中東）への進出",
        "M&Aによる事業多角化（菓子・給食事業等）",
        "グループ原材料共通化によるコスト削減",
      ],
      target: "2026年3月期 売上収益2,884億円・増益回帰",
    },
    strengths: [
      "牛角・大戸屋・かっぱ寿司等の多ブランドポートフォリオ",
      "フードコート業態「牛角焼肉食堂」が60店舗超と急成長",
      "居酒屋・和食・回転寿司・ハンバーガー等幅広い業態カバー",
      "グループ工場活用による原材料の共通化・内製化",
    ],
    challenges: [
      "農畜産物の高騰・慢性的な人手不足によるコスト上昇",
      "かっぱ寿司の競争力回復が課題",
      "有利子負債が大きく自己資本比率が低い（25.7%）",
      "消費者の選別志向・節約志向への対応",
    ],
    latestNews: [
      { date: "2025-05-09", headline: "2025年3月期決算発表、増収も原材料高で税引前利益26.5%減" },
      { date: "2025-06-01", headline: "牛角焼肉食堂が60店舗突破、フードコート業態が急成長" },
      { date: "2025-04-01", headline: "日本銘菓総本舗・ソシオフードサービスをグループ化" },
      { date: "2026-02-10", headline: "2026年3月期Q3は増収増益、コラボ企画等が貢献" },
    ],
  },
];
