import type { Competitor } from "./competitors";

export const diningCompanies: Competitor[] = [
  {
    slug: "zensho-hd",
    name: "ゼンショーHD",
    nameEn: "Zensho Holdings",
    logo: "善",
    color: "#ef4444",
    stockCode: "7550",
    overview:
      "国内外食業界売上高首位。すき家・はま寿司・ココス・ジョリーパスタ等を展開し、国内外食初の売上高1兆円を達成。M&Aによる規模拡大と海外展開を積極化し、グループ全体で約14,900店舗を運営。食材の一括調達やサプライチェーン構築により高い原価管理力を持つ。2026年3月期Q3累計は増収増益、はま寿司が好調。",
    financials: {
      revenue: "1兆2,235億円（予想）",
      revenueYoy: "+7.6%",
      operatingProfit: "820億円（予想）",
      opMargin: "6.7%",
      keyMetric: "約14,900店",
      keyMetricLabel: "店舗数",
      fiscalYear: "2026年3月期（予想）",
    },
    pl: {
      revenue: "1兆2,235億円（予想）",
      cogs: "5,010億円",
      grossProfit: "7,225億円",
      grossMargin: "59.1%",
      sga: "6,405億円",
      rd: "—",
      operatingProfit: "820億円（予想）",
      opMargin: "6.7%",
      netIncome: "425億円（予想）",
      netMargin: "3.5%",
      fiscalYear: "2026年3月期（予想）",
    },
    bs: {
      totalAssets: "9,436億円",
      currentAssets: "2,600億円",
      cash: "1,315億円",
      fixedAssets: "6,836億円",
      totalLiab: "6,182億円",
      currentLiab: "2,700億円",
      fixedLiab: "3,482億円",
      interestBearingDebt: "2,514億円",
      equity: "3,254億円",
      equityRatio: "34.5%",
      fiscalYear: "2026年3月期Q3（2025年12月末）",
    },
    cf: {
      operatingCF: "+789億円",
      investingCF: "-664億円",
      financingCF: "-162億円",
      freeCF: "+125億円",
      capex: "600億円",
      dividends: "70円/株",
      fiscalYear: "2025年3月期",
    },
    strategy: {
      title: "成長戦略",
      summary:
        "M&Aを活用したグローバル展開を加速。海外3,000店舗新規出店を計画し、テイクアウト寿司「ZENSHI」等の新業態で米国市場を開拓。国内ではすき家・はま寿司の既存店強化とDX推進による効率化を推進。",
      keyPoints: [
        "海外3,000店舗出店計画（2028年3月期目標）",
        "M&Aによる業態多角化・規模拡大",
        "サプライチェーン一体経営による原価低減",
        "DX推進（モバイルオーダー・省人化）",
      ],
      target: "2028年3月期 売上高1兆4,810億円・営業利益1,165億円",
    },
    strengths: [
      "国内外食業界売上高No.1、初の1兆円達成",
      "垂直統合型サプライチェーンによるコスト優位性",
      "M&A実績豊富（ロッテリア等）でスケール拡大",
      "海外展開の加速（すき家・はま寿司のグローバル化）",
    ],
    challenges: [
      "すき家の異物混入問題による一時的な信頼低下",
      "有利子負債約2,500億円と財務レバレッジの高さ",
      "人手不足・人件費上昇への対応",
      "海外事業の収益化と為替リスク",
    ],
    latestNews: [
      { date: "2026-02-12", headline: "2026年3月期Q3決算発表、4-12月純利益355億円（前年同期比4%増）" },
      { date: "2026-02-12", headline: "はま寿司が売上28%増・営業利益24%増と絶好調、グループ成長を牽引" },
      { date: "2025-05-13", headline: "2025年3月期決算発表、国内外食初の売上高1兆円達成" },
      { date: "2025-05-13", headline: "新中期経営計画策定、2028年3月期に売上高1.48兆円目標" },
    ],
  },
  {
    slug: "skylark-hd",
    name: "すかいらーくHD",
    nameEn: "Skylark Holdings",
    logo: "す",
    color: "#3b82f6",
    stockCode: "3197",
    overview:
      "国内最大級のファミリーレストランチェーン。ガスト・バーミヤン・しゃぶ葉・ジョナサン等を展開し、約3,111店舗を運営。2025年12月期は既存店売上好調と資さんうどんのM&A効果で大幅増収増益、10期ぶりに最高益を更新。業態転換や「しんぱち食堂」買収で低価格帯を強化。",
    financials: {
      revenue: "4,578億円",
      revenueYoy: "+14.1%",
      operatingProfit: "300億円",
      opMargin: "6.5%",
      keyMetric: "3,111店",
      keyMetricLabel: "店舗数",
      fiscalYear: "2025年12月期",
    },
    pl: {
      revenue: "4,578億円",
      cogs: "1,466億円",
      grossProfit: "3,112億円",
      grossMargin: "68.0%",
      sga: "2,812億円",
      rd: "—",
      operatingProfit: "300億円",
      opMargin: "6.5%",
      netIncome: "167億円",
      netMargin: "3.7%",
      fiscalYear: "2025年12月期",
    },
    bs: {
      totalAssets: "5,185億円",
      currentAssets: "900億円",
      cash: "343億円",
      fixedAssets: "4,285億円",
      totalLiab: "3,310億円",
      currentLiab: "1,200億円",
      fixedLiab: "2,110億円",
      interestBearingDebt: "1,300億円",
      equity: "1,876億円",
      equityRatio: "36.2%",
      fiscalYear: "2025年12月期",
    },
    cf: {
      operatingCF: "+745億円",
      investingCF: "-341億円",
      financingCF: "-255億円",
      freeCF: "+404億円",
      capex: "300億円",
      dividends: "22円/株",
      fiscalYear: "2025年12月期",
    },
    strategy: {
      title: "成長戦略",
      summary:
        "「店舗中心経営」に舵を切り、国内では3年間で300店舗の新規出店を計画。M&Aにより資さんうどん・マレーシアのSuki-Yaを傘下に加え、業態多様化と海外成長を推進。DX・人的資本投資で生産性向上を図る。",
      keyPoints: [
        "3ヶ年で国内300店舗出店計画",
        "M&A活用（資さんうどん・海外ブランド）",
        "業態転換による高収益化（しゃぶ葉等）",
        "DX推進・配膳ロボット導入",
      ],
      target: "2026年12月期 売上収益4,900億円（前期比7.0%増）・営業利益335億円",
    },
    strengths: [
      "ガストを中核とした圧倒的な店舗ネットワーク",
      "業態転換の柔軟性（不採算店→しゃぶ葉等へ転換）",
      "セントラルキッチンによるコスト管理と品質均一化",
      "配膳ロボット等DXによる生産性向上",
    ],
    challenges: [
      "原材料費・人件費の上昇圧力",
      "既存店の老朽化と改装投資の必要性",
      "消費者の外食離れ・中食シフトへの対応",
      "M&A統合リスク（資さんうどん等のPMI）",
    ],
    latestNews: [
      { date: "2026-03-24", headline: "干物定食「しんぱち食堂」を買収、資さんうどんに続き低価格帯を強化" },
      { date: "2026-03-12", headline: "資さんうどんが100店舗達成、神奈川県寒川町に出店" },
      { date: "2026-02-13", headline: "2025年12月期決算発表、営業利益300億円で10期ぶり最高益更新" },
    ],
  },
  {
    slug: "mcdonalds-japan",
    name: "日本マクドナルドHD",
    nameEn: "McDonald's Holdings Japan",
    logo: "M",
    color: "#f59e0b",
    stockCode: "2702",
    overview:
      "マクドナルドの日本法人。全国約3,025店舗を展開し、全店売上高は過去最高の8,886億円を達成。既存店売上高は41四半期連続プラスを継続。フランチャイズモデル主体で高い収益性を維持し、デジタル・モバイルオーダーの普及率も業界トップクラス。2025年12月期は3期連続最高益を達成。",
    financials: {
      revenue: "4,166億円",
      revenueYoy: "+2.7%",
      operatingProfit: "533億円",
      opMargin: "12.8%",
      keyMetric: "約3,025店",
      keyMetricLabel: "店舗数",
      fiscalYear: "2025年12月期",
    },
    pl: {
      revenue: "4,166億円",
      cogs: "2,410億円",
      grossProfit: "1,756億円",
      grossMargin: "42.2%",
      sga: "1,223億円",
      rd: "—",
      operatingProfit: "533億円",
      opMargin: "12.8%",
      netIncome: "339億円",
      netMargin: "8.1%",
      fiscalYear: "2025年12月期",
    },
    bs: {
      totalAssets: "3,645億円",
      currentAssets: "1,100億円",
      cash: "600億円",
      fixedAssets: "2,545億円",
      totalLiab: "1,700億円",
      currentLiab: "950億円",
      fixedLiab: "750億円",
      interestBearingDebt: "—",
      equity: "1,945億円",
      equityRatio: "77.0%",
      fiscalYear: "2025年12月期",
    },
    cf: {
      operatingCF: "+532億円",
      investingCF: "-425億円",
      financingCF: "-67億円",
      freeCF: "+107億円",
      capex: "400億円",
      dividends: "56円/株",
      fiscalYear: "2025年12月期",
    },
    strategy: {
      title: "成長戦略",
      summary:
        "2025-2027年度中期経営計画で「メニュー・バリュー」「店舗ポートフォリオ・デジタル」「サステナビリティ・ピープル」の3領域に注力。3年間で100店舗以上の純増と、モバイルオーダー・タッチパネル注文の全店導入を推進。",
      keyPoints: [
        "3年間で100店舗以上の純増",
        "モバイルオーダー・デジタル投資の加速",
        "メニューイノベーションとバリュー戦略",
        "株主資本配当率（DOE）3%目標",
      ],
      target: "2027年12月期 全店売上高1兆円・営業利益率10%以上維持",
    },
    strengths: [
      "41四半期連続既存店プラスの圧倒的ブランド力",
      "フランチャイズモデルによる高い営業利益率（12.8%）",
      "デジタル・モバイルオーダーの業界最高水準の普及",
      "無借金経営に近い強固な財務基盤",
    ],
    challenges: [
      "原材料費（牛肉・小麦等）の国際価格上昇",
      "フランチャイジーの人材確保難",
      "国内市場の成熟化と出店余地の限界",
      "健康志向の高まりへの対応",
    ],
    latestNews: [
      { date: "2026-02-13", headline: "2026年1月度の既存店売上高11.7%増と好調持続" },
      { date: "2026-02-06", headline: "2025年12月期決算発表、営業利益533億円で3期連続最高益" },
      { date: "2026-02-06", headline: "2026年12月期予想：SWS9,420億円・営業利益545億円、40-80店純増計画" },
      { date: "2025-09-30", headline: "店舗数3,000店を突破、マイルストーン達成" },
    ],
  },
  {
    slug: "toridoll-hd",
    name: "トリドールHD",
    nameEn: "Toridoll Holdings",
    logo: "丸",
    color: "#10b981",
    stockCode: "3397",
    overview:
      "讃岐うどん「丸亀製麺」を主力ブランドとする外食チェーン。国内外で14カ国に約1,167店舗を展開し、約20ブランドを運営。2026年3月期Q3累計は売上収益2,105億円（前年同期比4.3%増）、営業利益163億円（同41.0%増）と大幅増益。丸亀製麺の営業利益率は18%に到達し過去最高水準。",
    financials: {
      revenue: "2,820億円（予想）",
      revenueYoy: "+5.1%",
      operatingProfit: "146億円（予想）",
      opMargin: "5.2%",
      keyMetric: "約1,167店",
      keyMetricLabel: "店舗数",
      fiscalYear: "2026年3月期（予想）",
    },
    pl: {
      revenue: "2,820億円（予想）",
      cogs: "840億円",
      grossProfit: "1,980億円",
      grossMargin: "70.2%",
      sga: "1,834億円",
      rd: "—",
      operatingProfit: "146億円（予想）",
      opMargin: "5.2%",
      netIncome: "55億円（予想）",
      netMargin: "2.0%",
      fiscalYear: "2026年3月期（予想）",
    },
    bs: {
      totalAssets: "3,232億円",
      currentAssets: "550億円",
      cash: "280億円",
      fixedAssets: "2,682億円",
      totalLiab: "2,267億円",
      currentLiab: "700億円",
      fixedLiab: "1,567億円",
      interestBearingDebt: "914億円",
      equity: "965億円",
      equityRatio: "27.0%",
      fiscalYear: "2026年3月期Q2（2025年9月末）",
    },
    cf: {
      operatingCF: "+380億円",
      investingCF: "-300億円",
      financingCF: "-50億円",
      freeCF: "+80億円",
      capex: "280億円",
      dividends: "11円/株",
      fiscalYear: "2025年3月期",
    },
    strategy: {
      title: "成長戦略",
      summary:
        "国内丸亀製麺の収益力強化を軸に、海外展開を「MARUGAME UDON」ブランドで加速。2028年3月期までに海外3,000店舗を目標。不採算海外事業は売却・FC化で効率化し、国内の繁盛店モデルを海外に展開する戦略。",
      keyPoints: [
        "海外3,000店舗目標（2028年3月期）",
        "丸亀製麺の国内既存店強化と過去最高利益の継続",
        "不採算海外事業の整理・FC化（英国事業売却等）",
        "多ブランド戦略（ずんどう屋等の海外展開）",
      ],
      target: "2028年3月期 海外3,000店舗・グローバル外食企業へ",
    },
    strengths: [
      "丸亀製麺の圧倒的ブランド力と高収益性（営業利益率18%）",
      "製麺から調理まで店内一貫製造によるライブ感と品質",
      "14ヶ国・20ブランドの多角的海外展開",
      "海外MARUGAME UDONが300店舗突破、高い成長性",
    ],
    challenges: [
      "海外事業の収益化と減損リスクへの対応",
      "英国等一部地域の市況悪化への対応",
      "有利子負債914億円と財務レバレッジの管理",
      "原材料費・人件費上昇による利益圧迫",
    ],
    latestNews: [
      { date: "2026-03-23", headline: "正社員6.12%賃上げで妥結、3年連続で組合要求超の満額以上" },
      { date: "2026-02-13", headline: "2026年3月期Q3決算、営業利益163億円（前年同期比41%増）と大幅増益" },
      { date: "2025-11-17", headline: "2026年3月期中間期で売上・利益共に過去最高、丸亀製麺の営業利益率18%" },
    ],
  },
  {
    slug: "colowide",
    name: "コロワイド",
    nameEn: "Colowide",
    logo: "コ",
    color: "#8b5cf6",
    stockCode: "7616",
    overview:
      "牛角・かっぱ寿司・大戸屋・フレッシュネスバーガー・ステーキ宮等を傘下に持つ総合外食グループ。国内外約2,623店舗を展開。2026年3月期Q3累計は売上収益2,179億円（前年同期比8.7%増）、事業利益96億円（同34.6%増）と増収増益。コラボ企画や食べ放題プロモーションが奏功。",
    financials: {
      revenue: "2,884億円（予想）",
      revenueYoy: "+7.2%",
      operatingProfit: "113億円（予想）",
      opMargin: "3.9%",
      keyMetric: "2,623店",
      keyMetricLabel: "店舗数",
      fiscalYear: "2026年3月期（予想）",
    },
    pl: {
      revenue: "2,884億円（予想）",
      cogs: "910億円",
      grossProfit: "1,974億円",
      grossMargin: "68.4%",
      sga: "1,861億円",
      rd: "—",
      operatingProfit: "113億円（予想）",
      opMargin: "3.9%",
      netIncome: "21億円（予想）",
      netMargin: "0.7%",
      fiscalYear: "2026年3月期（予想）",
    },
    bs: {
      totalAssets: "3,456億円",
      currentAssets: "580億円",
      cash: "260億円",
      fixedAssets: "2,876億円",
      totalLiab: "2,617億円",
      currentLiab: "920億円",
      fixedLiab: "1,697億円",
      interestBearingDebt: "1,841億円",
      equity: "839億円",
      equityRatio: "24.3%",
      fiscalYear: "2026年3月期Q3（2025年12月末）",
    },
    cf: {
      operatingCF: "+200億円",
      investingCF: "-120億円",
      financingCF: "-100億円",
      freeCF: "+80億円",
      capex: "100億円",
      dividends: "5円/株",
      fiscalYear: "2025年3月期",
    },
    strategy: {
      title: "成長戦略",
      summary:
        "国内ではフードコート業態「牛角焼肉食堂」「とんかつ神楽坂さくら」の出店を加速。海外は中東エリアへの新規進出とインドネシアでの牛角・温野菜の拡大を推進。グループ内で原材料共通化を進めコスト効率を向上。",
      keyPoints: [
        "牛角焼肉食堂（FC専門店）の全国展開加速",
        "海外新規エリア（中東）への進出",
        "M&Aによる事業多角化（菓子・給食事業等）",
        "グループ原材料共通化によるコスト削減",
      ],
      target: "2030年3月期 売上高5,000億円",
    },
    strengths: [
      "牛角・大戸屋・かっぱ寿司等の多ブランドポートフォリオ",
      "フードコート業態「牛角焼肉食堂」が60店舗超と急成長",
      "居酒屋・和食・回転寿司・ハンバーガー等幅広い業態カバー",
      "グループ工場活用による原材料の共通化・内製化",
    ],
    challenges: [
      "農畜産物の高騰・慢性的な人手不足によるコスト上昇",
      "かっぱ寿司の競争力回復が課題",
      "有利子負債1,841億円と自己資本比率が低い（24.3%）",
      "消費者の選別志向・節約志向への対応",
    ],
    latestNews: [
      { date: "2026-03-24", headline: "カフェ・ベローチェ・珈琲館のC-Unitedを約440億円で買収、過去最大のM&A" },
      { date: "2026-02-10", headline: "2026年3月期Q3決算、事業利益96億円（前年同期比34.6%増）で通期計画超過" },
      { date: "2025-11-07", headline: "2026年3月期Q2決算、事業利益54億円（前年同期比51.4%増）と大幅増益" },
    ],
  },
];
