export type TrendDirection = "up" | "down" | "flat";
export type IndicatorStatus = "good" | "bad" | "neutral";

export interface EconomicIndicator {
  name: string;
  nameEn: string;
  purpose: string;
  purposeEn?: string;
  value: string;
  valueEn?: string;
  unit: string;
  unitEn?: string;
  trend: TrendDirection;
  status: IndicatorStatus;
  description: string;
  descriptionEn?: string;
  category: "growth" | "prices" | "labor" | "financial" | "trade" | "monetary";
  lastUpdated: string;
  change?: string;
  changeEn?: string;
  sparkline?: number[];
}

export const economicIndicators: EconomicIndicator[] = [
  {
    name: "GDP成長率",
    nameEn: "GDP Growth Rate",
    purpose: "景気全体の伸びや縮みを確認し、日本経済が拡大局面か減速局面かを判断するために見る指標。",
    purposeEn: "Tracks the overall expansion or contraction of the economy to judge whether Japan is in an upturn or slowdown.",
    value: "0.8",
    unit: "%",
    unitEn: "%",
    trend: "down",
    status: "neutral",
    description: "IMF予測（4月2日公表）。外需減と中東紛争の影響で成長鈍化。内需は堅調で失業率も低水準を維持。",
    descriptionEn: "IMF forecast (released April 2). Growth is slowing due to weaker external demand and the Middle East conflict, while domestic demand remains firm and unemployment stays low.",
    category: "growth",
    lastUpdated: "2026-04-09",
    change: "前期 1.2%",
    changeEn: "Previous: 1.2%",
    sparkline: [1.8, 1.5, 1.2, 1.0, 0.9, 0.8],
  },
  {
    name: "消費者物価指数 (CPI)",
    nameEn: "CPI (YoY)",
    purpose: "モノやサービスの値上がり圧力を把握し、家計負担や日銀の金融政策の方向感を読むために見る指標。",
    purposeEn: "Measures price pressure on goods and services to gauge household burden and the likely direction of BOJ monetary policy.",
    value: "1.6",
    unit: "%",
    unitEn: "%",
    trend: "down",
    status: "good",
    description: "生鮮食品を除くコアCPI（2月）。電気・ガス補助金の再開により2022年3月以来の2%割れ。総合CPIは1.3%。3月は原油高と補助金終了で再上昇の見込み。",
    descriptionEn: "Core CPI excluding fresh food (February). The resumption of electricity and gas subsidies pushed it below 2% for the first time since March 2022. Headline CPI is 1.3%. March is expected to rebound on higher oil prices and the end of subsidies.",
    category: "prices",
    lastUpdated: "2026-04-09",
    change: "前月 2.0%",
    changeEn: "Previous: 2.0%",
    sparkline: [3.1, 2.8, 2.5, 2.3, 2.0, 1.6],
  },
  {
    name: "完全失業率",
    nameEn: "Unemployment Rate",
    purpose: "雇用環境の強さを確認し、景気後退の兆しや賃金上昇余地を見極めるために見る指標。",
    purposeEn: "Gauges the strength of the labor market to spot signs of recession and assess room for wage growth.",
    value: "2.6",
    unit: "%",
    unitEn: "%",
    trend: "down",
    status: "good",
    description: "季節調整値（2月）。前月の2.7%から改善。歴史的な低水準を維持。",
    descriptionEn: "Seasonally adjusted figure (February). Improved from 2.7% the previous month and remains at a historically low level.",
    category: "labor",
    lastUpdated: "2026-04-09",
    change: "前月 2.7%",
    changeEn: "Previous: 2.7%",
    sparkline: [2.5, 2.5, 2.4, 2.5, 2.7, 2.6],
  },
  {
    name: "日経平均株価",
    nameEn: "Nikkei 225",
    purpose: "市場が日本企業の業績や先行きリスクをどう織り込んでいるかをざっくり掴むために見る指標。",
    purposeEn: "Offers a quick read on how the market is pricing Japanese corporate earnings and forward-looking risks.",
    value: "56,308",
    valueEn: "56,308",
    unit: "円",
    unitEn: "JPY",
    trend: "up",
    status: "good",
    description: "4月8日は前日比+2,879円（+5.39%）、終値5万6308円。米・イランが2週間の即時停戦で合意し、ホルムズ海峡が全面再開へ。歴代3位の上げ幅を記録。",
    descriptionEn: "Closed up 2,879 yen (+5.39%) on April 8 to 56,308 yen — the third-largest daily gain on record. The US and Iran agreed on a two-week ceasefire, reopening the Strait of Hormuz.",
    category: "financial",
    lastUpdated: "2026-04-09",
    change: "前日 53,429円",
    changeEn: "Previous: 53,429 JPY",
    sparkline: [50000, 52463, 53123, 53414, 53429, 56308],
  },
  {
    name: "円ドル為替レート",
    nameEn: "USD/JPY",
    purpose: "輸入物価、企業収益、海外投資の採算に直結する円安・円高の流れを確認するために見る指標。",
    purposeEn: "Tracks yen weakness or strength, which directly affects import prices, corporate earnings, and overseas investment returns.",
    value: "159.8",
    valueEn: "159.8",
    unit: "円/ドル",
    unitEn: "JPY/USD",
    trend: "up",
    status: "bad",
    description: "原油高継続で円安圧力が強い。トランプ大統領のイラン猶予期限到来で地政学リスクが高まり、リスクオフの円買いとの綱引き。日銀4月会合での利上げ観測は6-7割。",
    descriptionEn: "Sustained high oil prices keep downward pressure on the yen. Rising geopolitical risk from Trump's Iran deadline is offsetting risk-off yen buying. Markets price a 60-70% chance of a BOJ rate hike at the April meeting.",
    category: "financial",
    lastUpdated: "2026-04-09",
    change: "前日 159.6円",
    changeEn: "Previous: 159.6",
    sparkline: [153, 155, 158, 159.0, 159.6, 159.8],
  },
  {
    name: "経常収支",
    nameEn: "Current Account",
    purpose: "日本が海外との取引や投資でどれだけ稼げているかを確認し、対外的な稼ぐ力を測るために見る指標。",
    purposeEn: "Measures how much Japan earns from overseas trade and investment, reflecting its external earning power.",
    value: "+9,426",
    valueEn: "+9,426",
    unit: "億円",
    unitEn: "100M JPY",
    trend: "up",
    status: "good",
    description: "2026年1月の経常収支黒字。前年同月比で大幅改善。",
    descriptionEn: "Current account surplus for January 2026. Significantly improved year on year.",
    category: "trade",
    lastUpdated: "2026-04-09",
    change: "前年同月 +6,831億円",
    changeEn: "Year ago: +6,831 (100M JPY)",
    sparkline: [5200, 5800, 6200, 6831, 8100, 9426],
  },
  {
    name: "貿易収支",
    nameEn: "Trade Balance",
    purpose: "輸出と輸入のバランスを確認し、為替や資源価格が日本経済に与える影響を読むために見る指標。",
    purposeEn: "Tracks the balance of exports and imports to gauge how FX moves and commodity prices are affecting Japan.",
    value: "+573",
    valueEn: "+573",
    unit: "億円",
    unitEn: "100M JPY",
    trend: "down",
    status: "neutral",
    description: "2026年2月の貿易収支。黒字は維持するも前年同月比で大幅減。",
    descriptionEn: "Trade balance for February 2026. Still in surplus but down sharply year on year.",
    category: "trade",
    lastUpdated: "2026-04-09",
    change: "前月 +1,234億円",
    changeEn: "Previous: +1,234 (100M JPY)",
    sparkline: [800, 1500, 1200, 1234, 900, 573],
  },
  {
    name: "日銀政策金利",
    nameEn: "BOJ Policy Rate",
    purpose: "住宅ローン金利や企業の資金調達コストに影響する金融政策スタンスを確認するために見る指標。",
    purposeEn: "Signals the BOJ's policy stance, which influences mortgage rates and corporate funding costs.",
    value: "0.75",
    unit: "%",
    unitEn: "%",
    trend: "up",
    status: "neutral",
    description: "3月会合で据え置き（8対1）。高田委員が1%を主張し反対。IMFは利上げ継続を勧告。市場は4月27-28日会合での利上げを6-7割織り込み。",
    descriptionEn: "Held steady at the March meeting (8-1 vote). Board member Takata dissented, calling for 1%. The IMF has recommended continued rate hikes, and markets price a 60-70% chance of a hike at the April 27-28 meeting.",
    category: "monetary",
    lastUpdated: "2026-04-09",
    change: "前回 0.50%",
    changeEn: "Previous: 0.50%",
    sparkline: [0, 0, 0.1, 0.25, 0.5, 0.75],
  },
  {
    name: "10年国債利回り",
    nameEn: "10Y JGB Yield",
    purpose: "長期金利の水準を確認し、将来の成長期待やインフレ見通し、市場の金利観を把握するために見る指標。",
    purposeEn: "Shows the level of long-term rates and reflects expectations for growth, inflation, and future monetary policy.",
    value: "2.39",
    unit: "%",
    unitEn: "%",
    trend: "up",
    status: "neutral",
    description: "ホルムズ海峡封鎖によるインフレ懸念で25年ぶりの高水準。日銀の追加利上げ観測も長期金利を押し上げ。",
    descriptionEn: "At a 25-year high on inflation concerns from the Hormuz Strait blockade. Expectations of further BOJ rate hikes are also pushing long-term yields higher.",
    category: "monetary",
    lastUpdated: "2026-04-09",
    change: "前日 2.40%",
    changeEn: "Previous: 2.40%",
    sparkline: [1.0, 1.3, 1.7, 2.1, 2.40, 2.39],
  },
  {
    name: "マネーストック M2",
    nameEn: "Money Supply M2",
    purpose: "市中にどれだけお金が出回っているかを確認し、金融緩和の効き具合や資金需要をみるために見る指標。",
    purposeEn: "Measures the amount of money circulating in the economy to assess the effectiveness of easing and funding demand.",
    value: "1,274.9",
    valueEn: "1,274.9",
    unit: "兆円",
    unitEn: "trillion JPY",
    trend: "down",
    status: "neutral",
    description: "2026年2月のM2残高。前月比でやや減少。",
    descriptionEn: "M2 balance for February 2026. Slightly down from the previous month.",
    category: "monetary",
    lastUpdated: "2026-04-09",
    change: "前月 1,278.3兆円",
    changeEn: "Previous: 1,278.3 trillion JPY",
    sparkline: [1260, 1265, 1270, 1275, 1278, 1274.9],
  },
  {
    name: "鉱工業生産指数",
    nameEn: "Industrial Production",
    purpose: "工場の生産活動の強弱を確認し、輸出や設備投資を含む景気の先行きを読むために見る指標。",
    purposeEn: "Tracks factory output to read the economic outlook, including exports and capital investment.",
    value: "横ばい",
    valueEn: "Flat",
    unit: "",
    unitEn: "",
    trend: "flat",
    status: "neutral",
    description: "米国関税引き上げの前倒し需要と反動減が交錯。全体としてはほぼ横ばい。",
    descriptionEn: "Front-loaded demand from US tariff hikes and the subsequent pullback are offsetting each other, leaving output roughly flat overall.",
    category: "growth",
    lastUpdated: "2026-04-09",
    change: "前月比 ±0.0%",
    changeEn: "MoM: ±0.0%",
    sparkline: [98, 99, 100, 99, 100, 100],
  },
  {
    name: "消費支出",
    nameEn: "Consumer Spending",
    purpose: "家計が実際にどれだけお金を使っているかを確認し、内需の強さを判断するために見る指標。",
    purposeEn: "Measures how much households are actually spending to judge the strength of domestic demand.",
    value: "-1.0",
    unit: "% (前年比)",
    unitEn: "% YoY",
    trend: "down",
    status: "bad",
    description: "2026年2月の実質消費支出（2人以上世帯）は前年同月比-1.0%（名目+0.7%）。物価上昇の影響で実質ベースが落ち込んだ。",
    descriptionEn: "Real consumer spending (two-or-more-person households) fell 1.0% YoY in February 2026 (nominal +0.7%). The drop in real terms reflects the continued impact of price increases.",
    category: "growth",
    lastUpdated: "2026-04-09",
    change: "前月 +0.8%",
    changeEn: "Previous: +0.8%",
    sparkline: [-0.5, 0.1, 0.2, 0.3, 0.8, -1.0],
  },
  {
    name: "有効求人倍率",
    nameEn: "Job-to-Applicant Ratio",
    purpose: "企業の採用意欲と労働需給の逼迫度を確認し、人手不足や賃金上昇圧力をみるために見る指標。",
    purposeEn: "Captures hiring appetite and labor market tightness to gauge labor shortages and wage pressure.",
    value: "1.19",
    unit: "倍",
    unitEn: "x",
    trend: "up",
    status: "neutral",
    description: "2026年2月の有効求人倍率（季節調整値）。前月の1.18から0.01ポイント上昇。依然として1倍超で雇用需要は底堅い。",
    descriptionEn: "Job-to-applicant ratio (seasonally adjusted) for February 2026. Rose 0.01 points from 1.18 the previous month and remains above 1.0, indicating firm hiring demand.",
    category: "labor",
    lastUpdated: "2026-04-09",
    change: "前月 1.18倍",
    changeEn: "Previous: 1.18x",
    sparkline: [1.25, 1.24, 1.22, 1.21, 1.20, 1.18],
  },
];

export interface EconomyNewsItem {
  date: string;
  title: string;
  titleEn?: string;
  summary: string;
  summaryEn?: string;
  category: "policy" | "market" | "trade" | "fiscal" | "labor" | "corporate";
  impact: "positive" | "negative" | "neutral";
  relatedIndicators?: string[];
}

export const economyNews: EconomyNewsItem[] = [
  {
    date: "2026-04-08",
    title: "米・イラン2週間停戦合意で日経平均2,879円高、歴代3位の急騰",
    titleEn: "US-Iran two-week ceasefire drives Nikkei up 2,879 yen — third-largest gain on record",
    summary: "米国とイランが即時2週間停戦で合意（パキスタン仲介）。ホルムズ海峡の全面再開が見込まれ、日経平均は前日比+2,879円の56,308円で終値（歴代3位の上げ幅）。原油先物は急落しWTIは100ドル割れ目前。10日からイスラマバードで最終合意交渉開始。",
    summaryEn: "The US and Iran reached an immediate two-week ceasefire brokered by Pakistan, with a full reopening of the Strait of Hormuz expected. The Nikkei 225 surged 2,879 yen to close at 56,308 — the third-largest single-day gain on record. Crude oil futures fell sharply with WTI approaching sub-$100. Final agreement talks begin in Islamabad on April 10.",
    category: "market",
    impact: "positive",
    relatedIndicators: ["Nikkei 225", "Trade Balance", "CPI (YoY)"],
  },
  {
    date: "2026-04-07",
    title: "トランプ大統領のイラン猶予期限が到来、原油113ドル台で高止まり",
    titleEn: "Trump's Iran deadline arrives; oil holds above $113",
    summary: "トランプ大統領がイランに設定した猶予期限が4月6日夜（日本時間7日午前9時）に到来。ホルムズ海峡では4月5日に15隻が通過したが本格的な封鎖解除には至っておらず、WTI原油は113.85ドルと高止まり。市場は次の展開を注視。",
    summaryEn: "The deadline President Trump set for Iran passed on the evening of April 6 (9 a.m. JST on April 7). While 15 vessels transited the Strait of Hormuz on April 5, the blockade has not been fully lifted and WTI crude remains elevated at $113.85. Markets are watching for the next move.",
    category: "trade",
    impact: "negative",
    relatedIndicators: ["CPI (YoY)", "Trade Balance", "Nikkei 225"],
  },
  {
    date: "2026-04-06",
    title: "日経平均53,414円、ホルムズ海峡通航許可で反発",
    titleEn: "Nikkei 225 rebounds to 53,414 on Hormuz transit approval",
    summary: "イランが日欧船舶の海峡通航を許可したことを好感し、日経平均は前日比+290円の53,414円で引け。商船三井LNG船「ソハール」の通過も確認され、封鎖緩和への期待が広がる。",
    summaryEn: "The Nikkei 225 closed up 290 yen at 53,414 after Iran cleared Japanese and European ships to transit the strait. MOL's LNG carrier Sohar was also confirmed to have passed through, fueling hopes of an easing blockade.",
    category: "market",
    impact: "positive",
    relatedIndicators: ["Nikkei 225"],
  },
  {
    date: "2026-04-05",
    title: "ホルムズ海峡で15隻が通過、商船三井LNG船も確認",
    titleEn: "15 vessels transit Hormuz Strait, including MOL LNG carrier",
    summary: "イランの許可を得て15隻がホルムズ海峡を通過（ファルス通信報道）。商船三井のLNG船「ソハール」も通過を確認。湾内にはなお約2,190隻・約2万人の乗員が足止め状態。日本関係船舶は約44-45隻。",
    summaryEn: "With Iran's permission, 15 vessels transited the Strait of Hormuz (per Fars News). MOL's LNG carrier Sohar was among them. Roughly 2,190 ships and 20,000 crew remain stranded in the Gulf, including about 44-45 Japan-linked vessels.",
    category: "trade",
    impact: "positive",
    relatedIndicators: ["Trade Balance", "CPI (YoY)"],
  },
  {
    date: "2026-04-04",
    title: "イラン、日本・欧州船舶のホルムズ海峡通航を初めて許可　原油先物やや下落",
    titleEn: "Iran first allows Japan and Europe ships through Hormuz; oil futures ease",
    summary: "封鎖後初めて日欧の関係船舶がホルムズ海峡の通航を認められた。海峡再開への期待から日経平均は一時1.7%上昇し53,300円台を回復。ただし本格的な通航再開には至っておらず、先行き不透明。",
    summaryEn: "For the first time since the blockade began, Japanese and European vessels were permitted to transit the Strait of Hormuz. Hopes of a reopening lifted the Nikkei 225 as much as 1.7% to reclaim the 53,300 level, though a full resumption of traffic remains uncertain.",
    category: "market",
    impact: "positive",
    relatedIndicators: ["Nikkei 225", "CPI (YoY)"],
  },
  {
    date: "2026-04-01",
    title: "日銀短観3月調査、大企業製造業DI＋17と改善も先行きは大幅悪化",
    titleEn: "BOJ Tankan March: large manufacturer DI improves to +17 but outlook slumps",
    summary: "大企業製造業の業況判断DIは＋17と前回（＋15）から改善し2021年Q4以来の高水準。一方、先行きDIは原油高・中東情勢の不透明感を反映して大幅に悪化。",
    summaryEn: "The business conditions DI for large manufacturers rose to +17 from +15, the highest since Q4 2021. The forward-looking DI, however, deteriorated sharply, reflecting high oil prices and uncertainty over the Middle East.",
    category: "corporate",
    impact: "neutral",
    relatedIndicators: ["GDP Growth Rate", "Nikkei 225"],
  },
  {
    date: "2026-04-01",
    title: "4月の食品値上げ2,798品目、2026年初の値上げラッシュ",
    titleEn: "2,798 food items see April price hikes, the first wave of 2026",
    summary: "帝国データバンク調べで4月の飲食料品値上げは2,798品目（平均14%）。調味料1,514品目、加工食品609品目、酒類・飲料369品目。電気・ガス補助金も3月末で終了し家計への影響大。",
    summaryEn: "According to Teikoku Databank, 2,798 food and beverage items are seeing April price hikes (average 14%): 1,514 seasonings, 609 processed foods, and 369 alcoholic drinks and beverages. Electricity and gas subsidies also ended at the close of March, adding pressure on households.",
    category: "market",
    impact: "negative",
    relatedIndicators: ["CPI (YoY)", "Consumer Spending"],
  },
  {
    date: "2026-04-01",
    title: "暫定予算8.6兆円が成立、本予算122.3兆円は4月11日に自然成立見込み",
    titleEn: "8.6 trillion yen stopgap budget enacted; 122.3 trillion main budget to pass April 11",
    summary: "本予算（一般会計122.3兆円、過去最大）は衆院通過済みだが参院審議中のため、4月1〜11日をカバーする暫定予算8.6兆円が成立。11年ぶりの暫定予算。本予算は憲法の30日ルールにより4月11日に自然成立の見込み。",
    summaryEn: "With the main budget (a record 122.3 trillion yen general account) already through the lower house but still under Upper House review, a 8.6 trillion yen stopgap budget covering April 1-11 was enacted, the first in 11 years. The main budget is expected to pass automatically on April 11 under the constitution's 30-day rule.",
    category: "fiscal",
    impact: "neutral",
  },
  {
    date: "2026-04-01",
    title: "防衛増税が始動　たばこ税・法人税が引き上げ",
    titleEn: "Defense tax hikes begin: tobacco and corporate taxes raised",
    summary: "防衛費増額の財源として、たばこ税と法人税の引き上げが4月1日に施行。段階的な増税の第一弾として実施。",
    summaryEn: "Increases in the tobacco tax and corporate tax to fund higher defense spending took effect on April 1, marking the first step in a phased tax-hike plan.",
    category: "fiscal",
    impact: "neutral",
  },
  {
    date: "2026-03-31",
    title: "東京都区部3月CPI、前年比+1.7%　原油高の影響は限定的",
    titleEn: "Tokyo core CPI +1.7% YoY in March; oil price impact still limited",
    summary: "東京都区部の3月消費者物価指数（生鮮食品除く）は前年比+1.7%。2月の全国コアCPI+1.6%からやや上昇も、原油高の本格的な波及は4月以降の見通し。",
    summaryEn: "Tokyo's March CPI excluding fresh food rose 1.7% year on year, edging up from the nationwide core CPI of 1.6% in February. The full pass-through from higher oil prices is expected from April onward.",
    category: "policy",
    impact: "neutral",
    relatedIndicators: ["CPI (YoY)", "BOJ Policy Rate"],
  },
  {
    date: "2026-03-26",
    title: "政府、原油国家備蓄の放出を開始　ホルムズ海峡迂回ルートも拡大",
    titleEn: "Japan taps national oil reserves and expands Hormuz bypass routes",
    summary: "ホルムズ海峡の事実上の封鎖を受け、政府は国家石油備蓄の一部放出を決定。同時にマレーシア経由の迂回輸入ルート拡大や、米国・カナダからのLNG調達強化を進める。",
    summaryEn: "In response to the de facto closure of the Strait of Hormuz, the government has decided to release part of its national oil reserves while expanding bypass import routes via Malaysia and stepping up LNG procurement from the US and Canada.",
    category: "policy",
    impact: "neutral",
    relatedIndicators: ["CPI (YoY)", "Trade Balance"],
  },
  {
    date: "2026-03-24",
    title: "2月コアCPI、前年比+1.6%　2022年3月以来の2%割れ",
    titleEn: "February core CPI +1.6% YoY, below 2% for first time since March 2022",
    summary: "生鮮食品を除くコアCPIは前年同月比+1.6%。電気・ガス補助金の再開が主因で、電気代は前年比-8.0%。総合CPIは+1.3%まで低下。3月以降は原油高と補助金終了で再上昇の見込み。",
    summaryEn: "Core CPI excluding fresh food rose 1.6% year on year. The main driver was the resumption of electricity and gas subsidies, which pulled electricity prices down 8.0% YoY. Headline CPI slowed to +1.3%. From March it is expected to rebound on higher oil prices and the end of subsidies.",
    category: "policy",
    impact: "positive",
    relatedIndicators: ["CPI (YoY)", "BOJ Policy Rate"],
  },
  {
    date: "2026-03-23",
    title: "春闘1次集計、賃上げ率5.26%　大手で満額回答相次ぐ",
    titleEn: "Shunto first tally: wage hikes 5.26%, full answers common at large firms",
    summary: "連合の第1回集計（1,100組合）で賃上げ率は5.26%（ベア3.85%）。自動車・電機など大手で満額回答が相次ぎ、3年連続5%超の高水準を維持。",
    summaryEn: "In Rengo's first tally of 1,100 unions, the wage hike rate came in at 5.26% (3.85% base pay increase). Major automakers and electronics firms granted full demands in many cases, keeping the figure above 5% for a third straight year.",
    category: "labor",
    impact: "positive",
    relatedIndicators: ["Consumer Spending", "Unemployment Rate"],
  },
  {
    date: "2026-03-19",
    title: "日銀、政策金利0.75%で据え置き（8対1）",
    titleEn: "BOJ holds policy rate at 0.75% in 8-1 vote",
    summary: "日銀は金融政策決定会合で政策金利を0.75%に据え置き。8対1で決定（高田委員が1%への利上げを主張し反対）。中東情勢の不透明感を注視しつつ、利上げ継続の姿勢は維持。",
    summaryEn: "The BOJ kept its policy rate at 0.75% at its monetary policy meeting in an 8-1 vote, with board member Takata dissenting in favor of a hike to 1%. The Bank maintained a stance of further hikes while watching Middle East uncertainty.",
    category: "policy",
    impact: "neutral",
    relatedIndicators: ["BOJ Policy Rate", "10Y JGB Yield", "USD/JPY"],
  },
  {
    date: "2026-03-13",
    title: "令和8年度予算案が衆議院を通過、参議院へ送付",
    titleEn: "FY2026 budget passes lower house, sent to upper house",
    summary: "一般会計総額122.3兆円（過去最大）の予算案が衆議院本会議で可決。1月の衆院解散で審議日程が圧縮され、参院での30日ルールによる自然成立（4月11日）が確定的に。",
    summaryEn: "A record 122.3 trillion yen general account budget cleared the lower house plenary. With the January dissolution compressing the schedule, automatic passage in the upper house under the 30-day rule on April 11 is now all but certain.",
    category: "fiscal",
    impact: "neutral",
    relatedIndicators: ["GDP Growth Rate"],
  },
  {
    date: "2026-03-11",
    title: "米USTR、日本含む16カ国にセクション301調査を開始",
    titleEn: "USTR opens Section 301 probes on 16 economies including Japan",
    summary: "米通商代表部が「製造業の構造的過剰生産能力」を理由に、日本を含む16の経済圏に対しセクション301調査を開始。7月24日までに関税措置の可否を判断する方針。IEEPA関税の代替手段として注目。",
    summaryEn: "The USTR opened Section 301 investigations into 16 economies including Japan, citing structural manufacturing overcapacity. It plans to decide on tariff action by July 24. The probes are drawing attention as a possible alternative to IEEPA tariffs.",
    category: "trade",
    impact: "negative",
    relatedIndicators: ["Trade Balance", "Nikkei 225"],
  },
  {
    date: "2026-03-10",
    title: "1月経常収支、9,426億円の黒字　前年比+38%",
    titleEn: "January current account surplus 942.6 billion yen, up 38% YoY",
    summary: "海外投資からの第一次所得収支が拡大し、経常収支は前年同月比38%増の黒字を記録。円安による海外利益の膨張が寄与。",
    summaryEn: "A bigger primary income surplus from overseas investments drove the current account surplus 38% higher year on year. Yen weakness, which inflates foreign earnings in yen terms, was a key contributor.",
    category: "trade",
    impact: "positive",
    relatedIndicators: ["Current Account", "USD/JPY"],
  },
  {
    date: "2026-03-07",
    title: "実質消費支出、前年比+0.8%で3ヶ月連続増",
    titleEn: "Real consumer spending +0.8% YoY, third straight monthly gain",
    summary: "総務省の家計調査で1月の実質消費支出は前年同月比+0.8%と3ヶ月連続の増加。賃上げ効果が徐々に消費に波及。",
    summaryEn: "Real consumer spending rose 0.8% year on year in January, the third straight monthly increase, according to the MIC household survey. Wage hikes are gradually feeding through to consumption.",
    category: "labor",
    impact: "positive",
  },
  {
    date: "2026-03-05",
    title: "ホルムズ海峡が事実上封鎖　大手海運がペルシャ湾通過を停止",
    titleEn: "Strait of Hormuz effectively closed as major shippers halt Gulf transits",
    summary: "大手海上保険会社が戦争リスク保険の引き受けを停止したことで、日本郵船・川崎汽船など主要海運がホルムズ海峡通過を停止。日本の輸入原油の約92%が中東経由であり、エネルギー安全保障上の重大な危機。",
    summaryEn: "With leading marine insurers suspending war-risk coverage, Japanese shipping majors including NYK Line and K Line halted transits of the Strait of Hormuz. Since roughly 92% of Japan's crude imports come via the Middle East, this marks a serious energy security crisis.",
    category: "trade",
    impact: "negative",
    relatedIndicators: ["CPI (YoY)", "Trade Balance"],
  },
  {
    date: "2026-03-02",
    title: "原油価格が急騰、WTI112ドル超　イラン革命防衛隊がホルムズ海峡封鎖を宣言",
    titleEn: "Oil jumps past $112 on IRGC's Hormuz blockade declaration",
    summary: "米・イスラエルによるイラン空爆（2月28日）を受け、イラン革命防衛隊がホルムズ海峡の封鎖を宣言。WTI原油先物は112ドル超に急騰し2022年以来の高値。ブレントはピーク時126ドルに達した。",
    summaryEn: "After US and Israeli airstrikes on Iran on February 28, the Islamic Revolutionary Guard Corps declared a blockade of the Strait of Hormuz. WTI crude futures surged above $112, the highest since 2022, and Brent peaked at $126.",
    category: "trade",
    impact: "negative",
    relatedIndicators: ["CPI (YoY)", "Trade Balance", "USD/JPY"],
  },
  {
    date: "2026-02-28",
    title: "有効求人倍率、1.18倍に低下も高水準維持",
    titleEn: "Job-to-applicant ratio slips to 1.18 but stays elevated",
    summary: "1月の有効求人倍率は1.18倍と前月から0.02ポイント低下。人手不足は継続も、一部業種で求人の慎重姿勢が見られる。",
    summaryEn: "The January job-to-applicant ratio fell 0.02 point from the previous month to 1.18. Labor shortages persist, though some industries are showing a more cautious hiring stance.",
    category: "labor",
    impact: "neutral",
  },
  {
    date: "2026-02-24",
    title: "トランプ大統領、セクション122に基づく暫定10%関税を発動",
    titleEn: "Trump invokes Section 122 to impose interim 10% tariff",
    summary: "最高裁によるIEEPA関税違憲判決を受け、トランプ大統領は貿易法セクション122に基づき全世界からの輸入品に一律10%の暫定関税を発動。有効期限は150日間（7月24日まで）。",
    summaryEn: "Following the Supreme Court's ruling that IEEPA tariffs were unconstitutional, President Trump invoked Section 122 of the Trade Act to impose a flat 10% interim tariff on all imports for a 150-day period ending July 24.",
    category: "trade",
    impact: "negative",
    relatedIndicators: ["Trade Balance", "USD/JPY"],
  },
  {
    date: "2026-02-20",
    title: "米最高裁、IEEPA相互関税を違憲と判決　関税は即時停止",
    titleEn: "US Supreme Court strikes down IEEPA reciprocal tariffs; levies halt immediately",
    summary: "米連邦最高裁が2025年4月のIEEPA（国際緊急経済権限法）に基づく相互関税を違法・無効と判決。日本への15%関税を含む全IEEPA関税が2月24日に停止。トランプ政権は代替手段を模索。",
    summaryEn: "The US Supreme Court ruled the April 2025 reciprocal tariffs imposed under the International Emergency Economic Powers Act (IEEPA) unlawful and void. All IEEPA-based tariffs, including the 15% on Japan, were halted on February 24. The Trump administration is now seeking alternatives.",
    category: "trade",
    impact: "positive",
    relatedIndicators: ["Trade Balance", "Nikkei 225", "USD/JPY"],
  },
  {
    date: "2026-02-18",
    title: "第2次高市内閣発足、経済政策の継続を表明",
    titleEn: "Second Takaichi cabinet launches, pledges continuity on the economy",
    summary: "衆院選大勝を受け第2次高市内閣が発足。高市首相は「賃上げと投資の好循環を加速する」と表明し、戦略的インフラ投資の強化を掲げる。",
    summaryEn: "Following a sweeping election win, the second Takaichi cabinet took office. Prime Minister Takaichi pledged to accelerate a virtuous cycle of wage hikes and investment and to strengthen strategic infrastructure spending.",
    category: "policy",
    impact: "neutral",
  },
  {
    date: "2026-02-10",
    title: "日経平均、終値5万7,000円超え　衆院選後の最高値更新",
    titleEn: "Nikkei 225 closes above 57,000, a new post-election high",
    summary: "衆院選で与党圧勝を受け、海外投資家の日本株選好が加速。日経平均は終値で5万7,000円を突破し、2025年10月の5万円突破からわずか4ヶ月で7,000円上昇。",
    summaryEn: "After the ruling coalition's landslide election win, foreign investors ramped up their preference for Japanese equities. The Nikkei 225 closed above 57,000, rising 7,000 points in just four months since clearing 50,000 in October 2025.",
    category: "market",
    impact: "positive",
  },
  {
    date: "2025-12-19",
    title: "日銀、政策金利を0.75%に引き上げ",
    titleEn: "BOJ raises policy rate to 0.75%",
    summary: "日銀は0.50%から0.75%への追加利上げを決定。1995年9月以来約30年ぶりの高水準。為替市場では一時円高に振れるも、その後円安基調に回帰。",
    summaryEn: "The BOJ decided to raise its policy rate from 0.50% to 0.75%, the highest level in about 30 years, since September 1995. The yen briefly strengthened in FX markets before reverting to a weaker trend.",
    category: "policy",
    impact: "neutral",
    relatedIndicators: ["BOJ Policy Rate", "USD/JPY", "10Y JGB Yield"],
  },
];

export const newsCategoryLabels: Record<string, string> = {
  policy: "政策",
  market: "市場",
  trade: "貿易",
  fiscal: "財政",
  labor: "雇用",
  corporate: "企業",
};

export const newsCategoryLabelsEn: Record<string, string> = {
  policy: "Policy",
  market: "Market",
  trade: "Trade",
  fiscal: "Fiscal",
  labor: "Labor",
  corporate: "Corporate",
};

export const categoryLabels: Record<string, { ja: string; en: string }> = {
  growth: { ja: "成長・生産", en: "Growth & Production" },
  prices: { ja: "物価", en: "Prices" },
  labor: { ja: "雇用", en: "Labor" },
  financial: { ja: "金融市場", en: "Financial Markets" },
  trade: { ja: "貿易・国際収支", en: "Trade & Balance of Payments" },
  monetary: { ja: "金融政策", en: "Monetary Policy" },
};
