export type TrendDirection = "up" | "down" | "flat";
export type IndicatorStatus = "good" | "bad" | "neutral";

export interface EconomicIndicator {
  name: string;
  nameEn: string;
  purpose: string;
  value: string;
  unit: string;
  trend: TrendDirection;
  status: IndicatorStatus;
  description: string;
  category: "growth" | "prices" | "labor" | "financial" | "trade" | "monetary";
  lastUpdated: string;
  change?: string;
  sparkline?: number[];
}

export const economicIndicators: EconomicIndicator[] = [
  {
    name: "GDP成長率",
    nameEn: "GDP Growth Rate",
    purpose: "景気全体の伸びや縮みを確認し、日本経済が拡大局面か減速局面かを判断するために見る指標。",
    value: "0.8",
    unit: "%",
    trend: "down",
    status: "neutral",
    description: "IMF予測（4月2日公表）。外需減と中東紛争の影響で成長鈍化。内需は堅調で失業率も低水準を維持。",
    category: "growth",
    lastUpdated: "2026-04-02",
    change: "前期 1.2%",
    sparkline: [1.8, 1.5, 1.2, 1.0, 0.9, 0.8],
  },
  {
    name: "消費者物価指数 (CPI)",
    nameEn: "CPI (YoY)",
    purpose: "モノやサービスの値上がり圧力を把握し、家計負担や日銀の金融政策の方向感を読むために見る指標。",
    value: "1.6",
    unit: "%",
    trend: "down",
    status: "good",
    description: "生鮮食品を除くコアCPI（2月）。電気・ガス補助金の再開により2022年3月以来の2%割れ。総合CPIは1.3%。3月は原油高と補助金終了で再上昇の見込み。",
    category: "prices",
    lastUpdated: "2026-03-24",
    change: "前月 2.0%",
    sparkline: [3.1, 2.8, 2.5, 2.3, 2.0, 1.6],
  },
  {
    name: "完全失業率",
    nameEn: "Unemployment Rate",
    purpose: "雇用環境の強さを確認し、景気後退の兆しや賃金上昇余地を見極めるために見る指標。",
    value: "2.6",
    unit: "%",
    trend: "down",
    status: "good",
    description: "季節調整値（2月）。前月の2.7%から改善。歴史的な低水準を維持。",
    category: "labor",
    lastUpdated: "2026-03-28",
    change: "前月 2.7%",
    sparkline: [2.5, 2.5, 2.4, 2.5, 2.7, 2.6],
  },
  {
    name: "日経平均株価",
    nameEn: "Nikkei 225",
    purpose: "市場が日本企業の業績や先行きリスクをどう織り込んでいるかをざっくり掴むために見る指標。",
    value: "53,414",
    unit: "円",
    trend: "up",
    status: "neutral",
    description: "4月6日は前日比+290円。ホルムズ海峡で日欧船舶15隻の通過が確認され、封鎖緩和期待で買い優勢。ただしトランプ大統領のイラン猶予期限到来で先行き不透明。",
    category: "financial",
    lastUpdated: "2026-04-06",
    change: "前日 53,123円",
    sparkline: [47000, 50000, 57000, 52463, 53123, 53414],
  },
  {
    name: "円ドル為替レート",
    nameEn: "USD/JPY",
    purpose: "輸入物価、企業収益、海外投資の採算に直結する円安・円高の流れを確認するために見る指標。",
    value: "159.8",
    unit: "円/ドル",
    trend: "up",
    status: "bad",
    description: "原油高継続で円安圧力が強い。トランプ大統領のイラン猶予期限到来で地政学リスクが高まり、リスクオフの円買いとの綱引き。日銀4月会合での利上げ観測は6-7割。",
    category: "financial",
    lastUpdated: "2026-04-07",
    change: "前日 159.6円",
    sparkline: [153, 155, 158, 159.0, 159.6, 159.8],
  },
  {
    name: "経常収支",
    nameEn: "Current Account",
    purpose: "日本が海外との取引や投資でどれだけ稼げているかを確認し、対外的な稼ぐ力を測るために見る指標。",
    value: "+9,426",
    unit: "億円",
    trend: "up",
    status: "good",
    description: "2026年1月の経常収支黒字。前年同月比で大幅改善。",
    category: "trade",
    lastUpdated: "2026-03-10",
    change: "前年同月 +6,831億円",
    sparkline: [5200, 5800, 6200, 6831, 8100, 9426],
  },
  {
    name: "貿易収支",
    nameEn: "Trade Balance",
    purpose: "輸出と輸入のバランスを確認し、為替や資源価格が日本経済に与える影響を読むために見る指標。",
    value: "+573",
    unit: "億円",
    trend: "down",
    status: "neutral",
    description: "2026年2月の貿易収支。黒字は維持するも前年同月比で大幅減。",
    category: "trade",
    lastUpdated: "2026-03-19",
    change: "前月 +1,234億円",
    sparkline: [800, 1500, 1200, 1234, 900, 573],
  },
  {
    name: "日銀政策金利",
    nameEn: "BOJ Policy Rate",
    purpose: "住宅ローン金利や企業の資金調達コストに影響する金融政策スタンスを確認するために見る指標。",
    value: "0.75",
    unit: "%",
    trend: "up",
    status: "neutral",
    description: "3月会合で据え置き（8対1）。高田委員が1%を主張し反対。IMFは利上げ継続を勧告。市場は4月27-28日会合での利上げを6-7割織り込み。",
    category: "monetary",
    lastUpdated: "2026-03-19",
    change: "前回 0.50%",
    sparkline: [0, 0, 0.1, 0.25, 0.5, 0.75],
  },
  {
    name: "10年国債利回り",
    nameEn: "10Y JGB Yield",
    purpose: "長期金利の水準を確認し、将来の成長期待やインフレ見通し、市場の金利観を把握するために見る指標。",
    value: "2.39",
    unit: "%",
    trend: "up",
    status: "neutral",
    description: "ホルムズ海峡封鎖によるインフレ懸念で25年ぶりの高水準。日銀の追加利上げ観測も長期金利を押し上げ。",
    category: "monetary",
    lastUpdated: "2026-04-03",
    change: "前日 2.40%",
    sparkline: [1.0, 1.3, 1.7, 2.1, 2.40, 2.39],
  },
  {
    name: "マネーストック M2",
    nameEn: "Money Supply M2",
    purpose: "市中にどれだけお金が出回っているかを確認し、金融緩和の効き具合や資金需要をみるために見る指標。",
    value: "1,274.9",
    unit: "兆円",
    trend: "down",
    status: "neutral",
    description: "2026年2月のM2残高。前月比でやや減少。",
    category: "monetary",
    lastUpdated: "2026-03-12",
    change: "前月 1,278.3兆円",
    sparkline: [1260, 1265, 1270, 1275, 1278, 1274.9],
  },
  {
    name: "鉱工業生産指数",
    nameEn: "Industrial Production",
    purpose: "工場の生産活動の強弱を確認し、輸出や設備投資を含む景気の先行きを読むために見る指標。",
    value: "横ばい",
    unit: "",
    trend: "flat",
    status: "neutral",
    description: "米国関税引き上げの前倒し需要と反動減が交錯。全体としてはほぼ横ばい。",
    category: "growth",
    lastUpdated: "2026-03-28",
    change: "前月比 ±0.0%",
    sparkline: [98, 99, 100, 99, 100, 100],
  },
  {
    name: "消費支出",
    nameEn: "Consumer Spending",
    purpose: "家計が実際にどれだけお金を使っているかを確認し、内需の強さを判断するために見る指標。",
    value: "+0.8",
    unit: "% (前年比)",
    trend: "up",
    status: "neutral",
    description: "実質消費支出は緩やかに回復。賃金上昇が消費を下支え。",
    category: "growth",
    lastUpdated: "2026-03-07",
    change: "前月 +0.3%",
    sparkline: [-1.2, -0.5, 0.1, 0.2, 0.3, 0.8],
  },
  {
    name: "有効求人倍率",
    nameEn: "Job-to-Applicant Ratio",
    purpose: "企業の採用意欲と労働需給の逼迫度を確認し、人手不足や賃金上昇圧力をみるために見る指標。",
    value: "1.18",
    unit: "倍",
    trend: "down",
    status: "neutral",
    description: "2026年1月の有効求人倍率。前月の1.20から低下も依然1倍超。",
    category: "labor",
    lastUpdated: "2026-02-28",
    change: "前月 1.20倍",
    sparkline: [1.25, 1.24, 1.22, 1.21, 1.20, 1.18],
  },
];

export interface EconomyNewsItem {
  date: string;
  title: string;
  summary: string;
  category: "policy" | "market" | "trade" | "fiscal" | "labor" | "corporate";
  impact: "positive" | "negative" | "neutral";
  relatedIndicators?: string[];
}

export const economyNews: EconomyNewsItem[] = [
  {
    date: "2026-04-07",
    title: "トランプ大統領のイラン猶予期限が到来、原油113ドル台で高止まり",
    summary: "トランプ大統領がイランに設定した猶予期限が4月6日夜（日本時間7日午前9時）に到来。ホルムズ海峡では4月5日に15隻が通過したが本格的な封鎖解除には至っておらず、WTI原油は113.85ドルと高止まり。市場は次の展開を注視。",
    category: "trade",
    impact: "negative",
    relatedIndicators: ["CPI (YoY)", "Trade Balance", "Nikkei 225"],
  },
  {
    date: "2026-04-06",
    title: "日経平均53,414円、ホルムズ海峡通航許可で反発",
    summary: "イランが日欧船舶の海峡通航を許可したことを好感し、日経平均は前日比+290円の53,414円で引け。商船三井LNG船「ソハール」の通過も確認され、封鎖緩和への期待が広がる。",
    category: "market",
    impact: "positive",
    relatedIndicators: ["Nikkei 225"],
  },
  {
    date: "2026-04-05",
    title: "ホルムズ海峡で15隻が通過、商船三井LNG船も確認",
    summary: "イランの許可を得て15隻がホルムズ海峡を通過（ファルス通信報道）。商船三井のLNG船「ソハール」も通過を確認。湾内にはなお約2,190隻・約2万人の乗員が足止め状態。日本関係船舶は約44-45隻。",
    category: "trade",
    impact: "positive",
    relatedIndicators: ["Trade Balance", "CPI (YoY)"],
  },
  {
    date: "2026-04-04",
    title: "イラン、日本・欧州船舶のホルムズ海峡通航を初めて許可　原油先物やや下落",
    summary: "封鎖後初めて日欧の関係船舶がホルムズ海峡の通航を認められた。海峡再開への期待から日経平均は一時1.7%上昇し53,300円台を回復。ただし本格的な通航再開には至っておらず、先行き不透明。",
    category: "market",
    impact: "positive",
    relatedIndicators: ["Nikkei 225", "CPI (YoY)"],
  },
  {
    date: "2026-04-01",
    title: "日銀短観3月調査、大企業製造業DI＋17と改善も先行きは大幅悪化",
    summary: "大企業製造業の業況判断DIは＋17と前回（＋15）から改善し2021年Q4以来の高水準。一方、先行きDIは原油高・中東情勢の不透明感を反映して大幅に悪化。",
    category: "corporate",
    impact: "neutral",
    relatedIndicators: ["GDP Growth Rate", "Nikkei 225"],
  },
  {
    date: "2026-04-01",
    title: "4月の食品値上げ2,798品目、2026年初の値上げラッシュ",
    summary: "帝国データバンク調べで4月の飲食料品値上げは2,798品目（平均14%）。調味料1,514品目、加工食品609品目、酒類・飲料369品目。電気・ガス補助金も3月末で終了し家計への影響大。",
    category: "market",
    impact: "negative",
    relatedIndicators: ["CPI (YoY)", "Consumer Spending"],
  },
  {
    date: "2026-04-01",
    title: "暫定予算8.6兆円が成立、本予算122.3兆円は4月11日に自然成立見込み",
    summary: "本予算（一般会計122.3兆円、過去最大）は衆院通過済みだが参院審議中のため、4月1〜11日をカバーする暫定予算8.6兆円が成立。11年ぶりの暫定予算。本予算は憲法の30日ルールにより4月11日に自然成立の見込み。",
    category: "fiscal",
    impact: "neutral",
  },
  {
    date: "2026-04-01",
    title: "防衛増税が始動　たばこ税・法人税が引き上げ",
    summary: "防衛費増額の財源として、たばこ税と法人税の引き上げが4月1日に施行。段階的な増税の第一弾として実施。",
    category: "fiscal",
    impact: "neutral",
  },
  {
    date: "2026-03-31",
    title: "東京都区部3月CPI、前年比+1.7%　原油高の影響は限定的",
    summary: "東京都区部の3月消費者物価指数（生鮮食品除く）は前年比+1.7%。2月の全国コアCPI+1.6%からやや上昇も、原油高の本格的な波及は4月以降の見通し。",
    category: "policy",
    impact: "neutral",
    relatedIndicators: ["CPI (YoY)", "BOJ Policy Rate"],
  },
  {
    date: "2026-03-26",
    title: "政府、原油国家備蓄の放出を開始　ホルムズ海峡迂回ルートも拡大",
    summary: "ホルムズ海峡の事実上の封鎖を受け、政府は国家石油備蓄の一部放出を決定。同時にマレーシア経由の迂回輸入ルート拡大や、米国・カナダからのLNG調達強化を進める。",
    category: "policy",
    impact: "neutral",
    relatedIndicators: ["CPI (YoY)", "Trade Balance"],
  },
  {
    date: "2026-03-24",
    title: "2月コアCPI、前年比+1.6%　2022年3月以来の2%割れ",
    summary: "生鮮食品を除くコアCPIは前年同月比+1.6%。電気・ガス補助金の再開が主因で、電気代は前年比-8.0%。総合CPIは+1.3%まで低下。3月以降は原油高と補助金終了で再上昇の見込み。",
    category: "policy",
    impact: "positive",
    relatedIndicators: ["CPI (YoY)", "BOJ Policy Rate"],
  },
  {
    date: "2026-03-23",
    title: "春闘1次集計、賃上げ率5.26%　大手で満額回答相次ぐ",
    summary: "連合の第1回集計（1,100組合）で賃上げ率は5.26%（ベア3.85%）。自動車・電機など大手で満額回答が相次ぎ、3年連続5%超の高水準を維持。",
    category: "labor",
    impact: "positive",
    relatedIndicators: ["Consumer Spending", "Unemployment Rate"],
  },
  {
    date: "2026-03-19",
    title: "日銀、政策金利0.75%で据え置き（8対1）",
    summary: "日銀は金融政策決定会合で政策金利を0.75%に据え置き。8対1で決定（高田委員が1%への利上げを主張し反対）。中東情勢の不透明感を注視しつつ、利上げ継続の姿勢は維持。",
    category: "policy",
    impact: "neutral",
    relatedIndicators: ["BOJ Policy Rate", "10Y JGB Yield", "USD/JPY"],
  },
  {
    date: "2026-03-13",
    title: "令和8年度予算案が衆議院を通過、参議院へ送付",
    summary: "一般会計総額122.3兆円（過去最大）の予算案が衆議院本会議で可決。1月の衆院解散で審議日程が圧縮され、参院での30日ルールによる自然成立（4月11日）が確定的に。",
    category: "fiscal",
    impact: "neutral",
    relatedIndicators: ["GDP Growth Rate"],
  },
  {
    date: "2026-03-11",
    title: "米USTR、日本含む16カ国にセクション301調査を開始",
    summary: "米通商代表部が「製造業の構造的過剰生産能力」を理由に、日本を含む16の経済圏に対しセクション301調査を開始。7月24日までに関税措置の可否を判断する方針。IEEPA関税の代替手段として注目。",
    category: "trade",
    impact: "negative",
    relatedIndicators: ["Trade Balance", "Nikkei 225"],
  },
  {
    date: "2026-03-10",
    title: "1月経常収支、9,426億円の黒字　前年比+38%",
    summary: "海外投資からの第一次所得収支が拡大し、経常収支は前年同月比38%増の黒字を記録。円安による海外利益の膨張が寄与。",
    category: "trade",
    impact: "positive",
    relatedIndicators: ["Current Account", "USD/JPY"],
  },
  {
    date: "2026-03-07",
    title: "実質消費支出、前年比+0.8%で3ヶ月連続増",
    summary: "総務省の家計調査で1月の実質消費支出は前年同月比+0.8%と3ヶ月連続の増加。賃上げ効果が徐々に消費に波及。",
    category: "labor",
    impact: "positive",
  },
  {
    date: "2026-03-05",
    title: "ホルムズ海峡が事実上封鎖　大手海運がペルシャ湾通過を停止",
    summary: "大手海上保険会社が戦争リスク保険の引き受けを停止したことで、日本郵船・川崎汽船など主要海運がホルムズ海峡通過を停止。日本の輸入原油の約92%が中東経由であり、エネルギー安全保障上の重大な危機。",
    category: "trade",
    impact: "negative",
    relatedIndicators: ["CPI (YoY)", "Trade Balance"],
  },
  {
    date: "2026-03-02",
    title: "原油価格が急騰、WTI112ドル超　イラン革命防衛隊がホルムズ海峡封鎖を宣言",
    summary: "米・イスラエルによるイラン空爆（2月28日）を受け、イラン革命防衛隊がホルムズ海峡の封鎖を宣言。WTI原油先物は112ドル超に急騰し2022年以来の高値。ブレントはピーク時126ドルに達した。",
    category: "trade",
    impact: "negative",
    relatedIndicators: ["CPI (YoY)", "Trade Balance", "USD/JPY"],
  },
  {
    date: "2026-02-28",
    title: "有効求人倍率、1.18倍に低下も高水準維持",
    summary: "1月の有効求人倍率は1.18倍と前月から0.02ポイント低下。人手不足は継続も、一部業種で求人の慎重姿勢が見られる。",
    category: "labor",
    impact: "neutral",
  },
  {
    date: "2026-02-24",
    title: "トランプ大統領、セクション122に基づく暫定10%関税を発動",
    summary: "最高裁によるIEEPA関税違憲判決を受け、トランプ大統領は貿易法セクション122に基づき全世界からの輸入品に一律10%の暫定関税を発動。有効期限は150日間（7月24日まで）。",
    category: "trade",
    impact: "negative",
    relatedIndicators: ["Trade Balance", "USD/JPY"],
  },
  {
    date: "2026-02-20",
    title: "米最高裁、IEEPA相互関税を違憲と判決　関税は即時停止",
    summary: "米連邦最高裁が2025年4月のIEEPA（国際緊急経済権限法）に基づく相互関税を違法・無効と判決。日本への15%関税を含む全IEEPA関税が2月24日に停止。トランプ政権は代替手段を模索。",
    category: "trade",
    impact: "positive",
    relatedIndicators: ["Trade Balance", "Nikkei 225", "USD/JPY"],
  },
  {
    date: "2026-02-18",
    title: "第2次高市内閣発足、経済政策の継続を表明",
    summary: "衆院選大勝を受け第2次高市内閣が発足。高市首相は「賃上げと投資の好循環を加速する」と表明し、戦略的インフラ投資の強化を掲げる。",
    category: "policy",
    impact: "neutral",
  },
  {
    date: "2026-02-10",
    title: "日経平均、終値5万7,000円超え　衆院選後の最高値更新",
    summary: "衆院選で与党圧勝を受け、海外投資家の日本株選好が加速。日経平均は終値で5万7,000円を突破し、2025年10月の5万円突破からわずか4ヶ月で7,000円上昇。",
    category: "market",
    impact: "positive",
  },
  {
    date: "2025-12-19",
    title: "日銀、政策金利を0.75%に引き上げ",
    summary: "日銀は0.50%から0.75%への追加利上げを決定。1995年9月以来約30年ぶりの高水準。為替市場では一時円高に振れるも、その後円安基調に回帰。",
    category: "policy",
    impact: "neutral",
    relatedIndicators: ["BOJ Policy Rate", "USD/JPY", "10Y JGB Yield"],
  },
];

export const newsCategoryLabels: Record<string, string> = {
  policy: "政策",
  market: "市場",
  trade: "貿易",
  fiscal: "財政",
  labor: "雇用",
  corporate: "企業",
};

export const categoryLabels: Record<string, { ja: string; en: string }> = {
  growth: { ja: "成長・生産", en: "Growth & Production" },
  prices: { ja: "物価", en: "Prices" },
  labor: { ja: "雇用", en: "Labor" },
  financial: { ja: "金融市場", en: "Financial Markets" },
  trade: { ja: "貿易・国際収支", en: "Trade & Balance of Payments" },
  monetary: { ja: "金融政策", en: "Monetary Policy" },
};
