export type TrendDirection = "up" | "down" | "flat";
export type IndicatorStatus = "good" | "bad" | "neutral";

export interface EconomicIndicator {
  name: string;
  nameEn: string;
  value: string;
  unit: string;
  trend: TrendDirection;
  status: IndicatorStatus;
  description: string;
  category: "growth" | "prices" | "labor" | "financial" | "trade" | "monetary";
  lastUpdated: string;
  change?: string;
  sparkline?: number[];
}

export const economicIndicators: EconomicIndicator[] = [
  {
    name: "GDP成長率",
    nameEn: "GDP Growth Rate",
    value: "0.8",
    unit: "%",
    trend: "down",
    status: "neutral",
    description: "IMF予測（4月2日公表）。外需減と中東紛争の影響で成長鈍化。内需は堅調で失業率も低水準を維持。",
    category: "growth",
    lastUpdated: "2026-04-02",
    change: "前期 1.2%",
    sparkline: [1.8, 1.5, 1.2, 1.0, 0.9, 0.8],
  },
  {
    name: "消費者物価指数 (CPI)",
    nameEn: "CPI (YoY)",
    value: "1.6",
    unit: "%",
    trend: "down",
    status: "good",
    description: "生鮮食品を除くコアCPI（2月）。電気・ガス補助金の再開により2022年3月以来の2%割れ。総合CPIは1.3%。3月は原油高と補助金終了で再上昇の見込み。",
    category: "prices",
    lastUpdated: "2026-03-24",
    change: "前月 2.0%",
    sparkline: [3.1, 2.8, 2.5, 2.3, 2.0, 1.6],
  },
  {
    name: "完全失業率",
    nameEn: "Unemployment Rate",
    value: "2.6",
    unit: "%",
    trend: "down",
    status: "good",
    description: "季節調整値（2月）。前月の2.7%から改善。歴史的な低水準を維持。",
    category: "labor",
    lastUpdated: "2026-03-28",
    change: "前月 2.7%",
    sparkline: [2.5, 2.5, 2.4, 2.5, 2.7, 2.6],
  },
  {
    name: "日経平均株価",
    nameEn: "Nikkei 225",
    value: "53,123",
    unit: "円",
    trend: "up",
    status: "neutral",
    description: "4月3日は反発し前日比660円高。中東情勢を背景にエネルギー・防衛関連株が選好される一方、輸出株は円高圧力と関税リスクで上値重い。",
    category: "financial",
    lastUpdated: "2026-04-03",
    change: "前日 52,463円",
    sparkline: [42000, 47000, 50000, 57000, 52463, 53123],
  },
  {
    name: "円ドル為替レート",
    nameEn: "USD/JPY",
    value: "159.4",
    unit: "円/ドル",
    trend: "up",
    status: "bad",
    description: "中東情勢による原油高が円安圧力に。日銀の4月追加利上げ観測が円高要因として綱引き。IMFは日銀に利上げ継続を勧告。",
    category: "financial",
    lastUpdated: "2026-04-03",
    change: "前日 159.0円",
    sparkline: [150, 153, 155, 158, 159.0, 159.4],
  },
  {
    name: "経常収支",
    nameEn: "Current Account",
    value: "+9,426",
    unit: "億円",
    trend: "up",
    status: "good",
    description: "2026年1月の経常収支黒字。前年同月比で大幅改善。",
    category: "trade",
    lastUpdated: "2026-03-10",
    change: "前年同月 +6,831億円",
    sparkline: [5200, 5800, 6200, 6831, 8100, 9426],
  },
  {
    name: "貿易収支",
    nameEn: "Trade Balance",
    value: "+573",
    unit: "億円",
    trend: "down",
    status: "neutral",
    description: "2026年2月の貿易収支。黒字は維持するも前年同月比で大幅減。",
    category: "trade",
    lastUpdated: "2026-03-19",
    change: "前月 +1,234億円",
    sparkline: [800, 1500, 1200, 1234, 900, 573],
  },
  {
    name: "日銀政策金利",
    nameEn: "BOJ Policy Rate",
    value: "0.75",
    unit: "%",
    trend: "up",
    status: "neutral",
    description: "3月会合で据え置き（8対1）。高田委員が1%を主張し反対。IMFは利上げ継続を勧告。市場は4月27-28日会合での利上げを6-7割織り込み。",
    category: "monetary",
    lastUpdated: "2026-03-19",
    change: "前回 0.50%",
    sparkline: [0, 0, 0.1, 0.25, 0.5, 0.75],
  },
  {
    name: "10年国債利回り",
    nameEn: "10Y JGB Yield",
    value: "2.39",
    unit: "%",
    trend: "up",
    status: "neutral",
    description: "ホルムズ海峡封鎖によるインフレ懸念で25年ぶりの高水準。日銀の追加利上げ観測も長期金利を押し上げ。",
    category: "monetary",
    lastUpdated: "2026-04-03",
    change: "前日 2.40%",
    sparkline: [1.0, 1.3, 1.7, 2.1, 2.40, 2.39],
  },
  {
    name: "マネーストック M2",
    nameEn: "Money Supply M2",
    value: "1,274.9",
    unit: "兆円",
    trend: "down",
    status: "neutral",
    description: "2026年2月のM2残高。前月比でやや減少。",
    category: "monetary",
    lastUpdated: "2026-03-12",
    change: "前月 1,278.3兆円",
    sparkline: [1260, 1265, 1270, 1275, 1278, 1274.9],
  },
  {
    name: "鉱工業生産指数",
    nameEn: "Industrial Production",
    value: "横ばい",
    unit: "",
    trend: "flat",
    status: "neutral",
    description: "米国関税引き上げの前倒し需要と反動減が交錯。全体としてはほぼ横ばい。",
    category: "growth",
    lastUpdated: "2026-03-28",
    change: "前月比 ±0.0%",
    sparkline: [98, 99, 100, 99, 100, 100],
  },
  {
    name: "消費支出",
    nameEn: "Consumer Spending",
    value: "+0.8",
    unit: "% (前年比)",
    trend: "up",
    status: "neutral",
    description: "実質消費支出は緩やかに回復。賃金上昇が消費を下支え。",
    category: "growth",
    lastUpdated: "2026-03-07",
    change: "前月 +0.3%",
    sparkline: [-1.2, -0.5, 0.1, 0.2, 0.3, 0.8],
  },
  {
    name: "有効求人倍率",
    nameEn: "Job-to-Applicant Ratio",
    value: "1.18",
    unit: "倍",
    trend: "down",
    status: "neutral",
    description: "2026年1月の有効求人倍率。前月の1.20から低下も依然1倍超。",
    category: "labor",
    lastUpdated: "2026-02-28",
    change: "前月 1.20倍",
    sparkline: [1.25, 1.24, 1.22, 1.21, 1.20, 1.18],
  },
];

export interface EconomyNewsItem {
  date: string;
  title: string;
  summary: string;
  category: "policy" | "market" | "trade" | "fiscal" | "labor" | "corporate";
  impact: "positive" | "negative" | "neutral";
  relatedIndicators?: string[];
}

export const economyNews: EconomyNewsItem[] = [
  {
    date: "2026-04-04",
    title: "IMF、日銀に利上げ継続を勧告　中東リスク下でも",
    summary: "IMFは2026年対日4条協議の結論を公表。成長率0.8%の見通しの下でも、インフレ圧力を踏まえ日銀に利上げ継続を勧告。中東紛争による原油高リスクにも言及。",
    category: "policy",
    impact: "neutral",
    relatedIndicators: ["BOJ Policy Rate", "GDP Growth Rate", "CPI (YoY)"],
  },
  {
    date: "2026-04-03",
    title: "日経平均反発、前日比660円高の53,123円　エネルギー関連株が牽引",
    summary: "原油高の恩恵を受けるINPEX等エネルギー株や防衛関連株が買われ反発。ただし中東情勢の先行き不透明感から上値は限定的。週間では下落。",
    category: "market",
    impact: "positive",
    relatedIndicators: ["Nikkei 225"],
  },
  {
    date: "2026-04-03",
    title: "春闘3次集計、賃上げ率5.09%　中小も5%到達",
    summary: "連合の第3回集計（2,311組合）で賃上げ率は5.09%。中小企業（300人未満）も5.00%と前年並みの高水準を維持し、3年連続5%超の賃上げが実現。",
    category: "labor",
    impact: "positive",
    relatedIndicators: ["Consumer Spending", "Unemployment Rate"],
  },
  {
    date: "2026-04-02",
    title: "トランプ大統領、対イラン演説で軍事エスカレーション示唆　原油急騰",
    summary: "トランプ大統領が全米向け演説で「2-3週間以内にさらなる軍事行動」を示唆。WTI原油先物は一時112ドル超に急騰（前日比+12%）。日本のエネルギーコスト上昇懸念が一段と高まる。",
    category: "trade",
    impact: "negative",
    relatedIndicators: ["CPI (YoY)", "Trade Balance"],
  },
  {
    date: "2026-04-02",
    title: "IMF対日4条協議：GDP成長率0.8%に減速見通し",
    summary: "IMF理事会が2026年対日4条協議を終了。成長率は外需減と中東紛争の影響で0.8%に減速する見通し。内需は堅調で失業率は低水準を維持と評価。",
    category: "policy",
    impact: "neutral",
    relatedIndicators: ["GDP Growth Rate", "Unemployment Rate"],
  },
  {
    date: "2026-04-02",
    title: "トランプ相互関税から1年 — 日本への影響を振り返る",
    summary: "2025年4月2日の24%相互関税発表から1年。7月の日米枠組み合意で15%に引き下げ、2026年2月の最高裁違憲判決でIEEPA関税は無効化。現在はセクション122に基づく暫定10%関税が適用中。新たなセクション301調査も開始。",
    category: "trade",
    impact: "neutral",
    relatedIndicators: ["Trade Balance", "USD/JPY", "Nikkei 225"],
  },
  {
    date: "2026-04-01",
    title: "4月の食品値上げ2,798品目、2026年初の値上げラッシュ",
    summary: "帝国データバンク調べで4月の飲食料品値上げは2,798品目（平均14%）。調味料1,514品目、加工食品609品目、酒類・飲料369品目。電気・ガス補助金も3月末で終了し家計への影響大。",
    category: "market",
    impact: "negative",
    relatedIndicators: ["CPI (YoY)", "Consumer Spending"],
  },
  {
    date: "2026-04-01",
    title: "暫定予算8.6兆円が成立、本予算122.3兆円は4月11日に自然成立見込み",
    summary: "本予算（一般会計122.3兆円、過去最大）は衆院通過済みだが参院審議中のため、4月1〜11日をカバーする暫定予算8.6兆円が成立。11年ぶりの暫定予算。本予算は憲法の30日ルールにより4月11日に自然成立の見込み。",
    category: "fiscal",
    impact: "neutral",
  },
  {
    date: "2026-04-01",
    title: "防衛増税が始動　たばこ税・法人税が引き上げ",
    summary: "防衛費増額の財源として、たばこ税と法人税の引き上げが4月1日に施行。段階的な増税の第一弾として実施。",
    category: "fiscal",
    impact: "neutral",
  },
  {
    date: "2026-03-31",
    title: "東京都区部3月CPI、前年比+1.7%　原油高の影響は限定的",
    summary: "東京都区部の3月消費者物価指数（生鮮食品除く）は前年比+1.7%。2月の全国コアCPI+1.6%からやや上昇も、原油高の本格的な波及は4月以降の見通し。",
    category: "policy",
    impact: "neutral",
    relatedIndicators: ["CPI (YoY)", "BOJ Policy Rate"],
  },
  {
    date: "2026-03-26",
    title: "政府、原油国家備蓄の放出を開始　ホルムズ海峡迂回ルートも拡大",
    summary: "ホルムズ海峡の事実上の封鎖を受け、政府は国家石油備蓄の一部放出を決定。同時にマレーシア経由の迂回輸入ルート拡大や、米国・カナダからのLNG調達強化を進める。",
    category: "policy",
    impact: "neutral",
    relatedIndicators: ["CPI (YoY)", "Trade Balance"],
  },
  {
    date: "2026-03-24",
    title: "2月コアCPI、前年比+1.6%　2022年3月以来の2%割れ",
    summary: "生鮮食品を除くコアCPIは前年同月比+1.6%。電気・ガス補助金の再開が主因で、電気代は前年比-8.0%。総合CPIは+1.3%まで低下。3月以降は原油高と補助金終了で再上昇の見込み。",
    category: "policy",
    impact: "positive",
    relatedIndicators: ["CPI (YoY)", "BOJ Policy Rate"],
  },
  {
    date: "2026-03-23",
    title: "春闘1次集計、賃上げ率5.26%　大手で満額回答相次ぐ",
    summary: "連合の第1回集計（1,100組合）で賃上げ率は5.26%（ベア3.85%）。自動車・電機など大手で満額回答が相次ぎ、3年連続5%超の高水準を維持。",
    category: "labor",
    impact: "positive",
    relatedIndicators: ["Consumer Spending", "Unemployment Rate"],
  },
  {
    date: "2026-03-19",
    title: "日銀、政策金利0.75%で据え置き（8対1）",
    summary: "日銀は金融政策決定会合で政策金利を0.75%に据え置き。8対1で決定（高田委員が1%への利上げを主張し反対）。中東情勢の不透明感を注視しつつ、利上げ継続の姿勢は維持。",
    category: "policy",
    impact: "neutral",
    relatedIndicators: ["BOJ Policy Rate", "10Y JGB Yield", "USD/JPY"],
  },
  {
    date: "2026-03-14",
    title: "トヨタ、EV新ライン稼働で豊田市に3,000億円投資",
    summary: "トヨタ自動車が次世代EV専用ラインの稼働を開始。2028年までにEV生産能力を年間50万台に引き上げ。部品メーカーへの波及効果も期待。",
    category: "corporate",
    impact: "positive",
  },
  {
    date: "2026-03-10",
    title: "1月経常収支、9,426億円の黒字　前年比+38%",
    summary: "海外投資からの第一次所得収支が拡大し、経常収支は前年同月比38%増の黒字を記録。円安による海外利益の膨張が寄与。",
    category: "trade",
    impact: "positive",
    relatedIndicators: ["Current Account", "USD/JPY"],
  },
  {
    date: "2026-03-07",
    title: "実質消費支出、前年比+0.8%で3ヶ月連続増",
    summary: "総務省の家計調査で1月の実質消費支出は前年同月比+0.8%と3ヶ月連続の増加。賃上げ効果が徐々に消費に波及。",
    category: "labor",
    impact: "positive",
  },
  {
    date: "2026-02-28",
    title: "有効求人倍率、1.18倍に低下も高水準維持",
    summary: "1月の有効求人倍率は1.18倍と前月から0.02ポイント低下。人手不足は継続も、一部業種で求人の慎重姿勢が見られる。",
    category: "labor",
    impact: "neutral",
  },
  {
    date: "2026-02-18",
    title: "第2次高市内閣発足、経済政策の継続を表明",
    summary: "衆院選大勝を受け第2次高市内閣が発足。高市首相は「賃上げと投資の好循環を加速する」と表明し、戦略的インフラ投資の強化を掲げる。",
    category: "policy",
    impact: "neutral",
  },
  {
    date: "2026-02-10",
    title: "日経平均、終値5万7,000円超え　衆院選後の最高値更新",
    summary: "衆院選で与党圧勝を受け、海外投資家の日本株選好が加速。日経平均は終値で5万7,000円を突破し、2025年10月の5万円突破からわずか4ヶ月で7,000円上昇。",
    category: "market",
    impact: "positive",
  },
  {
    date: "2025-12-19",
    title: "日銀、政策金利を0.75%に引き上げ",
    summary: "日銀は0.50%から0.75%への追加利上げを決定。1995年9月以来約30年ぶりの高水準。為替市場では一時円高に振れるも、その後円安基調に回帰。",
    category: "policy",
    impact: "neutral",
    relatedIndicators: ["BOJ Policy Rate", "USD/JPY", "10Y JGB Yield"],
  },
];

export const newsCategoryLabels: Record<string, string> = {
  policy: "政策",
  market: "市場",
  trade: "貿易",
  fiscal: "財政",
  labor: "雇用",
  corporate: "企業",
};

export const categoryLabels: Record<string, { ja: string; en: string }> = {
  growth: { ja: "成長・生産", en: "Growth & Production" },
  prices: { ja: "物価", en: "Prices" },
  labor: { ja: "雇用", en: "Labor" },
  financial: { ja: "金融市場", en: "Financial Markets" },
  trade: { ja: "貿易・国際収支", en: "Trade & Balance of Payments" },
  monetary: { ja: "金融政策", en: "Monetary Policy" },
};
