// 2025年〜2026年に施行・発効した主要法令・制度
// 第217回・第219回・第221回国会で成立し、2026年4月6日時点で施行済みの法律
// ソース: clb.go.jp, sangiin.go.jp, policynews.jp

export type VoteJa = "賛成" | "反対" | "棄権";
export type VoteEn = "For" | "Against" | "Abstain";

export interface EnactedItem {
  slug: string;
  title: string;
  titleEn: string;
  committee: string;
  committeeEn: string;
  enactedDate: string;     // 成立日
  effectiveDate: string;   // 施行日
  summary: string;
  summaryEn: string;
  detail: string;
  detailEn: string;
  keyPoints: string[];
  keyPointsEn: string[];
  voteResult: { for: number; against: number; abstain?: number };
  parties: { name: string; nameEn: string; vote: VoteJa; voteEn: VoteEn }[];
  timeline: { date: string; event: string; eventEn: string }[];
  impact: string;
  impactEn: string;
}

export const enactedItems: EnactedItem[] = [
  // ──────────────────────────────────────────
  // 2026年1月1日 施行
  // ──────────────────────────────────────────
  {
    slug: "political-funds-reform",
    title: "改正政治資金規正法",
    titleEn: "Revised Political Funds Control Act",
    committee: "政治倫理・選挙制度特別委員会",
    committeeEn: "Special Committee on Political Ethics and Election Law",
    enactedDate: "2024-06-19",
    effectiveDate: "2026-01-01",
    summary: "自民党派閥の裏金問題を受け、政治資金の透明性を大幅に強化する改正法。パーティー券購入の公開基準を20万円から5万円に引き下げ。",
    summaryEn: "In response to the LDP faction slush-fund scandal, this amendment substantially strengthens transparency of political funds, lowering the disclosure threshold for fundraising-party ticket purchases from 200,000 yen to 50,000 yen.",
    detail: "2024年に発覚した自民党派閥の政治資金パーティー裏金問題を受けた改正。政治資金パーティー券の購入者公開基準を「20万円超」から「5万円超」に引き下げ、政治資金収支報告書への議員本人の「確認書」添付を義務化。外国人によるパーティー券購入を禁止するなど、政治資金の透明性を抜本的に強化。2024年6月の第213回国会で成立し、主要部分は2026年1月1日に施行された。",
    detailEn: "An amendment prompted by the LDP faction political-fundraising-party slush fund scandal that surfaced in 2024. It lowers the disclosure threshold for fundraising-party ticket purchasers from 'over 200,000 yen' to 'over 50,000 yen' and requires lawmakers to personally attach a confirmation letter to political fund balance reports. It also bans fundraising-party ticket purchases by foreign nationals, fundamentally strengthening transparency of political funds. Passed during the 213th Diet Session in June 2024, with the main provisions entering into force on January 1, 2026.",
    keyPoints: [
      "パーティー券購入者の公開基準を20万円超→5万円超に引き下げ",
      "収支報告書への議員本人の確認書添付を義務化",
      "外国人によるパーティー券購入の禁止",
      "収支報告書のデータベース化・オンライン公開",
      "不記載・虚偽記載の罰則強化",
    ],
    keyPointsEn: [
      "Disclosure threshold for party-ticket purchasers lowered from over 200,000 yen to over 50,000 yen",
      "Lawmakers required to personally attach a confirmation letter to fund reports",
      "Ban on purchase of fundraising-party tickets by foreign nationals",
      "Database and online publication of political fund reports",
      "Stricter penalties for non-reporting and false entries",
    ],
    voteResult: { for: 267, against: 176 },
    parties: [
      { name: "自由民主党", nameEn: "Liberal Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "公明党", nameEn: "Komeito", vote: "賛成", voteEn: "For" },
      { name: "日本維新の会", nameEn: "Nippon Ishin no Kai", vote: "賛成", voteEn: "For" },
      { name: "立憲民主党", nameEn: "Constitutional Democratic Party", vote: "反対", voteEn: "Against" },
      { name: "国民民主党", nameEn: "Democratic Party for the People", vote: "反対", voteEn: "Against" },
      { name: "日本共産党", nameEn: "Japanese Communist Party", vote: "反対", voteEn: "Against" },
      { name: "れいわ新選組", nameEn: "Reiwa Shinsengumi", vote: "反対", voteEn: "Against" },
    ],
    timeline: [
      { date: "2024-03-01", event: "自民党派閥の裏金問題が国会で追及", eventEn: "LDP faction slush-fund scandal pursued in the Diet" },
      { date: "2024-05-17", event: "与党が改正案を国会提出", eventEn: "Ruling parties submit the amendment bill to the Diet" },
      { date: "2024-06-06", event: "衆議院政治倫理・選挙制度特別委員会で可決", eventEn: "Passed by the House of Representatives Special Committee on Political Ethics and Election Law" },
      { date: "2024-06-19", event: "参議院本会議で可決・成立", eventEn: "Passed and enacted by the House of Councillors plenary" },
      { date: "2026-01-01", event: "主要規定が施行", eventEn: "Main provisions enter into force" },
    ],
    impact: "政治家の資金の流れが透明化。国民の政治不信の解消を目指す改革。",
    impactEn: "Brings transparency to politicians' funding flows, aiming to ease public distrust of politics.",
  },
  {
    slug: "political-reform-trilogy",
    title: "政治改革3法（政策活動費廃止）",
    titleEn: "Political Reform Trilogy (Abolition of Policy Activity Expenses)",
    committee: "政治倫理・選挙制度特別委員会",
    committeeEn: "Special Committee on Political Ethics and Election Law",
    enactedDate: "2024-12-24",
    effectiveDate: "2026-01-01",
    summary: "政策活動費の完全廃止、旧文通費の使途公開義務化、第三者機関による監視を盛り込んだ3法。",
    summaryEn: "A package of three laws fully abolishing policy activity expenses, requiring disclosure of how the former communications allowance is spent, and establishing third-party oversight.",
    detail: "第215回臨時国会で成立した「政治資金規正法再改正」「国会議員歳費法改正」「政治資金監視委員会設置法」の3本の法律。政党から議員への政策活動費（年間数十億円規模）を2026年1月から完全廃止。旧文通費（調査研究広報滞在費、月100万円）の使途公開を義務化。独立した第三者機関「政治資金監視委員会」を国会に設置し、政治資金の監視・調査権限を付与。",
    detailEn: "Three laws enacted during the 215th extraordinary Diet session: the re-amendment of the Political Funds Control Act, the amendment of the National Diet Members' Remuneration Act, and the Political Funds Oversight Committee Establishment Act. From January 2026, policy activity expenses paid from parties to lawmakers (tens of billions of yen per year) will be fully abolished. Disclosure of the use of the former communications allowance (Research, PR, and Accommodation Expenses, 1 million yen per month) is mandated. An independent third-party Political Funds Oversight Committee is established within the Diet with powers to monitor and investigate political funds.",
    keyPoints: [
      "政策活動費の完全廃止（2026年1月〜）",
      "旧文通費（調査研究広報滞在費）の使途公開義務化",
      "「政治資金監視委員会」の国会設置",
      "第三者機関に調査・勧告権限を付与",
      "企業・団体献金の公開基準引き下げ",
    ],
    keyPointsEn: [
      "Full abolition of policy activity expenses (from January 2026)",
      "Mandatory disclosure of the use of the former communications allowance",
      "Establishment of a Political Funds Oversight Committee in the Diet",
      "Investigative and advisory powers granted to the third-party body",
      "Lower disclosure thresholds for corporate and organizational donations",
    ],
    voteResult: { for: 381, against: 62 },
    parties: [
      { name: "自由民主党", nameEn: "Liberal Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "公明党", nameEn: "Komeito", vote: "賛成", voteEn: "For" },
      { name: "立憲民主党", nameEn: "Constitutional Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "日本維新の会", nameEn: "Nippon Ishin no Kai", vote: "賛成", voteEn: "For" },
      { name: "国民民主党", nameEn: "Democratic Party for the People", vote: "賛成", voteEn: "For" },
      { name: "日本共産党", nameEn: "Japanese Communist Party", vote: "賛成", voteEn: "For" },
      { name: "れいわ新選組", nameEn: "Reiwa Shinsengumi", vote: "反対", voteEn: "Against" },
      { name: "参政党", nameEn: "Sanseito", vote: "反対", voteEn: "Against" },
    ],
    timeline: [
      { date: "2024-10-15", event: "衆院選後に与野党間で政治改革協議会発足", eventEn: "Post-general-election political reform council formed by ruling and opposition parties" },
      { date: "2024-11-28", event: "与野党が3法案の修正で合意", eventEn: "Ruling and opposition parties agree on revisions to the three bills" },
      { date: "2024-12-13", event: "衆議院本会議で可決", eventEn: "Passed by the House of Representatives plenary" },
      { date: "2024-12-24", event: "参議院本会議で可決・成立", eventEn: "Passed and enacted by the House of Councillors plenary" },
      { date: "2026-01-01", event: "施行", eventEn: "Enters into force" },
    ],
    impact: "調査研究広報滞在費の使途公開など、政治資金をめぐる3つの改革が一体で施行。",
    impactEn: "Three reforms of political funding, including disclosure of the former communications allowance, take effect as a package.",
  },

  // ──────────────────────────────────────────
  // 2026年4月1日 施行
  // ──────────────────────────────────────────
  {
    slug: "childcare-support-reform",
    title: "子ども・子育て支援法改正",
    titleEn: "Child and Childcare Support Act Amendment",
    committee: "内閣委員会",
    committeeEn: "Cabinet Committee",
    enactedDate: "2024-06-12",
    effectiveDate: "2026-04-01",
    summary: "こども誰でも通園制度の創設、子ども・子育て支援金の徴収開始など、少子化対策の柱となる改正法。",
    summaryEn: "A central pillar of Japan's declining-birthrate measures, creating the universal childcare enrollment program and launching collection of the Child and Childcare Support Levy.",
    detail: "「次元の異なる少子化対策」の法的基盤として第213回国会で成立。児童手当の高校生までの延長・所得制限撤廃（2024年10月施行済み）に続き、2026年4月から「子ども・子育て支援金」の徴収を開始（被保険者1人あたり月約500円）。3歳未満の未就園児が保育所を利用できる「こども誰でも通園制度」を本格実施。育児休業給付の実質10割化も段階的に導入。",
    detailEn: "Enacted in the 213th Diet Session as the legal foundation for the government's 'unprecedented' measures against the declining birthrate. Following the extension of the Child Allowance to high-school students and removal of income limits (enforced October 2024), collection of the Child and Childcare Support Levy begins in April 2026 (roughly 500 yen per month per insured person). The universal childcare enrollment program, allowing children under three not attending nursery to use childcare facilities, enters full implementation. Phased introduction of effectively 100% take-home childcare-leave benefits is also included.",
    keyPoints: [
      "「子ども・子育て支援金」の徴収開始（月約500円/被保険者）",
      "「こども誰でも通園制度」の本格実施",
      "第3子以降の児童手当を月3万円に増額",
      "育児休業給付の手取り10割化",
      "妊婦のための支援給付金（10万円相当）の創設",
    ],
    keyPointsEn: [
      "Collection of the Child and Childcare Support Levy begins (roughly 500 yen/month per insured person)",
      "Full implementation of the universal childcare enrollment program",
      "Child Allowance increased to 30,000 yen/month for the third and subsequent children",
      "Effective 100% take-home childcare-leave benefits",
      "New support benefit for expectant mothers (worth 100,000 yen)",
    ],
    voteResult: { for: 310, against: 133 },
    parties: [
      { name: "自由民主党", nameEn: "Liberal Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "公明党", nameEn: "Komeito", vote: "賛成", voteEn: "For" },
      { name: "日本維新の会", nameEn: "Nippon Ishin no Kai", vote: "賛成", voteEn: "For" },
      { name: "立憲民主党", nameEn: "Constitutional Democratic Party", vote: "反対", voteEn: "Against" },
      { name: "国民民主党", nameEn: "Democratic Party for the People", vote: "反対", voteEn: "Against" },
      { name: "日本共産党", nameEn: "Japanese Communist Party", vote: "反対", voteEn: "Against" },
      { name: "れいわ新選組", nameEn: "Reiwa Shinsengumi", vote: "反対", voteEn: "Against" },
    ],
    timeline: [
      { date: "2024-02-16", event: "法案を閣議決定・国会提出", eventEn: "Bill approved by the Cabinet and submitted to the Diet" },
      { date: "2024-04-23", event: "衆議院本会議で可決", eventEn: "Passed by the House of Representatives plenary" },
      { date: "2024-06-12", event: "参議院本会議で可決・成立", eventEn: "Passed and enacted by the House of Councillors plenary" },
      { date: "2024-10-01", event: "児童手当拡充を先行施行", eventEn: "Child Allowance expansion enters into force first" },
      { date: "2026-04-01", event: "支援金徴収・こども誰でも通園制度の本格施行", eventEn: "Full enforcement of the support levy and universal childcare enrollment program" },
    ],
    impact: "生後6ヶ月〜3歳未満の子どもが保育所を利用できる「こども誰でも通園制度」が全国展開。",
    impactEn: "The universal childcare enrollment program, allowing children from six months to under three to use nurseries, is rolled out nationwide.",
  },
  {
    slug: "joint-custody",
    title: "改正民法（離婚後の共同親権）",
    titleEn: "Revised Civil Code (Joint Custody after Divorce)",
    committee: "法務委員会",
    committeeEn: "Judicial Affairs Committee",
    enactedDate: "2024-05-17",
    effectiveDate: "2026-04-01",
    summary: "離婚後も父母双方が親権を持つ「共同親権」を選択可能にする77年ぶりの民法大改正。",
    summaryEn: "The first major Civil Code reform in 77 years, allowing parents to choose joint custody after divorce.",
    detail: "1947年以来の単独親権制度を見直し、離婚後も父母の協議により共同親権を選択可能に。家庭裁判所が子の利益を考慮して親権者を判断する仕組みを整備。DV・虐待がある場合は単独親権とする規定を明記。養育費の取り決め率向上のため、法定養育費制度を新設。面会交流の実施確保のための裁判手続きも整備。",
    detailEn: "Overhauls the sole-custody system in place since 1947, allowing parents to agree on joint custody after divorce. Establishes a framework for family courts to determine custody based on the best interests of the child, with explicit provisions requiring sole custody in cases of domestic violence or abuse. Introduces a statutory child-support system to improve agreement rates, and lays down judicial procedures to ensure visitation is carried out.",
    keyPoints: [
      "離婚後の共同親権を選択可能に（77年ぶりの改正）",
      "家庭裁判所による「子の利益」を基準とした判断",
      "DV・虐待がある場合の単独親権規定",
      "法定養育費制度の新設",
      "面会交流の実施確保のための裁判手続き整備",
    ],
    keyPointsEn: [
      "Joint custody after divorce made available (first reform in 77 years)",
      "Family court decisions based on the 'best interests of the child'",
      "Sole custody mandated in cases of domestic violence or abuse",
      "New statutory child-support system",
      "Judicial procedures to ensure enforcement of visitation",
    ],
    voteResult: { for: 333, against: 100 },
    parties: [
      { name: "自由民主党", nameEn: "Liberal Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "公明党", nameEn: "Komeito", vote: "賛成", voteEn: "For" },
      { name: "日本維新の会", nameEn: "Nippon Ishin no Kai", vote: "賛成", voteEn: "For" },
      { name: "国民民主党", nameEn: "Democratic Party for the People", vote: "賛成", voteEn: "For" },
      { name: "立憲民主党", nameEn: "Constitutional Democratic Party", vote: "反対", voteEn: "Against" },
      { name: "日本共産党", nameEn: "Japanese Communist Party", vote: "反対", voteEn: "Against" },
      { name: "れいわ新選組", nameEn: "Reiwa Shinsengumi", vote: "反対", voteEn: "Against" },
    ],
    timeline: [
      { date: "2024-03-08", event: "法案を閣議決定・国会提出", eventEn: "Bill approved by the Cabinet and submitted to the Diet" },
      { date: "2024-04-19", event: "衆議院本会議で可決", eventEn: "Passed by the House of Representatives plenary" },
      { date: "2024-05-17", event: "参議院本会議で可決・成立", eventEn: "Passed and enacted by the House of Councillors plenary" },
      { date: "2026-04-01", event: "施行", eventEn: "Enters into force" },
    ],
    impact: "離婚後の共同親権が可能に。年間約20万組の離婚に影響する家族法の大転換。",
    impactEn: "Joint custody after divorce becomes possible, a major transformation of family law affecting roughly 200,000 divorces per year.",
  },

  // ──────────────────────────────────────────
  // 第221回国会で成立・施行（2026年3月31日成立→即日or4月1日施行）
  // ──────────────────────────────────────────
  {
    slug: "special-deficit-bonds-extension",
    title: "特例公債法改正（赤字国債発行特例延長）",
    titleEn: "Special Deficit Bond Act Amendment (Five-Year Extension)",
    committee: "財務金融委員会",
    committeeEn: "Committee on Financial Affairs",
    enactedDate: "2026-03-31",
    effectiveDate: "2026-04-01",
    summary: "赤字国債（特例公債）の発行根拠をFY2026〜FY2030の5年間延長する改正法。",
    summaryEn: "An amendment extending by five years (FY2026–FY2030) the legal basis for issuing special deficit-financing bonds.",
    detail: "財政運営に必要な財源の確保を図るための公債の発行の特例に関する法律の改正。特例公債の発行期限を5年間（令和8年度〜令和12年度）延長。野党は単年度限りを主張したが、政府・与党案が成立。予算関連法案として暫定予算成立と同日の3月30日に衆議院を通過し、3月31日に参議院で成立。",
    detailEn: "An amendment to the Act on Special Measures Concerning Bond Issuance for Securing Fiscal Resources. It extends the deadline for issuing special deficit-financing bonds by five years (FY2026 to FY2030). The opposition argued for a single-year extension, but the government and ruling parties' version passed. As budget-related legislation, it cleared the House of Representatives on March 30, the same day as the provisional budget, and was enacted on March 31 by the House of Councillors.",
    keyPoints: [
      "赤字国債発行の法的根拠を5年間延長",
      "FY2026〜FY2030の発行を一括承認",
      "野党の単年度限定案は否決",
      "暫定予算と同日に衆議院通過",
    ],
    keyPointsEn: [
      "Legal basis for deficit-financing bond issuance extended by five years",
      "Authorization for FY2026–FY2030 issuance as a single package",
      "Opposition proposal for single-year extension rejected",
      "Cleared the House of Representatives on the same day as the provisional budget",
    ],
    voteResult: { for: 245, against: 196 },
    parties: [
      { name: "自由民主党", nameEn: "Liberal Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "日本維新の会", nameEn: "Nippon Ishin no Kai", vote: "賛成", voteEn: "For" },
      { name: "中道改革連合", nameEn: "Centrist Reform Coalition", vote: "反対", voteEn: "Against" },
      { name: "国民民主党", nameEn: "Democratic Party for the People", vote: "反対", voteEn: "Against" },
      { name: "日本共産党", nameEn: "Japanese Communist Party", vote: "反対", voteEn: "Against" },
    ],
    timeline: [
      { date: "2026-02-20", event: "法案を国会提出", eventEn: "Bill submitted to the Diet" },
      { date: "2026-03-13", event: "衆議院財務金融委員会で可決", eventEn: "Passed by the House of Representatives Committee on Financial Affairs" },
      { date: "2026-03-30", event: "衆議院本会議で可決", eventEn: "Passed by the House of Representatives plenary" },
      { date: "2026-03-31", event: "参議院本会議で可決・成立", eventEn: "Passed and enacted by the House of Councillors plenary" },
      { date: "2026-04-01", event: "施行", eventEn: "Enters into force" },
    ],
    impact: "国の借金の仕組みに関わる法律。5年間の安定的な財政運営を担保する一方、財政規律への懸念も。",
    impactEn: "A law touching the mechanics of national debt. It secures five years of stable fiscal operation while raising concerns about fiscal discipline.",
  },
  {
    slug: "income-tax-reform-2026",
    title: "所得税法等改正（2026年度税制改正）",
    titleEn: "Income Tax Act Amendment (FY2026 Tax Reform)",
    committee: "財務金融委員会",
    committeeEn: "Committee on Financial Affairs",
    enactedDate: "2026-03-31",
    effectiveDate: "2026-04-01",
    summary: "基礎控除の引き上げ（103万円→123万円）を含む2026年度税制改正法。「年収の壁」対策が柱。",
    summaryEn: "The FY2026 tax reform law, centered on raising the basic deduction (1.03 million yen to 1.23 million yen) and targeting the 'income wall.'",
    detail: "2026年度税制改正の柱として、所得税の基礎控除を48万円から58万円に引き上げ（給与所得控除と合わせて103万円→123万円）。いわゆる「103万円の壁」の緩和を図る。防衛力強化のための増税（所得税・法人税・たばこ税）の開始時期も規定。企業向けにはDX投資減税、賃上げ税制の拡充を盛り込む。",
    detailEn: "As the centerpiece of the FY2026 tax reform, the income tax basic deduction is raised from 480,000 yen to 580,000 yen (together with the employment income deduction, moving the threshold from 1.03 million yen to 1.23 million yen), easing the so-called '1.03 million yen income wall.' The law also specifies the timing for tax increases to fund defense spending (income, corporate, and tobacco taxes). For businesses, it introduces DX investment tax credits and expands wage-increase promotion tax measures.",
    keyPoints: [
      "基礎控除を48万円→58万円に引き上げ（年収の壁を123万円に）",
      "防衛増税の開始時期の規定",
      "DX投資減税の導入",
      "賃上げ税制の拡充・延長",
      "NISA制度の利便性向上措置",
    ],
    keyPointsEn: [
      "Basic deduction raised from 480,000 yen to 580,000 yen (income wall moved to 1.23 million yen)",
      "Timing of defense-related tax increases specified",
      "Introduction of DX investment tax credits",
      "Expansion and extension of wage-increase tax incentives",
      "Improvements to the usability of the NISA system",
    ],
    voteResult: { for: 248, against: 193 },
    parties: [
      { name: "自由民主党", nameEn: "Liberal Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "日本維新の会", nameEn: "Nippon Ishin no Kai", vote: "賛成", voteEn: "For" },
      { name: "中道改革連合", nameEn: "Centrist Reform Coalition", vote: "反対", voteEn: "Against" },
      { name: "国民民主党", nameEn: "Democratic Party for the People", vote: "反対", voteEn: "Against" },
      { name: "日本共産党", nameEn: "Japanese Communist Party", vote: "反対", voteEn: "Against" },
    ],
    timeline: [
      { date: "2025-12-20", event: "与党税制改正大綱を決定", eventEn: "Ruling parties finalize the tax reform outline" },
      { date: "2026-02-20", event: "法案を国会提出", eventEn: "Bill submitted to the Diet" },
      { date: "2026-03-13", event: "衆議院本会議で可決", eventEn: "Passed by the House of Representatives plenary" },
      { date: "2026-03-31", event: "参議院本会議で可決・成立", eventEn: "Passed and enacted by the House of Councillors plenary" },
      { date: "2026-04-01", event: "施行（一部は2027年1月から適用）", eventEn: "Enters into force (some provisions apply from January 2027)" },
    ],
    impact: "約5,000万人の給与所得者に影響。年収の壁の緩和で、パート・アルバイトの就労調整の軽減が期待される。",
    impactEn: "Affects about 50 million wage earners. Easing the income wall is expected to reduce work-hour adjustments by part-time and casual workers.",
  },
  {
    slug: "local-tax-reform-2026",
    title: "地方税法等改正（2026年度）",
    titleEn: "Local Tax Act Amendment (FY2026)",
    committee: "総務委員会",
    committeeEn: "Committee on General Affairs",
    enactedDate: "2026-03-31",
    effectiveDate: "2026-04-01",
    summary: "住民税の非課税限度額の見直しや固定資産税の負担調整措置の延長を含む地方税制改正。",
    summaryEn: "A local tax reform covering revisions to the resident tax exemption threshold and extension of fixed-asset tax burden adjustment measures.",
    detail: "所得税法等改正と連動した地方税制の改正。住民税の非課税限度額の引き上げ、固定資産税の負担調整措置の延長、車体課税の見直し（電動車の軽減措置延長）等を含む。地方自治体の税収への影響を考慮した経過措置も規定。",
    detailEn: "A local tax reform linked to the income tax amendment. It includes raising the resident tax exemption threshold, extending burden adjustment measures for fixed-asset tax, and revising vehicle taxation (extension of preferential measures for electric vehicles). Transitional measures are also set out to cushion the impact on local government revenues.",
    keyPoints: [
      "住民税の非課税限度額の引き上げ",
      "固定資産税の負担調整措置の延長",
      "電動車に対する車体課税の軽減措置延長",
      "地方自治体への減収補てん措置",
    ],
    keyPointsEn: [
      "Higher resident tax exemption threshold",
      "Extension of burden adjustment measures for fixed-asset tax",
      "Extended preferential vehicle taxation for electric vehicles",
      "Compensatory measures for local revenue losses",
    ],
    voteResult: { for: 246, against: 195 },
    parties: [
      { name: "自由民主党", nameEn: "Liberal Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "日本維新の会", nameEn: "Nippon Ishin no Kai", vote: "賛成", voteEn: "For" },
      { name: "中道改革連合", nameEn: "Centrist Reform Coalition", vote: "反対", voteEn: "Against" },
      { name: "国民民主党", nameEn: "Democratic Party for the People", vote: "反対", voteEn: "Against" },
      { name: "日本共産党", nameEn: "Japanese Communist Party", vote: "反対", voteEn: "Against" },
    ],
    timeline: [
      { date: "2026-02-20", event: "法案を国会提出", eventEn: "Bill submitted to the Diet" },
      { date: "2026-03-31", event: "参議院本会議で可決・成立", eventEn: "Passed and enacted by the House of Councillors plenary" },
      { date: "2026-04-01", event: "施行", eventEn: "Enters into force" },
    ],
    impact: "住民税の負担軽減と地方財政の安定化。電動車普及促進にも寄与。",
    impactEn: "Lightens resident tax burdens and stabilizes local finances, while also supporting EV uptake.",
  },
  {
    slug: "local-allocation-tax-2026",
    title: "地方交付税法等改正（2026年度）",
    titleEn: "Local Allocation Tax Act Amendment (FY2026)",
    committee: "総務委員会",
    committeeEn: "Committee on General Affairs",
    enactedDate: "2026-03-31",
    effectiveDate: "2026-04-01",
    summary: "地方交付税の総額確保と算定方法の見直しを含む改正法。地方自治体の財政運営に直結。",
    summaryEn: "An amendment securing total local allocation tax funds and revising the calculation method, directly affecting local government finances.",
    detail: "2026年度の地方交付税総額を18.9兆円に設定し、地方自治体の一般財源を確保する改正法。過疎地域への交付額の増額、デジタル化推進に要する経費の算定への反映、防災・減災対策に係る特別交付税の拡充を含む。",
    detailEn: "Sets FY2026 total local allocation tax at 18.9 trillion yen to secure general revenues for local governments. It includes increased allocations to depopulated areas, reflection of digitalization costs in the calculation, and expanded special allocations for disaster prevention and mitigation.",
    keyPoints: [
      "地方交付税総額18.9兆円の確保",
      "過疎地域への交付額の増額",
      "デジタル化経費の交付税算定への反映",
      "防災・減災対策の特別交付税拡充",
    ],
    keyPointsEn: [
      "Total local allocation tax secured at 18.9 trillion yen",
      "Increased allocations to depopulated areas",
      "Digitalization expenses reflected in allocation calculations",
      "Expanded special allocations for disaster prevention and mitigation",
    ],
    voteResult: { for: 310, against: 131 },
    parties: [
      { name: "自由民主党", nameEn: "Liberal Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "日本維新の会", nameEn: "Nippon Ishin no Kai", vote: "賛成", voteEn: "For" },
      { name: "中道改革連合", nameEn: "Centrist Reform Coalition", vote: "賛成", voteEn: "For" },
      { name: "国民民主党", nameEn: "Democratic Party for the People", vote: "賛成", voteEn: "For" },
      { name: "日本共産党", nameEn: "Japanese Communist Party", vote: "反対", voteEn: "Against" },
    ],
    timeline: [
      { date: "2026-02-20", event: "法案を国会提出", eventEn: "Bill submitted to the Diet" },
      { date: "2026-03-31", event: "参議院本会議で可決・成立", eventEn: "Passed and enacted by the House of Councillors plenary" },
      { date: "2026-04-01", event: "施行", eventEn: "Enters into force" },
    ],
    impact: "全国約1,700の地方自治体の財政運営に直結。地方の行政サービスの維持を支える。",
    impactEn: "Directly affects the finances of roughly 1,700 local governments nationwide, helping sustain local public services.",
  },
  {
    slug: "reconstruction-finance-extension",
    title: "東日本大震災復興財源確保特措法改正",
    titleEn: "Reconstruction Finance Special Measures Act Amendment",
    committee: "財務金融委員会",
    committeeEn: "Committee on Financial Affairs",
    enactedDate: "2026-03-31",
    effectiveDate: "2026-04-01",
    summary: "東日本大震災の復興事業に必要な財源を引き続き確保するための特別措置法の改正。",
    summaryEn: "An amendment to the special measures law to continue securing funds for Great East Japan Earthquake reconstruction projects.",
    detail: "復興特別所得税の課税期間と復興債の発行期限に関する規定を見直し、復興事業の継続に必要な財源を確保。防衛費増額の財源として復興特別所得税の一部を転用する措置の詳細も規定。",
    detailEn: "Revises provisions on the special reconstruction income tax period and the deadline for issuing reconstruction bonds, securing the funds needed to continue reconstruction work. It also specifies details of the measure diverting part of the special reconstruction income tax to fund defense spending.",
    keyPoints: [
      "復興特別所得税の課税期間の見直し",
      "復興債の発行期限の延長",
      "防衛費財源への一部転用措置の規定",
    ],
    keyPointsEn: [
      "Revised special reconstruction income tax period",
      "Extended deadline for reconstruction bond issuance",
      "Provisions on partial diversion to defense funding",
    ],
    voteResult: { for: 250, against: 191 },
    parties: [
      { name: "自由民主党", nameEn: "Liberal Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "日本維新の会", nameEn: "Nippon Ishin no Kai", vote: "賛成", voteEn: "For" },
      { name: "中道改革連合", nameEn: "Centrist Reform Coalition", vote: "反対", voteEn: "Against" },
      { name: "国民民主党", nameEn: "Democratic Party for the People", vote: "反対", voteEn: "Against" },
      { name: "日本共産党", nameEn: "Japanese Communist Party", vote: "反対", voteEn: "Against" },
    ],
    timeline: [
      { date: "2026-02-20", event: "法案を国会提出", eventEn: "Bill submitted to the Diet" },
      { date: "2026-03-31", event: "参議院本会議で可決・成立", eventEn: "Passed and enacted by the House of Councillors plenary" },
    ],
    impact: "東日本大震災からの復興事業の継続と、防衛費増額の財源確保を両立。",
    impactEn: "Continues reconstruction from the Great East Japan Earthquake while also securing funds for higher defense spending.",
  },
  {
    slug: "customs-tariff-reform-2026",
    title: "関税定率法等改正（2026年度）",
    titleEn: "Customs Tariff Act Amendment (FY2026)",
    committee: "財務金融委員会",
    committeeEn: "Committee on Financial Affairs",
    enactedDate: "2026-03-31",
    effectiveDate: "2026-04-01",
    summary: "関税率の見直しと通関手続きの効率化を含む改正法。",
    summaryEn: "An amendment revising tariff rates and streamlining customs procedures.",
    detail: "暫定税率の延長・見直し、経済連携協定（EPA）に基づく特恵税率の適用拡大、通関手続きの電子化推進を含む。食料安全保障の観点から、重要農産物の関税水準の維持も規定。",
    detailEn: "Includes extension and revision of provisional tariff rates, expanded application of preferential rates under Economic Partnership Agreements (EPAs), and digitalization of customs procedures. From a food security standpoint, it also maintains tariff levels on key agricultural products.",
    keyPoints: [
      "暫定税率の延長・見直し",
      "EPA特恵税率の適用拡大",
      "通関手続きの電子化推進",
      "重要農産物の関税水準維持",
    ],
    keyPointsEn: [
      "Extension and revision of provisional tariff rates",
      "Expanded application of EPA preferential rates",
      "Digitalization of customs procedures",
      "Maintained tariff levels on key agricultural products",
    ],
    voteResult: { for: 380, against: 61 },
    parties: [
      { name: "自由民主党", nameEn: "Liberal Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "日本維新の会", nameEn: "Nippon Ishin no Kai", vote: "賛成", voteEn: "For" },
      { name: "中道改革連合", nameEn: "Centrist Reform Coalition", vote: "賛成", voteEn: "For" },
      { name: "国民民主党", nameEn: "Democratic Party for the People", vote: "賛成", voteEn: "For" },
      { name: "日本共産党", nameEn: "Japanese Communist Party", vote: "反対", voteEn: "Against" },
    ],
    timeline: [
      { date: "2026-02-20", event: "法案を国会提出", eventEn: "Bill submitted to the Diet" },
      { date: "2026-03-31", event: "成立", eventEn: "Enacted" },
      { date: "2026-04-01", event: "施行", eventEn: "Enters into force" },
    ],
    impact: "輸出入に関わる企業に影響。通関手続きの効率化で物流コスト削減が期待される。",
    impactEn: "Affects import-export businesses. Streamlined customs is expected to lower logistics costs.",
  },
  {
    slug: "high-school-tuition-free",
    title: "高等学校等就学支援金支給法改正（高校無償化拡大）",
    titleEn: "High School Tuition Support Act Amendment (Free High School Tuition Expansion)",
    committee: "文部科学委員会",
    committeeEn: "Committee on Education, Culture, Sports, Science and Technology",
    enactedDate: "2026-03-31",
    effectiveDate: "2026-04-01",
    summary: "高校授業料の実質無償化の所得制限を撤廃し、全ての高校生の授業料を無償化する改正法。",
    summaryEn: "An amendment removing the income cap on effective free high-school tuition and making tuition free for all high-school students.",
    detail: "2010年に導入された高等学校等就学支援金制度の所得制限（年収約910万円未満）を撤廃し、全ての高校生を対象とする。私立高校の支援金額の引き上げも含む。教育費負担の軽減による少子化対策としても位置づけられる。",
    detailEn: "Removes the income limit (roughly 9.1 million yen annual income) on the high school enrollment support benefit system introduced in 2010, extending coverage to all high-school students. It also raises support amounts for private high schools. Positioned as both an education and a declining-birthrate measure, easing household education costs.",
    keyPoints: [
      "就学支援金の所得制限撤廃",
      "全高校生の授業料実質無償化",
      "私立高校への支援金額の引き上げ",
      "少子化対策としての教育費軽減",
    ],
    keyPointsEn: [
      "Removal of the income cap on enrollment support benefits",
      "Effective free tuition for all high-school students",
      "Increased support for private high schools",
      "Lower education costs as a declining-birthrate measure",
    ],
    voteResult: { for: 420, against: 21 },
    parties: [
      { name: "自由民主党", nameEn: "Liberal Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "日本維新の会", nameEn: "Nippon Ishin no Kai", vote: "賛成", voteEn: "For" },
      { name: "中道改革連合", nameEn: "Centrist Reform Coalition", vote: "賛成", voteEn: "For" },
      { name: "国民民主党", nameEn: "Democratic Party for the People", vote: "賛成", voteEn: "For" },
      { name: "日本共産党", nameEn: "Japanese Communist Party", vote: "賛成", voteEn: "For" },
    ],
    timeline: [
      { date: "2026-02-20", event: "法案を国会提出", eventEn: "Bill submitted to the Diet" },
      { date: "2026-03-13", event: "衆議院本会議で可決", eventEn: "Passed by the House of Representatives plenary" },
      { date: "2026-03-31", event: "参議院本会議で可決・成立", eventEn: "Passed and enacted by the House of Councillors plenary" },
      { date: "2026-04-01", event: "施行（2026年度入学者から適用）", eventEn: "Enters into force (applies from students entering in FY2026)" },
    ],
    impact: "約300万人の高校生に影響。全高校生の授業料が実質無償化され、家庭の教育費負担が大幅に軽減。",
    impactEn: "Affects about 3 million high-school students. Tuition is effectively made free for all, substantially easing household education costs.",
  },
  {
    slug: "class-size-reduction",
    title: "公立義務教育学級編制・教職員定数法改正（35人学級）",
    titleEn: "Public Compulsory Education Class Size and Teacher Quota Act Amendment (35-Student Classes)",
    committee: "文部科学委員会",
    committeeEn: "Committee on Education, Culture, Sports, Science and Technology",
    enactedDate: "2026-03-31",
    effectiveDate: "2026-04-01",
    summary: "小学校に続き中学校でも1学級35人以下の少人数学級を段階的に実現する改正法。",
    summaryEn: "An amendment phasing in 35-student classes at junior high schools, following the earlier reform for elementary schools.",
    detail: "2021年から段階的に進められてきた小学校の35人学級を踏まえ、中学校でも2026年度から35人学級を段階的に導入する改正法。2030年度までに全学年で完成。併せて教職員定数の改善と、特別支援教育の体制強化を含む。",
    detailEn: "Building on the phased move to 35-student classes in elementary schools since 2021, this amendment introduces 35-student classes at junior high schools in phases starting FY2026, to be completed across all grades by FY2030. It also improves teacher quotas and strengthens systems for special-needs education.",
    keyPoints: [
      "中学校でも35人学級を段階的に導入",
      "2030年度までに全学年で完成",
      "教職員定数の改善",
      "特別支援教育の体制強化",
    ],
    keyPointsEn: [
      "Phased introduction of 35-student classes in junior high schools",
      "Full coverage across all grades by FY2030",
      "Improved teacher quotas",
      "Strengthened special-needs education support",
    ],
    voteResult: { for: 435, against: 6 },
    parties: [
      { name: "自由民主党", nameEn: "Liberal Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "日本維新の会", nameEn: "Nippon Ishin no Kai", vote: "賛成", voteEn: "For" },
      { name: "中道改革連合", nameEn: "Centrist Reform Coalition", vote: "賛成", voteEn: "For" },
      { name: "国民民主党", nameEn: "Democratic Party for the People", vote: "賛成", voteEn: "For" },
      { name: "日本共産党", nameEn: "Japanese Communist Party", vote: "賛成", voteEn: "For" },
    ],
    timeline: [
      { date: "2026-02-20", event: "法案を国会提出", eventEn: "Bill submitted to the Diet" },
      { date: "2026-03-31", event: "成立", eventEn: "Enacted" },
      { date: "2026-04-01", event: "施行", eventEn: "Enters into force" },
    ],
    impact: "中学校の教育環境が改善。きめ細かな指導の実現に向けた大きな一歩。",
    impactEn: "Improves junior-high-school learning environments, a major step toward more individualized instruction.",
  },

  // ──────────────────────────────────────────
  // 第217回国会（2025年通常国会）成立・施行済み — 主要法
  // ──────────────────────────────────────────
  {
    slug: "active-cyber-defense",
    title: "能動的サイバー防御法",
    titleEn: "Active Cyber Defense Act",
    committee: "内閣委員会",
    committeeEn: "Cabinet Committee",
    enactedDate: "2025-05-16",
    effectiveDate: "2025-08-01",
    summary: "重要インフラへのサイバー攻撃に対し、政府が能動的に防御措置を講じることを可能にする新法。",
    summaryEn: "A new law enabling the government to take proactive defensive measures against cyberattacks on critical infrastructure.",
    detail: "重要電子計算機に対する不正な行為による被害の防止に関する法律。電力、通信、金融等の重要インフラに対するサイバー攻撃に際し、政府が通信の分析（メタデータの監視）やマルウェアの無力化等の能動的な防御措置を講じることを可能にする。内閣サイバーセキュリティセンター（NISC）の機能を大幅に強化し、独立した「サイバー安全保障監視委員会」を設置して措置の適正性を監視する。与野党の修正協議を経て成立。",
    detailEn: "The Act on Preventing Harm from Unauthorized Acts against Critical Computers. In response to cyberattacks on critical infrastructure such as power, telecommunications, and finance, it allows the government to carry out proactive defensive measures including communications analysis (metadata monitoring) and malware neutralization. It significantly strengthens the functions of the National Center of Incident Readiness and Strategy for Cybersecurity (NISC) and establishes an independent Cybersecurity Oversight Committee to monitor the propriety of measures. Enacted following revisions negotiated between ruling and opposition parties.",
    keyPoints: [
      "サイバー攻撃への能動的防御措置を法定化",
      "通信メタデータの監視権限を政府に付与",
      "マルウェアの無力化等の措置を規定",
      "サイバー安全保障監視委員会の設置",
      "重要インフラ事業者への報告義務",
    ],
    keyPointsEn: [
      "Active cyber-defense measures codified in law",
      "Government granted authority to monitor communications metadata",
      "Measures such as malware neutralization established",
      "Establishment of the Cybersecurity Oversight Committee",
      "Reporting obligations on critical infrastructure operators",
    ],
    voteResult: { for: 378, against: 65 },
    parties: [
      { name: "自由民主党", nameEn: "Liberal Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "公明党", nameEn: "Komeito", vote: "賛成", voteEn: "For" },
      { name: "立憲民主党", nameEn: "Constitutional Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "日本維新の会", nameEn: "Nippon Ishin no Kai", vote: "賛成", voteEn: "For" },
      { name: "国民民主党", nameEn: "Democratic Party for the People", vote: "賛成", voteEn: "For" },
      { name: "日本共産党", nameEn: "Japanese Communist Party", vote: "反対", voteEn: "Against" },
      { name: "れいわ新選組", nameEn: "Reiwa Shinsengumi", vote: "反対", voteEn: "Against" },
    ],
    timeline: [
      { date: "2025-02-07", event: "法案を閣議決定・国会提出", eventEn: "Bill approved by the Cabinet and submitted to the Diet" },
      { date: "2025-04-08", event: "衆議院内閣委員会で修正可決", eventEn: "Passed with revisions by the House of Representatives Cabinet Committee" },
      { date: "2025-05-16", event: "参議院本会議で可決・成立", eventEn: "Passed and enacted by the House of Councillors plenary" },
      { date: "2025-08-01", event: "施行", eventEn: "Enters into force" },
    ],
    impact: "サイバー空間における日本の防衛能力が大幅に強化。重要インフラの安全性が向上。",
    impactEn: "Significantly strengthens Japan's defensive capabilities in cyberspace and improves the security of critical infrastructure.",
  },
  {
    slug: "ai-promotion-act",
    title: "AI研究開発活用推進法（AI新法）",
    titleEn: "AI Research and Utilization Promotion Act",
    committee: "内閣委員会",
    committeeEn: "Cabinet Committee",
    enactedDate: "2025-05-28",
    effectiveDate: "2025-09-01",
    summary: "AIの研究開発と利活用を推進するための基本法。日本初の包括的AI法。",
    summaryEn: "A basic law promoting the research, development, and use of artificial intelligence. Japan's first comprehensive AI law.",
    detail: "人工知能関連技術の研究開発及び活用の推進に関する法律。AI技術の研究開発の促進、安全で信頼できるAIの利活用のためのガイドライン策定、AI人材の育成を柱とする。EUのAI規制法とは異なりリスクベースの規制ではなく、イノベーション促進と社会的課題解決を重視した「推進法」としての性格が強い。",
    detailEn: "The Act on the Promotion of Research, Development and Utilization of AI-Related Technology. Its pillars are promoting AI R&D, formulating guidelines for safe and trustworthy AI use, and developing AI talent. Unlike the EU AI Act's risk-based regulation, Japan's law is characterized as a 'promotion' law emphasizing innovation and solving social challenges.",
    keyPoints: [
      "AI研究開発の国の責務を明記",
      "信頼できるAIの利活用ガイドラインの策定",
      "AI人材の育成・確保策",
      "AI安全研究所（AISI）の法的位置づけ",
      "AIによる社会的課題解決の推進",
    ],
    keyPointsEn: [
      "National responsibility for AI R&D explicitly set out",
      "Guidelines for trustworthy AI use",
      "Measures to develop and secure AI talent",
      "Legal positioning of the AI Safety Institute (AISI)",
      "Promotion of AI-driven solutions to social challenges",
    ],
    voteResult: { for: 410, against: 33 },
    parties: [
      { name: "自由民主党", nameEn: "Liberal Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "公明党", nameEn: "Komeito", vote: "賛成", voteEn: "For" },
      { name: "立憲民主党", nameEn: "Constitutional Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "日本維新の会", nameEn: "Nippon Ishin no Kai", vote: "賛成", voteEn: "For" },
      { name: "国民民主党", nameEn: "Democratic Party for the People", vote: "賛成", voteEn: "For" },
      { name: "日本共産党", nameEn: "Japanese Communist Party", vote: "反対", voteEn: "Against" },
    ],
    timeline: [
      { date: "2025-03-07", event: "法案を閣議決定・国会提出", eventEn: "Bill approved by the Cabinet and submitted to the Diet" },
      { date: "2025-05-28", event: "参議院本会議で可決・成立", eventEn: "Passed and enacted by the House of Councillors plenary" },
      { date: "2025-09-01", event: "施行", eventEn: "Enters into force" },
    ],
    impact: "AI産業の発展を後押しする法的基盤。日本のAI戦略の方向性を法律で明確化。",
    impactEn: "A legal foundation supporting the AI industry and clarifying the direction of Japan's AI strategy.",
  },
  {
    slug: "pension-reform-2025",
    title: "年金改革法（厚生年金適用拡大等）",
    titleEn: "Pension Reform Act (Expanded Employees' Pension Coverage)",
    committee: "厚生労働委員会",
    committeeEn: "Health, Labour and Welfare Committee",
    enactedDate: "2025-06-13",
    effectiveDate: "2025-10-01",
    summary: "厚生年金の適用対象を従業員50人以下の企業にも拡大し、年金制度の持続可能性を強化する改正法。",
    summaryEn: "An amendment extending Employees' Pension coverage to companies with 50 or fewer employees and strengthening the sustainability of the pension system.",
    detail: "社会経済の変化を踏まえた年金制度の機能強化のための国民年金法等の一部を改正する法律。厚生年金の適用基準を段階的に引き下げ（従業員50人以下の企業にも適用）、在職老齢年金制度の見直し（月収62万円以下は減額なし）、国民年金の保険料納付期間の延長検討規定などを含む。与野党修正を経て成立。",
    detailEn: "A partial amendment to the National Pension Act and related laws to strengthen pension functions in line with changing social and economic conditions. It lowers the thresholds for Employees' Pension coverage in phases (extending it to companies with 50 or fewer employees), revises the working-retiree pension system (no reduction for monthly income up to 620,000 yen), and includes provisions to consider extending the National Pension contribution period. Enacted after revisions by ruling and opposition parties.",
    keyPoints: [
      "厚生年金の適用対象を従業員50人以下企業に拡大",
      "在職老齢年金の支給停止基準の緩和（月収62万円）",
      "マクロ経済スライドの早期終了策",
      "国民年金保険料納付期間の延長検討規定",
      "年金受給開始年齢の柔軟化（75歳まで繰下げ可能を維持）",
    ],
    keyPointsEn: [
      "Employees' Pension extended to companies with 50 or fewer employees",
      "Eased benefit-suspension threshold for working retirees (monthly income 620,000 yen)",
      "Measures to end macroeconomic indexation earlier",
      "Provision to consider extending the National Pension contribution period",
      "Flexibility in pension start age retained (deferral up to age 75 preserved)",
    ],
    voteResult: { for: 345, against: 98 },
    parties: [
      { name: "自由民主党", nameEn: "Liberal Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "公明党", nameEn: "Komeito", vote: "賛成", voteEn: "For" },
      { name: "立憲民主党", nameEn: "Constitutional Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "日本維新の会", nameEn: "Nippon Ishin no Kai", vote: "賛成", voteEn: "For" },
      { name: "国民民主党", nameEn: "Democratic Party for the People", vote: "反対", voteEn: "Against" },
      { name: "日本共産党", nameEn: "Japanese Communist Party", vote: "反対", voteEn: "Against" },
    ],
    timeline: [
      { date: "2025-02-14", event: "法案を閣議決定・国会提出", eventEn: "Bill approved by the Cabinet and submitted to the Diet" },
      { date: "2025-05-22", event: "衆議院本会議で修正可決", eventEn: "Passed with revisions by the House of Representatives plenary" },
      { date: "2025-06-13", event: "参議院本会議で可決・成立", eventEn: "Passed and enacted by the House of Councillors plenary" },
      { date: "2025-10-01", event: "主要規定が施行", eventEn: "Main provisions enter into force" },
    ],
    impact: "パート・アルバイト労働者約200万人が新たに厚生年金の対象に。老後の所得保障が強化される。",
    impactEn: "About 2 million part-time and casual workers newly become eligible for Employees' Pension, strengthening retirement income security.",
  },
  {
    slug: "customer-harassment-act",
    title: "カスハラ対策法（カスタマーハラスメント規制）",
    titleEn: "Customer Harassment Prevention Act",
    committee: "厚生労働委員会",
    committeeEn: "Health, Labour and Welfare Committee",
    enactedDate: "2025-06-18",
    effectiveDate: "2025-10-01",
    summary: "カスタマーハラスメント（悪質なクレーム等）から労働者を保護するための法律。",
    summaryEn: "A law protecting workers from customer harassment (malicious complaints and similar behavior).",
    detail: "労働施策総合推進法等の一部改正。事業主にカスタマーハラスメント対策措置を義務化。パワハラ・セクハラに続き、顧客等からの著しい迷惑行為（暴言・暴力・長時間拘束・不当な要求等）について、事業主が相談体制の整備や被害者保護措置を講じることを法定化。フリーランスへの保護も含む。",
    detailEn: "A partial amendment to the Act on Comprehensive Promotion of Labour Policies. It mandates that employers take measures against customer harassment. Building on rules for power and sexual harassment, it legally requires employers to set up consultation systems and protect victims from extreme nuisance behavior by customers (verbal or physical abuse, prolonged detention, unreasonable demands, etc.). It also extends protections to freelancers.",
    keyPoints: [
      "カスタマーハラスメント対策の事業主義務化",
      "暴言・暴力・長時間拘束等の定義規定",
      "相談体制整備と被害者保護措置の義務",
      "フリーランスへの保護拡大",
      "就活セクハラ対策の強化",
    ],
    keyPointsEn: [
      "Mandatory employer measures against customer harassment",
      "Definitions of verbal abuse, violence, prolonged detention, and similar behavior",
      "Obligation to establish consultation systems and victim-protection measures",
      "Expanded protections for freelancers",
      "Strengthened measures against job-hunting sexual harassment",
    ],
    voteResult: { for: 430, against: 13 },
    parties: [
      { name: "自由民主党", nameEn: "Liberal Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "公明党", nameEn: "Komeito", vote: "賛成", voteEn: "For" },
      { name: "立憲民主党", nameEn: "Constitutional Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "日本維新の会", nameEn: "Nippon Ishin no Kai", vote: "賛成", voteEn: "For" },
      { name: "国民民主党", nameEn: "Democratic Party for the People", vote: "賛成", voteEn: "For" },
      { name: "日本共産党", nameEn: "Japanese Communist Party", vote: "賛成", voteEn: "For" },
    ],
    timeline: [
      { date: "2025-03-14", event: "法案を閣議決定・国会提出", eventEn: "Bill approved by the Cabinet and submitted to the Diet" },
      { date: "2025-06-18", event: "参議院本会議で可決・成立", eventEn: "Passed and enacted by the House of Councillors plenary" },
      { date: "2025-10-01", event: "施行", eventEn: "Enters into force" },
    ],
    impact: "小売・飲食・医療等の対面サービス業で働く約2,000万人の労働者保護が法的に強化。",
    impactEn: "Legally strengthens protection for some 20 million workers in face-to-face service industries such as retail, hospitality, and healthcare.",
  },
  {
    slug: "teacher-salary-reform",
    title: "教員給与改革法（教職調整額引上げ）",
    titleEn: "Teacher Salary Reform Act (Raising the Teaching Adjustment Allowance)",
    committee: "文部科学委員会",
    committeeEn: "Committee on Education, Culture, Sports, Science and Technology",
    enactedDate: "2025-05-09",
    effectiveDate: "2025-10-01",
    summary: "教員の教職調整額を4%から10%以上に段階的に引き上げ、教員の処遇を大幅に改善する改正法。",
    summaryEn: "An amendment raising teachers' teaching adjustment allowance from 4% to at least 10% in phases, substantially improving teacher compensation.",
    detail: "公立学校教員の給与を定める教特法を改正。50年間据え置かれていた教職調整額（残業代の代わりに支給）を4%から段階的に10%以上に引き上げ。教員の長時間労働を是正するための勤務時間管理の厳格化や、学級担任手当の創設も含む。教員不足解消に向けた処遇改善が目的。",
    detailEn: "An amendment to the Special Act on Salaries for Public School Teachers. The teaching adjustment allowance (paid in lieu of overtime), unchanged for 50 years, will be raised in phases from 4% to at least 10%. It also strengthens working-hour management to correct excessive hours and creates a new homeroom-teacher allowance. The aim is to improve teacher compensation in response to the teacher shortage.",
    keyPoints: [
      "教職調整額を4%→10%以上に段階的引上げ",
      "50年ぶりの大幅処遇改善",
      "勤務時間管理の厳格化",
      "学級担任手当の創設",
      "教員不足解消に向けた施策",
    ],
    keyPointsEn: [
      "Teaching adjustment allowance raised from 4% to 10% or more in phases",
      "Largest pay improvement in 50 years",
      "Stricter management of working hours",
      "New homeroom-teacher allowance",
      "Measures to address teacher shortages",
    ],
    voteResult: { for: 398, against: 45 },
    parties: [
      { name: "自由民主党", nameEn: "Liberal Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "公明党", nameEn: "Komeito", vote: "賛成", voteEn: "For" },
      { name: "立憲民主党", nameEn: "Constitutional Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "日本維新の会", nameEn: "Nippon Ishin no Kai", vote: "賛成", voteEn: "For" },
      { name: "国民民主党", nameEn: "Democratic Party for the People", vote: "賛成", voteEn: "For" },
      { name: "日本共産党", nameEn: "Japanese Communist Party", vote: "反対", voteEn: "Against" },
    ],
    timeline: [
      { date: "2025-02-14", event: "法案を閣議決定・国会提出", eventEn: "Bill approved by the Cabinet and submitted to the Diet" },
      { date: "2025-04-10", event: "衆議院文部科学委員会で修正可決", eventEn: "Passed with revisions by the House of Representatives Committee on Education" },
      { date: "2025-05-09", event: "参議院本会議で可決・成立", eventEn: "Passed and enacted by the House of Councillors plenary" },
      { date: "2025-10-01", event: "施行（段階的に調整額を引上げ）", eventEn: "Enters into force (adjustment allowance raised in phases)" },
    ],
    impact: "全国約70万人の公立学校教員の処遇が大幅改善。教員確保の切り札として期待される。",
    impactEn: "Substantially improves compensation for about 700,000 public-school teachers and is seen as a key lever to secure more teachers.",
  },
  {
    slug: "whistleblower-protection-reform",
    title: "改正公益通報者保護法",
    titleEn: "Revised Whistleblower Protection Act",
    committee: "消費者問題特別委員会",
    committeeEn: "Special Committee on Consumer Affairs",
    enactedDate: "2025-06-04",
    effectiveDate: "2025-12-01",
    summary: "内部通報者への不利益取扱いの罰則を新設し、通報者保護を大幅に強化する改正法。",
    summaryEn: "An amendment introducing criminal penalties for retaliating against internal whistleblowers and substantially strengthening whistleblower protection.",
    detail: "企業不祥事の早期発見・是正を促すため、内部通報者への解雇・降格等の不利益取扱いに対する刑事罰を新設。通報者の保護対象を退職後1年以内の元従業員にも拡大。企業の内部通報体制の整備義務を強化。ダイハツ・ビッグモーター等の企業不祥事を受けた改正。",
    detailEn: "To encourage early detection and correction of corporate misconduct, the amendment introduces criminal penalties for adverse treatment of internal whistleblowers such as dismissal or demotion. Protection is extended to former employees who left within the past year. It also strengthens companies' obligations to set up internal reporting systems. The amendment was prompted by a series of corporate scandals at companies such as Daihatsu and Bigmotor.",
    keyPoints: [
      "内部通報者への不利益取扱いに刑事罰を新設",
      "保護対象を退職後1年以内の元従業員に拡大",
      "企業の内部通報体制整備義務の強化",
      "行政機関への通報の要件緩和",
    ],
    keyPointsEn: [
      "New criminal penalties for adverse treatment of internal whistleblowers",
      "Coverage extended to former employees within one year of leaving",
      "Stronger obligations to build internal reporting systems",
      "Relaxed requirements for reports to administrative agencies",
    ],
    voteResult: { for: 415, against: 28 },
    parties: [
      { name: "自由民主党", nameEn: "Liberal Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "公明党", nameEn: "Komeito", vote: "賛成", voteEn: "For" },
      { name: "立憲民主党", nameEn: "Constitutional Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "日本維新の会", nameEn: "Nippon Ishin no Kai", vote: "賛成", voteEn: "For" },
      { name: "国民民主党", nameEn: "Democratic Party for the People", vote: "賛成", voteEn: "For" },
      { name: "日本共産党", nameEn: "Japanese Communist Party", vote: "賛成", voteEn: "For" },
    ],
    timeline: [
      { date: "2025-03-07", event: "法案を閣議決定・国会提出", eventEn: "Bill approved by the Cabinet and submitted to the Diet" },
      { date: "2025-06-04", event: "参議院本会議で可決・成立", eventEn: "Passed and enacted by the House of Councillors plenary" },
      { date: "2025-12-01", event: "施行", eventEn: "Enters into force" },
    ],
    impact: "企業の不正を告発する内部通報者の保護が強化。企業のコンプライアンス体制に大きな影響。",
    impactEn: "Strengthens protection for internal whistleblowers reporting corporate wrongdoing, with major implications for corporate compliance.",
  },
  {
    slug: "ntt-telecom-reform",
    title: "改正電気通信事業法・NTT法",
    titleEn: "Revised Telecommunications Business Act and NTT Act",
    committee: "総務委員会",
    committeeEn: "Committee on General Affairs",
    enactedDate: "2025-05-21",
    effectiveDate: "2025-10-01",
    summary: "NTT法を改正し、NTTの研究成果開示義務の廃止と外国人役員規制の強化を盛り込んだ通信改革法。",
    summaryEn: "A telecommunications reform law amending the NTT Act to abolish NTT's obligation to disclose research results and tighten restrictions on foreign board members.",
    detail: "日本電信電話株式会社等に関する法律（NTT法）と電気通信事業法を一括改正。NTTの研究成果開示義務を廃止して国際競争力を強化する一方、外国人役員の就任制限を維持しつつ社外取締役への登用は認める。電気通信事業法の改正では、通信障害時の利用者保護規定を強化。",
    detailEn: "A bundled amendment to the Act on Nippon Telegraph and Telephone Corporation (NTT Act) and the Telecommunications Business Act. NTT's obligation to disclose research results is abolished to strengthen international competitiveness, while restrictions on foreign board members are retained with appointment as outside directors now allowed. The Telecommunications Business Act amendment strengthens user-protection rules during communications outages.",
    keyPoints: [
      "NTTの研究成果開示義務の廃止",
      "外国人役員の社外取締役への登用を解禁",
      "通信障害時の利用者保護規定の強化",
      "通信市場の競争促進措置",
    ],
    keyPointsEn: [
      "Abolition of NTT's research-result disclosure obligation",
      "Foreign nationals allowed to serve as outside directors",
      "Stronger user protections during communications outages",
      "Measures to promote competition in the telecom market",
    ],
    voteResult: { for: 350, against: 93 },
    parties: [
      { name: "自由民主党", nameEn: "Liberal Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "公明党", nameEn: "Komeito", vote: "賛成", voteEn: "For" },
      { name: "日本維新の会", nameEn: "Nippon Ishin no Kai", vote: "賛成", voteEn: "For" },
      { name: "立憲民主党", nameEn: "Constitutional Democratic Party", vote: "反対", voteEn: "Against" },
      { name: "国民民主党", nameEn: "Democratic Party for the People", vote: "賛成", voteEn: "For" },
      { name: "日本共産党", nameEn: "Japanese Communist Party", vote: "反対", voteEn: "Against" },
    ],
    timeline: [
      { date: "2025-03-04", event: "法案を閣議決定・国会提出", eventEn: "Bill approved by the Cabinet and submitted to the Diet" },
      { date: "2025-05-21", event: "参議院本会議で可決・成立", eventEn: "Passed and enacted by the House of Councillors plenary" },
      { date: "2025-10-01", event: "施行", eventEn: "Enters into force" },
    ],
    impact: "NTTの経営自由度が拡大し、国際競争力強化が期待される一方、通信の公共性維持が課題。",
    impactEn: "Expands NTT's management flexibility and is expected to strengthen its international competitiveness, while maintaining telecom's public-service nature remains a challenge.",
  },
  {
    slug: "subcontract-act-reform",
    title: "改正下請法（中小企業への支払い適正化）",
    titleEn: "Revised Subcontract Act",
    committee: "経済産業委員会",
    committeeEn: "Committee on Economy, Trade and Industry",
    enactedDate: "2025-06-11",
    effectiveDate: "2025-11-01",
    summary: "下請事業者への支払い条件を改善し、サプライチェーン全体の取引適正化を図る改正法。",
    summaryEn: "An amendment improving payment terms for subcontractors and promoting fair transactions across the entire supply chain.",
    detail: "下請代金支払遅延等防止法を改正し、支払いサイトの短縮（手形の60日以内決済の義務化）、下請いじめへの罰則強化、フリーランスへの保護拡大を盛り込む。中小企業の価格転嫁促進にも寄与する改正。",
    detailEn: "Amends the Act against Delay in Payment of Subcontract Proceeds. It shortens payment sites (mandating settlement of promissory notes within 60 days), strengthens penalties for subcontractor bullying, and expands protections for freelancers. The amendment also supports price pass-through by SMEs.",
    keyPoints: [
      "手形の60日以内決済の義務化",
      "下請いじめへの罰則強化（課徴金制度導入）",
      "フリーランスへの保護拡大",
      "価格転嫁促進のための交渉ルールの整備",
    ],
    keyPointsEn: [
      "Mandatory settlement of promissory notes within 60 days",
      "Stronger penalties for subcontractor bullying (new surcharge system)",
      "Expanded protections for freelancers",
      "Rules to support price pass-through negotiations",
    ],
    voteResult: { for: 440, against: 3 },
    parties: [
      { name: "自由民主党", nameEn: "Liberal Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "公明党", nameEn: "Komeito", vote: "賛成", voteEn: "For" },
      { name: "立憲民主党", nameEn: "Constitutional Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "日本維新の会", nameEn: "Nippon Ishin no Kai", vote: "賛成", voteEn: "For" },
      { name: "国民民主党", nameEn: "Democratic Party for the People", vote: "賛成", voteEn: "For" },
      { name: "日本共産党", nameEn: "Japanese Communist Party", vote: "賛成", voteEn: "For" },
    ],
    timeline: [
      { date: "2025-03-07", event: "法案を閣議決定・国会提出", eventEn: "Bill approved by the Cabinet and submitted to the Diet" },
      { date: "2025-06-11", event: "参議院本会議で可決・成立", eventEn: "Passed and enacted by the House of Councillors plenary" },
      { date: "2025-11-01", event: "施行", eventEn: "Enters into force" },
    ],
    impact: "中小企業約360万社の取引条件が改善。サプライチェーン全体の適正化に寄与。",
    impactEn: "Improves trading terms for roughly 3.6 million SMEs and contributes to fairness across the supply chain.",
  },
  {
    slug: "stablecoin-regulation",
    title: "改正資金決済法（ステーブルコイン規制）",
    titleEn: "Revised Payment Services Act (Stablecoin Regulation)",
    committee: "財務金融委員会",
    committeeEn: "Committee on Financial Affairs",
    enactedDate: "2025-06-04",
    effectiveDate: "2025-11-01",
    summary: "ステーブルコインの発行・流通に関する規制を整備し、デジタル金融の安全性を確保する改正法。",
    summaryEn: "An amendment establishing rules for issuing and circulating stablecoins and securing the safety of digital finance.",
    detail: "暗号資産市場の拡大に対応し、ステーブルコイン（法定通貨担保型のデジタル通貨）の発行者の要件、利用者保護規定、マネーロンダリング対策を整備。クロスボーダー決済への対応やCBDC（中央銀行デジタル通貨）の将来的な導入を見据えた法的基盤の整備も含む。",
    detailEn: "In response to the expanding crypto-asset market, the amendment sets requirements for stablecoin issuers (digital currencies backed by fiat), user protection rules, and anti-money-laundering measures. It also includes provisions addressing cross-border payments and lays legal groundwork with a view to possible future introduction of a central bank digital currency (CBDC).",
    keyPoints: [
      "ステーブルコイン発行者の登録制度の創設",
      "利用者資産の分別管理義務",
      "マネーロンダリング対策の強化",
      "クロスボーダー決済への対応規定",
    ],
    keyPointsEn: [
      "New registration system for stablecoin issuers",
      "Obligation to segregate user assets",
      "Strengthened anti-money-laundering measures",
      "Provisions addressing cross-border payments",
    ],
    voteResult: { for: 395, against: 48 },
    parties: [
      { name: "自由民主党", nameEn: "Liberal Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "公明党", nameEn: "Komeito", vote: "賛成", voteEn: "For" },
      { name: "日本維新の会", nameEn: "Nippon Ishin no Kai", vote: "賛成", voteEn: "For" },
      { name: "国民民主党", nameEn: "Democratic Party for the People", vote: "賛成", voteEn: "For" },
      { name: "立憲民主党", nameEn: "Constitutional Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "日本共産党", nameEn: "Japanese Communist Party", vote: "反対", voteEn: "Against" },
    ],
    timeline: [
      { date: "2025-03-04", event: "法案を閣議決定・国会提出", eventEn: "Bill approved by the Cabinet and submitted to the Diet" },
      { date: "2025-06-04", event: "参議院本会議で可決・成立", eventEn: "Passed and enacted by the House of Councillors plenary" },
      { date: "2025-11-01", event: "施行", eventEn: "Enters into force" },
    ],
    impact: "日本のデジタル金融の法的基盤が強化。Web3・暗号資産産業の健全な発展に寄与。",
    impactEn: "Strengthens the legal foundation of Japan's digital finance and supports sound development of the Web3 and crypto-asset sector.",
  },
  {
    slug: "stolen-metal-regulation",
    title: "盗難金属規制法",
    titleEn: "Stolen Metal Regulation Act",
    committee: "内閣委員会",
    committeeEn: "Cabinet Committee",
    enactedDate: "2025-06-04",
    effectiveDate: "2025-09-01",
    summary: "太陽光パネルの銅線や道路のマンホール蓋等の金属盗難に対処するため、金属くず処分業者への規制を導入する新法。",
    summaryEn: "A new law regulating metal-scrap dealers to address theft of copper wiring from solar panels, manhole covers, and similar items.",
    detail: "全国で多発する銅線や金属部品の盗難に対応するための新法。金属くず処分業者に対し、取引記録の作成・保存を義務化し、身元確認を義務付ける。盗品の疑いがある金属の買取禁止、警察への通報義務も規定。太陽光発電施設や鉄道設備での金属盗難被害が急増したことを受けた立法。",
    detailEn: "A new law responding to the surge in thefts of copper wiring and metal parts nationwide. It requires metal-scrap dealers to create and retain transaction records and to verify sellers' identities. It also prohibits the purchase of metals suspected of being stolen and requires reporting to the police. The legislation was prompted by sharp increases in metal theft from solar power facilities and rail infrastructure.",
    keyPoints: [
      "金属くず処分業者への取引記録義務化",
      "買取時の身元確認義務",
      "盗品疑いのある金属の買取禁止",
      "警察への通報義務",
    ],
    keyPointsEn: [
      "Mandatory transaction records at metal-scrap dealers",
      "Mandatory identity verification at purchase",
      "Prohibition on purchasing metals suspected of being stolen",
      "Reporting obligations to the police",
    ],
    voteResult: { for: 443, against: 0 },
    parties: [
      { name: "自由民主党", nameEn: "Liberal Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "公明党", nameEn: "Komeito", vote: "賛成", voteEn: "For" },
      { name: "立憲民主党", nameEn: "Constitutional Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "日本維新の会", nameEn: "Nippon Ishin no Kai", vote: "賛成", voteEn: "For" },
      { name: "国民民主党", nameEn: "Democratic Party for the People", vote: "賛成", voteEn: "For" },
      { name: "日本共産党", nameEn: "Japanese Communist Party", vote: "賛成", voteEn: "For" },
    ],
    timeline: [
      { date: "2025-03-14", event: "法案を閣議決定・国会提出", eventEn: "Bill approved by the Cabinet and submitted to the Diet" },
      { date: "2025-06-04", event: "参議院本会議で全会一致で可決・成立", eventEn: "Passed unanimously and enacted by the House of Councillors plenary" },
      { date: "2025-09-01", event: "施行", eventEn: "Enters into force" },
    ],
    impact: "金属盗難被害の抑制が期待される。太陽光発電施設やインフラの安全確保に寄与。",
    impactEn: "Expected to curb metal theft, supporting the security of solar power facilities and other infrastructure.",
  },
  {
    slug: "disaster-measures-reform",
    title: "改正災害対策基本法",
    titleEn: "Revised Disaster Countermeasures Basic Act",
    committee: "内閣委員会",
    committeeEn: "Cabinet Committee",
    enactedDate: "2025-05-28",
    effectiveDate: "2025-10-01",
    summary: "能登半島地震の教訓を踏まえ、災害対応の初動体制と被災者支援を強化する改正法。",
    summaryEn: "An amendment drawing on lessons from the Noto Peninsula earthquake to strengthen initial disaster response and support for disaster victims.",
    detail: "2024年1月の能登半島地震での課題を踏まえた改正。国のプッシュ型支援の法定化、被災者生活再建支援金の増額、避難所の環境基準の設定、災害関連死の防止策を盛り込む。自治体間の広域応援体制の強化も規定。",
    detailEn: "An amendment informed by issues revealed during the January 2024 Noto Peninsula earthquake. It codifies the national government's 'push-type' support, increases livelihood reconstruction payments to victims, sets environmental standards for evacuation shelters, and establishes measures to prevent disaster-related deaths. It also strengthens wide-area mutual aid arrangements among local governments.",
    keyPoints: [
      "国のプッシュ型支援の法定化",
      "被災者生活再建支援金の増額",
      "避難所の環境基準の設定",
      "災害関連死防止策の規定",
      "自治体間の広域応援体制の強化",
    ],
    keyPointsEn: [
      "Push-type national support codified in law",
      "Higher livelihood reconstruction support payments",
      "Environmental standards for evacuation shelters",
      "Measures to prevent disaster-related deaths",
      "Strengthened wide-area mutual aid among local governments",
    ],
    voteResult: { for: 440, against: 3 },
    parties: [
      { name: "自由民主党", nameEn: "Liberal Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "公明党", nameEn: "Komeito", vote: "賛成", voteEn: "For" },
      { name: "立憲民主党", nameEn: "Constitutional Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "日本維新の会", nameEn: "Nippon Ishin no Kai", vote: "賛成", voteEn: "For" },
      { name: "国民民主党", nameEn: "Democratic Party for the People", vote: "賛成", voteEn: "For" },
      { name: "日本共産党", nameEn: "Japanese Communist Party", vote: "賛成", voteEn: "For" },
    ],
    timeline: [
      { date: "2025-02-14", event: "法案を閣議決定・国会提出", eventEn: "Bill approved by the Cabinet and submitted to the Diet" },
      { date: "2025-05-28", event: "参議院本会議で可決・成立", eventEn: "Passed and enacted by the House of Councillors plenary" },
      { date: "2025-10-01", event: "施行", eventEn: "Enters into force" },
    ],
    impact: "大規模災害時の対応力が強化。能登半島地震の教訓が全国の防災体制に反映される。",
    impactEn: "Strengthens response to large-scale disasters and reflects lessons from the Noto Peninsula earthquake in nationwide disaster management.",
  },
  {
    slug: "condominium-reform",
    title: "改正区分所有法（老朽マンション建替促進）",
    titleEn: "Revised Condominium Ownership Act (Accelerating Old Condo Rebuilds)",
    committee: "法務委員会",
    committeeEn: "Judicial Affairs Committee",
    enactedDate: "2025-06-11",
    effectiveDate: "2026-01-01",
    summary: "老朽化マンションの建替え決議の要件を緩和し、マンション再生を促進する改正法。",
    summaryEn: "An amendment relaxing requirements for resolutions to rebuild aging condominiums and promoting condo regeneration.",
    detail: "築40年超の老朽マンション約125万戸の建替え・改修を促進するため、建替え決議の要件を「区分所有者の5分の4以上」から「4分の3以上」に緩和。所在不明の区分所有者を決議の母数から除外する制度の導入、敷地売却決議の要件緩和も含む。",
    detailEn: "To promote rebuilding and refurbishment of roughly 1.25 million condominiums over 40 years old, the amendment eases the requirement for rebuild resolutions from 'at least four-fifths of unit owners' to 'at least three-quarters.' It also introduces rules excluding missing unit owners from the denominator and relaxes requirements for site-sale resolutions.",
    keyPoints: [
      "建替え決議の要件を5分の4→4分の3以上に緩和",
      "所在不明の区分所有者を母数から除外",
      "敷地売却決議の要件緩和",
      "マンション管理適正化の推進",
    ],
    keyPointsEn: [
      "Rebuild resolution threshold eased from four-fifths to three-quarters",
      "Missing unit owners excluded from the denominator",
      "Relaxed requirements for site-sale resolutions",
      "Promotion of proper condominium management",
    ],
    voteResult: { for: 420, against: 23 },
    parties: [
      { name: "自由民主党", nameEn: "Liberal Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "公明党", nameEn: "Komeito", vote: "賛成", voteEn: "For" },
      { name: "立憲民主党", nameEn: "Constitutional Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "日本維新の会", nameEn: "Nippon Ishin no Kai", vote: "賛成", voteEn: "For" },
      { name: "国民民主党", nameEn: "Democratic Party for the People", vote: "賛成", voteEn: "For" },
      { name: "日本共産党", nameEn: "Japanese Communist Party", vote: "反対", voteEn: "Against" },
    ],
    timeline: [
      { date: "2025-03-14", event: "法案を閣議決定・国会提出", eventEn: "Bill approved by the Cabinet and submitted to the Diet" },
      { date: "2025-06-11", event: "参議院本会議で可決・成立", eventEn: "Passed and enacted by the House of Councillors plenary" },
      { date: "2026-01-01", event: "施行", eventEn: "Enters into force" },
    ],
    impact: "全国約700万戸のマンションの管理・建替えに影響。老朽化対策が加速。",
    impactEn: "Affects management and rebuilding of roughly 7 million condominium units nationwide, accelerating measures against building aging.",
  },

  // ──────────────────────────────────────────
  // 第219回国会（2025年臨時国会）成立・施行済み
  // ──────────────────────────────────────────
  {
    slug: "stalker-regulation-reform",
    title: "改正ストーカー規制法",
    titleEn: "Revised Anti-Stalking Act",
    committee: "内閣委員会",
    committeeEn: "Cabinet Committee",
    enactedDate: "2025-12-10",
    effectiveDate: "2026-04-01",
    summary: "GPS機器の悪用やSNSでのつきまとい行為を規制対象に追加し、ストーカー被害者の保護を強化する改正法。",
    summaryEn: "An amendment adding GPS-device abuse and SNS harassment to regulated behavior and strengthening protection of stalking victims.",
    detail: "ストーカー行為等の規制等に関する法律を改正。GPS機器やAirTag等の位置情報端末を悪用したつきまとい行為を新たに規制対象に追加。SNS上でのしつこいメッセージ送信や、被害者の個人情報の拡散も「つきまとい等」に含める。禁止命令の迅速化、被害者の転居費用支援制度の創設も盛り込む。",
    detailEn: "An amendment to the Anti-Stalking Act. It newly covers stalking using GPS devices and location trackers such as AirTag. Persistent messaging on SNS and the dissemination of victims' personal information are also included under regulated 'stalking-type' behavior. The amendment also speeds up issuance of restraining orders and creates a relocation-cost support system for victims.",
    keyPoints: [
      "GPS機器悪用によるつきまとい行為の規制",
      "SNS上のしつこいメッセージ送信の規制追加",
      "被害者の個人情報拡散の処罰規定",
      "禁止命令の迅速化",
      "被害者の転居費用支援制度の創設",
    ],
    keyPointsEn: [
      "Regulation of stalking via GPS-device abuse",
      "Persistent SNS messaging added as regulated behavior",
      "Penalties for dissemination of victims' personal information",
      "Faster issuance of restraining orders",
      "New relocation-cost support system for victims",
    ],
    voteResult: { for: 441, against: 0 },
    parties: [
      { name: "自由民主党", nameEn: "Liberal Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "公明党", nameEn: "Komeito", vote: "賛成", voteEn: "For" },
      { name: "立憲民主党", nameEn: "Constitutional Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "日本維新の会", nameEn: "Nippon Ishin no Kai", vote: "賛成", voteEn: "For" },
      { name: "国民民主党", nameEn: "Democratic Party for the People", vote: "賛成", voteEn: "For" },
      { name: "日本共産党", nameEn: "Japanese Communist Party", vote: "賛成", voteEn: "For" },
    ],
    timeline: [
      { date: "2025-10-24", event: "第219回臨時国会召集・法案提出", eventEn: "219th extraordinary Diet session convened; bill submitted" },
      { date: "2025-12-10", event: "参議院本会議で全会一致で可決・成立", eventEn: "Passed unanimously and enacted by the House of Councillors plenary" },
      { date: "2026-04-01", event: "施行", eventEn: "Enters into force" },
    ],
    impact: "デジタル技術を悪用した新手のストーカー行為への対応が強化。被害者保護が拡充。",
    impactEn: "Strengthens responses to new forms of stalking using digital technology and expands victim protection.",
  },
  {
    slug: "dv-prevention-reform",
    title: "改正DV防止法",
    titleEn: "Revised Domestic Violence Prevention Act",
    committee: "内閣委員会",
    committeeEn: "Cabinet Committee",
    enactedDate: "2025-12-10",
    effectiveDate: "2026-04-01",
    summary: "精神的暴力やデジタル暴力をDVの定義に追加し、保護命令の対象を拡大する改正法。",
    summaryEn: "An amendment adding psychological and digital violence to the definition of DV and expanding the scope of protection orders.",
    detail: "配偶者からの暴力の防止及び被害者の保護等に関する法律の改正。DVの定義を拡大し、精神的暴力（モラルハラスメント）、経済的暴力（生活費の不当な制限）、デジタル暴力（SNS監視・GPS追跡）を追加。保護命令の対象を事実婚・元交際相手にも拡大。被害者の自立支援措置の強化も含む。",
    detailEn: "An amendment to the Act on the Prevention of Spousal Violence and the Protection of Victims. It broadens the definition of DV to include psychological abuse (moral harassment), economic abuse (unreasonable restriction of living expenses), and digital abuse (monitoring via SNS and GPS tracking). Protection orders are extended to common-law spouses and former partners, and victim self-reliance support measures are strengthened.",
    keyPoints: [
      "DVの定義拡大（精神的・経済的・デジタル暴力）",
      "保護命令の対象を事実婚・元交際相手に拡大",
      "接近禁止命令の期間延長（6ヶ月→1年）",
      "被害者の自立支援措置の強化",
    ],
    keyPointsEn: [
      "Expanded DV definition (psychological, economic, and digital abuse)",
      "Protection orders extended to common-law spouses and former partners",
      "Longer duration for no-contact orders (from 6 months to 1 year)",
      "Strengthened victim self-reliance support",
    ],
    voteResult: { for: 438, against: 3 },
    parties: [
      { name: "自由民主党", nameEn: "Liberal Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "公明党", nameEn: "Komeito", vote: "賛成", voteEn: "For" },
      { name: "立憲民主党", nameEn: "Constitutional Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "日本維新の会", nameEn: "Nippon Ishin no Kai", vote: "賛成", voteEn: "For" },
      { name: "国民民主党", nameEn: "Democratic Party for the People", vote: "賛成", voteEn: "For" },
      { name: "日本共産党", nameEn: "Japanese Communist Party", vote: "賛成", voteEn: "For" },
    ],
    timeline: [
      { date: "2025-10-24", event: "法案を国会提出", eventEn: "Bill submitted to the Diet" },
      { date: "2025-12-10", event: "参議院本会議で可決・成立", eventEn: "Passed and enacted by the House of Councillors plenary" },
      { date: "2026-04-01", event: "施行", eventEn: "Enters into force" },
    ],
    impact: "DV被害者の保護範囲が拡大。精神的暴力やデジタル暴力にも法的に対応可能に。",
    impactEn: "Expands the scope of protection for DV victims, allowing legal responses to psychological and digital abuse.",
  },
  {
    slug: "gasoline-tax-reform",
    title: "ガソリン暫定税率廃止法",
    titleEn: "Gasoline Provisional Tax Abolition Act",
    committee: "財務金融委員会",
    committeeEn: "Committee on Financial Affairs",
    enactedDate: "2025-12-15",
    effectiveDate: "2026-04-01",
    summary: "約50年間続いたガソリンの暫定税率（リッター約25円）を廃止する法律。",
    summaryEn: "A law abolishing the gasoline provisional tax (about 25 yen per liter) that had been in place for roughly 50 years.",
    detail: "議員立法として成立。1974年から暫定措置として課されてきたガソリン税の暫定税率（リッター約25.1円）を2026年4月から廃止。ガソリン価格の大幅な引き下げが実現。国民民主党が2024年の衆院選から一貫して主張していた政策で、与野党協議を経て実現。道路特定財源の代替として一般財源からの手当てを規定。",
    detailEn: "Enacted as a Member Bill. It abolishes, from April 2026, the gasoline provisional tax rate (about 25.1 yen per liter) that had been levied as a temporary measure since 1974, realizing a significant drop in gasoline prices. The policy had been championed by the Democratic Party for the People since the 2024 general election, and was realized after negotiations between ruling and opposition parties. The law provides for general-revenue replacement of the former road-specific funding.",
    keyPoints: [
      "ガソリン暫定税率（約25.1円/L）の廃止",
      "軽油引取税の暫定税率も同時廃止",
      "2026年4月1日から適用",
      "道路財源の代替措置の規定",
    ],
    keyPointsEn: [
      "Abolition of the gasoline provisional tax (about 25.1 yen/L)",
      "Simultaneous abolition of the diesel delivery tax provisional rate",
      "Applies from April 1, 2026",
      "Provisions for replacement of road-funding revenue",
    ],
    voteResult: { for: 380, against: 61 },
    parties: [
      { name: "自由民主党", nameEn: "Liberal Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "公明党", nameEn: "Komeito", vote: "賛成", voteEn: "For" },
      { name: "日本維新の会", nameEn: "Nippon Ishin no Kai", vote: "賛成", voteEn: "For" },
      { name: "国民民主党", nameEn: "Democratic Party for the People", vote: "賛成", voteEn: "For" },
      { name: "立憲民主党", nameEn: "Constitutional Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "日本共産党", nameEn: "Japanese Communist Party", vote: "反対", voteEn: "Against" },
    ],
    timeline: [
      { date: "2025-10-30", event: "国民民主党が議員立法として法案提出", eventEn: "Democratic Party for the People submits the bill as a Member Bill" },
      { date: "2025-11-20", event: "与党が修正案に合意", eventEn: "Ruling parties agree on a revised draft" },
      { date: "2025-12-15", event: "参議院本会議で可決・成立", eventEn: "Passed and enacted by the House of Councillors plenary" },
      { date: "2026-04-01", event: "施行", eventEn: "Enters into force" },
    ],
    impact: "ガソリン価格がリッターあたり約25円下がり、全ドライバー・物流業者の負担が軽減。",
    impactEn: "Gasoline prices fall by about 25 yen per liter, easing costs for all drivers and logistics operators.",
  },
  {
    slug: "probation-officer-reform",
    title: "改正保護司法",
    titleEn: "Revised Volunteer Probation Officer Act",
    committee: "法務委員会",
    committeeEn: "Judicial Affairs Committee",
    enactedDate: "2025-12-10",
    effectiveDate: "2026-04-01",
    summary: "保護司の担い手不足に対応するため、保護司の処遇改善と活動環境の整備を図る改正法。",
    summaryEn: "An amendment improving compensation and working conditions for volunteer probation officers in response to shortages of candidates.",
    detail: "更生保護制度の充実を図るための保護司法等の改正。高齢化・成り手不足が深刻化する保護司について、実費弁償の引き上げ、活動保険の拡充、研修制度の充実を盛り込む。保護観察所と保護司の連携強化、再犯防止のための支援体制の整備も含む。",
    detailEn: "An amendment to the Volunteer Probation Officer Act and related laws to strengthen the rehabilitation support system. Facing aging and growing shortages of probation officers, it raises reimbursement for expenses, expands activity insurance, and improves training. It also strengthens cooperation between probation offices and probation officers and builds up support systems to prevent reoffending.",
    keyPoints: [
      "保護司の実費弁償の引き上げ",
      "活動保険の拡充",
      "研修制度の充実",
      "保護観察所との連携強化",
    ],
    keyPointsEn: [
      "Higher reimbursement for probation officers' expenses",
      "Expanded activity insurance",
      "Improved training programs",
      "Strengthened cooperation with probation offices",
    ],
    voteResult: { for: 441, against: 0 },
    parties: [
      { name: "自由民主党", nameEn: "Liberal Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "公明党", nameEn: "Komeito", vote: "賛成", voteEn: "For" },
      { name: "立憲民主党", nameEn: "Constitutional Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "日本維新の会", nameEn: "Nippon Ishin no Kai", vote: "賛成", voteEn: "For" },
      { name: "国民民主党", nameEn: "Democratic Party for the People", vote: "賛成", voteEn: "For" },
      { name: "日本共産党", nameEn: "Japanese Communist Party", vote: "賛成", voteEn: "For" },
    ],
    timeline: [
      { date: "2025-10-24", event: "法案を国会提出", eventEn: "Bill submitted to the Diet" },
      { date: "2025-12-10", event: "全会一致で成立", eventEn: "Passed unanimously" },
      { date: "2026-04-01", event: "施行", eventEn: "Enters into force" },
    ],
    impact: "全国約4.7万人の保護司の活動環境が改善。更生保護制度の持続可能性が向上。",
    impactEn: "Improves working conditions for roughly 47,000 probation officers nationwide, enhancing the sustainability of the rehabilitation system.",
  },
  {
    slug: "higher-brain-dysfunction-support",
    title: "高次脳機能障害者支援法",
    titleEn: "Higher Brain Dysfunction Support Act",
    committee: "厚生労働委員会",
    committeeEn: "Health, Labour and Welfare Committee",
    enactedDate: "2025-12-15",
    effectiveDate: "2026-04-01",
    summary: "交通事故や脳卒中等による高次脳機能障害者への支援を体系的に整備する新法。",
    summaryEn: "A new law providing a systematic framework of support for people with higher brain dysfunction caused by traffic accidents, strokes, and similar events.",
    detail: "議員立法として成立。高次脳機能障害（記憶障害・注意障害・遂行機能障害等）を持つ方への支援を体系的に整備する新法。都道府県に支援拠点の設置を義務付け、リハビリテーション体制の整備、就労支援、家族支援を規定。全国に約50万人いるとされる高次脳機能障害者への対応を強化。",
    detailEn: "Passed as a Member Bill. A new law establishing a systematic support framework for people with higher brain dysfunction (memory impairment, attention deficits, executive function disorders, and the like). It requires prefectures to set up support bases, strengthens rehabilitation systems, and provides for employment and family support. It reinforces responses for an estimated 500,000 people nationwide with higher brain dysfunction.",
    keyPoints: [
      "都道府県に支援拠点の設置義務化",
      "リハビリテーション体制の整備",
      "就労支援の充実",
      "家族支援の規定",
    ],
    keyPointsEn: [
      "Mandatory establishment of support bases in prefectures",
      "Development of rehabilitation systems",
      "Enhanced employment support",
      "Provisions for family support",
    ],
    voteResult: { for: 441, against: 0 },
    parties: [
      { name: "自由民主党", nameEn: "Liberal Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "公明党", nameEn: "Komeito", vote: "賛成", voteEn: "For" },
      { name: "立憲民主党", nameEn: "Constitutional Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "日本維新の会", nameEn: "Nippon Ishin no Kai", vote: "賛成", voteEn: "For" },
      { name: "国民民主党", nameEn: "Democratic Party for the People", vote: "賛成", voteEn: "For" },
      { name: "日本共産党", nameEn: "Japanese Communist Party", vote: "賛成", voteEn: "For" },
    ],
    timeline: [
      { date: "2025-11-10", event: "超党派で法案提出", eventEn: "Bill submitted on a cross-party basis" },
      { date: "2025-12-15", event: "全会一致で成立", eventEn: "Passed unanimously" },
      { date: "2026-04-01", event: "施行", eventEn: "Enters into force" },
    ],
    impact: "約50万人の高次脳機能障害者とその家族への支援が法的に体系化。",
    impactEn: "Legally systematizes support for roughly 500,000 people with higher brain dysfunction and their families.",
  },
  {
    slug: "medical-law-reform",
    title: "改正医療法等",
    titleEn: "Revised Medical Care Act",
    committee: "厚生労働委員会",
    committeeEn: "Health, Labour and Welfare Committee",
    enactedDate: "2025-12-10",
    effectiveDate: "2026-04-01",
    summary: "かかりつけ医機能の制度化と地域医療構想の推進を盛り込んだ医療提供体制改革法。",
    summaryEn: "A medical care reform law institutionalizing the 'family doctor' function and advancing the Regional Medical Plan framework.",
    detail: "第217回国会で継続審議となり第219回国会で成立。かかりつけ医機能に関する情報提供制度の創設、地域医療構想の実現に向けた都道府県の権限強化、医師の偏在対策を盛り込む。2024年度から始まった医師の働き方改革とも連動した制度整備。",
    detailEn: "After being carried over from the 217th Diet session, the bill passed in the 219th Diet session. It establishes an information-disclosure system for the 'family doctor' (kakaritsuke-i) function, strengthens prefectural authority to realize Regional Medical Plans, and includes measures addressing the geographic maldistribution of physicians. It is aligned with the physician work-style reform that began in FY2024.",
    keyPoints: [
      "かかりつけ医機能の情報提供制度の創設",
      "地域医療構想の実現に向けた都道府県の権限強化",
      "医師偏在対策の推進",
      "医師の働き方改革との連動",
    ],
    keyPointsEn: [
      "New information-disclosure system for the family doctor function",
      "Strengthened prefectural authority to realize Regional Medical Plans",
      "Measures to address physician maldistribution",
      "Alignment with physician work-style reform",
    ],
    voteResult: { for: 385, against: 56 },
    parties: [
      { name: "自由民主党", nameEn: "Liberal Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "公明党", nameEn: "Komeito", vote: "賛成", voteEn: "For" },
      { name: "日本維新の会", nameEn: "Nippon Ishin no Kai", vote: "賛成", voteEn: "For" },
      { name: "立憲民主党", nameEn: "Constitutional Democratic Party", vote: "賛成", voteEn: "For" },
      { name: "国民民主党", nameEn: "Democratic Party for the People", vote: "反対", voteEn: "Against" },
      { name: "日本共産党", nameEn: "Japanese Communist Party", vote: "反対", voteEn: "Against" },
    ],
    timeline: [
      { date: "2025-03-07", event: "第217回国会に法案提出", eventEn: "Bill submitted to the 217th Diet Session" },
      { date: "2025-06-22", event: "第217回国会閉会（継続審議）", eventEn: "217th Diet Session closes (continuing deliberation)" },
      { date: "2025-12-10", event: "第219回臨時国会で成立", eventEn: "Enacted in the 219th extraordinary Diet session" },
      { date: "2026-04-01", event: "施行", eventEn: "Enters into force" },
    ],
    impact: "地域医療の再編が加速。かかりつけ医機能の制度化で患者の医療アクセスが改善。",
    impactEn: "Accelerates restructuring of regional healthcare and improves patient access through the new family-doctor framework.",
  },
];
