import type { Competitor } from "./competitors";

export const entertainmentCompanies: Competitor[] = [
  {
    slug: "sony",
    name: "ソニーグループ",
    nameEn: "Sony Group",
    logo: "S",
    color: "#3b82f6",
    stockCode: "6758",
    overview:
      "ゲーム（PlayStation）、音楽、映画、半導体（CMOSイメージセンサー）、エレクトロニクスを擁する世界的エンタテインメント・テクノロジー企業。2025年3月期は金融除きベースで売上高・営業利益・純利益がいずれも過去最高を更新。KADOKAWAへの出資でIP戦略を加速。2025年10月に金融事業をスピンオフ予定。",
    financials: {
      revenue: "12兆9,571億円",
      revenueYoy: "-0.3%",
      operatingProfit: "1兆4,072億円",
      opMargin: "10.9%",
      fiscalYear: "2025年3月期",
    },
    pl: {
      revenue: "12兆9,571億円",
      cogs: "9兆2,000億円",
      grossProfit: "3兆7,571億円",
      grossMargin: "29.0%",
      sga: "1兆8,500億円",
      rd: "6,800億円",
      operatingProfit: "1兆4,072億円",
      opMargin: "10.9%",
      netIncome: "1兆1,416億円",
      netMargin: "8.8%",
      fiscalYear: "2025年3月期",
    },
    bs: {
      totalAssets: "35兆2,000億円",
      currentAssets: "12兆5,000億円",
      cash: "1兆9,500億円",
      fixedAssets: "22兆7,000億円",
      totalLiab: "27兆8,000億円",
      currentLiab: "10兆2,000億円",
      fixedLiab: "17兆6,000億円",
      interestBearingDebt: "5兆2,000億円",
      equity: "7兆4,000億円",
      equityRatio: "21.0%",
      fiscalYear: "2025年3月期",
    },
    cf: {
      operatingCF: "+1兆6,800億円",
      investingCF: "-1兆2,200億円",
      financingCF: "-3,500億円",
      freeCF: "+4,600億円",
      capex: "5,200億円",
      dividends: "1,200億円",
      fiscalYear: "2025年3月期",
    },
    strategy: {
      title: "成長戦略",
      summary:
        "金融事業のスピンオフにより「エンタテインメント×テクノロジー」企業へ再定義。技術IPとコンテンツIPの融合を軸に、ゲーム・音楽・映画・アニメのクロスメディア展開を推進。KADOKAWA出資やCrunchyrollでアニメIP基盤を強化。",
      keyPoints: [
        "金融スピンオフでエンタメ・テクノロジー純化",
        "CMOSイメージセンサーのシェア拡大",
        "KADOKAWA出資によるアニメ・出版IP取り込み",
        "AFEELA（EV）でモビリティ参入",
      ],
      target: "第五次中計：連結営業利益CAGR10%以上、営業利益率10%以上",
    },
    strengths: [
      "ゲーム・音楽・映画・半導体の多角的エンタメポートフォリオ",
      "CMOSイメージセンサーで世界シェア約50%",
      "PlayStation Network（PSN）の月間アクティブユーザー1.2億人超",
      "Crunchyroll・Aniplexによるアニメ領域の垂直統合",
    ],
    challenges: [
      "金融スピンオフ後の自己資本比率低下リスク",
      "米国関税の影響（2025年度1,000億円規模）",
      "ゲーム事業のサイクル依存（PS5ライフサイクル後期）",
      "EV（AFEELA）事業の収益化までの投資負担",
    ],
    latestNews: [
      { date: "2025-05-14", headline: "2025年3月期決算発表、金融除き売上・利益とも過去最高を更新" },
      { date: "2024-12-19", headline: "KADOKAWAと資本業務提携、約500億円出資で筆頭株主に" },
      { date: "2025-05-15", headline: "2025年度の米国関税影響は1,000億円に抑制と発表" },
      { date: "2025-01-07", headline: "CES 2025でAFEELA 1を正式発表、価格89,900ドルから" },
    ],
  },
  {
    slug: "nintendo",
    name: "任天堂",
    nameEn: "Nintendo",
    logo: "任",
    color: "#ef4444",
    stockCode: "7974",
    overview:
      "家庭用ゲーム機・ソフトの世界的メーカー。マリオ・ゼルダ・ポケモンなど強力なIPを保有。2025年3月期はSwitchのライフサイクル後期で前年の大型タイトル反動減により大幅減収減益。2025年6月にNintendo Switch 2を発売し次世代への移行を開始。",
    financials: {
      revenue: "1兆1,649億円",
      revenueYoy: "-30.3%",
      operatingProfit: "2,825億円",
      opMargin: "24.2%",
      fiscalYear: "2025年3月期",
    },
    pl: {
      revenue: "1兆1,649億円",
      cogs: "5,800億円",
      grossProfit: "5,849億円",
      grossMargin: "50.2%",
      sga: "3,024億円",
      rd: "1,200億円",
      operatingProfit: "2,825億円",
      opMargin: "24.2%",
      netIncome: "2,788億円",
      netMargin: "23.9%",
      fiscalYear: "2025年3月期",
    },
    bs: {
      totalAssets: "3兆3,985億円",
      currentAssets: "2兆8,500億円",
      cash: "1兆4,141億円",
      fixedAssets: "5,485億円",
      totalLiab: "6,730億円",
      currentLiab: "5,800億円",
      fixedLiab: "930億円",
      interestBearingDebt: "0円",
      equity: "2兆7,254億円",
      equityRatio: "80.2%",
      fiscalYear: "2025年3月期",
    },
    cf: {
      operatingCF: "+3,200億円",
      investingCF: "+2,800億円",
      financingCF: "-1,600億円",
      freeCF: "+6,000億円",
      capex: "800億円",
      dividends: "1,500億円",
      fiscalYear: "2025年3月期",
    },
    strategy: {
      title: "成長戦略",
      summary:
        "Nintendo Switch 2を2025年6月に発売し次世代プラットフォームへ移行。ハード・ソフト一体型の独自路線を堅持しつつ、映画・テーマパーク（USJ）などIP展開を多角化。Switch 2では後方互換性を確保しユーザー基盤を継承。",
      keyPoints: [
        "Nintendo Switch 2（2025年6月発売、初年度1,500万台目標）",
        "マリオ映画第2弾など映像IP展開",
        "USJスーパーニンテンドーワールド拡張",
        "ニンテンドーアカウントによるエコシステム強化",
      ],
      target: "2026年3月期 売上高1兆9,000億円（+63%）、営業利益3,200億円（+13%）",
    },
    strengths: [
      "マリオ・ゼルダ・ポケモンなど世界的IPの保有",
      "無借金経営・自己資本比率80%超の盤石な財務基盤",
      "ハード・ソフト一体開発による高い利益率",
      "映画・テーマパークなど非ゲームIP収益の拡大",
    ],
    challenges: [
      "Switch 2の立ち上げリスク（普及速度・価格設定）",
      "Switch世代末期による業績谷間（前年比大幅減収減益）",
      "メモリ高騰による製造コスト増（BOMの21-23%）",
      "年末商戦の減速と生産台数引き下げリスク",
    ],
    latestNews: [
      { date: "2025-06-05", headline: "Nintendo Switch 2が発売開始" },
      { date: "2025-05-08", headline: "2025年3月期決算発表、Switch 2初年度1,500万台販売を計画" },
      { date: "2025-04-02", headline: "Nintendo Switch 2の発売日を2025年6月5日と正式発表" },
      { date: "2026-03-24", headline: "Switch 2生産台数を一部引き下げとの報道" },
    ],
  },
  {
    slug: "bandai-namco",
    name: "バンダイナムコHD",
    nameEn: "Bandai Namco Holdings",
    logo: "B",
    color: "#f59e0b",
    stockCode: "7832",
    overview:
      "ガンダム・ドラゴンボール・ワンピースなど強力IPを軸に、玩具・ゲーム・映像・アミューズメントを展開するIP総合企業。2025年3月期は『エルデンリング』DLC、『学園アイドルマスター』、『ドラゴンボール Sparking! ZERO』のヒットで売上・利益とも過去最高を更新。全事業セグメントが増収増益。",
    financials: {
      revenue: "1兆2,415億円",
      revenueYoy: "+18.2%",
      operatingProfit: "1,802億円",
      opMargin: "14.5%",
      fiscalYear: "2025年3月期",
    },
    pl: {
      revenue: "1兆2,415億円",
      cogs: "7,200億円",
      grossProfit: "5,215億円",
      grossMargin: "42.0%",
      sga: "3,413億円",
      rd: "800億円",
      operatingProfit: "1,802億円",
      opMargin: "14.5%",
      netIncome: "1,293億円",
      netMargin: "10.4%",
      fiscalYear: "2025年3月期",
    },
    bs: {
      totalAssets: "1兆3,500億円",
      currentAssets: "7,800億円",
      cash: "3,800億円",
      fixedAssets: "5,700億円",
      totalLiab: "3,800億円",
      currentLiab: "3,200億円",
      fixedLiab: "600億円",
      interestBearingDebt: "200億円",
      equity: "9,700億円",
      equityRatio: "71.9%",
      fiscalYear: "2025年3月期",
    },
    cf: {
      operatingCF: "+2,100億円",
      investingCF: "-620億円",
      financingCF: "-773億円",
      freeCF: "+1,480億円",
      capex: "424億円",
      dividends: "399億円",
      fiscalYear: "2025年3月期",
    },
    strategy: {
      title: "成長戦略",
      summary:
        "IP軸戦略を核に、ガンダム・ドラゴンボール・ワンピースなど主力IPのグローバル展開を強化。トイホビー・デジタル・映像・アミューズメントのクロスメディア展開で各IPの収益最大化を図る。ガンダムカードゲームの立ち上げやガンプラのグローバル需要拡大が新たな成長ドライバー。",
      keyPoints: [
        "IP軸戦略によるクロスメディア展開強化",
        "ガンダムIP年間売上1,200億円超の拡大",
        "デジタル事業の利益率改善（ヒットタイトル連発）",
        "海外売上比率の向上（特に北米・アジア）",
      ],
      target: "2026年3月期 売上高1兆2,000億円、営業利益1,450億円（保守的予想）",
    },
    strengths: [
      "ガンダム・ドラゴンボール・ワンピースなどIP資産の厚み",
      "トイホビー×デジタル×映像のクロスメディア展開力",
      "ガンプラの世界的ブランド力と高い利益率",
      "『エルデンリング』によるグローバルゲーム市場での存在感向上",
    ],
    challenges: [
      "大型タイトル依存（翌年の反動減リスク）",
      "ゲーム開発費の高騰と開発期間の長期化",
      "アミューズメント事業の国内市場縮小",
      "IP使用権のライセンス交渉リスク（集英社等との関係）",
    ],
    latestNews: [
      { date: "2025-05-08", headline: "2025年3月期決算、売上・利益とも過去最高を更新。全事業増収増益" },
      { date: "2025-05-08", headline: "ゲーム事業セグメント利益が前年比995%増と大幅回復" },
      { date: "2025-11-06", headline: "2026年3月期Q2決算、ガンダムIP売上が上半期1,272億円を達成" },
      { date: "2025-02-05", headline: "Q3累計で営業利益1,792億円、通期予想を上方修正" },
    ],
  },
  {
    slug: "square-enix",
    name: "スクウェア・エニックスHD",
    nameEn: "Square Enix Holdings",
    logo: "S",
    color: "#8b5cf6",
    stockCode: "9684",
    overview:
      "『ファイナルファンタジー』『ドラゴンクエスト』を擁するゲーム大手。2025年3月期は売上高が減少も「量から質」への構造改革が奏功し営業利益は24.6%増。海外パブリッシング組織の再編やスマホ・ブラウザゲームの整理を進め、中期経営計画で「再起動の3年間」を推進中。",
    financials: {
      revenue: "3,245億円",
      revenueYoy: "-8.9%",
      operatingProfit: "406億円",
      opMargin: "12.5%",
      fiscalYear: "2025年3月期",
    },
    pl: {
      revenue: "3,245億円",
      cogs: "1,950億円",
      grossProfit: "1,295億円",
      grossMargin: "39.9%",
      sga: "889億円",
      rd: "450億円",
      operatingProfit: "406億円",
      opMargin: "12.5%",
      netIncome: "244億円",
      netMargin: "7.5%",
      fiscalYear: "2025年3月期",
    },
    bs: {
      totalAssets: "4,162億円",
      currentAssets: "2,900億円",
      cash: "2,436億円",
      fixedAssets: "1,262億円",
      totalLiab: "798億円",
      currentLiab: "650億円",
      fixedLiab: "148億円",
      interestBearingDebt: "0円",
      equity: "3,364億円",
      equityRatio: "80.7%",
      fiscalYear: "2025年3月期",
    },
    cf: {
      operatingCF: "+520億円",
      investingCF: "-180億円",
      financingCF: "-250億円",
      freeCF: "+340億円",
      capex: "150億円",
      dividends: "180億円",
      fiscalYear: "2025年3月期",
    },
    strategy: {
      title: "成長戦略",
      summary:
        "中期経営計画で「再起動の3年間」を掲げ、「量から質」への転換を推進。主要IPであるFF・ドラクエを中心に大型タイトルの安定的投入を目指し、海外パブリッシング体制を抜本的に再編。開発拠点を日本に集約し、不採算事業の整理を進める。",
      keyPoints: [
        "「量から質」への開発方針転換",
        "海外パブリッシング組織の構造改革（2026年3月期に118億円再編費用）",
        "FF・ドラクエなど主力IPの安定的大型タイトル投入",
        "不採算スマホ・ブラウザゲームの整理",
      ],
      target: "中計期間（2025-2027年3月期）を「再起動の3年間」と位置づけ収益体質を改善",
    },
    strengths: [
      "FF・ドラクエなどグローバルで認知される大型IPの保有",
      "無借金経営・自己資本比率80%超の安定した財務基盤",
      "MMORPG『FF14』の長期安定収益",
      "『ドラクエ3 HD-2D リメイク』の好調な販売",
    ],
    challenges: [
      "HDゲーム部門の営業利益率が競合比で低水準",
      "スマホ・ブラウザゲームの縮小傾向",
      "大型タイトルの開発期間長期化と投資回収リスク",
      "海外スタジオ閉鎖に伴う組織再編コスト",
    ],
    latestNews: [
      { date: "2025-05-14", headline: "2025年3月期決算発表、営業利益24.6%増で構造改革の効果が顕在化" },
      { date: "2025-05-14", headline: "中期経営計画の進捗報告、海外パブリッシング再編に118億円計上" },
      { date: "2025-11-06", headline: "中間期決算、『ドラクエ3 HD-2Dリメイク』が想定以上の販売" },
      { date: "2025-02-04", headline: "Q3決算発表、FF14が安定収益を維持" },
    ],
  },
  {
    slug: "toei",
    name: "東映",
    nameEn: "Toei Company",
    logo: "映",
    color: "#10b981",
    stockCode: "9605",
    overview:
      "映画・テレビ番組の制作・配給を手がける総合映像企業。仮面ライダー・スーパー戦隊・プリキュアなどの特撮・アニメIPを保有。子会社の東映アニメーションがワンピース・ドラゴンボール等のアニメ制作で高収益。2025年3月期はアニメのマルチユース展開が好調で増収増益。中長期ビジョン「TOEI NEW WAVE 2033」を策定。",
    financials: {
      revenue: "1,799億円",
      revenueYoy: "+5.0%",
      operatingProfit: "351億円",
      opMargin: "19.5%",
      fiscalYear: "2025年3月期",
    },
    pl: {
      revenue: "1,799億円",
      cogs: "1,150億円",
      grossProfit: "649億円",
      grossMargin: "36.1%",
      sga: "298億円",
      rd: "—",
      operatingProfit: "351億円",
      opMargin: "19.5%",
      netIncome: "157億円",
      netMargin: "8.7%",
      fiscalYear: "2025年3月期",
    },
    bs: {
      totalAssets: "4,812億円",
      currentAssets: "2,400億円",
      cash: "1,200億円",
      fixedAssets: "2,412億円",
      totalLiab: "1,102億円",
      currentLiab: "700億円",
      fixedLiab: "402億円",
      interestBearingDebt: "150億円",
      equity: "3,710億円",
      equityRatio: "58.9%",
      fiscalYear: "2025年3月期",
    },
    cf: {
      operatingCF: "+145億円",
      investingCF: "-80億円",
      financingCF: "-50億円",
      freeCF: "+65億円",
      capex: "60億円",
      dividends: "40億円",
      fiscalYear: "2025年3月期",
    },
    strategy: {
      title: "成長戦略",
      summary:
        "中長期ビジョン「TOEI NEW WAVE 2033」を掲げ、実写・アニメ映像事業のグローバル展開を加速。2025年4月にIP・アニメ開発部を新設し組織体制を強化。東映アニメーションのIP企業への転換を推進し、版権ビジネスの拡大を図る。",
      keyPoints: [
        "「TOEI NEW WAVE 2033」中長期ビジョンの推進",
        "IP・アニメ開発部の新設による体制強化",
        "東映アニメーションのIP企業化（版権収益拡大）",
        "国際事業部門新設によるグローバル展開加速",
      ],
      target: "2033年に向けグローバルコンテンツ創造発信基盤を確立",
    },
    strengths: [
      "仮面ライダー・スーパー戦隊・プリキュアなど長寿特撮・アニメIP",
      "東映アニメーション（ワンピース・ドラゴンボール制作）の高収益",
      "映画館（T・ジョイ）からコンテンツ制作・配給までの垂直統合",
      "不動産事業（東映太秦映画村等）による安定収益基盤",
    ],
    challenges: [
      "実写映画の興行収入の不安定さ（ヒット依存）",
      "テレビ放映権料の構造的な低迷",
      "グローバル市場での競争激化（Netflix等OTTとの競争）",
      "特撮IP（仮面ライダー等）の少子化による国内市場縮小",
    ],
    latestNews: [
      { date: "2025-05-14", headline: "2025年3月期決算、営業利益19.8%増の351億円。アニメマルチユースが好調" },
      { date: "2025-04-01", headline: "IP・アニメ開発部を新設、国際事業部門も設置" },
      { date: "2025-05-16", headline: "東映アニメーション決算、売上1,008億円・営業利益324億円で過去最高" },
      { date: "2025-08-08", headline: "2026年3月期Q1決算説明資料を開示" },
    ],
  },
];
