import type { Competitor } from "./competitors";

export const entertainmentCompanies: Competitor[] = [
  {
    slug: "sony",
    name: "ソニーグループ",
    nameEn: "Sony Group",
    logo: "S",
    color: "#3b82f6",
    stockCode: "6758",
    overview:
      "ゲーム（PlayStation）、音楽、映画、半導体（CMOSイメージセンサー）、エレクトロニクスを擁する世界的エンタテインメント・テクノロジー企業。2025年10月に金融事業（ソニーフィナンシャルグループ）をスピンオフ上場済み。2026年3月期は半導体イメージセンサーの好調で3度の上方修正を実施し、営業利益は前期比20%超の増益見通し。",
    financials: {
      revenue: "12兆3,000億円（予想）",
      revenueYoy: "+2.2%",
      operatingProfit: "1兆5,400億円（予想）",
      opMargin: "12.5%",
      fiscalYear: "2026年3月期（通期予想）",
    },
    pl: {
      revenue: "12兆3,000億円（予想）",
      cogs: "8兆5,000億円",
      grossProfit: "3兆8,000億円",
      grossMargin: "30.9%",
      sga: "1兆7,000億円",
      rd: "6,600億円",
      operatingProfit: "1兆5,400億円（予想）",
      opMargin: "12.5%",
      netIncome: "1兆1,300億円（予想）",
      netMargin: "9.2%",
      fiscalYear: "2026年3月期（通期予想）",
    },
    bs: {
      totalAssets: "30兆5,000億円",
      currentAssets: "11兆2,000億円",
      cash: "2兆865億円",
      fixedAssets: "19兆3,000億円",
      totalLiab: "22兆5,000億円",
      currentLiab: "8兆8,000億円",
      fixedLiab: "13兆7,000億円",
      interestBearingDebt: "4兆5,000億円",
      equity: "8兆0,000億円",
      equityRatio: "26.2%",
      fiscalYear: "2026年3月期Q3時点",
    },
    cf: {
      operatingCF: "+1兆3,532億円",
      investingCF: "-1兆6,977億円",
      financingCF: "-6,099億円",
      freeCF: "-3,445億円",
      capex: "5,500億円",
      dividends: "1,300億円",
      fiscalYear: "2026年3月期Q3累計",
    },
    strategy: {
      title: "成長戦略",
      summary:
        "金融事業のスピンオフにより「エンタテインメント×テクノロジー」企業へ再定義。技術IPとコンテンツIPの融合を軸に、ゲーム・音楽・映画・アニメのクロスメディア展開を推進。KADOKAWA出資やCrunchyrollでアニメIP基盤を強化。",
      keyPoints: [
        "金融スピンオフでエンタメ・テクノロジー純化",
        "CMOSイメージセンサーのシェア拡大",
        "KADOKAWA出資によるアニメ・出版IP取り込み",
        "AFEELA（EV）でモビリティ参入",
      ],
      target: "第五次中計：連結営業利益CAGR10%以上、営業利益率10%以上",
    },
    strengths: [
      "ゲーム・音楽・映画・半導体の多角的エンタメポートフォリオ",
      "CMOSイメージセンサーで世界シェア約50%",
      "PlayStation Network（PSN）の月間アクティブユーザー1.2億人超",
      "Crunchyroll・Aniplexによるアニメ領域の垂直統合",
    ],
    challenges: [
      "金融スピンオフ完了後の連結総資産縮小と投資CF負担",
      "米国関税の影響（2025年度1,000億円規模）",
      "ゲーム事業のサイクル依存（PS5ライフサイクル後期）",
      "EV（AFEELA）事業の収益化までの投資負担",
    ],
    latestNews: [
      { date: "2026-02-05", headline: "2026年3月期Q3決算発表、営業利益21%増の1兆2,839億円。通期予想を3度目の上方修正（営業利益1兆5,400億円）" },
      { date: "2025-11-11", headline: "Q2決算で通期純利益予想を8%上方修正、鬼滅の刃など好調" },
      { date: "2025-10-01", headline: "金融事業（ソニーフィナンシャルグループ）のスピンオフ上場を実施" },
      { date: "2025-05-14", headline: "2025年3月期決算発表、金融除き売上・利益とも過去最高を更新" },
    ],
  },
  {
    slug: "nintendo",
    name: "任天堂",
    nameEn: "Nintendo",
    logo: "任",
    color: "#ef4444",
    stockCode: "7974",
    overview:
      "家庭用ゲーム機・ソフトの世界的メーカー。マリオ・ゼルダ・ポケモンなど強力なIPを保有。2025年6月にNintendo Switch 2を発売し、12月末時点で累計1,737万台を販売（過去最速ペース）。2026年3月期はSwitch 2効果で売上高が前期比93%増の2兆2,500億円を見込む大幅増収増益。旧Switchは歴代ハード販売台数トップ（累計1億5,537万台）を達成。",
    financials: {
      revenue: "2兆2,500億円（予想）",
      revenueYoy: "+93.1%",
      operatingProfit: "3,700億円（予想）",
      opMargin: "16.4%",
      fiscalYear: "2026年3月期（通期予想）",
    },
    pl: {
      revenue: "2兆2,500億円（予想）",
      cogs: "1兆3,500億円",
      grossProfit: "9,000億円",
      grossMargin: "40.0%",
      sga: "5,300億円",
      rd: "1,400億円",
      operatingProfit: "3,700億円（予想）",
      opMargin: "16.4%",
      netIncome: "3,500億円（予想）",
      netMargin: "15.6%",
      fiscalYear: "2026年3月期（通期予想）",
    },
    bs: {
      totalAssets: "3兆8,000億円",
      currentAssets: "3兆0,500億円",
      cash: "1兆2,000億円",
      fixedAssets: "7,500億円",
      totalLiab: "1兆0,500億円",
      currentLiab: "8,800億円",
      fixedLiab: "1,700億円",
      interestBearingDebt: "0円",
      equity: "2兆7,500億円",
      equityRatio: "72.4%",
      fiscalYear: "2026年3月期Q3時点",
    },
    cf: {
      operatingCF: "+4,500億円",
      investingCF: "-2,000億円",
      financingCF: "-1,800億円",
      freeCF: "+2,500億円",
      capex: "1,500億円",
      dividends: "1,600億円",
      fiscalYear: "2026年3月期Q3累計",
    },
    strategy: {
      title: "成長戦略",
      summary:
        "Nintendo Switch 2を2025年6月に発売し次世代プラットフォームへ移行。ハード・ソフト一体型の独自路線を堅持しつつ、映画・テーマパーク（USJ）などIP展開を多角化。Switch 2では後方互換性を確保しユーザー基盤を継承。",
      keyPoints: [
        "Nintendo Switch 2（2025年6月発売、Q3末で1,737万台販売。通期1,900万台目標に上方修正）",
        "マリオ映画第2弾など映像IP展開",
        "USJスーパーニンテンドーワールド拡張",
        "ニンテンドーアカウントによるエコシステム強化",
      ],
      target: "2026年3月期 売上高2兆2,500億円（+93%）、営業利益3,700億円（+31%）",
    },
    strengths: [
      "マリオ・ゼルダ・ポケモンなど世界的IPの保有",
      "無借金経営・自己資本比率80%超の盤石な財務基盤",
      "ハード・ソフト一体開発による高い利益率",
      "映画・テーマパークなど非ゲームIP収益の拡大",
    ],
    challenges: [
      "Switch 2の立ち上げリスク（普及速度・価格設定）",
      "Switch世代末期による業績谷間（前年比大幅減収減益）",
      "メモリ高騰による製造コスト増（BOMの21-23%）",
      "年末商戦の減速と生産台数引き下げリスク",
    ],
    latestNews: [
      { date: "2026-03-24", headline: "Switch 2のQ4生産台数を最大200万台引き下げ、米国年末商戦が想定下回る" },
      { date: "2026-02-03", headline: "2026年3月期Q3決算発表、売上高99.3%増。Switch 2累計1,737万台、マリカワールド1,403万本" },
      { date: "2025-11-04", headline: "Q2決算で通期売上予想を2兆2,500億円に上方修正、Switch 2目標1,900万台に引き上げ" },
      { date: "2025-06-05", headline: "Nintendo Switch 2が発売開始、過去最速ペースで販売台数を記録" },
    ],
  },
  {
    slug: "bandai-namco",
    name: "バンダイナムコHD",
    nameEn: "Bandai Namco Holdings",
    logo: "B",
    color: "#f59e0b",
    stockCode: "7832",
    overview:
      "ガンダム・ドラゴンボール・ワンピースなど強力IPを軸に、玩具・ゲーム・映像・アミューズメントを展開するIP総合企業。2026年3月期はQ3累計で売上高が初の1兆円突破。ガンダムIPが四半期600億円規模に成長し、映像作品「GQuuuuuuX」や大阪万博出展で話題を創出。通期予想を上方修正し売上高1兆3,000億円、営業利益1,810億円を見込む。エルデンリング映画化（A24共同制作）も発表。",
    financials: {
      revenue: "1兆3,000億円（予想）",
      revenueYoy: "+4.7%",
      operatingProfit: "1,810億円（予想）",
      opMargin: "13.9%",
      fiscalYear: "2026年3月期（通期予想）",
    },
    pl: {
      revenue: "1兆3,000億円（予想）",
      cogs: "7,500億円",
      grossProfit: "5,500億円",
      grossMargin: "42.3%",
      sga: "3,690億円",
      rd: "850億円",
      operatingProfit: "1,810億円（予想）",
      opMargin: "13.9%",
      netIncome: "1,300億円（予想）",
      netMargin: "10.0%",
      fiscalYear: "2026年3月期（通期予想）",
    },
    bs: {
      totalAssets: "1兆4,000億円",
      currentAssets: "8,200億円",
      cash: "3,500億円",
      fixedAssets: "5,800億円",
      totalLiab: "4,000億円",
      currentLiab: "3,400億円",
      fixedLiab: "600億円",
      interestBearingDebt: "200億円",
      equity: "1兆0,000億円",
      equityRatio: "71.4%",
      fiscalYear: "2026年3月期Q3時点",
    },
    cf: {
      operatingCF: "+1,600億円",
      investingCF: "-550億円",
      financingCF: "-700億円",
      freeCF: "+1,050億円",
      capex: "400億円",
      dividends: "420億円",
      fiscalYear: "2026年3月期Q3累計",
    },
    strategy: {
      title: "成長戦略",
      summary:
        "IP軸戦略を核に、ガンダム・ドラゴンボール・ワンピースなど主力IPのグローバル展開を強化。トイホビー・デジタル・映像・アミューズメントのクロスメディア展開で各IPの収益最大化を図る。ガンダムカードゲームの立ち上げやガンプラのグローバル需要拡大が新たな成長ドライバー。",
      keyPoints: [
        "IP軸戦略によるクロスメディア展開強化",
        "ガンダムIP年間売上1,200億円超の拡大",
        "デジタル事業の利益率改善（ヒットタイトル連発）",
        "海外売上比率の向上（特に北米・アジア）",
      ],
      target: "2026年3月期 売上高1兆3,000億円、営業利益1,810億円（上方修正済み）",
    },
    strengths: [
      "ガンダム・ドラゴンボール・ワンピースなどIP資産の厚み",
      "トイホビー×デジタル×映像のクロスメディア展開力",
      "ガンプラの世界的ブランド力と高い利益率",
      "『エルデンリング』によるグローバルゲーム市場での存在感向上",
    ],
    challenges: [
      "大型タイトル依存（翌年の反動減リスク）",
      "ゲーム開発費の高騰と開発期間の長期化",
      "アミューズメント事業の国内市場縮小",
      "IP使用権のライセンス交渉リスク（集英社等との関係）",
    ],
    latestNews: [
      { date: "2026-02-05", headline: "2026年3月期Q3決算、売上高1兆22億円で初の1兆円突破。通期予想を上方修正（売上1兆3,000億円、営業利益1,810億円）" },
      { date: "2025-11-06", headline: "Q2決算、ガンダムIP売上が上半期1,272億円を達成。通期予想を増額修正" },
      { date: "2025-05-23", headline: "エルデンリング映画化を発表、米A24と共同制作。監督はアレックス・ガーランド氏" },
      { date: "2025-05-08", headline: "2025年3月期決算、売上・利益とも過去最高を更新。全事業増収増益" },
    ],
  },
  {
    slug: "square-enix",
    name: "スクウェア・エニックスHD",
    nameEn: "Square Enix Holdings",
    logo: "S",
    color: "#8b5cf6",
    stockCode: "9684",
    overview:
      "『ファイナルファンタジー』『ドラゴンクエスト』を擁するゲーム大手。2026年3月期は売上高こそ13.7%減の2,800億円だが、「量から質」への構造改革が着実に進み営業利益は20.7%増の490億円を見込む。Q3累計では営業利益39%増と収益性改善が顕在化。海外組織再編費用98億円を計上しつつも通期純利益は上方修正。『ドラクエ7 Reimagined』を2026年2月に発売。",
    financials: {
      revenue: "2,800億円（予想）",
      revenueYoy: "-13.7%",
      operatingProfit: "490億円（予想）",
      opMargin: "17.5%",
      fiscalYear: "2026年3月期（通期予想）",
    },
    pl: {
      revenue: "2,800億円（予想）",
      cogs: "1,550億円",
      grossProfit: "1,250億円",
      grossMargin: "44.6%",
      sga: "760億円",
      rd: "420億円",
      operatingProfit: "490億円（予想）",
      opMargin: "17.5%",
      netIncome: "270億円（予想）",
      netMargin: "9.6%",
      fiscalYear: "2026年3月期（通期予想）",
    },
    bs: {
      totalAssets: "4,234億円",
      currentAssets: "2,950億円",
      cash: "2,300億円",
      fixedAssets: "1,284億円",
      totalLiab: "811億円",
      currentLiab: "660億円",
      fixedLiab: "151億円",
      interestBearingDebt: "0円",
      equity: "3,422億円",
      equityRatio: "80.7%",
      fiscalYear: "2026年3月期Q3時点",
    },
    cf: {
      operatingCF: "+550億円",
      investingCF: "-190億円",
      financingCF: "-260億円",
      freeCF: "+360億円",
      capex: "160億円",
      dividends: "185億円",
      fiscalYear: "2026年3月期Q3累計",
    },
    strategy: {
      title: "成長戦略",
      summary:
        "中期経営計画で「再起動の3年間」を掲げ、「量から質」への転換を推進。主要IPであるFF・ドラクエを中心に大型タイトルの安定的投入を目指し、海外パブリッシング体制を抜本的に再編。開発拠点を日本に集約し、不採算事業の整理を進める。",
      keyPoints: [
        "「量から質」への開発方針転換",
        "海外パブリッシング組織の構造改革（2026年3月期に118億円再編費用）",
        "FF・ドラクエなど主力IPの安定的大型タイトル投入",
        "不採算スマホ・ブラウザゲームの整理",
      ],
      target: "中計期間（2025-2027年3月期）を「再起動の3年間」と位置づけ収益体質を改善",
    },
    strengths: [
      "FF・ドラクエなどグローバルで認知される大型IPの保有",
      "無借金経営・自己資本比率80%超の安定した財務基盤",
      "MMORPG『FF14』の長期安定収益",
      "『ドラクエ3 HD-2D リメイク』の好調な販売",
    ],
    challenges: [
      "HDゲーム部門の営業利益率が競合比で低水準",
      "スマホ・ブラウザゲームの縮小傾向",
      "大型タイトルの開発期間長期化と投資回収リスク",
      "海外スタジオ閉鎖に伴う組織再編コスト",
    ],
    latestNews: [
      { date: "2026-02-05", headline: "2026年3月期Q3決算、営業利益39%増の463億円。通期純利益予想を上方修正（270億円）" },
      { date: "2026-02-05", headline: "『ドラゴンクエストVII Reimagined』発売、3DCGリメイクで好評" },
      { date: "2025-11-06", headline: "中間期決算、営業利益28.8%増。海外組織再編費用98億円を特損計上し最終減益" },
      { date: "2025-05-14", headline: "2025年3月期決算発表、営業利益24.6%増で構造改革の効果が顕在化" },
    ],
  },
  {
    slug: "toei",
    name: "東映",
    nameEn: "Toei Company",
    logo: "映",
    color: "#10b981",
    stockCode: "9605",
    overview:
      "映画・テレビ番組の制作・配給を手がける総合映像企業。仮面ライダー・スーパー戦隊・プリキュアなどの特撮・アニメIPを保有。子会社の東映アニメーションがワンピース・ドラゴンボール等のアニメ制作で高収益。2026年3月期は劇場版『鬼滅の刃』や映画『国宝』のヒットで興行関連事業が好調。Q3累計で売上高4.6%増、営業利益9.6%増。不動産売却益で純利益予想を30%増に上方修正。年間配当を前期の2倍の36円に増配。",
    financials: {
      revenue: "1,774億円（予想）",
      revenueYoy: "-1.4%",
      operatingProfit: "312億円（予想）",
      opMargin: "17.6%",
      fiscalYear: "2026年3月期（通期予想）",
    },
    pl: {
      revenue: "1,774億円（予想）",
      cogs: "1,150億円",
      grossProfit: "624億円",
      grossMargin: "35.2%",
      sga: "312億円",
      rd: "—",
      operatingProfit: "312億円（予想）",
      opMargin: "17.6%",
      netIncome: "205億円（予想）",
      netMargin: "11.6%",
      fiscalYear: "2026年3月期（通期予想）",
    },
    bs: {
      totalAssets: "4,900億円",
      currentAssets: "2,500億円",
      cash: "1,250億円",
      fixedAssets: "2,400億円",
      totalLiab: "1,100億円",
      currentLiab: "720億円",
      fixedLiab: "380億円",
      interestBearingDebt: "130億円",
      equity: "3,800億円",
      equityRatio: "59.0%",
      fiscalYear: "2026年3月期Q3時点",
    },
    cf: {
      operatingCF: "+160億円",
      investingCF: "-70億円",
      financingCF: "-55億円",
      freeCF: "+90億円",
      capex: "55億円",
      dividends: "50億円",
      fiscalYear: "2026年3月期Q3累計",
    },
    strategy: {
      title: "成長戦略",
      summary:
        "中長期ビジョン「TOEI NEW WAVE 2033」を掲げ、実写・アニメ映像事業のグローバル展開を加速。2025年4月にIP・アニメ開発部を新設し組織体制を強化。東映アニメーションのIP企業への転換を推進し、版権ビジネスの拡大を図る。",
      keyPoints: [
        "「TOEI NEW WAVE 2033」中長期ビジョンの推進",
        "IP・アニメ開発部の新設による体制強化",
        "東映アニメーションのIP企業化（版権収益拡大）",
        "国際事業部門新設によるグローバル展開加速",
      ],
      target: "2033年に向けグローバルコンテンツ創造発信基盤を確立",
    },
    strengths: [
      "仮面ライダー・スーパー戦隊・プリキュアなど長寿特撮・アニメIP",
      "東映アニメーション（ワンピース・ドラゴンボール制作）の高収益",
      "映画館（T・ジョイ）からコンテンツ制作・配給までの垂直統合",
      "不動産事業（東映太秦映画村等）による安定収益基盤",
    ],
    challenges: [
      "実写映画の興行収入の不安定さ（ヒット依存）",
      "テレビ放映権料の構造的な低迷",
      "グローバル市場での競争激化（Netflix等OTTとの競争）",
      "特撮IP（仮面ライダー等）の少子化による国内市場縮小",
    ],
    latestNews: [
      { date: "2026-02-13", headline: "2026年3月期Q3決算、売上高1,363億円（+4.6%）、営業利益277億円（+9.6%）。興行・建築内装が補完" },
      { date: "2025-11-13", headline: "通期純利益予想を30%増の205億円に上方修正。不動産売却益と年間配当2倍（36円）を発表" },
      { date: "2025-11-14", headline: "Q2決算、劇場版『鬼滅の刃』や映画『国宝』のヒットで興行関連事業好調" },
      { date: "2025-04-01", headline: "IP・アニメ開発部を新設、国際事業部門も設置。TOEI NEW WAVE 2033を推進" },
    ],
  },
];
