import type { Competitor } from "./competitors";

export const financeCompanies: Competitor[] = [
  {
    slug: "mufg",
    name: "三菱UFJ FG",
    nameEn: "MUFG",
    logo: "M",
    color: "#ef4444",
    stockCode: "8306",
    overview:
      "国内最大の金融グループ。銀行・信託・証券・カード・リースを網羅。総資産は約400兆円で邦銀首位。海外展開にも積極的で、米国・アジアに幅広いネットワークを持つ。2025年3月期は金利上昇と海外事業の拡大で純利益が過去最高を更新。",
    financials: {
      revenue: "9兆2,810億円",
      revenueYoy: "+17.5%",
      operatingProfit: "—",
      opMargin: "—",
      keyMetric: "1兆8,629億円",
      keyMetricLabel: "純利益",
      keyMetricYoy: "+27.1%",
      fiscalYear: "2025年3月期",
    },
    pl: { revenue: "9兆2,810億円", cogs: "3兆8,000億円", grossProfit: "5兆4,810億円", grossMargin: "59.1%", sga: "3兆4,000億円", rd: "3,000億円", operatingProfit: "2兆810億円", opMargin: "22.4%", netIncome: "1兆8,629億円", netMargin: "20.1%", fiscalYear: "2025年3月期" },
    bs: { totalAssets: "404兆円", currentAssets: "—", cash: "113兆円", fixedAssets: "—", totalLiab: "382兆円", currentLiab: "—", fixedLiab: "—", interestBearingDebt: "—", equity: "22兆円", equityRatio: "5.4%", fiscalYear: "2025年3月期" },
    cf: { operatingCF: "+8兆5,000億円", investingCF: "-6兆2,000億円", financingCF: "-1兆8,000億円", freeCF: "+2兆3,000億円", capex: "5,500億円", dividends: "5,500億円", fiscalYear: "2025年3月期" },
    strategy: {
      title: "成長戦略",
      summary: "国内金利上昇を追い風に預貸金利鞘を拡大。海外は米国・アジアを重点地域として法人取引を強化。ウェルスマネジメントとデジタル化にも注力。",
      keyPoints: ["国内金利上昇の恩恵", "海外展開（米・ASEAN）", "ウェルスマネジメント", "DX推進"],
      target: "2026年3月期 純利益2兆円を目指す",
    },
    strengths: [
      "総資産400兆円超、邦銀最大のスケール",
      "金利上昇による利鞘拡大で過去最高益",
      "海外ネットワーク（Morgan Stanley提携含む）",
      "モルガン・スタンレーとの戦略的提携",
    ],
    challenges: [
      "海外与信リスクの管理",
      "国内人口減少に伴う預金基盤の縮小",
      "DX投資・システム統合コスト",
    ],
    latestNews: [
      { date: "2025-05-01", headline: "2025年3月期 純利益1兆8,629億円で過去最高" },
      { date: "2025-11-01", headline: "2026年3月期 純利益2兆円目標を発表" },
      { date: "2026-02-01", headline: "Q3累計純利益1兆5,800億円、過去最高ペース" },
    ],
  },
  {
    slug: "smfg",
    name: "三井住友FG",
    nameEn: "SMFG",
    logo: "S",
    color: "#10b981",
    stockCode: "8316",
    overview:
      "三井住友銀行を中核とする総合金融グループ。効率性（OHR）の高さが強み。SMBCグループ証券・SMBCコンシューマーファイナンスなどを傘下に持つ。金利上昇と手数料収入の拡大で増益基調。",
    financials: {
      revenue: "6兆8,000億円",
      revenueYoy: "+15.2%",
      operatingProfit: "—",
      opMargin: "—",
      keyMetric: "1兆1,810億円",
      keyMetricLabel: "純利益",
      keyMetricYoy: "+36.9%",
      fiscalYear: "2025年3月期",
    },
    pl: { revenue: "6兆8,000億円", cogs: "2兆5,000億円", grossProfit: "4兆3,000億円", grossMargin: "63.2%", sga: "2兆4,000億円", rd: "2,200億円", operatingProfit: "1兆9,000億円", opMargin: "27.9%", netIncome: "1兆1,810億円", netMargin: "17.4%", fiscalYear: "2025年3月期" },
    bs: { totalAssets: "303兆円", currentAssets: "—", cash: "76兆円", fixedAssets: "—", totalLiab: "286兆円", currentLiab: "—", fixedLiab: "—", interestBearingDebt: "—", equity: "17兆円", equityRatio: "5.6%", fiscalYear: "2025年3月期" },
    cf: { operatingCF: "+5兆8,000億円", investingCF: "-4兆2,000億円", financingCF: "-1兆2,000億円", freeCF: "+1兆6,000億円", capex: "4,200億円", dividends: "4,000億円", fiscalYear: "2025年3月期" },
    strategy: {
      title: "成長戦略",
      summary: "効率経営を強みに国内リテール・法人の深耕と、アジアを中心とした海外展開を推進。Olive（総合金融サービス）を核にデジタルリテール変革を加速。",
      keyPoints: ["Olive（デジタル金融）", "アジア展開", "効率経営（低OHR）", "ウェルスマネジメント"],
      target: "2026年3月期 純利益1兆2,600億円を計画",
    },
    strengths: [
      "邦銀トップクラスのコスト効率（OHR）",
      "Oliveによるデジタルリテール変革",
      "金利上昇による利鞘拡大",
      "アジア展開（インドネシア等）",
    ],
    challenges: [
      "純利益規模でMUFGに大差",
      "海外展開の収益貢献度向上",
      "コンシューマーファイナンスの規制リスク",
    ],
    latestNews: [
      { date: "2025-05-01", headline: "2025年3月期 純利益1兆1,810億円で過去最高" },
      { date: "2025-10-01", headline: "Olive会員数が1,000万人を突破" },
      { date: "2026-02-01", headline: "Q3累計純利益9,800億円" },
    ],
  },
  {
    slug: "mizuho",
    name: "みずほFG",
    nameEn: "Mizuho Financial Group",
    logo: "み",
    color: "#3b82f6",
    stockCode: "8411",
    overview:
      "みずほ銀行・みずほ証券・みずほ信託銀行を中核とする総合金融グループ。大企業取引・投資銀行分野に強み。過去のシステム障害を経て信頼回復に注力し、IT基盤の刷新を推進中。",
    financials: {
      revenue: "5兆2,000億円",
      revenueYoy: "+12.8%",
      operatingProfit: "—",
      opMargin: "—",
      keyMetric: "8,200億円",
      keyMetricLabel: "純利益",
      keyMetricYoy: "+22.4%",
      fiscalYear: "2025年3月期",
    },
    pl: { revenue: "5兆2,000億円", cogs: "2兆1,000億円", grossProfit: "3兆1,000億円", grossMargin: "59.6%", sga: "1兆9,500億円", rd: "2,000億円", operatingProfit: "1兆1,500億円", opMargin: "22.1%", netIncome: "8,200億円", netMargin: "15.8%", fiscalYear: "2025年3月期" },
    bs: { totalAssets: "271兆円", currentAssets: "—", cash: "62兆円", fixedAssets: "—", totalLiab: "257兆円", currentLiab: "—", fixedLiab: "—", interestBearingDebt: "—", equity: "14兆円", equityRatio: "5.2%", fiscalYear: "2025年3月期" },
    cf: { operatingCF: "+4兆5,000億円", investingCF: "-3兆2,000億円", financingCF: "-9,000億円", freeCF: "+1兆3,000億円", capex: "3,500億円", dividends: "2,800億円", fiscalYear: "2025年3月期" },
    strategy: {
      title: "成長戦略",
      summary: "法人・投資銀行ビジネスを強化し、国内外の大型案件でプレゼンスを高める。IT基盤の安定化・高度化に継続投資。アジア・米国でのビジネス拡大。",
      keyPoints: ["法人・投資銀行強化", "IT基盤刷新", "アジア・米国展開", "サステナブルファイナンス"],
      target: "2026年3月期 純利益8,500億円を計画",
    },
    strengths: [
      "大企業取引・投資銀行分野での強み",
      "金利上昇による業績改善",
      "3メガ中最も積極的なIT投資",
    ],
    challenges: [
      "過去のシステム障害による信頼低下",
      "3メガ中で収益規模が最小",
      "OHRの改善余地",
    ],
    latestNews: [
      { date: "2025-05-01", headline: "2025年3月期 純利益8,200億円で過去最高" },
      { date: "2025-09-01", headline: "次期勘定系システムの開発計画を発表" },
      { date: "2026-02-01", headline: "Q3累計純利益6,500億円" },
    ],
  },
  {
    slug: "nomura",
    name: "野村ホールディングス",
    nameEn: "Nomura Holdings",
    logo: "野",
    color: "#f59e0b",
    stockCode: "8604",
    overview:
      "日本最大の証券会社グループ。国内リテール・ホールセール（投資銀行）・アセットマネジメントの3セグメントで展開。米国・欧州・アジアにグローバルネットワークを持つ。市況改善と海外リストラ効果で業績回復。",
    financials: {
      revenue: "1兆9,200億円",
      revenueYoy: "+31.5%",
      operatingProfit: "3,800億円",
      opMargin: "19.8%",
      keyMetric: "2,930億円",
      keyMetricLabel: "純利益",
      keyMetricYoy: "+120.5%",
      fiscalYear: "2025年3月期",
    },
    pl: { revenue: "1兆9,200億円", cogs: "—", grossProfit: "1兆9,200億円", grossMargin: "—", sga: "1兆5,400億円", rd: "—", operatingProfit: "3,800億円", opMargin: "19.8%", netIncome: "2,930億円", netMargin: "15.3%", fiscalYear: "2025年3月期" },
    bs: { totalAssets: "56兆円", currentAssets: "—", cash: "4兆2,000億円", fixedAssets: "—", totalLiab: "52兆5,000億円", currentLiab: "—", fixedLiab: "—", interestBearingDebt: "—", equity: "3兆5,000億円", equityRatio: "6.3%", fiscalYear: "2025年3月期" },
    cf: { operatingCF: "+8,500億円", investingCF: "-2,800億円", financingCF: "-4,200億円", freeCF: "+5,700億円", capex: "1,200億円", dividends: "1,000億円", fiscalYear: "2025年3月期" },
    strategy: {
      title: "成長戦略",
      summary: "ウェルスマネジメントを最重点領域に据え、富裕層向けサービスを強化。海外事業は収益性を重視した選択と集中。アセットマネジメントの拡大も推進。",
      keyPoints: ["ウェルスマネジメント強化", "海外事業の選択と集中", "AM事業拡大", "デジタル証券"],
      target: "ROE8-10%の安定的な実現",
    },
    strengths: [
      "国内証券リテールで圧倒的シェア",
      "グローバルな投資銀行ネットワーク",
      "市況改善で純利益が2倍超に回復",
    ],
    challenges: [
      "市況依存型の収益構造",
      "海外事業の安定的な黒字化",
      "資産運用立国の流れへの対応",
    ],
    latestNews: [
      { date: "2025-05-01", headline: "2025年3月期 純利益2,930億円と大幅増益" },
      { date: "2025-10-01", headline: "ウェルスマネジメント部門の組織再編を実施" },
      { date: "2026-02-01", headline: "Q3累計純利益2,800億円、通期見通しを上方修正" },
    ],
  },
  {
    slug: "daiwa",
    name: "大和証券グループ",
    nameEn: "Daiwa Securities Group",
    logo: "大",
    color: "#6366f1",
    stockCode: "8601",
    overview:
      "国内2位の証券グループ。リテール・ホールセール・アセットマネジメントを展開。大和ネクスト銀行を傘下に持ち、銀証連携モデルを推進。NISA口座の拡大と資産運用事業の強化に注力。",
    financials: {
      revenue: "7,400億円",
      revenueYoy: "+25.4%",
      operatingProfit: "1,680億円",
      opMargin: "22.7%",
      keyMetric: "1,250億円",
      keyMetricLabel: "純利益",
      keyMetricYoy: "+52.4%",
      fiscalYear: "2025年3月期",
    },
    pl: { revenue: "7,400億円", cogs: "—", grossProfit: "7,400億円", grossMargin: "—", sga: "5,720億円", rd: "—", operatingProfit: "1,680億円", opMargin: "22.7%", netIncome: "1,250億円", netMargin: "16.9%", fiscalYear: "2025年3月期" },
    bs: { totalAssets: "28兆5,000億円", currentAssets: "—", cash: "2兆5,000億円", fixedAssets: "—", totalLiab: "26兆8,000億円", currentLiab: "—", fixedLiab: "—", interestBearingDebt: "—", equity: "1兆7,000億円", equityRatio: "6.0%", fiscalYear: "2025年3月期" },
    cf: { operatingCF: "+3,200億円", investingCF: "-1,200億円", financingCF: "-1,800億円", freeCF: "+2,000億円", capex: "600億円", dividends: "550億円", fiscalYear: "2025年3月期" },
    strategy: {
      title: "成長戦略",
      summary: "「貯蓄から投資へ」の国策を追い風に、NISA・iDeCoを中心としたリテール基盤の拡大。大和ネクスト銀行との銀証連携を深化。アセットマネジメント事業の拡大にも注力。",
      keyPoints: ["NISA・資産形成支援", "銀証連携（大和ネクスト銀行）", "AM事業拡大", "デジタル化推進"],
      target: "ROE10%超の安定的実現",
    },
    strengths: [
      "NISA口座の積極的な獲得",
      "銀証連携モデル（大和ネクスト銀行）",
      "市況改善で大幅増益",
    ],
    challenges: [
      "野村との規模差",
      "ネット証券との手数料競争",
      "海外事業の収益力",
    ],
    latestNews: [
      { date: "2025-05-01", headline: "2025年3月期 純利益1,250億円と大幅増益" },
      { date: "2025-09-01", headline: "NISA口座数が200万を突破" },
      { date: "2026-02-01", headline: "Q3累計純利益1,100億円" },
    ],
  },
];
