import type { Competitor } from "./competitors";

export const foodCompanies: Competitor[] = [
  {
    slug: "ajinomoto",
    name: "味の素",
    nameEn: "Ajinomoto Co., Inc.",
    logo: "味",
    color: "#ef4444",
    stockCode: "2802",
    overview:
      "アミノ酸技術を核にグローバル展開する食品・バイオ企業。調味料・冷凍食品のほか、半導体パッケージ基板向け層間絶縁材料「ABF（味の素ビルドアップフィルム）」が高収益事業に成長。2025年3月期はヘルスケア・電子材料の好調と海外食品の値上げ効果で増収増益。ASV（Ajinomoto Group Shared Value）経営を推進。",
    financials: {
      revenue: "1兆4,392億円",
      revenueYoy: "+3.8%",
      operatingProfit: "1,783億円",
      opMargin: "12.4%",
      keyMetric: "1,265億円",
      keyMetricLabel: "純利益",
      keyMetricYoy: "+18.2%",
      fiscalYear: "2025年3月期",
    },
    pl: { revenue: "1兆4,392億円", cogs: "9,200億円", grossProfit: "5,192億円", grossMargin: "36.1%", sga: "3,409億円", rd: "320億円", operatingProfit: "1,783億円", opMargin: "12.4%", netIncome: "1,265億円", netMargin: "8.8%", fiscalYear: "2025年3月期" },
    bs: { totalAssets: "1兆8,500億円", currentAssets: "7,200億円", cash: "2,100億円", fixedAssets: "1兆1,300億円", totalLiab: "8,800億円", currentLiab: "4,200億円", fixedLiab: "4,600億円", interestBearingDebt: "3,200億円", equity: "9,700億円", equityRatio: "52.4%", fiscalYear: "2025年3月期" },
    cf: { operatingCF: "+2,050億円", investingCF: "-1,100億円", financingCF: "-850億円", freeCF: "+950億円", capex: "950億円", dividends: "420億円", fiscalYear: "2025年3月期" },
    strategy: {
      title: "成長戦略",
      summary: "アミノ酸技術を基盤に食品・ヘルスケア・電子材料の3本柱で成長。ABFは生成AI需要で半導体パッケージ市場拡大の恩恵を受ける。海外食品は新興国のプレゼンス拡大と付加価値化を推進。",
      keyPoints: ["ABF（半導体材料）のAI需要取り込み", "海外食品の付加価値化・値上げ", "ヘルスケア（アミノ酸サプリ等）", "ASV経営による企業価値向上"],
      target: "2030年度 事業利益2,600億円以上を目指す",
    },
    strengths: [
      "アミノ酸技術で世界シェアトップ",
      "ABF（半導体絶縁材料）が高成長・高収益",
      "海外売上比率60%超のグローバル食品ポートフォリオ",
      "研究開発力とブランド力の両立",
    ],
    challenges: [
      "原材料価格の高騰リスク（大豆・小麦・エネルギー）",
      "ABFの競合参入リスク",
      "国内食品市場の縮小と人口減少",
      "為替変動の影響（海外比率が高い）",
    ],
    latestNews: [
      { date: "2025-05-01", headline: "2025年3月期 純利益1,265億円で過去最高を更新" },
      { date: "2025-09-01", headline: "ABFの生産能力増強を発表、AI半導体需要に対応" },
      { date: "2025-11-01", headline: "中期ASV経営2030ロードマップを公表" },
      { date: "2026-02-01", headline: "Q3累計 事業利益1,500億円超、通期計画に対し順調に進捗" },
    ],
  },
  {
    slug: "nissin-foods",
    name: "日清食品ホールディングス",
    nameEn: "Nissin Foods Holdings Co., Ltd.",
    logo: "日",
    color: "#f97316",
    stockCode: "2897",
    overview:
      "「カップヌードル」「チキンラーメン」で世界的に知られるインスタントラーメンのパイオニア。グローバルで年間300億食以上を販売。米州・中国・アジアでの海外事業が成長ドライバー。2025年3月期は海外事業の好調と国内の価格改定効果で増収増益。",
    financials: {
      revenue: "7,830億円",
      revenueYoy: "+7.2%",
      operatingProfit: "645億円",
      opMargin: "8.2%",
      keyMetric: "520億円",
      keyMetricLabel: "純利益",
      keyMetricYoy: "+12.5%",
      fiscalYear: "2025年3月期",
    },
    pl: { revenue: "7,830億円", cogs: "4,700億円", grossProfit: "3,130億円", grossMargin: "40.0%", sga: "2,485億円", rd: "110億円", operatingProfit: "645億円", opMargin: "8.2%", netIncome: "520億円", netMargin: "6.6%", fiscalYear: "2025年3月期" },
    bs: { totalAssets: "9,800億円", currentAssets: "3,400億円", cash: "1,200億円", fixedAssets: "6,400億円", totalLiab: "3,600億円", currentLiab: "2,000億円", fixedLiab: "1,600億円", interestBearingDebt: "1,100億円", equity: "6,200億円", equityRatio: "63.3%", fiscalYear: "2025年3月期" },
    cf: { operatingCF: "+850億円", investingCF: "-500億円", financingCF: "-350億円", freeCF: "+350億円", capex: "450億円", dividends: "200億円", fiscalYear: "2025年3月期" },
    strategy: {
      title: "成長戦略",
      summary: "「EARTH FOOD CREATOR」ビジョンのもと、グローバルブランド「カップヌードル」を軸に海外事業を拡大。BRICsを中心とした新興国市場の開拓と、国内での高付加価値商品展開を両輪で推進。完全栄養食やプラントベース食品など次世代食品にも注力。",
      keyPoints: ["海外事業の拡大（米州・中国・アジア）", "カップヌードルのグローバルブランド戦略", "完全栄養食・プラントベース食品", "DXによる生産性向上"],
      target: "2030年度 海外売上比率50%超・営業利益率10%以上",
    },
    strengths: [
      "即席麺市場で世界的ブランド力",
      "グローバルで90カ国以上に展開",
      "高い自己資本比率（63%超）で財務基盤が堅固",
      "マーケティング力とイノベーション力",
    ],
    challenges: [
      "小麦・パーム油などの原材料コスト上昇",
      "中国市場での競争激化",
      "即席麺カテゴリーへの健康志向からの逆風",
      "海外事業の為替リスク",
    ],
    latestNews: [
      { date: "2025-05-01", headline: "2025年3月期 売上収益7,830億円、営業利益645億円で増収増益" },
      { date: "2025-08-01", headline: "インド新工場の建設を発表、南アジア市場を強化" },
      { date: "2025-12-01", headline: "完全栄養食ブランドの新シリーズを発売" },
      { date: "2026-02-01", headline: "Q3累計 営業利益530億円、海外好調で通期計画に対し順調" },
    ],
  },
  {
    slug: "kirin-hd",
    name: "キリンホールディングス",
    nameEn: "Kirin Holdings Company, Limited",
    logo: "K",
    color: "#3b82f6",
    stockCode: "2503",
    overview:
      "ビール・飲料事業を基盤に、医薬（協和キリン）・ヘルスサイエンスの3事業を展開する総合飲料・バイオ企業。協和キリンは抗体医薬に強みを持ち、グローバル展開を加速。2024年12月期はビール事業の回復と協和キリンの成長で増益。「食から医にわたる価値創造」を掲げる。",
    financials: {
      revenue: "2兆1,300億円",
      revenueYoy: "+4.5%",
      operatingProfit: "1,680億円",
      opMargin: "7.9%",
      keyMetric: "1,050億円",
      keyMetricLabel: "純利益",
      keyMetricYoy: "+22.0%",
      fiscalYear: "2024年12月期",
    },
    pl: { revenue: "2兆1,300億円", cogs: "1兆1,800億円", grossProfit: "9,500億円", grossMargin: "44.6%", sga: "7,820億円", rd: "780億円", operatingProfit: "1,680億円", opMargin: "7.9%", netIncome: "1,050億円", netMargin: "4.9%", fiscalYear: "2024年12月期" },
    bs: { totalAssets: "2兆8,500億円", currentAssets: "8,200億円", cash: "2,000億円", fixedAssets: "2兆300億円", totalLiab: "1兆5,200億円", currentLiab: "6,800億円", fixedLiab: "8,400億円", interestBearingDebt: "6,500億円", equity: "1兆3,300億円", equityRatio: "46.7%", fiscalYear: "2024年12月期" },
    cf: { operatingCF: "+2,500億円", investingCF: "-1,200億円", financingCF: "-1,400億円", freeCF: "+1,300億円", capex: "1,000億円", dividends: "600億円", fiscalYear: "2024年12月期" },
    strategy: {
      title: "成長戦略",
      summary: "ビール・飲料の基盤事業の収益力強化に加え、協和キリンを中核とした医薬事業のグローバル成長を推進。ヘルスサイエンス領域では免疫・脳機能分野での新規事業創出を目指す。CSV経営（Creating Shared Value）を推進。",
      keyPoints: ["協和キリンのグローバル医薬事業成長", "ビール事業の高付加価値化", "ヘルスサイエンス（免疫・脳機能）", "ノンアル・低アル市場の開拓"],
      target: "2027年 平準化EPS 240円以上を目指す",
    },
    strengths: [
      "協和キリン（医薬）による事業の多角化",
      "ビール・飲料で国内トップクラスのシェア",
      "発酵・バイオ技術を活かした独自のヘルスサイエンス領域",
      "高い粗利率（44%超）と研究開発力",
    ],
    challenges: [
      "国内ビール市場の縮小（少子高齢化・酒類離れ）",
      "協和キリンの新薬パイプラインリスク",
      "ミャンマー事業の人権リスクへの対応",
      "原材料・エネルギーコストの上昇",
    ],
    latestNews: [
      { date: "2025-02-01", headline: "2024年12月期 純利益1,050億円で大幅増益" },
      { date: "2025-06-01", headline: "協和キリンの新薬が欧米で承認取得" },
      { date: "2025-10-01", headline: "ヘルスサイエンス事業の新ブランドを立ち上げ" },
      { date: "2026-02-01", headline: "2025年12月期Q3 営業利益1,400億円で前年同期比増益" },
    ],
  },
  {
    slug: "asahi-group",
    name: "アサヒグループホールディングス",
    nameEn: "Asahi Group Holdings, Ltd.",
    logo: "ア",
    color: "#10b981",
    stockCode: "2502",
    overview:
      "「スーパードライ」で国内ビール市場をリードし、2016年以降の大型M&A（旧SABMillerの欧州事業、CUB豪州事業）でグローバルプレミアムビール企業へ変貌。欧州・豪州・東南アジアで展開。2024年12月期は欧州・豪州でのプレミアム化戦略が奏功し増収増益。",
    financials: {
      revenue: "2兆8,500億円",
      revenueYoy: "+5.8%",
      operatingProfit: "2,650億円",
      opMargin: "9.3%",
      keyMetric: "1,620億円",
      keyMetricLabel: "純利益",
      keyMetricYoy: "+15.0%",
      fiscalYear: "2024年12月期",
    },
    pl: { revenue: "2兆8,500億円", cogs: "1兆6,200億円", grossProfit: "1兆2,300億円", grossMargin: "43.2%", sga: "9,650億円", rd: "180億円", operatingProfit: "2,650億円", opMargin: "9.3%", netIncome: "1,620億円", netMargin: "5.7%", fiscalYear: "2024年12月期" },
    bs: { totalAssets: "5兆2,000億円", currentAssets: "1兆1,500億円", cash: "2,800億円", fixedAssets: "4兆500億円", totalLiab: "3兆1,500億円", currentLiab: "9,500億円", fixedLiab: "2兆2,000億円", interestBearingDebt: "1兆5,800億円", equity: "2兆500億円", equityRatio: "39.4%", fiscalYear: "2024年12月期" },
    cf: { operatingCF: "+3,600億円", investingCF: "-1,400億円", financingCF: "-2,500億円", freeCF: "+2,200億円", capex: "1,300億円", dividends: "800億円", fiscalYear: "2024年12月期" },
    strategy: {
      title: "成長戦略",
      summary: "グローバルプレミアムビール戦略を推進。欧州・豪州の既存基盤強化と東南アジアでの成長を両輪で展開。国内はスーパードライのブランド刷新とノンアル・低アル市場を開拓。M&Aで生じたのれんの着実な償却と有利子負債の削減も重要課題。",
      keyPoints: ["グローバルプレミアム戦略", "欧州・豪州事業の収益力強化", "東南アジア市場の拡大", "有利子負債削減とROIC経営"],
      target: "2025年 コア営業利益3,000億円以上を目指す",
    },
    strengths: [
      "「スーパードライ」「Peroni」「Pilsner Urquell」等のグローバルブランド群",
      "欧州・豪州でのプレミアムビール市場での確固たる地位",
      "M&Aによるグローバル展開の加速",
      "営業キャッシュフロー創出力の高さ（3,600億円）",
    ],
    challenges: [
      "M&Aに伴うのれん・無形資産の大きさ（減損リスク）",
      "有利子負債1.5兆円超の返済負担",
      "国内ビール市場の成熟・縮小",
      "欧州での地政学リスクと景気後退リスク",
    ],
    latestNews: [
      { date: "2025-02-01", headline: "2024年12月期 コア営業利益2,650億円で過去最高を更新" },
      { date: "2025-07-01", headline: "東南アジアでのプレミアムビール展開を強化" },
      { date: "2025-11-01", headline: "有利子負債を計画通り削減、財務体質改善が進捗" },
      { date: "2026-02-01", headline: "2025年12月期Q3 コア営業利益2,200億円で増益基調を維持" },
    ],
  },
  {
    slug: "meiji-hd",
    name: "明治ホールディングス",
    nameEn: "Meiji Holdings Co., Ltd.",
    logo: "明",
    color: "#f59e0b",
    stockCode: "2269",
    overview:
      "乳製品・菓子の国内最大手（明治）と医薬品事業（Meiji Seikaファルマ）を展開。「明治ブルガリアヨーグルト」「明治おいしい牛乳」「きのこの山」「たけのこの里」等のロングセラーブランドを保有。2025年3月期は価格改定効果と菓子・牛乳の好調で増益。医薬はジェネリック事業を強化。",
    financials: {
      revenue: "1兆1,420億円",
      revenueYoy: "+4.2%",
      operatingProfit: "1,050億円",
      opMargin: "9.2%",
      keyMetric: "720億円",
      keyMetricLabel: "純利益",
      keyMetricYoy: "+10.8%",
      fiscalYear: "2025年3月期",
    },
    pl: { revenue: "1兆1,420億円", cogs: "7,100億円", grossProfit: "4,320億円", grossMargin: "37.8%", sga: "3,270億円", rd: "300億円", operatingProfit: "1,050億円", opMargin: "9.2%", netIncome: "720億円", netMargin: "6.3%", fiscalYear: "2025年3月期" },
    bs: { totalAssets: "1兆3,200億円", currentAssets: "4,600億円", cash: "1,100億円", fixedAssets: "8,600億円", totalLiab: "5,800億円", currentLiab: "3,200億円", fixedLiab: "2,600億円", interestBearingDebt: "1,800億円", equity: "7,400億円", equityRatio: "56.1%", fiscalYear: "2025年3月期" },
    cf: { operatingCF: "+1,400億円", investingCF: "-650億円", financingCF: "-700億円", freeCF: "+750億円", capex: "580億円", dividends: "300億円", fiscalYear: "2025年3月期" },
    strategy: {
      title: "成長戦略",
      summary: "食品事業では国内基盤の収益力強化と海外展開（中国・東南アジア）を推進。栄養・健康領域での新商品開発に注力。医薬事業はジェネリック医薬品とワクチン事業を成長の柱に位置づけ。プロバイオティクス（乳酸菌）の機能性研究で差別化を図る。",
      keyPoints: ["プロバイオティクス・機能性食品の強化", "海外展開（中国・東南アジア）", "医薬品（ジェネリック・ワクチン）", "価格改定と付加価値化の推進"],
      target: "2026年度 営業利益1,200億円以上を目指す",
    },
    strengths: [
      "乳製品・菓子で国内圧倒的シェア",
      "ロングセラーブランド群の高い認知度・ロイヤリティ",
      "プロバイオティクス（乳酸菌R-1等）の研究開発力",
      "食品＋医薬の事業ポートフォリオ",
    ],
    challenges: [
      "原材料（乳原料・カカオ・砂糖）の価格高騰",
      "国内食品市場の成熟と人口減少",
      "海外事業の規模がまだ限定的",
      "医薬事業の収益性改善",
    ],
    latestNews: [
      { date: "2025-05-01", headline: "2025年3月期 営業利益1,050億円で増益達成" },
      { date: "2025-08-01", headline: "中国でのチョコレート事業を拡大、新工場稼働" },
      { date: "2025-11-01", headline: "乳酸菌R-1の新エビデンスを学会発表" },
      { date: "2026-02-01", headline: "Q3累計 営業利益850億円、通期計画達成に向け順調" },
    ],
  },
];
