import type { Competitor } from "./competitors";

export const materialsCompanies: Competitor[] = [
  {
    slug: "nippon-steel",
    name: "日本製鉄",
    nameEn: "Nippon Steel Corporation",
    logo: "鉄",
    color: "#3b82f6",
    stockCode: "5401",
    overview:
      "国内最大手の鉄鋼メーカー。粗鋼生産量で国内首位、世界4位。高炉一貫製鉄所を国内外に展開し、自動車向け高級鋼板に強み。USスチール買収を推進し、グローバル粗鋼生産能力の拡大を目指す。2025年3月期は鋼材需要の回復と価格転嫁で増収も、原料高や海外事業の再編コストが利益を圧迫。",
    financials: {
      revenue: "7兆8,340億円",
      revenueYoy: "+3.5%",
      operatingProfit: "5,210億円",
      opMargin: "6.7%",
      keyMetric: "3,440億円",
      keyMetricLabel: "純利益",
      keyMetricYoy: "-15.2%",
      fiscalYear: "2025年3月期",
    },
    pl: { revenue: "7兆8,340億円", cogs: "6兆6,800億円", grossProfit: "1兆1,540億円", grossMargin: "14.7%", sga: "6,330億円", rd: "800億円", operatingProfit: "5,210億円", opMargin: "6.7%", netIncome: "3,440億円", netMargin: "4.4%", fiscalYear: "2025年3月期" },
    bs: { totalAssets: "10兆2,000億円", currentAssets: "3兆5,000億円", cash: "4,200億円", fixedAssets: "6兆7,000億円", totalLiab: "5兆8,000億円", currentLiab: "2兆5,000億円", fixedLiab: "3兆3,000億円", interestBearingDebt: "2兆8,000億円", equity: "4兆4,000億円", equityRatio: "43.1%", fiscalYear: "2025年3月期" },
    cf: { operatingCF: "+6,800億円", investingCF: "-5,200億円", financingCF: "-2,100億円", freeCF: "+1,600億円", capex: "4,800億円", dividends: "1,200億円", fiscalYear: "2025年3月期" },
    strategy: {
      title: "成長戦略",
      summary: "USスチール買収によるグローバル粗鋼1億トン体制の構築を目指す。国内では高炉再編・脱炭素製鉄（水素還元製鉄）への移行を推進。高級鋼板の技術優位を維持しつつ、海外での生産能力を拡大。",
      keyPoints: ["USスチール買収", "水素還元製鉄・カーボンニュートラル", "高級鋼板の技術優位", "インド・ASEAN拡大"],
      target: "2026年3月期 粗鋼生産能力1億トン体制を目指す",
    },
    strengths: [
      "国内粗鋼生産量首位、自動車向け高級鋼板で圧倒的シェア",
      "USスチール買収によるグローバルプレゼンス拡大",
      "水素還元製鉄など脱炭素技術の開発力",
      "インド（AM/NS India）での成長基盤",
    ],
    challenges: [
      "USスチール買収の規制リスク・政治的障壁",
      "中国の過剰生産による鋼材価格下落リスク",
      "脱炭素への巨額設備投資負担",
      "国内鉄鋼需要の構造的減少",
    ],
    latestNews: [
      { date: "2025-05-01", headline: "2025年3月期 純利益3,440億円で着地、原料高が重荷" },
      { date: "2025-09-01", headline: "USスチール買収に関する米国政府の審査が継続" },
      { date: "2025-12-01", headline: "水素還元製鉄の実証実験を君津製鉄所で開始" },
      { date: "2026-02-01", headline: "Q3累計純利益2,800億円、鋼材価格は堅調に推移" },
    ],
  },
  {
    slug: "jfe-holdings",
    name: "JFEホールディングス",
    nameEn: "JFE Holdings, Inc.",
    logo: "J",
    color: "#64748b",
    stockCode: "5411",
    overview:
      "国内2位の鉄鋼メーカー。JFEスチール・JFEエンジニアリング・JFE商事の3社を中核に事業展開。電磁鋼板で世界トップクラスのシェアを持ち、EV向け需要の増加が追い風。2025年3月期は国内鋼材スプレッド改善で増益。",
    financials: {
      revenue: "5兆1,200億円",
      revenueYoy: "+2.8%",
      operatingProfit: "3,150億円",
      opMargin: "6.2%",
      keyMetric: "2,050億円",
      keyMetricLabel: "純利益",
      keyMetricYoy: "+42.0%",
      fiscalYear: "2025年3月期",
    },
    pl: { revenue: "5兆1,200億円", cogs: "4兆4,200億円", grossProfit: "7,000億円", grossMargin: "13.7%", sga: "3,850億円", rd: "550億円", operatingProfit: "3,150億円", opMargin: "6.2%", netIncome: "2,050億円", netMargin: "4.0%", fiscalYear: "2025年3月期" },
    bs: { totalAssets: "5兆8,000億円", currentAssets: "2兆1,000億円", cash: "2,100億円", fixedAssets: "3兆7,000億円", totalLiab: "3兆3,000億円", currentLiab: "1兆5,000億円", fixedLiab: "1兆8,000億円", interestBearingDebt: "1兆5,000億円", equity: "2兆5,000億円", equityRatio: "43.1%", fiscalYear: "2025年3月期" },
    cf: { operatingCF: "+4,500億円", investingCF: "-3,200億円", financingCF: "-1,500億円", freeCF: "+1,300億円", capex: "3,000億円", dividends: "700億円", fiscalYear: "2025年3月期" },
    strategy: {
      title: "成長戦略",
      summary: "電磁鋼板の増産投資でEV・再エネ向け需要を取り込む。国内高炉の再編・統合を進めつつ、インド・ASEANでの海外展開を加速。カーボンニュートラルスチールの実現に向けた技術開発を推進。",
      keyPoints: ["電磁鋼板の増産・EV対応", "国内高炉再編・コスト削減", "インド（JSWスチールとの提携）", "グリーンスチール技術開発"],
      target: "2027年3月期 ROE10%以上を目標",
    },
    strengths: [
      "電磁鋼板で世界トップクラスのシェア（EV・モーター向け）",
      "JFEエンジニアリングの環境・エネルギー事業",
      "鋼材スプレッド改善による収益力回復",
      "インドJSWスチールとの戦略的提携",
    ],
    challenges: [
      "日本製鉄との競争（規模・投資力の差）",
      "中国鉄鋼の供給過剰リスク",
      "高炉の脱炭素化に伴う設備投資負担",
      "海外事業の利益貢献度が限定的",
    ],
    latestNews: [
      { date: "2025-05-01", headline: "2025年3月期 純利益2,050億円、前期比42%増で大幅回復" },
      { date: "2025-08-01", headline: "電磁鋼板の増産設備が西日本製鉄所で稼働開始" },
      { date: "2025-11-01", headline: "インドJSWスチールとの合弁事業を拡大" },
      { date: "2026-02-01", headline: "Q3累計純利益1,700億円、鋼材需要は底堅い" },
    ],
  },
  {
    slug: "asahi-kasei",
    name: "旭化成",
    nameEn: "Asahi Kasei Corporation",
    logo: "旭",
    color: "#10b981",
    stockCode: "3407",
    overview:
      "マテリアル・住宅・ヘルスケアの3領域で事業を展開する総合化学メーカー。リチウムイオン電池用セパレータ「ハイポア」で世界シェア首位。住宅事業（ヘーベルハウス）や医薬・医療機器事業も収益の柱。2025年3月期はマテリアル事業の市況回復と住宅事業の堅調で増益。",
    financials: {
      revenue: "2兆7,850億円",
      revenueYoy: "+4.2%",
      operatingProfit: "1,850億円",
      opMargin: "6.6%",
      keyMetric: "1,150億円",
      keyMetricLabel: "純利益",
      keyMetricYoy: "+38.5%",
      fiscalYear: "2025年3月期",
    },
    pl: { revenue: "2兆7,850億円", cogs: "1兆9,600億円", grossProfit: "8,250億円", grossMargin: "29.6%", sga: "6,400億円", rd: "1,050億円", operatingProfit: "1,850億円", opMargin: "6.6%", netIncome: "1,150億円", netMargin: "4.1%", fiscalYear: "2025年3月期" },
    bs: { totalAssets: "3兆5,500億円", currentAssets: "1兆2,800億円", cash: "2,400億円", fixedAssets: "2兆2,700億円", totalLiab: "1兆8,500億円", currentLiab: "7,800億円", fixedLiab: "1兆700億円", interestBearingDebt: "8,500億円", equity: "1兆7,000億円", equityRatio: "47.9%", fiscalYear: "2025年3月期" },
    cf: { operatingCF: "+3,200億円", investingCF: "-2,100億円", financingCF: "-1,200億円", freeCF: "+1,100億円", capex: "1,900億円", dividends: "500億円", fiscalYear: "2025年3月期" },
    strategy: {
      title: "成長戦略",
      summary: "「Care for People, Care for Earth」をスローガンに、環境・ヘルスケア分野への経営資源シフトを推進。LiB用セパレータの増産投資を加速し、EV市場の成長を取り込む。水素関連技術やCO2分離膜など次世代環境事業も育成。",
      keyPoints: ["LiBセパレータ増産（EV対応）", "ヘルスケア事業の拡大", "水素・CO2分離など環境技術", "住宅事業の安定収益"],
      target: "2026年3月期 営業利益2,200億円を計画",
    },
    strengths: [
      "LiBセパレータ「ハイポア」で世界シェア首位",
      "マテリアル・住宅・ヘルスケアの3本柱で事業リスク分散",
      "住宅（ヘーベルハウス）の安定的なストック収益",
      "研究開発力（ノーベル化学賞・吉野彰氏のLiB開発）",
    ],
    challenges: [
      "石油化学事業の市況変動リスク",
      "LiBセパレータの競争激化（中国勢の台頭）",
      "住宅事業の国内市場縮小リスク",
      "ヘルスケア事業のM&A統合リスク",
    ],
    latestNews: [
      { date: "2025-05-01", headline: "2025年3月期 純利益1,150億円、前期比38%増で回復基調" },
      { date: "2025-09-01", headline: "カナダでLiBセパレータ新工場の建設を決定" },
      { date: "2025-12-01", headline: "ヘルスケア事業で米国バイオ企業を買収" },
      { date: "2026-02-01", headline: "Q3累計純利益950億円、通期計画に対し順調に進捗" },
    ],
  },
  {
    slug: "mitsubishi-chemical",
    name: "三菱ケミカルグループ",
    nameEn: "Mitsubishi Chemical Group Corporation",
    logo: "三",
    color: "#8b5cf6",
    stockCode: "4188",
    overview:
      "国内最大の総合化学メーカー。機能商品・素材・産業ガス・ヘルスケアの4セグメントで事業を展開。MMAモノマー（メタクリル酸メチル）で世界首位。ジョンマーク・ギルソンCEOの下で大規模な事業ポートフォリオ再編を推進。2025年3月期はスペシャリティマテリアルズの回復と構造改革効果で増益。",
    financials: {
      revenue: "4兆3,600億円",
      revenueYoy: "+1.8%",
      operatingProfit: "2,050億円",
      opMargin: "4.7%",
      keyMetric: "820億円",
      keyMetricLabel: "純利益",
      keyMetricYoy: "黒字転換",
      fiscalYear: "2025年3月期",
    },
    pl: { revenue: "4兆3,600億円", cogs: "3兆3,500億円", grossProfit: "1兆100億円", grossMargin: "23.2%", sga: "8,050億円", rd: "1,350億円", operatingProfit: "2,050億円", opMargin: "4.7%", netIncome: "820億円", netMargin: "1.9%", fiscalYear: "2025年3月期" },
    bs: { totalAssets: "5兆5,000億円", currentAssets: "1兆8,500億円", cash: "3,200億円", fixedAssets: "3兆6,500億円", totalLiab: "3兆6,000億円", currentLiab: "1兆3,500億円", fixedLiab: "2兆2,500億円", interestBearingDebt: "1兆8,500億円", equity: "1兆9,000億円", equityRatio: "34.5%", fiscalYear: "2025年3月期" },
    cf: { operatingCF: "+3,800億円", investingCF: "-2,500億円", financingCF: "-1,500億円", freeCF: "+1,300億円", capex: "2,300億円", dividends: "500億円", fiscalYear: "2025年3月期" },
    strategy: {
      title: "成長戦略",
      summary: "「KAITEKI経営」からポートフォリオ再編型経営へ移行。石化・炭素事業の切り離しを進め、スペシャリティマテリアルズ（半導体材料・電池材料等）とヘルスケアに経営資源を集中。産業ガス事業（大陽日酸）の安定収益を基盤に、高付加価値分野へのシフトを加速。",
      keyPoints: ["石化・炭素事業の分離・再編", "スペシャリティマテリアルズへの集中", "産業ガス（大陽日酸）の安定成長", "ヘルスケア事業の強化"],
      target: "2026年3月期 コア営業利益3,000億円を目標",
    },
    strengths: [
      "MMAモノマーで世界シェア首位",
      "産業ガス（大陽日酸）の安定収益基盤",
      "半導体材料・電池材料など高付加価値素材の技術力",
      "国内最大の化学メーカーとしてのスケールメリット",
    ],
    challenges: [
      "石化・炭素事業の構造改革の進捗",
      "有利子負債の高水準（D/Eレシオの改善）",
      "ポートフォリオ再編に伴う一時的なコスト負担",
      "中国の化学品供給過剰による価格競争",
    ],
    latestNews: [
      { date: "2025-05-01", headline: "2025年3月期 純利益820億円で黒字転換" },
      { date: "2025-08-01", headline: "石化事業の分離に向けた検討開始を発表" },
      { date: "2025-11-01", headline: "半導体材料の増産に向け九州で新工場建設を決定" },
      { date: "2026-02-01", headline: "Q3累計純利益700億円、構造改革効果が顕在化" },
    ],
  },
  {
    slug: "sumitomo-chemical",
    name: "住友化学",
    nameEn: "Sumitomo Chemical Co., Ltd.",
    logo: "住",
    color: "#f59e0b",
    stockCode: "4005",
    overview:
      "石油化学・エネルギー機能材料・情報電子化学・健康農業関連・医薬品の5事業を展開する総合化学メーカー。子会社の住友ファーマ（旧・大日本住友製薬）の業績が全体に大きく影響。2025年3月期は住友ファーマの構造改革費用が重荷となり最終赤字が継続。",
    financials: {
      revenue: "2兆4,500億円",
      revenueYoy: "-3.5%",
      operatingProfit: "450億円",
      opMargin: "1.8%",
      keyMetric: "-450億円",
      keyMetricLabel: "純利益",
      keyMetricYoy: "赤字継続",
      fiscalYear: "2025年3月期",
    },
    pl: { revenue: "2兆4,500億円", cogs: "1兆8,200億円", grossProfit: "6,300億円", grossMargin: "25.7%", sga: "5,850億円", rd: "1,400億円", operatingProfit: "450億円", opMargin: "1.8%", netIncome: "-450億円", netMargin: "-1.8%", fiscalYear: "2025年3月期" },
    bs: { totalAssets: "3兆5,000億円", currentAssets: "1兆1,500億円", cash: "2,100億円", fixedAssets: "2兆3,500億円", totalLiab: "2兆3,500億円", currentLiab: "9,500億円", fixedLiab: "1兆4,000億円", interestBearingDebt: "1兆2,500億円", equity: "1兆1,500億円", equityRatio: "32.9%", fiscalYear: "2025年3月期" },
    cf: { operatingCF: "+1,200億円", investingCF: "-800億円", financingCF: "-500億円", freeCF: "+400億円", capex: "1,100億円", dividends: "200億円", fiscalYear: "2025年3月期" },
    strategy: {
      title: "成長戦略",
      summary: "住友ファーマの構造改革を最優先課題とし、医薬品事業の早期黒字化を目指す。化学事業ではエネルギー機能材料（リチウムイオン電池用セパレータ・正極材）と情報電子化学（半導体材料・ディスプレイ材料）を成長ドライバーに位置づけ。農薬事業のグローバル展開も強化。",
      keyPoints: ["住友ファーマの構造改革・黒字化", "エネルギー機能材料（LiB素材）", "情報電子化学（半導体・ディスプレイ）", "農薬事業のグローバル拡大"],
      target: "2027年3月期 コア営業利益1,500億円を目標",
    },
    strengths: [
      "農薬事業でグローバルに強いポジション",
      "情報電子化学（フォトレジスト等）の技術力",
      "エネルギー機能材料（LiB正極材・セパレータ）の成長ポテンシャル",
      "住友グループのネットワークと信用力",
    ],
    challenges: [
      "住友ファーマの赤字が連結業績を大きく毀損",
      "有利子負債の高水準と財務健全性の回復",
      "石油化学事業の構造的な低収益",
      "医薬品パイプラインの開発リスク",
    ],
    latestNews: [
      { date: "2025-05-01", headline: "2025年3月期 最終赤字450億円、住友ファーマの改革費用が重荷" },
      { date: "2025-09-01", headline: "住友ファーマが北米事業の大幅縮小を発表" },
      { date: "2025-12-01", headline: "LiB正極材の増産に向けた設備投資を決定" },
      { date: "2026-02-01", headline: "Q3累計で最終赤字縮小、化学事業の回復が寄与" },
    ],
  },
];
