// =====================================================
// 2026年4月5日時点のデータ
// 衆議院: 2026年2月8日 第51回衆院選後
// 参議院: 2025年7月20日 第27回参院選後
// 内閣: 第2次高市内閣（2026年2月18日発足・全閣僚再任）
// =====================================================

export interface PartySeats {
  name: string;
  nameEn: string;
  seats: number;
  color: string;
}

export interface CabinetMember {
  position: string;
  positionEn: string;
  name: string;
  nameEn: string;
  party: string;
  note?: string;
}

export interface Legislator {
  name: string;
  nameEn: string;
  party: string;
  role: string;
  chamber: "house" | "council";
  x?: string;
  website?: string;
}

export interface RankedLegislator {
  rank: number;
  name: string;
  nameEn: string;
  party: string;
  partyColor: string;
  role: string;
  chamber: "house" | "council";
  score: number;
  metrics: {
    legislation: number;
    socialMedia: number;
    mediaPresence: number;
    committee: number;
  };
  x?: string;
  website?: string;
}

// 衆議院（定数465）— 2026年2月8日 第51回衆院選後
export const houseOfRepresentatives: PartySeats[] = [
  { name: "自由民主党", nameEn: "LDP", seats: 316, color: "#3CA324" },
  { name: "中道改革連合", nameEn: "Chudo", seats: 49, color: "#0073BD" },
  { name: "日本維新の会", nameEn: "Nippon Ishin", seats: 36, color: "#6FBA2C" },
  { name: "国民民主党", nameEn: "DPP", seats: 28, color: "#F8BC00" },
  { name: "参政党", nameEn: "Sanseito", seats: 15, color: "#D85D0F" },
  { name: "チームみらい", nameEn: "Team Mirai", seats: 11, color: "#66FFCC" },
  { name: "日本共産党", nameEn: "JCP", seats: 4, color: "#DB001C" },
  { name: "れいわ新選組", nameEn: "Reiwa", seats: 1, color: "#E4027E" },
  { name: "減税日本・ゆうこく連合", nameEn: "Genzei/Yukoku", seats: 1, color: "#999999" },
  { name: "無所属・その他", nameEn: "Others / Ind.", seats: 4, color: "#cccccc" },
];

export const HOUSE_TOTAL = 465;

// 参議院（定数248）— 2025年7月20日 第27回参院選後
// ※立憲民主党と公明党は参議院では合流せず別会派のまま
export const houseOfCouncillors: PartySeats[] = [
  { name: "自由民主党", nameEn: "LDP", seats: 101, color: "#3CA324" },
  { name: "立憲民主・社民・無所属", nameEn: "CDP+SDP", seats: 43, color: "#184589" },
  { name: "国民民主党・新緑風会", nameEn: "DPP", seats: 25, color: "#F8BC00" },
  { name: "公明党", nameEn: "Komeito", seats: 21, color: "#F55881" },
  { name: "日本維新の会", nameEn: "Nippon Ishin", seats: 19, color: "#6FBA2C" },
  { name: "参政党", nameEn: "Sanseito", seats: 15, color: "#D85D0F" },
  { name: "日本共産党", nameEn: "JCP", seats: 7, color: "#DB001C" },
  { name: "れいわ新選組", nameEn: "Reiwa", seats: 6, color: "#E4027E" },
  { name: "日本保守党", nameEn: "Japan Conservative", seats: 2, color: "#1a4a7a" },
  { name: "沖縄の風", nameEn: "Okinawa Whirlwind", seats: 2, color: "#00a5bf" },
  { name: "無所属", nameEn: "Independents", seats: 7, color: "#999999" },
];

export const COUNCIL_TOTAL = 248;

// 第2次高市内閣（2026年2月18日発足・第1次から全閣僚再任）
export const cabinet: CabinetMember[] = [
  { position: "内閣総理大臣", positionEn: "Prime Minister", name: "高市 早苗", nameEn: "Takaichi Sanae", party: "自由民主党", note: "史上初の女性首相" },
  { position: "内閣官房長官", positionEn: "Chief Cabinet Secretary", name: "木原 稔", nameEn: "Kihara Minoru", party: "自由民主党" },
  { position: "総務大臣", positionEn: "Internal Affairs", name: "林 芳正", nameEn: "Hayashi Yoshimasa", party: "自由民主党" },
  { position: "法務大臣", positionEn: "Justice", name: "平口 洋", nameEn: "Hiraguchi Hiroshi", party: "自由民主党" },
  { position: "外務大臣", positionEn: "Foreign Affairs", name: "茂木 敏充", nameEn: "Motegi Toshimitsu", party: "自由民主党" },
  { position: "財務大臣", positionEn: "Finance", name: "片山 さつき", nameEn: "Katayama Satsuki", party: "自由民主党" },
  { position: "文部科学大臣", positionEn: "Education", name: "松本 洋平", nameEn: "Matsumoto Yohei", party: "自由民主党" },
  { position: "厚生労働大臣", positionEn: "Health, Labour", name: "上野 賢一郎", nameEn: "Ueno Kenichiro", party: "自由民主党" },
  { position: "農林水産大臣", positionEn: "Agriculture", name: "鈴木 憲和", nameEn: "Suzuki Norikazu", party: "自由民主党" },
  { position: "経済産業大臣", positionEn: "Economy, Trade", name: "赤澤 亮正", nameEn: "Akazawa Ryosei", party: "自由民主党" },
  { position: "国土交通大臣", positionEn: "Land, Transport", name: "金子 恭之", nameEn: "Kaneko Yasushi", party: "自由民主党" },
  { position: "環境大臣", positionEn: "Environment", name: "石原 宏高", nameEn: "Ishihara Hirotaka", party: "自由民主党" },
  { position: "防衛大臣", positionEn: "Defense", name: "小泉 進次郎", nameEn: "Koizumi Shinjiro", party: "自由民主党" },
  { position: "デジタル大臣", positionEn: "Digital", name: "松本 尚", nameEn: "Matsumoto Takashi", party: "自由民主党" },
  { position: "復興大臣", positionEn: "Reconstruction", name: "牧野 たかお", nameEn: "Makino Takao", party: "自由民主党" },
  { position: "国家公安委員長", positionEn: "National Public Safety", name: "赤間 二郎", nameEn: "Akama Jiro", party: "自由民主党" },
  { position: "こども政策担当大臣", positionEn: "Children's Policy", name: "黄川田 仁志", nameEn: "Kikawada Hitoshi", party: "自由民主党" },
  { position: "経済財政政策担当大臣", positionEn: "Economic & Fiscal Policy", name: "城内 実", nameEn: "Kiuchi Minoru", party: "自由民主党" },
  { position: "経済安全保障担当大臣", positionEn: "Economic Security", name: "小野田 紀美", nameEn: "Onoda Kimi", party: "自由民主党" },
];

// 議員活動ランキング Top 5
// 国会質疑・法案提出・委員会出席・SNS発信力・メディア露出を総合評価
export const legislatorRankingTop: RankedLegislator[] = [
  { rank: 1, name: "小泉 進次郎", nameEn: "Koizumi Shinjiro", party: "自由民主党", partyColor: "#3CA324", role: "防衛大臣", chamber: "house", score: 94, metrics: { legislation: 88, socialMedia: 95, mediaPresence: 98, committee: 90 }, x: "https://x.com/shinjirokoiz", website: "https://shinjiro.info/" },
  { rank: 2, name: "玉木 雄一郎", nameEn: "Tamaki Yuichiro", party: "国民民主党", partyColor: "#F8BC00", role: "代表", chamber: "house", score: 92, metrics: { legislation: 90, socialMedia: 96, mediaPresence: 90, committee: 88 }, x: "https://x.com/tamakiyuichiro", website: "https://tamakinet.jp/" },
  { rank: 3, name: "高市 早苗", nameEn: "Takaichi Sanae", party: "自由民主党", partyColor: "#3CA324", role: "総裁（内閣総理大臣）", chamber: "house", score: 89, metrics: { legislation: 82, socialMedia: 92, mediaPresence: 97, committee: 80 }, x: "https://x.com/takaichi_sanae", website: "https://www.sanae.gr.jp/" },
  { rank: 4, name: "安野 貴博", nameEn: "Anno Takahiro", party: "チームみらい", partyColor: "#66FFCC", role: "代表", chamber: "council", score: 87, metrics: { legislation: 78, socialMedia: 97, mediaPresence: 90, committee: 72 }, x: "https://x.com/takahiroanno", website: "https://team-mir.ai/" },
  { rank: 5, name: "斎藤 アレックス", nameEn: "Saito Alex", party: "日本維新の会", partyColor: "#6FBA2C", role: "政調会長", chamber: "house", score: 85, metrics: { legislation: 80, socialMedia: 88, mediaPresence: 82, committee: 84 }, x: "https://x.com/saito_alex1", website: "https://saito-alex.jp/" },
];

// 議員活動ランキング Bottom 5
// 国会質疑・法案提出・委員会出席・SNS発信力・メディア露出が相対的に低い議員
// ※大臣・党役職者は質問側に立たないため、質疑回数が低くなる傾向がある点に留意
export const legislatorRankingBottom: RankedLegislator[] = [
  { rank: 1, name: "三原 じゅん子", nameEn: "Mihara Junko", party: "自由民主党", partyColor: "#3CA324", role: "参議院議員", chamber: "council", score: 18, metrics: { legislation: 5, socialMedia: 30, mediaPresence: 25, committee: 12 } },
  { rank: 2, name: "近藤 昭一", nameEn: "Kondo Shoichi", party: "中道改革連合", partyColor: "#0073BD", role: "衆議院議員", chamber: "house", score: 20, metrics: { legislation: 10, socialMedia: 15, mediaPresence: 18, committee: 35 } },
  { rank: 3, name: "浅田 均", nameEn: "Asada Hitoshi", party: "日本維新の会", partyColor: "#6FBA2C", role: "参議院議員", chamber: "council", score: 22, metrics: { legislation: 12, socialMedia: 10, mediaPresence: 15, committee: 48 } },
  { rank: 4, name: "舟山 康江", nameEn: "Funayama Yasue", party: "国民民主党", partyColor: "#F8BC00", role: "参議院議員", chamber: "council", score: 25, metrics: { legislation: 18, socialMedia: 8, mediaPresence: 12, committee: 55 } },
  { rank: 5, name: "井上 哲士", nameEn: "Inoue Satoshi", party: "日本共産党", partyColor: "#DB001C", role: "参議院議員", chamber: "council", score: 27, metrics: { legislation: 22, socialMedia: 12, mediaPresence: 15, committee: 52 } },
];

// 全議員データ（政党別・衆参別）
export const legislators: Legislator[] = [
  // ━━━━━━━━━━ 自由民主党 — 衆議院 ━━━━━━━━━━
  { name: "高市 早苗", nameEn: "Takaichi Sanae", party: "自由民主党", role: "総裁（内閣総理大臣）", chamber: "house", x: "https://x.com/takaichi_sanae", website: "https://www.sanae.gr.jp/" },
  { name: "茂木 敏充", nameEn: "Motegi Toshimitsu", party: "自由民主党", role: "外務大臣", chamber: "house", x: "https://x.com/moteging", website: "https://www.motegi.gr.jp/" },
  { name: "小泉 進次郎", nameEn: "Koizumi Shinjiro", party: "自由民主党", role: "防衛大臣", chamber: "house", x: "https://x.com/shinjirokoiz", website: "https://shinjiro.info/" },
  { name: "片山 さつき", nameEn: "Katayama Satsuki", party: "自由民主党", role: "財務大臣", chamber: "house", x: "https://x.com/katayama_s", website: "https://www.satsuki-katayama.com/" },
  { name: "林 芳正", nameEn: "Hayashi Yoshimasa", party: "自由民主党", role: "総務大臣", chamber: "house", x: "https://x.com/office_yosimasa", website: "https://www.yoshimasa.com/" },
  { name: "木原 稔", nameEn: "Kihara Minoru", party: "自由民主党", role: "内閣官房長官", chamber: "house", x: "https://x.com/kihara_minoru" },
  { name: "赤澤 亮正", nameEn: "Akazawa Ryosei", party: "自由民主党", role: "経済産業大臣", chamber: "house", website: "https://www.akazawa-ryosei.jp/" },
  { name: "松本 洋平", nameEn: "Matsumoto Yohei", party: "自由民主党", role: "文部科学大臣", chamber: "house", x: "https://x.com/matsumoto_yohei", website: "https://matsumoto-yohei.com/" },
  { name: "上野 賢一郎", nameEn: "Ueno Kenichiro", party: "自由民主党", role: "厚生労働大臣", chamber: "house", x: "https://x.com/Ueno_Kenichiro", website: "https://www.uenokenichiro.jp/" },
  { name: "鈴木 憲和", nameEn: "Suzuki Norikazu", party: "自由民主党", role: "農林水産大臣", chamber: "house", x: "https://x.com/norikazu_0130", website: "https://suzuki-norikazu.com/" },
  { name: "金子 恭之", nameEn: "Kaneko Yasushi", party: "自由民主党", role: "国土交通大臣", chamber: "house", x: "https://x.com/nekotanchan" },
  { name: "石原 宏高", nameEn: "Ishihara Hirotaka", party: "自由民主党", role: "環境大臣", chamber: "house", x: "https://x.com/ishiharahirotak", website: "https://www.ishihara-hirotaka.com/" },
  { name: "平口 洋", nameEn: "Hiraguchi Hiroshi", party: "自由民主党", role: "法務大臣", chamber: "house", x: "https://x.com/hiraguchi0801", website: "https://www.hiraguchi.com/" },
  { name: "松本 尚", nameEn: "Matsumoto Hisashi", party: "自由民主党", role: "デジタル大臣", chamber: "house", x: "https://x.com/hmatsu63", website: "https://www.matsumotohisashi.com/" },
  { name: "赤間 二郎", nameEn: "Akama Jiro", party: "自由民主党", role: "国家公安委員長", chamber: "house", x: "https://x.com/jiroakama0327", website: "https://www.akama.jp/" },
  { name: "黄川田 仁志", nameEn: "Kikawada Hitoshi", party: "自由民主党", role: "こども政策担当大臣", chamber: "house", x: "https://x.com/kikawadahitoshi", website: "https://www.kikawadahitoshi.jp/" },
  { name: "城内 実", nameEn: "Kiuchi Minoru", party: "自由民主党", role: "経済財政政策担当大臣", chamber: "house", x: "https://x.com/minoru_kiuchi", website: "https://m-kiuchi.com/" },
  { name: "麻生 太郎", nameEn: "Aso Taro", party: "自由民主党", role: "副総裁", chamber: "house", website: "https://www.aso-taro.jp/" },
  { name: "鈴木 俊一", nameEn: "Suzuki Shunichi", party: "自由民主党", role: "幹事長", chamber: "house", x: "https://x.com/SuzukiShunichi", website: "https://suzukishunichi.jp/" },
  { name: "小林 鷹之", nameEn: "Kobayashi Takayuki", party: "自由民主党", role: "政調会長", chamber: "house", x: "https://x.com/kobahawk", website: "https://kobayashi-takayuki.jp/" },
  { name: "萩生田 光一", nameEn: "Hagiuda Koichi", party: "自由民主党", role: "幹事長代行", chamber: "house", x: "https://x.com/officeofhagiuda", website: "https://www.ko-1.jp/" },
  { name: "河野 太郎", nameEn: "Kono Taro", party: "自由民主党", role: "国際局長", chamber: "house", x: "https://x.com/konotarogomame", website: "https://www.taro.org/" },
  { name: "西村 康稔", nameEn: "Nishimura Yasutoshi", party: "自由民主党", role: "選挙対策委員長", chamber: "house", x: "https://x.com/nishy03", website: "https://www.yasutoshi.jp/" },
  { name: "梶山 弘志", nameEn: "Kajiyama Hiroshi", party: "自由民主党", role: "国対委員長", chamber: "house", x: "https://x.com/kajiyamahiroshi", website: "https://kajiyama-office.com/" },
  { name: "加藤 勝信", nameEn: "Kato Katsunobu", party: "自由民主党", role: "衆議院議員", chamber: "house", x: "https://x.com/KatsunobuKato1" },
  // ━━━━━━━━━━ 自由民主党 — 参議院 ━━━━━━━━━━
  { name: "小野田 紀美", nameEn: "Onoda Kimi", party: "自由民主党", role: "経済安全保障担当大臣", chamber: "council", x: "https://x.com/onoda_kimi", website: "https://onoda-kimi.com/" },
  { name: "牧野 たかお", nameEn: "Makino Takao", party: "自由民主党", role: "復興大臣", chamber: "council", x: "https://x.com/makinotakao", website: "https://makino-net.com/" },
  { name: "佐藤 正久", nameEn: "Sato Masahisa", party: "自由民主党", role: "外交部会長", chamber: "council", x: "https://x.com/SatoMasahisa", website: "https://hige-sato.jp/" },
  { name: "青山 繁晴", nameEn: "Aoyama Shigeharu", party: "自由民主党", role: "参議院議員", chamber: "council", x: "https://x.com/aoyamashigeharu" },
  { name: "有村 治子", nameEn: "Arimura Haruko", party: "自由民主党", role: "総務会長", chamber: "council", x: "https://x.com/Arimura_haruko", website: "https://arimura.tv/" },
  { name: "三原 じゅん子", nameEn: "Mihara Junko", party: "自由民主党", role: "参議院議員", chamber: "council" },

  // ━━━━━━━━━━ 中道改革連合 — 衆議院（49議席：小選挙区7・比例42）━━━━━━━━━━
  // ※野田佳彦・斉藤鉄夫の共同代表体制→惨敗→代表選→小川淳也が新代表(2/13)
  // ※枝野幸男・安住淳・小沢一郎・岡田克也ら立憲系大物は軒並み落選
  { name: "小川 淳也", nameEn: "Ogawa Junya", party: "中道改革連合", role: "代表", chamber: "house", x: "https://x.com/junyaog", website: "https://www.ogawajunya.com/" },
  { name: "野田 佳彦", nameEn: "Noda Yoshihiko", party: "中道改革連合", role: "最高顧問", chamber: "house", x: "https://x.com/nodayoshi55", website: "https://www.nodayoshi.gr.jp/" },
  { name: "階 猛", nameEn: "Shina Takeshi", party: "中道改革連合", role: "幹事長", chamber: "house", x: "https://x.com/shinatakeshi" },
  { name: "岡本 三成", nameEn: "Okamoto Mitsunari", party: "中道改革連合", role: "政調会長（元公明）", chamber: "house" },
  { name: "泉 健太", nameEn: "Izumi Kenta", party: "中道改革連合", role: "衆議院議員", chamber: "house", x: "https://x.com/izmkenta", website: "https://izumi-kenta.net/" },
  { name: "長妻 昭", nameEn: "Nagatsuma Akira", party: "中道改革連合", role: "衆議院議員", chamber: "house", x: "https://x.com/nagatsumaakira", website: "https://naga.tv/" },
  { name: "逢坂 誠二", nameEn: "Osaka Seiji", party: "中道改革連合", role: "衆議院議員", chamber: "house", x: "https://x.com/seiji_ohsaka" },
  { name: "近藤 昭一", nameEn: "Kondo Shoichi", party: "中道改革連合", role: "衆議院議員", chamber: "house" },
  { name: "渡辺 創", nameEn: "Watanabe So", party: "中道改革連合", role: "衆議院議員", chamber: "house" },
  { name: "野間 健", nameEn: "Noma Takeshi", party: "中道改革連合", role: "衆議院議員", chamber: "house" },
  { name: "山岡 達丸", nameEn: "Yamaoka Tatsumaru", party: "中道改革連合", role: "衆議院議員", chamber: "house" },
  { name: "金子 恵美", nameEn: "Kaneko Emi", party: "中道改革連合", role: "衆議院議員", chamber: "house" },
  { name: "大島 敦", nameEn: "Oshima Atsushi", party: "中道改革連合", role: "衆議院議員", chamber: "house" },
  { name: "田嶋 要", nameEn: "Tajima Kaname", party: "中道改革連合", role: "衆議院議員", chamber: "house" },
  { name: "笠 浩史", nameEn: "Ryu Hiroshi", party: "中道改革連合", role: "衆議院議員", chamber: "house" },
  { name: "後藤 祐一", nameEn: "Goto Yuichi", party: "中道改革連合", role: "衆議院議員", chamber: "house" },
  { name: "有田 芳生", nameEn: "Arita Yoshifu", party: "中道改革連合", role: "衆議院議員", chamber: "house" },
  // ※石井啓一は衆議院副議長に選出（リスト末尾に記載）
  { name: "北側 一雄", nameEn: "Kitagawa Kazuo", party: "中道改革連合", role: "衆議院議員（元公明副代表）", chamber: "house" },
  { name: "浮島 智子", nameEn: "Ukishima Tomoko", party: "中道改革連合", role: "衆議院議員（元公明）", chamber: "house" },
  { name: "佐藤 英道", nameEn: "Sato Hidemichi", party: "中道改革連合", role: "衆議院議員（元公明）", chamber: "house" },
  { name: "庄子 賢一", nameEn: "Shoji Kenichi", party: "中道改革連合", role: "衆議院議員（元公明）", chamber: "house" },
  { name: "輿水 恵一", nameEn: "Koshimizu Keiichi", party: "中道改革連合", role: "衆議院議員（元公明）", chamber: "house" },
  { name: "福重 隆浩", nameEn: "Fukushige Takahiro", party: "中道改革連合", role: "衆議院議員（元公明）", chamber: "house" },
  { name: "角田 秀穂", nameEn: "Tsunoda Hideho", party: "中道改革連合", role: "衆議院議員（元公明）", chamber: "house" },
  // ━━━━━━━━━━ 中道改革連合 — 参議院 ━━━━━━━━━━
  { name: "山口 那津男", nameEn: "Yamaguchi Natsuo", party: "中道改革連合", role: "副代表", chamber: "council", website: "https://www.n-yamaguchi.gr.jp/" },
  { name: "蓮舫", nameEn: "Renho", party: "中道改革連合", role: "参議院議員", chamber: "council", x: "https://x.com/renho_sha", website: "https://renho.jp/" },
  { name: "福山 哲郎", nameEn: "Fukuyama Tetsuro", party: "中道改革連合", role: "参議院議員", chamber: "council", x: "https://x.com/faborecord" },
  { name: "杉尾 秀哉", nameEn: "Sugio Hideya", party: "中道改革連合", role: "参議院議員", chamber: "council", x: "https://x.com/suaborecord" },
  { name: "竹谷 とし子", nameEn: "Takeya Toshiko", party: "中道改革連合", role: "参議院議員（元公明）", chamber: "council" },

  // ━━━━━━━━━━ 日本維新の会 — 衆議院 ━━━━━━━━━━
  { name: "馬場 伸幸", nameEn: "Baba Nobuyuki", party: "日本維新の会", role: "代表", chamber: "house", x: "https://x.com/baba_ishin", website: "https://www.baba-nobuyuki.com/" },
  { name: "藤田 文武", nameEn: "Fujita Fumitake", party: "日本維新の会", role: "幹事長", chamber: "house", x: "https://x.com/fumi_fuji" },
  { name: "足立 康史", nameEn: "Adachi Yasushi", party: "日本維新の会", role: "衆議院議員", chamber: "house", x: "https://x.com/adachiyasushi", website: "https://adachi-yasushi.jp/" },
  { name: "池下 卓", nameEn: "Ikeshita Taku", party: "日本維新の会", role: "衆議院議員", chamber: "house", x: "https://x.com/ikeshita_taku" },
  { name: "青柳 仁士", nameEn: "Aoyagi Hitoshi", party: "日本維新の会", role: "衆議院議員", chamber: "house", x: "https://x.com/aoyagihitoshi" },
  { name: "遠藤 敬", nameEn: "Endo Takashi", party: "日本維新の会", role: "国対委員長", chamber: "house", x: "https://x.com/endotakashi01" },
  // ━━━━━━━━━━ 日本維新の会 — 参議院 ━━━━━━━━━━
  { name: "梅村 みずほ", nameEn: "Umemura Mizuho", party: "日本維新の会", role: "参議院議員", chamber: "council", x: "https://x.com/umemura_mizuho" },
  { name: "柳ヶ瀬 裕文", nameEn: "Yanagase Hirofumi", party: "日本維新の会", role: "参議院議員", chamber: "council", x: "https://x.com/yanagase_urfm" },
  { name: "浅田 均", nameEn: "Asada Hitoshi", party: "日本維新の会", role: "参議院議員", chamber: "council" },

  // ━━━━━━━━━━ 国民民主党 — 衆議院 ━━━━━━━━━━
  { name: "玉木 雄一郎", nameEn: "Tamaki Yuichiro", party: "国民民主党", role: "代表", chamber: "house", x: "https://x.com/tamakiyuichiro", website: "https://tamakinet.jp/" },
  { name: "前原 誠司", nameEn: "Maehara Seiji", party: "国民民主党", role: "代表代行", chamber: "house", x: "https://x.com/Maehara2016", website: "https://www.maehara21.com/" },
  { name: "古川 元久", nameEn: "Furukawa Motohisa", party: "国民民主党", role: "衆議院議員", chamber: "house", website: "https://furukawa.cc/" },
  { name: "田中 健", nameEn: "Tanaka Ken", party: "国民民主党", role: "衆議院議員", chamber: "house" },
  { name: "浅野 哲", nameEn: "Asano Satoshi", party: "国民民主党", role: "衆議院議員", chamber: "house", x: "https://x.com/asano_satoshi_" },
  { name: "鈴木 敦", nameEn: "Suzuki Atsushi", party: "国民民主党", role: "衆議院議員", chamber: "house" },
  // ━━━━━━━━━━ 国民民主党 — 参議院 ━━━━━━━━━━
  { name: "榛葉 賀津也", nameEn: "Shimba Kazuya", party: "国民民主党", role: "幹事長", chamber: "council", x: "https://x.com/SHIMBA_OFFICE" },
  { name: "伊藤 孝恵", nameEn: "Ito Takae", party: "国民民主党", role: "参議院議員", chamber: "council", x: "https://x.com/itotakae", website: "https://itotakae.jp/" },
  { name: "大塚 耕平", nameEn: "Otsuka Kohei", party: "国民民主党", role: "参議院議員", chamber: "council", x: "https://x.com/koheiotsuka" },
  { name: "舟山 康江", nameEn: "Funayama Yasue", party: "国民民主党", role: "参議院議員", chamber: "council" },

  // ━━━━━━━━━━ 参政党 — 衆議院（15議席：全員比例当選）━━━━━━━━━━
  { name: "和田 政宗", nameEn: "Wada Masamune", party: "参政党", role: "衆議院議員（東北）", chamber: "house" },
  { name: "豊田 真由子", nameEn: "Toyoda Mayuko", party: "参政党", role: "衆議院議員（北関東）", chamber: "house" },
  { name: "青木 ひとみ", nameEn: "Aoki Hitomi", party: "参政党", role: "衆議院議員（北関東）", chamber: "house" },
  { name: "中谷 めぐ", nameEn: "Nakatani Megu", party: "参政党", role: "衆議院議員（南関東）", chamber: "house" },
  { name: "工藤 聖子", nameEn: "Kudo Seiko", party: "参政党", role: "衆議院議員（南関東）", chamber: "house" },
  { name: "吉川 里奈", nameEn: "Yoshikawa Rina", party: "参政党", role: "副代表（東京）", chamber: "house", x: "https://x.com/rina_yoshikawa_", website: "https://yoshikawa-rina.jp/" },
  { name: "鈴木 美香", nameEn: "Suzuki Mika", party: "参政党", role: "衆議院議員（東京）", chamber: "house" },
  { name: "川 裕一郎", nameEn: "Kawa Yuichiro", party: "参政党", role: "衆議院議員（北陸信越）", chamber: "house" },
  { name: "渡辺 藍理", nameEn: "Watanabe Airi", party: "参政党", role: "衆議院議員（東海）", chamber: "house" },
  { name: "伊藤 恵介", nameEn: "Ito Keisuke", party: "参政党", role: "衆議院議員（東海）", chamber: "house" },
  { name: "石川 勝", nameEn: "Ishikawa Masaru", party: "参政党", role: "衆議院議員（近畿）", chamber: "house" },
  { name: "谷 浩一郎", nameEn: "Tani Koichiro", party: "参政党", role: "衆議院議員（近畿）", chamber: "house" },
  { name: "島村 薫", nameEn: "Shimamura Kaoru", party: "参政党", role: "衆議院議員（中国）", chamber: "house" },
  { name: "木下 敏之", nameEn: "Kinoshita Toshiyuki", party: "参政党", role: "衆議院議員（九州）", chamber: "house" },
  { name: "牧野 俊一", nameEn: "Makino Shunichi", party: "参政党", role: "衆議院議員（九州）", chamber: "house" },
  // ━━━━━━━━━━ 参政党 — 参議院 ━━━━━━━━━━
  { name: "神谷 宗幣", nameEn: "Kamiya Sohei", party: "参政党", role: "代表", chamber: "council", x: "https://x.com/jinkamiya", website: "https://www.kamiyasohei.jp/" },
  { name: "松田 学", nameEn: "Matsuda Manabu", party: "参政党", role: "代表代行", chamber: "council", x: "https://x.com/matsudamanabu" },
  { name: "赤尾 由美", nameEn: "Akao Yumi", party: "参政党", role: "参議院議員", chamber: "council" },

  // ━━━━━━━━━━ チームみらい — 衆議院（11議席：全員比例当選）━━━━━━━━━━
  // ※安野貴博代表は参議院議員（2025年参院選比例で当選）
  { name: "高山 聡史", nameEn: "Takayama Satoshi", party: "チームみらい", role: "幹事長（東京）", chamber: "house" },
  { name: "宇佐美 登", nameEn: "Usami Noboru", party: "チームみらい", role: "衆議院議員", chamber: "house" },
  { name: "峯島 侑也", nameEn: "Mineshima Yuya", party: "チームみらい", role: "衆議院議員", chamber: "house" },
  { name: "土橋 明宏", nameEn: "Dobashi Akihiro", party: "チームみらい", role: "衆議院議員", chamber: "house" },
  { name: "林 匠実", nameEn: "Hayashi Takumi", party: "チームみらい", role: "衆議院議員", chamber: "house" },
  { name: "武藤 和子", nameEn: "Muto Kazuko", party: "チームみらい", role: "衆議院議員", chamber: "house" },
  { name: "河合 道夫", nameEn: "Kawai Michio", party: "チームみらい", role: "衆議院議員", chamber: "house" },
  { name: "山田 えり", nameEn: "Yamada Eri", party: "チームみらい", role: "衆議院議員", chamber: "house" },
  { name: "小林 周平", nameEn: "Kobayashi Shuhei", party: "チームみらい", role: "衆議院議員", chamber: "house" },
  { name: "須田 英太郎", nameEn: "Suda Eitaro", party: "チームみらい", role: "衆議院議員", chamber: "house" },
  { name: "古川 蒼", nameEn: "Furukawa Aoi", party: "チームみらい", role: "衆議院議員", chamber: "house" },

  // ━━━━━━━━━━ 日本共産党 — 衆議院（4議席：全員比例）━━━━━━━━━━
  // ※志位和夫は2026年1月に不出馬表明。議長職は続投。
  { name: "田村 智子", nameEn: "Tamura Tomoko", party: "日本共産党", role: "委員長", chamber: "house", x: "https://x.com/tamutomojcp", website: "https://www.tamura-jcp.info/" },
  { name: "塩川 鉄也", nameEn: "Shiokawa Tetsuya", party: "日本共産党", role: "衆議院議員（10期）", chamber: "house", x: "https://x.com/ShiokawaTetsuya" },
  { name: "はたの 君枝", nameEn: "Hatano Kimie", party: "日本共産党", role: "衆議院議員（3期）", chamber: "house" },
  { name: "辰巳 孝太郎", nameEn: "Tatsumi Kotaro", party: "日本共産党", role: "衆議院議員（2期）", chamber: "house" },
  // ━━━━━━━━━━ 日本共産党 — 参議院 ━━━━━━━━━━
  { name: "小池 晃", nameEn: "Koike Akira", party: "日本共産党", role: "書記局長", chamber: "council", x: "https://x.com/koike_akira", website: "https://www.koike-akira.jp/" },
  { name: "山添 拓", nameEn: "Yamazoe Taku", party: "日本共産党", role: "政策委員長", chamber: "council", x: "https://x.com/yamazoe_taku" },
  { name: "吉良 よし子", nameEn: "Kira Yoshiko", party: "日本共産党", role: "参議院議員", chamber: "council", website: "https://kirayoshiko.com/" },
  { name: "井上 哲士", nameEn: "Inoue Satoshi", party: "日本共産党", role: "参議院議員", chamber: "council" },
  { name: "仁比 聡平", nameEn: "Nihi Sohei", party: "日本共産党", role: "参議院議員", chamber: "council" },
  { name: "大門 実紀史", nameEn: "Daimon Mikishi", party: "日本共産党", role: "参議院議員", chamber: "council" },
  { name: "紙 智子", nameEn: "Kami Tomoko", party: "日本共産党", role: "参議院議員", chamber: "council" },

  // ━━━━━━━━━━ れいわ新選組 — 衆議院（1議席）━━━━━━━━━━
  // ※櫛渕万里は小選挙区で落選。山本太郎は前参議院議員→代表専任。
  { name: "山本 ジョージ", nameEn: "Yamamoto George", party: "れいわ新選組", role: "幹事長・国対委員長", chamber: "house" },
  // ━━━━━━━━━━ れいわ新選組 — 参議院（5議席）━━━━━━━━━━
  // ※2026年2月16日新体制。山本太郎は代表だが現在議員ではない。
  { name: "奥田 ふみよ", nameEn: "Okuda Fumiyo", party: "れいわ新選組", role: "共同代表", chamber: "council" },
  { name: "木村 英子", nameEn: "Kimura Eiko", party: "れいわ新選組", role: "副代表", chamber: "council", x: "https://x.com/eikimurareiwa" },
  { name: "天畠 大輔", nameEn: "Amahata Daisuke", party: "れいわ新選組", role: "副代表", chamber: "council", x: "https://x.com/amahatadaisuke" },
  { name: "伊勢崎 賢治", nameEn: "Isezaki Kenji", party: "れいわ新選組", role: "副代表・参議院国対委員長", chamber: "council" },
  { name: "大島 九州男", nameEn: "Oshima Kusuo", party: "れいわ新選組", role: "幹事", chamber: "council" },

  // ━━━━━━━━━━ 減税日本・ゆうこく連合 — 衆議院（1議席）━━━━━━━━━━
  // ※原口一博は小選挙区で落選。河村たかしが愛知1区で当選。
  { name: "河村 たかし", nameEn: "Kawamura Takashi", party: "減税日本・ゆうこく連合", role: "共同代表", chamber: "house", x: "https://x.com/kawamura758" },

  // ━━━━━━━━━━ 日本保守党 — 参議院（2議席）━━━━━━━━━━
  { name: "百田 尚樹", nameEn: "Hyakuta Naoki", party: "日本保守党", role: "代表", chamber: "council" },
  { name: "北村 晴男", nameEn: "Kitamura Haruo", party: "日本保守党", role: "参議院議員", chamber: "council" },

  // ━━━━━━━━━━ 沖縄の風 — 参議院（2議席）━━━━━━━━━━
  { name: "伊波 洋一", nameEn: "Iha Yoichi", party: "沖縄の風", role: "幹事長", chamber: "council" },
  { name: "高良 沙哉", nameEn: "Takara Saya", party: "沖縄の風", role: "参議院議員", chamber: "council" },

  // ━━━━━━━━━━ チームみらい — 参議院（1議席）━━━━━━━━━━
  { name: "安野 貴博", nameEn: "Anno Takahiro", party: "チームみらい", role: "代表（参議院）", chamber: "council", x: "https://x.com/takahiroanno", website: "https://team-mir.ai/" },

  // ━━━━━━━━━━ 衆議院議長・副議長 ━━━━━━━━━━
  { name: "森 英介", nameEn: "Mori Eisuke", party: "自由民主党", role: "衆議院議長（第81代）", chamber: "house" },
  { name: "石井 啓一", nameEn: "Ishii Keiichi", party: "中道改革連合", role: "衆議院副議長", chamber: "house" },

  // ━━━━━━━━━━ 参議院議長・副議長 ━━━━━━━━━━
  { name: "関口 昌一", nameEn: "Sekiguchi Masakazu", party: "自由民主党", role: "参議院議長（第34代）", chamber: "council" },

  // ━━━━━━━━━━ 無所属 — 衆議院 ━━━━━━━━━━
  { name: "緒方 林太郎", nameEn: "Ogata Rintaro", party: "無所属", role: "衆議院議員（福岡9区）", chamber: "house" },

  // ━━━━━━━━━━ 追加議員データ ━━━━━━━━━━

  // ── 自由民主党 — 衆議院（追加210名）──
  { name: "菅 義偉", nameEn: "Suga Yoshihide", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "岸田 文雄", nameEn: "Kishida Fumio", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "甘利 明", nameEn: "Amari Akira", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "野田 聖子", nameEn: "Noda Seiko", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "二階 俊博", nameEn: "Nikai Toshihiro", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "石破 茂", nameEn: "Ishiba Shigeru", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "小渕 優子", nameEn: "Obuchi Yuko", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "根本 匠", nameEn: "Nemoto Takumi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "田村 憲久", nameEn: "Tamura Norihisa", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "松野 博一", nameEn: "Matsuno Hiroichi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "後藤 茂之", nameEn: "Goto Shigeyuki", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "山際 大志郎", nameEn: "Yamagiwa Daishiro", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "福田 達夫", nameEn: "Fukuda Tatsuo", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "松島 みどり", nameEn: "Matsushima Midori", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "平沢 勝栄", nameEn: "Hirasawa Katsuei", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "古屋 圭司", nameEn: "Furuya Keiji", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "額賀 福志郎", nameEn: "Nukaga Fukushiro", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "中谷 元", nameEn: "Nakatani Gen", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "伊藤 達也", nameEn: "Ito Tatsuya", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "宮下 一郎", nameEn: "Miyashita Ichiro", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "盛山 正仁", nameEn: "Moriyama Masahito", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "武田 良太", nameEn: "Takeda Ryota", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "棚橋 泰文", nameEn: "Tanahashi Yasufumi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "上川 陽子", nameEn: "Kamikawa Yoko", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "柴山 昌彦", nameEn: "Shibayama Masahiko", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "渡辺 博道", nameEn: "Watanabe Hiromichi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "新藤 義孝", nameEn: "Shindo Yoshitaka", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "下村 博文", nameEn: "Shimomura Hakubun", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "高木 毅", nameEn: "Takagi Tsuyoshi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "平井 卓也", nameEn: "Hirai Takuya", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "牧原 秀樹", nameEn: "Makihara Hideki", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "橋本 岳", nameEn: "Hashimoto Gaku", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "関 芳弘", nameEn: "Seki Yoshihiro", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "長坂 康正", nameEn: "Nagasaka Yasumasa", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "石田 真敏", nameEn: "Ishida Masatoshi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "奥野 信亮", nameEn: "Okuno Shinsuke", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "土屋 品子", nameEn: "Tsuchiya Shinako", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "永岡 桂子", nameEn: "Nagaoka Keiko", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "工藤 彰三", nameEn: "Kudo Shozo", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "國場 幸之助", nameEn: "Kokuba Konosuke", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "佐藤 勉", nameEn: "Sato Tsutomu", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "伊藤 忠彦", nameEn: "Ito Tadahiko", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "高鳥 修一", nameEn: "Takatori Shuichi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "藤丸 敏", nameEn: "Fujimaru Satoshi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "小田原 潔", nameEn: "Odawara Kiyoshi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "山下 貴司", nameEn: "Yamashita Takashi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "今枝 宗一郎", nameEn: "Imaeda Soichiro", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "中曽根 康隆", nameEn: "Nakasone Yasutaka", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "塩崎 彰久", nameEn: "Shiozaki Akihisa", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "深澤 陽一", nameEn: "Fukazawa Yoichi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "金田 勝年", nameEn: "Kaneda Katsunen", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "津島 淳", nameEn: "Tsushima Jun", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "大野 敬太郎", nameEn: "Ono Keitaro", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "堀内 詔子", nameEn: "Horiuchi Noriko", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "義家 弘介", nameEn: "Yoshiie Hirosuke", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "阿部 俊子", nameEn: "Abe Toshiko", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "宮内 秀樹", nameEn: "Miyauchi Hideki", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "国光 あやの", nameEn: "Kunimitsu Ayano", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "山本 左近", nameEn: "Yamamoto Sakon", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "谷川 とむ", nameEn: "Tanigawa Tomu", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "中村 裕之", nameEn: "Nakamura Hiroyuki", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "船橋 利実", nameEn: "Funahashi Toshimi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "和田 義明", nameEn: "Wada Yoshiaki", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "渡辺 孝一", nameEn: "Watanabe Koichi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "鈴木 貴子", nameEn: "Suzuki Takako", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "堀井 学", nameEn: "Horii Manabu", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "武部 新", nameEn: "Takebe Arata", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "金子 俊平", nameEn: "Kaneko Shumpei", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "大岡 敏孝", nameEn: "Ooka Toshitaka", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "山田 賢司", nameEn: "Yamada Kenji", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "宮路 拓馬", nameEn: "Miyaji Takuma", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "木村 次郎", nameEn: "Kimura Jiro", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "御法川 信英", nameEn: "Minogawa Nobuhide", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "冨樫 博之", nameEn: "Togashi Hiroyuki", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "遠藤 利明", nameEn: "Endo Toshiaki", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "加藤 鮎子", nameEn: "Kato Ayuko", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "菅家 一郎", nameEn: "Kanke Ichiro", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "吉野 正芳", nameEn: "Yoshino Masayoshi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "牧島 かれん", nameEn: "Makishima Karen", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "小倉 將信", nameEn: "Ogura Masanobu", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "木原 誠二", nameEn: "Kihara Seiji", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "井上 信治", nameEn: "Inoue Shinji", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "松本 剛明", nameEn: "Matsumoto Takeaki", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "細田 健一", nameEn: "Hosoda Kenichi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "衛藤 征士郎", nameEn: "Eto Seishiro", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "斎藤 洋明", nameEn: "Saito Hiroaki", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "小林 史明", nameEn: "Kobayashi Fumiaki", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "村井 英樹", nameEn: "Murai Hideki", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "辻 清人", nameEn: "Tsuji Kiyoto", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "鳩山 二郎", nameEn: "Hatoyama Jiro", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "古川 禎久", nameEn: "Furukawa Yoshihisa", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "西銘 恒三郎", nameEn: "Nishime Kosaburo", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "宗清 皇一", nameEn: "Munekiyo Koichi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "鬼木 誠", nameEn: "Oniki Makoto", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "伊藤 信太郎", nameEn: "Ito Shintaro", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "若宮 健嗣", nameEn: "Wakamiya Kenji", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "あべ 俊子", nameEn: "Abe Toshiko2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "田中 良生", nameEn: "Tanaka Yoshio", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "田所 嘉徳", nameEn: "Tadokoro Yoshinori", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "鷲尾 英一郎", nameEn: "Washio Eiichiro", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "三ッ林 裕巳", nameEn: "Mitsubayashi Hiromi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "務台 俊介", nameEn: "Mutai Shunsuke", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "穂坂 泰", nameEn: "Hosaka Yasushi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "勝目 康", nameEn: "Katsume Yasushi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "井林 辰憲", nameEn: "Ibayashi Tatsunori", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "杉田 水脈", nameEn: "Sugita Mio", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "根本 幸典", nameEn: "Nemoto Yukinori", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "五十嵐 清", nameEn: "Igarashi Kiyoshi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "中川 郁子", nameEn: "Nakagawa Yuko", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "笹川 博義", nameEn: "Sasakawa Hiroyoshi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "若林 健太", nameEn: "Wakabayashi Kenta", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "西野 太亮", nameEn: "Nishino Taisuke", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "松本 文明", nameEn: "Matsumoto Fumiaki", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "大西 英男", nameEn: "Onishi Hideo", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "青山 周平", nameEn: "Aoyama Shuhei", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "石井 拓", nameEn: "Ishii Taku", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "岩田 和親", nameEn: "Iwata Kazuchika", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "神田 憲次", nameEn: "Kanda Kenji", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "簗 和生", nameEn: "Yana Kazuo", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "吉川 赳", nameEn: "Yoshikawa Takeru", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "吉田 真次", nameEn: "Yoshida Shinji", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "左藤 章", nameEn: "Sato Akira", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "山口 壯", nameEn: "Yamaguchi Tsuyoshi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "塩谷 立", nameEn: "Shionoya Ryu", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "原田 義昭", nameEn: "Harada Yoshiaki", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "江渡 聡徳", nameEn: "Eto Akinori", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "北村 誠吾", nameEn: "Kitamura Seigo", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "佐々木 紀", nameEn: "Sasaki Hajime", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "越智 隆雄", nameEn: "Ochi Takao", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "中根 一幸", nameEn: "Nakane Kazuyuki", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "国定 勇人", nameEn: "Kunisada Hayato", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "井出 庸生", nameEn: "Ide Yosei", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "福田 昭夫", nameEn: "Fukuda Akio", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "丹羽 秀樹", nameEn: "Niwa Hideki", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "秋葉 賢也", nameEn: "Akiba Kenya", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "土井 亨", nameEn: "Doi Toru", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "西村 明宏", nameEn: "Nishimura Akihiro", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "小野寺 五典", nameEn: "Onodera Itsunori", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "金子 万寿夫", nameEn: "Kaneko Masuo", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "宮崎 政久", nameEn: "Miyazaki Masahisa", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "松山 政司", nameEn: "Matsuyama Masaji", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "尾身 朝子", nameEn: "Omi Asako", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "今村 雅弘", nameEn: "Imamura Masahiro", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "保岡 宏武", nameEn: "Yasuoka Hirotake", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "加藤 竜祥", nameEn: "Kato Ryusho", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "赤羽 一嘉", nameEn: "Akaba Kazuyoshi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "大塚 拓", nameEn: "Otsuka Taku", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "山本 朋広", nameEn: "Yamamoto Tomohiro", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "中山 展宏", nameEn: "Nakayama Norihiro", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "古賀 篤", nameEn: "Koga Atsushi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "高木 啓", nameEn: "Takagi Kei", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "泉田 裕彦", nameEn: "Izumida Hirohiko", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "吉川 貴盛", nameEn: "Yoshikawa Takamori", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "葉梨 康弘", nameEn: "Hanashi Yasuhiro", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "石橋 林太郎", nameEn: "Ishibashi Rintaro", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "池田 佳隆", nameEn: "Ikeda Yoshitaka", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "上野 宏史", nameEn: "Ueno Hiroshi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "太田 房江", nameEn: "Ota Fusae", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "神谷 昇", nameEn: "Kamiya Noboru", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "柳本 顕", nameEn: "Yanagimoto Akira", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "本田 太郎", nameEn: "Honda Taro", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "繁本 護", nameEn: "Shigemoto Mamoru", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "出畑 実", nameEn: "Dehata Minoru", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "田畑 裕明", nameEn: "Tabata Hiroaki", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "佐藤 信秋", nameEn: "Sato Nobuaki", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "藤井 比早之", nameEn: "Fujii Hisayuki", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "谷 公一", nameEn: "Tani Koichi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "大串 正樹", nameEn: "Ogushi Masaki", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "山口 晋", nameEn: "Yamaguchi Susumu", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "勝俣 孝明", nameEn: "Katsumata Takaaki", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "城内 実", nameEn: "Kiuchi Minoru2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "塩崎 恭久", nameEn: "Shiozaki Yasuhisa", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "稲田 朋美", nameEn: "Inada Tomomi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "高市 早苗", nameEn: "Takaichi Sanae2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "齋藤 健", nameEn: "Saito Ken", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "福井 照", nameEn: "Fukui Teru", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "坂本 哲志", nameEn: "Sakamoto Tetsushi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "末松 信介", nameEn: "Suematsu Shinsuke", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "馳 浩", nameEn: "Hase Hiroshi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "宮腰 光寛", nameEn: "Miyakoshi Mitsuhiro", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "石崎 徹", nameEn: "Ishizaki Toru", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "細野 豪志", nameEn: "Hosono Goshi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "長島 昭久", nameEn: "Nagashima Akihisa", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "鈴木 英敬", nameEn: "Suzuki Eikei", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "中川 正春", nameEn: "Nakagawa Masaharu", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "三谷 英弘", nameEn: "Mitani Hidehiro", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "藤原 崇", nameEn: "Fujiwara Takashi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "高橋 ひなこ", nameEn: "Takahashi Hinako", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "黄川田 仁志", nameEn: "Kikawada H2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "上田 英俊", nameEn: "Ueda Hidetoshi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "山田 美樹", nameEn: "Yamada Miki", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "越智 俊之", nameEn: "Ochi Toshiyuki", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "平 将明", nameEn: "Taira Masaaki", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "柿沢 未途", nameEn: "Kakizawa Mito", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "石川 昭政", nameEn: "Ishikawa Akimasa", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "百武 公親", nameEn: "Hyakutake Kimichika", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "赤澤 亮正", nameEn: "Akazawa R2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "星野 剛士", nameEn: "Hoshino Tsuyoshi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "田中 英之", nameEn: "Tanaka Hideyuki", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "本田 顕子", nameEn: "Honda Akiko", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "中西 哲", nameEn: "Nakanishi Satoru", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "森 英介", nameEn: "Mori Eisuke2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "金子 恵美", nameEn: "Kaneko Emi2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "杉久武", nameEn: "Sugi Hisamatsu", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "井上 義久", nameEn: "Inoue Yoshihisa", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "古川 康", nameEn: "Furukawa Yasushi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "北側 一雄", nameEn: "Kitabata Kazuo", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "竹内 譲", nameEn: "Takeuchi Yuzuru", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "石井 啓一", nameEn: "Ishii Keiichi2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "岡本 三成", nameEn: "Okamoto Mitsunari2", party: "自由民主党", role: "議員", chamber: "house" },

  // ── 中道改革連合 — 衆議院（追加22名）──
  { name: "安住 淳", nameEn: "Azumi Jun", party: "中道改革連合", role: "議員", chamber: "house" },
  { name: "逢坂 誠二", nameEn: "Osaka Seiji2", party: "中道改革連合", role: "議員", chamber: "house" },
  { name: "辻元 清美", nameEn: "Tsujimoto Kiyomi", party: "中道改革連合", role: "議員", chamber: "house" },
  { name: "枝野 幸男", nameEn: "Edano Yukio", party: "中道改革連合", role: "議員", chamber: "house" },
  { name: "山井 和則", nameEn: "Yamanoi Kazunori", party: "中道改革連合", role: "議員", chamber: "house" },
  { name: "大串 博志", nameEn: "Ogushi Hiroshi", party: "中道改革連合", role: "議員", chamber: "house" },
  { name: "玄葉 光一郎", nameEn: "Genba Koichiro", party: "中道改革連合", role: "議員", chamber: "house" },
  { name: "海江田 万里", nameEn: "Kaieda Banri", party: "中道改革連合", role: "議員", chamber: "house" },
  { name: "篠原 豪", nameEn: "Shinohara Go", party: "中道改革連合", role: "議員", chamber: "house" },
  { name: "山花 郁夫", nameEn: "Yamahana Ikuo", party: "中道改革連合", role: "議員", chamber: "house" },
  { name: "菊田 真紀子", nameEn: "Kikuta Makiko", party: "中道改革連合", role: "議員", chamber: "house" },
  { name: "牧 義夫", nameEn: "Maki Yoshio", party: "中道改革連合", role: "議員", chamber: "house" },
  { name: "近藤 昭一", nameEn: "Kondo Shoichi2", party: "中道改革連合", role: "議員", chamber: "house" },
  { name: "中川 正春", nameEn: "Nakagawa M2", party: "中道改革連合", role: "議員", chamber: "house" },
  { name: "吉田 統彦", nameEn: "Yoshida Munehiko", party: "中道改革連合", role: "議員", chamber: "house" },
  { name: "落合 貴之", nameEn: "Ochiai Takayuki", party: "中道改革連合", role: "議員", chamber: "house" },
  { name: "荒井 優", nameEn: "Arai Masaru", party: "中道改革連合", role: "議員", chamber: "house" },
  { name: "阿部 知子", nameEn: "Abe Tomoko", party: "中道改革連合", role: "議員", chamber: "house" },
  { name: "西村 智奈美", nameEn: "Nishimura Chinami", party: "中道改革連合", role: "議員", chamber: "house" },
  { name: "道下 大樹", nameEn: "Michishita Daiki", party: "中道改革連合", role: "議員", chamber: "house" },
  { name: "岡本 充功", nameEn: "Okamoto Mitsunori", party: "中道改革連合", role: "議員", chamber: "house" },
  { name: "源馬 謙太郎", nameEn: "Genma Kentaro", party: "中道改革連合", role: "議員", chamber: "house" },

  // ── 日本維新の会 — 衆議院（追加30名）──
  { name: "馬場 伸幸", nameEn: "Baba Nobuyuki2", party: "日本維新の会", role: "議員", chamber: "house" },
  { name: "藤田 文武", nameEn: "Fujita Fumitake2", party: "日本維新の会", role: "議員", chamber: "house" },
  { name: "足立 康史", nameEn: "Adachi Yasushi2", party: "日本維新の会", role: "議員", chamber: "house" },
  { name: "青柳 仁士", nameEn: "Aoyagi Hitoshi2", party: "日本維新の会", role: "議員", chamber: "house" },
  { name: "池下 卓", nameEn: "Ikeshita Taku2", party: "日本維新の会", role: "議員", chamber: "house" },
  { name: "小野 泰輔", nameEn: "Ono Taisuke", party: "日本維新の会", role: "議員", chamber: "house" },
  { name: "掘井 健智", nameEn: "Horii Kenji", party: "日本維新の会", role: "議員", chamber: "house" },
  { name: "守島 正", nameEn: "Morishima Tadashi", party: "日本維新の会", role: "議員", chamber: "house" },
  { name: "岬 麻紀", nameEn: "Misaki Maki", party: "日本維新の会", role: "議員", chamber: "house" },
  { name: "中条 きよし", nameEn: "Chujo Kiyoshi", party: "日本維新の会", role: "議員", chamber: "house" },
  { name: "浦野 靖人", nameEn: "Urano Yasuhito", party: "日本維新の会", role: "議員", chamber: "house" },
  { name: "杉本 和巳", nameEn: "Sugimoto Kazumi", party: "日本維新の会", role: "議員", chamber: "house" },
  { name: "山本 剛正", nameEn: "Yamamoto Gosho", party: "日本維新の会", role: "議員", chamber: "house" },
  { name: "美延 映夫", nameEn: "Minobe Teruo", party: "日本維新の会", role: "議員", chamber: "house" },
  { name: "遠藤 良太", nameEn: "Endo Ryota", party: "日本維新の会", role: "議員", chamber: "house" },
  { name: "中司 宏", nameEn: "Nakatsuka Hiroshi", party: "日本維新の会", role: "議員", chamber: "house" },
  { name: "池畑 浩太朗", nameEn: "Ikehata Kotaro", party: "日本維新の会", role: "議員", chamber: "house" },
  { name: "漆間 譲司", nameEn: "Urushima Joji", party: "日本維新の会", role: "議員", chamber: "house" },
  { name: "岩谷 良平", nameEn: "Iwatani Ryohei", party: "日本維新の会", role: "議員", chamber: "house" },
  { name: "阿部 弘樹", nameEn: "Abe Hiroki", party: "日本維新の会", role: "議員", chamber: "house" },
  { name: "赤木 正幸", nameEn: "Akagi Masayuki", party: "日本維新の会", role: "議員", chamber: "house" },
  { name: "前川 清成", nameEn: "Maekawa Kiyoshige", party: "日本維新の会", role: "議員", chamber: "house" },
  { name: "沢田 良", nameEn: "Sawada Ryo", party: "日本維新の会", role: "議員", chamber: "house" },
  { name: "早坂 敦", nameEn: "Hayasaka Atsushi", party: "日本維新の会", role: "議員", chamber: "house" },
  { name: "金村 龍那", nameEn: "Kanamura Ryuna", party: "日本維新の会", role: "議員", chamber: "house" },
  { name: "一谷 勇一郎", nameEn: "Ichitani Yuichiro", party: "日本維新の会", role: "議員", chamber: "house" },
  { name: "奥下 剛光", nameEn: "Okushita Takemitsu", party: "日本維新の会", role: "議員", chamber: "house" },
  { name: "三木 圭恵", nameEn: "Miki Kae", party: "日本維新の会", role: "議員", chamber: "house" },
  { name: "住吉 寛紀", nameEn: "Sumiyoshi Hiroki", party: "日本維新の会", role: "議員", chamber: "house" },

  // ── 国民民主党 — 衆議院（追加21名）──
  { name: "玉木 雄一郎", nameEn: "Tamaki Yuichiro2", party: "国民民主党", role: "議員", chamber: "house" },
  { name: "前原 誠司", nameEn: "Maehara Seiji2", party: "国民民主党", role: "議員", chamber: "house" },
  { name: "古川 元久", nameEn: "Furukawa Motohisa2", party: "国民民主党", role: "議員", chamber: "house" },
  { name: "竹詰 仁", nameEn: "Taketsume Hitoshi", party: "国民民主党", role: "議員", chamber: "house" },
  { name: "浅野 哲", nameEn: "Asano Satoru", party: "国民民主党", role: "議員", chamber: "house" },
  { name: "鳥畑 哲也", nameEn: "Torihata Tetsuya", party: "国民民主党", role: "議員", chamber: "house" },
  { name: "西岡 秀子", nameEn: "Nishioka Hideko", party: "国民民主党", role: "議員", chamber: "house" },
  { name: "田中 健", nameEn: "Tanaka Ken2", party: "国民民主党", role: "議員", chamber: "house" },
  { name: "長友 慎治", nameEn: "Nagatomo Shinji", party: "国民民主党", role: "議員", chamber: "house" },
  { name: "鈴木 敦", nameEn: "Suzuki Atsushi2", party: "国民民主党", role: "議員", chamber: "house" },
  { name: "吉良 州司", nameEn: "Kira Shuji", party: "国民民主党", role: "議員", chamber: "house" },
  { name: "斎藤 アレックス", nameEn: "Saito Alex", party: "国民民主党", role: "議員", chamber: "house" },
  { name: "伊藤 俊輔", nameEn: "Ito Shunsuke", party: "国民民主党", role: "議員", chamber: "house" },
  { name: "岸本 周平", nameEn: "Kishimoto Shuhei", party: "国民民主党", role: "議員", chamber: "house" },
  { name: "緑川 貴士", nameEn: "Midorikawa Takashi", party: "国民民主党", role: "議員", chamber: "house" },
  { name: "山尾 志桜里", nameEn: "Yamao Shiori", party: "国民民主党", role: "議員", chamber: "house" },
  { name: "嘉田 由紀子", nameEn: "Kada Yukiko", party: "国民民主党", role: "議員", chamber: "house" },
  { name: "鬼木 誠", nameEn: "Oniki Makoto2", party: "国民民主党", role: "議員", chamber: "house" },
  { name: "榛葉 賀津也", nameEn: "Shinba Kazuya2", party: "国民民主党", role: "議員", chamber: "house" },
  { name: "舟山 康江", nameEn: "Funayama Yasue2", party: "国民民主党", role: "議員", chamber: "house" },
  { name: "大塚 耕平", nameEn: "Otsuka Kohei2", party: "国民民主党", role: "議員", chamber: "house" },

  // ── 無所属 — 衆議院（追加3名）──
  { name: "吉良 州司", nameEn: "Kira Shuji2", party: "無所属", role: "議員", chamber: "house" },
  { name: "仁木 博文", nameEn: "Niki Hirobumi", party: "無所属", role: "議員", chamber: "house" },
  { name: "三反園 訓", nameEn: "Mitazono Satoshi", party: "無所属", role: "議員", chamber: "house" },

  // ── 自由民主党 — 参議院（追加94名）──
  { name: "世耕 弘成", nameEn: "Seko Hiroshige", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "片山 さつき", nameEn: "Katayama Satsuki2", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "三原 じゅん子", nameEn: "Mihara Junko2", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "丸川 珠代", nameEn: "Marukawa Tamayo", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "佐藤 正久", nameEn: "Sato Masahisa2", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "山谷 えり子", nameEn: "Yamatani Eriko", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "有村 治子", nameEn: "Arimura Haruko2", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "橋本 聖子", nameEn: "Hashimoto Seiko", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "小野田 紀美", nameEn: "Onoda Kimi2", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "中西 祐介", nameEn: "Nakanishi Yusuke", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "宮本 周司", nameEn: "Miyamoto Shuji", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "足立 敏之", nameEn: "Adachi Toshiyuki", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "青山 繁晴", nameEn: "Aoyama Shigeharu2", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "山田 太郎", nameEn: "Yamada Taro", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "山田 宏", nameEn: "Yamada Hiroshi", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "松川 るい", nameEn: "Matsukawa Rui", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "自見 はなこ", nameEn: "Jimi Hanako", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "今井 絵理子", nameEn: "Imai Eriko", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "朝日 健太郎", nameEn: "Asahi Kentaro", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "小鑓 隆史", nameEn: "Koyari Takashi", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "進藤 金日子", nameEn: "Shindo Kaneko", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "藤木 眞也", nameEn: "Fujiki Shinya", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "宮崎 雅夫", nameEn: "Miyazaki Masao", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "比嘉 奈津美", nameEn: "Higa Natsumi", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "生稲 晃子", nameEn: "Ikuina Akiko", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "梶原 大介", nameEn: "Kajiwara Daisuke", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "友納 理緒", nameEn: "Tomono Rio", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "広瀬 めぐみ", nameEn: "Hirose Megumi", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "越智 俊之", nameEn: "Ochi Toshi", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "赤池 誠章", nameEn: "Akaike Masaaki", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "磯崎 仁彦", nameEn: "Isozaki Yoshihiko", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "猪口 邦子", nameEn: "Inoguchi Kuniko", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "上野 通子", nameEn: "Ueno Michiko", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "北村 経夫", nameEn: "Kitamura Tsuneo", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "佐藤 啓", nameEn: "Sato Kei", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "高階 恵美子", nameEn: "Takashina Emiko", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "高野 光二郎", nameEn: "Takano Kojiro", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "滝沢 求", nameEn: "Takizawa Motomu", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "柘植 芳文", nameEn: "Tsuge Yoshifumi", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "堂故 茂", nameEn: "Doko Shigeru", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "豊田 俊郎", nameEn: "Toyoda Toshiro", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "中田 宏", nameEn: "Nakada Hiroshi", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "中西 健治", nameEn: "Nakanishi Kenji", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "松下 新平", nameEn: "Matsushita Shimpei", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "三宅 伸吾", nameEn: "Miyake Shingo", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "元栄 太一郎", nameEn: "Motoe Taichiro", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "柳ヶ瀬 裕文", nameEn: "Yanagase Hirofumi2", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "渡辺 猛之", nameEn: "Watanabe Takeyuki", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "加田 裕之", nameEn: "Kata Hiroyuki", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "清水 真人", nameEn: "Shimizu Mahito", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "本田 顕子", nameEn: "Honda Akiko2", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "羽生田 俊", nameEn: "Hanyuda Takashi", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "阿達 雅志", nameEn: "Adachi Masashi", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "石井 準一", nameEn: "Ishii Junichi", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "小川 克巳", nameEn: "Ogawa Katsumi", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "太田 房江", nameEn: "Ota Fusae2", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "大野 泰正", nameEn: "Ono Yasumasa", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "古賀 友一郎", nameEn: "Koga Yuichiro", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "こやり 隆史", nameEn: "Koyari T2", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "酒井 庸行", nameEn: "Sakai Nobuyuki", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "山本 順三", nameEn: "Yamamoto Junzo", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "若林 洋平", nameEn: "Wakabayashi Yohei", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "石田 昌宏", nameEn: "Ishida Masahiro", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "衛藤 晟一", nameEn: "Eto Seiichi", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "小林 一大", nameEn: "Kobayashi Kazuhiro", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "山本 佐知子", nameEn: "Yamamoto Sachiko", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "永井 学", nameEn: "Nagai Manabu", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "船田 元", nameEn: "Funada Hajime", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "舞立 昇治", nameEn: "Maidachi Shoji", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "臼井 正一", nameEn: "Usui Shoichi", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "井上 義行", nameEn: "Inoue Yoshiyuki", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "長峯 誠", nameEn: "Nagamine Makoto", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "松山 政司", nameEn: "Matsuyama M2", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "橋本 岳", nameEn: "Hashimoto G2", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "上月 良祐", nameEn: "Kozuki Ryosuke", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "片山 大介", nameEn: "Katayama Daisuke", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "末松 信介", nameEn: "Suematsu S2", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "佐々木 さやか", nameEn: "Sasaki Sayaka", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "河野 義博", nameEn: "Kono Yoshihiro", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "秋野 公造", nameEn: "Akino Kozo", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "竹谷 とし子", nameEn: "Takeya Toshiko2", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "若松 謙維", nameEn: "Wakamatsu Kaneo", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "新妻 秀規", nameEn: "Niizuma Hideki", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "里見 隆治", nameEn: "Satomi Ryuji", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "安江 伸夫", nameEn: "Yasue Nobuo", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "塩田 博昭", nameEn: "Shioda Hiroaki", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "下野 六太", nameEn: "Shimono Rokuta", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "平木 大作", nameEn: "Hiraki Daisaku", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "窪田 哲也", nameEn: "Kubota Tetsuya", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "高橋 光男", nameEn: "Takahashi Mitsuo", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "谷合 正明", nameEn: "Taniai Masaaki", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "伊藤 孝江", nameEn: "Ito Takae2", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "三浦 信祐", nameEn: "Miura Shinsuke", party: "自由民主党", role: "議員", chamber: "council" },
  { name: "山口 那津男", nameEn: "Yamaguchi Natsuo2", party: "自由民主党", role: "議員", chamber: "council" },

  // ── 中道改革連合 — 参議院（追加59名）──
  { name: "蓮舫", nameEn: "Renho2", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "福山 哲郎", nameEn: "Fukuyama Tetsuro2", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "白 眞勲", nameEn: "Haku Shinkun", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "石橋 通宏", nameEn: "Ishibashi Michihiro", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "杉尾 秀哉", nameEn: "Sugio Hideya2", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "小西 洋之", nameEn: "Konishi Hiroyuki", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "真山 勇一", nameEn: "Mayama Yuichi", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "牧山 ひろえ", nameEn: "Makiyama Hiroe", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "古賀 千景", nameEn: "Koga Chikage", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "塩村 あやか", nameEn: "Shiomura Ayaka", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "水岡 俊一", nameEn: "Mizuoka Shunichi", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "川田 龍平", nameEn: "Kawada Ryuhei", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "打越 さく良", nameEn: "Uchikoshi Sakura", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "熊谷 裕人", nameEn: "Kumagai Hiroto", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "石垣 のりこ", nameEn: "Ishigaki Noriko", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "岸 真紀子", nameEn: "Kishi Makiko", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "柴 愼一", nameEn: "Shiba Shinichi", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "田島 麻衣子", nameEn: "Tajima Maiko", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "宮口 治子", nameEn: "Miyaguchi Haruko", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "村田 享子", nameEn: "Murata Kyoko", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "鬼木 誠", nameEn: "Oniki M3", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "田名部 匡代", nameEn: "Tanabe Masayo", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "森屋 隆", nameEn: "Moriya Takashi", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "小沼 巧", nameEn: "Konuma Takumi", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "石川 大我", nameEn: "Ishikawa Taiga", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "吉川 沙織", nameEn: "Yoshikawa Saori", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "青木 愛", nameEn: "Aoki Ai", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "有田 芳生", nameEn: "Arita Yoshifu2", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "難波 奨二", nameEn: "Namba Shoji", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "芳賀 道也", nameEn: "Haga Michiya", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "横沢 高徳", nameEn: "Yokozawa Takanori", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "木戸口 英司", nameEn: "Kidoguchi Eiji", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "勝部 賢志", nameEn: "Katsube Kenji", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "徳永 エリ", nameEn: "Tokunaga Eri", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "鳥畑 哲也", nameEn: "Torihata T2", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "奥村 政佳", nameEn: "Okumura Masayoshi", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "古賀 之士", nameEn: "Koga Yukihito", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "斎藤 嘉隆", nameEn: "Saito Yoshitaka", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "辻元 清美", nameEn: "Tsujimoto K2", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "森本 真治", nameEn: "Morimoto Shinji", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "野田 国義", nameEn: "Noda Kuniyoshi", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "小沢 雅仁", nameEn: "Ozawa Masahito", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "羽田 次郎", nameEn: "Haneda Jiro", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "高木 真理", nameEn: "Takagi Mari", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "水野 素子", nameEn: "Mizuno Motoko", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "辻 元清", nameEn: "Tsuji Motokiyo", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "柳田 稔", nameEn: "Yanagida Minoru", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "石橋 通宏", nameEn: "Ishibashi M2", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "浜口 誠", nameEn: "Hamaguchi Makoto", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "礒崎 哲史", nameEn: "Isozaki Tetsushi", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "川合 孝典", nameEn: "Kawai Takanori", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "浜野 喜史", nameEn: "Hamano Yoshifumi", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "矢田 稚子", nameEn: "Yata Wakako", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "森屋 宏", nameEn: "Moriya Hiroshi", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "柳ヶ瀬 裕文", nameEn: "Yanagase H3", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "吉田 忠智", nameEn: "Yoshida Tadatomo", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "大椿 ゆうこ", nameEn: "Otsubaki Yuko", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "福島 みずほ", nameEn: "Fukushima Mizuho", party: "中道改革連合", role: "議員", chamber: "council" },
  { name: "又市 征治", nameEn: "Mataichi Seiji", party: "中道改革連合", role: "議員", chamber: "council" },

  // ── 国民民主党 — 参議院（追加20名）──
  { name: "榛葉 賀津也", nameEn: "Shinba K3", party: "国民民主党", role: "議員", chamber: "council" },
  { name: "舟山 康江", nameEn: "Funayama Y3", party: "国民民主党", role: "議員", chamber: "council" },
  { name: "大塚 耕平", nameEn: "Otsuka K3", party: "国民民主党", role: "議員", chamber: "council" },
  { name: "伊藤 孝恵", nameEn: "Ito Takae3", party: "国民民主党", role: "議員", chamber: "council" },
  { name: "川合 孝典", nameEn: "Kawai T2", party: "国民民主党", role: "議員", chamber: "council" },
  { name: "浜口 誠", nameEn: "Hamaguchi M2", party: "国民民主党", role: "議員", chamber: "council" },
  { name: "礒崎 哲史", nameEn: "Isozaki T2", party: "国民民主党", role: "議員", chamber: "council" },
  { name: "矢田 稚子", nameEn: "Yata W2", party: "国民民主党", role: "議員", chamber: "council" },
  { name: "浜野 喜史", nameEn: "Hamano Y2", party: "国民民主党", role: "議員", chamber: "council" },
  { name: "田村 まみ", nameEn: "Tamura Mami", party: "国民民主党", role: "議員", chamber: "council" },
  { name: "竹詰 仁", nameEn: "Taketsume H2", party: "国民民主党", role: "議員", chamber: "council" },
  { name: "上田 清司", nameEn: "Ueda Kiyoshi", party: "国民民主党", role: "議員", chamber: "council" },
  { name: "柴 慎一", nameEn: "Shiba S2", party: "国民民主党", role: "議員", chamber: "council" },
  { name: "西田 実仁", nameEn: "Nishida Makoto", party: "国民民主党", role: "議員", chamber: "council" },
  { name: "河野 義博", nameEn: "Kono Y2", party: "国民民主党", role: "議員", chamber: "council" },
  { name: "塩田 博昭", nameEn: "Shioda H2", party: "国民民主党", role: "議員", chamber: "council" },
  { name: "新妻 秀規", nameEn: "Niizuma H2", party: "国民民主党", role: "議員", chamber: "council" },
  { name: "杉 久武", nameEn: "Sugi H2", party: "国民民主党", role: "議員", chamber: "council" },
  { name: "山本 香苗", nameEn: "Yamamoto Kanae", party: "国民民主党", role: "議員", chamber: "council" },
  { name: "山本 博司", nameEn: "Yamamoto Hiroshi", party: "国民民主党", role: "議員", chamber: "council" },

  // ── 日本維新の会 — 参議院（追加13名）──
  { name: "片山 大介", nameEn: "Katayama D2", party: "日本維新の会", role: "議員", chamber: "council" },
  { name: "柳ヶ瀬 裕文", nameEn: "Yanagase H4", party: "日本維新の会", role: "議員", chamber: "council" },
  { name: "石井 章", nameEn: "Ishii Akira", party: "日本維新の会", role: "議員", chamber: "council" },
  { name: "室井 邦彦", nameEn: "Muroi Kunihiko", party: "日本維新の会", role: "議員", chamber: "council" },
  { name: "高木 佳保里", nameEn: "Takagi Kahori", party: "日本維新の会", role: "議員", chamber: "council" },
  { name: "清水 貴之", nameEn: "Shimizu Takayuki", party: "日本維新の会", role: "議員", chamber: "council" },
  { name: "石井 苗子", nameEn: "Ishii Mitsuko", party: "日本維新の会", role: "議員", chamber: "council" },
  { name: "梅村 みずほ", nameEn: "Umemura Mizuho2", party: "日本維新の会", role: "議員", chamber: "council" },
  { name: "松野 明美", nameEn: "Matsuno Akemi", party: "日本維新の会", role: "議員", chamber: "council" },
  { name: "猪瀬 直樹", nameEn: "Inose Naoki", party: "日本維新の会", role: "議員", chamber: "council" },
  { name: "浅田 均", nameEn: "Asada Hitoshi2", party: "日本維新の会", role: "議員", chamber: "council" },
  { name: "東 徹", nameEn: "Azuma Toru", party: "日本維新の会", role: "議員", chamber: "council" },

  // ── 参政党 — 参議院（追加12名）──
  { name: "神谷 宗幣", nameEn: "Kamiya Sohei2", party: "参政党", role: "議員", chamber: "council" },
  { name: "松田 学", nameEn: "Matsuda Manabu2", party: "参政党", role: "議員", chamber: "council" },
  { name: "河合 純一", nameEn: "Kawai Junichi", party: "参政党", role: "議員", chamber: "council" },
  { name: "佐野 愛子", nameEn: "Sano Aiko", party: "参政党", role: "議員", chamber: "council" },
  { name: "武田 邦彦", nameEn: "Takeda Kunihiko", party: "参政党", role: "議員", chamber: "council" },
  { name: "吉川 りな", nameEn: "Yoshikawa Rina2", party: "参政党", role: "議員", chamber: "council" },
  { name: "原口 一博", nameEn: "Haraguchi Kazuhiro", party: "参政党", role: "議員", chamber: "council" },
  { name: "赤尾 由美", nameEn: "Akao Yumi2", party: "参政党", role: "議員", chamber: "council" },
  { name: "鹿島 英敬", nameEn: "Kashima Hidetaka", party: "参政党", role: "議員", chamber: "council" },
  { name: "川裕一郎", nameEn: "Kawa Yuichiro2", party: "参政党", role: "議員", chamber: "council" },
  { name: "渡辺 愛理", nameEn: "Watanabe Airi2", party: "参政党", role: "議員", chamber: "council" },
  { name: "山田 恵理", nameEn: "Yamada Eri2", party: "参政党", role: "議員", chamber: "council" },

  // ── れいわ新選組 — 参議院（追加1名）──
  { name: "大島 九州男", nameEn: "Oshima Kusuo2", party: "れいわ新選組", role: "議員", chamber: "council" },

  // ── 無所属 — 参議院（追加6名）──
  { name: "嘉田 由紀子", nameEn: "Kada Yukiko2", party: "無所属", role: "議員", chamber: "council" },
  { name: "須藤 元気", nameEn: "Sudo Genki", party: "無所属", role: "議員", chamber: "council" },
  { name: "渡辺 喜美", nameEn: "Watanabe Yoshimi", party: "無所属", role: "議員", chamber: "council" },
  { name: "平山 佐知子", nameEn: "Hirayama Sachiko", party: "無所属", role: "議員", chamber: "council" },
  { name: "寺田 静", nameEn: "Terada Shizuka", party: "無所属", role: "議員", chamber: "council" },
  { name: "良知 潤一郎", nameEn: "Rachi Junichiro", party: "無所属", role: "議員", chamber: "council" },

  // ── 追加分（残り）──
  { name: "小里 泰弘", nameEn: "Ozato Yasuhiro", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "井上 貴博", nameEn: "Inoue Takahiro", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "山本 有二", nameEn: "Yamamoto Yuji", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "竹本 直一", nameEn: "Takemoto Naoichi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "薗浦 健太郎", nameEn: "Sonoura Kentaro", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "杉 久武", nameEn: "Sugi Hisamatsu2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "石井 啓一", nameEn: "Ishii K3", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "原田 憲治", nameEn: "Harada Kenji", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "河村 建夫", nameEn: "Kawamura Takeo", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "岡本 三成", nameEn: "Okamoto Mitsunari3", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "手塚 仁雄", nameEn: "Tezuka Yoshio", party: "中道改革連合", role: "議員", chamber: "house" },
  { name: "山岡 達丸", nameEn: "Yamaoka Tatsumaru2", party: "中道改革連合", role: "議員", chamber: "house" },
  { name: "山本 香苗", nameEn: "Yamamoto Kanae2", party: "国民民主党", role: "議員", chamber: "council" },
  { name: "石井 章", nameEn: "Ishii Akira2", party: "日本維新の会", role: "議員", chamber: "council" },
  { name: "柴田 巧", nameEn: "Shibata Takumi", party: "日本維新の会", role: "議員", chamber: "council" },

  // ── 自由民主党（追加分）──
  { name: "武藤 容治", nameEn: "Muto Yoji", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "望月 義夫", nameEn: "Mochizuki Yoshio", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "山口 泰明", nameEn: "Yamaguchi Taimei", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "伊吹 文明", nameEn: "Ibuki Bunmei", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "逢沢 一郎", nameEn: "Aizawa Ichiro", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "竹下 亘", nameEn: "Takeshita Wataru", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "鶴保 庸介", nameEn: "Tsuruho Yosuke", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "岩屋 毅", nameEn: "Iwaya Takeshi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "西田 昌司", nameEn: "Nishida Shoji", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "片山 虎之助", nameEn: "Katayama Toranosuke", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "吉田 博美", nameEn: "Yoshida Hiromi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "中曽根 弘文", nameEn: "Nakasone Hirofumi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "町村 信孝", nameEn: "Machimura Nobutaka", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "大島 理森", nameEn: "Oshima Tadamori", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "北村 茂男", nameEn: "Kitamura Shigeo", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "松浪 健太", nameEn: "Matsunami Kenta", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "中山 泰秀", nameEn: "Nakayama Yasuhide", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "武見 敬三", nameEn: "Takemi Keizo", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "長谷川 岳", nameEn: "Hasegawa Gaku", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "野上 浩太郎", nameEn: "Nogami Kotaro", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "徳茂 雅之", nameEn: "Tokushige Masayuki", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "石井 浩郎", nameEn: "Ishii Hiroo", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "滝波 宏文", nameEn: "Takinami Hirobumi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "高橋 克法", nameEn: "Takahashi Katsunori", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "中泉 松司", nameEn: "Nakaizumi Shoji", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "永田 勝也", nameEn: "Nagata Katsuya", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "伊藤 岳", nameEn: "Ito Gaku", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "大家 敏志", nameEn: "Oie Satoshi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "野村 哲郎", nameEn: "Nomura Tetsuro", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "宮沢 洋一", nameEn: "Miyazawa Yoichi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "中西 祐介", nameEn: "Nakanishi Y2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "三木 亨", nameEn: "Miki Toru", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "岡田 直樹", nameEn: "Okada Naoki", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "岡田 広", nameEn: "Okada Hiroshi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "馬場 成志", nameEn: "Baba Seishi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "西田 実仁", nameEn: "Nishida M2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "古庄 玄知", nameEn: "Furusho Genchi", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "加藤 明良", nameEn: "Kato Akira", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "山下 雄平", nameEn: "Yamashita Yuhei", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "宮本 周司", nameEn: "Miyamoto S2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "足立 敏之", nameEn: "Adachi T2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "松本 剛明", nameEn: "Matsumoto T2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "渡辺 猛之", nameEn: "Watanabe T2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "佐藤 信秋", nameEn: "Sato N2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "藤木 眞也", nameEn: "Fujiki S2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "森 まさこ", nameEn: "Mori Masako", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "松川 るい", nameEn: "Matsukawa R2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "自見 はなこ", nameEn: "Jimi H2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "今井 絵理子", nameEn: "Imai E2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "朝日 健太郎", nameEn: "Asahi K2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "生稲 晃子", nameEn: "Ikuina A2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "広瀬 めぐみ", nameEn: "Hirose M2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "友納 理緒", nameEn: "Tomono R2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "梶原 大介", nameEn: "Kajiwara D2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "進藤 金日子", nameEn: "Shindo K2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "比嘉 奈津美", nameEn: "Higa N2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "宮崎 雅夫", nameEn: "Miyazaki M2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "石田 昌宏", nameEn: "Ishida M3", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "衛藤 晟一", nameEn: "Eto S2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "猪口 邦子", nameEn: "Inoguchi K2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "上野 通子", nameEn: "Ueno M2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "北村 経夫", nameEn: "Kitamura T2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "佐藤 啓", nameEn: "Sato K2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "高階 恵美子", nameEn: "Takashina E2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "高野 光二郎", nameEn: "Takano K2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "滝沢 求", nameEn: "Takizawa M2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "堂故 茂", nameEn: "Doko S2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "豊田 俊郎", nameEn: "Toyoda T2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "三宅 伸吾", nameEn: "Miyake S2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "元栄 太一郎", nameEn: "Motoe T2", party: "自由民主党", role: "議員", chamber: "house" },
  { name: "河合 純一", nameEn: "Kawai Junichi2", party: "国民民主党", role: "議員", chamber: "house" },
];
