// 政治ニュース タイムライン
// microCMS連携後はCMSから取得に切り替え可能

export interface PoliticsNewsItem {
  date: string;
  time: string;
  title: string;
  summary: string;
  tag: string;
  tagColor: string;
  source?: string;
  titleEn?: string;
  summaryEn?: string;
  tagEn?: string;
}

export const politicsNews: PoliticsNewsItem[] = [
  {
    date: "2026-04-14",
    time: "11:00",
    title: "政府、再審法改正の修正案を自民党に提示　検察抗告後の審理期間に制限",
    summary: "政府は再審制度見直しのための刑事訴訟法改正案の修正案を自民党の司法制度調査会などに提示した。検察が再審開始決定に抗告した場合、裁判所の審理期間に制限を設けることが柱。検察抗告の全面禁止を求める自民内の反発を受けた修正だが、禁止規定は盛り込まれておらず議論は継続。今国会での提出・成立は不透明な情勢。",
    tag: "国会",
    tagColor: "#2d3748",
    titleEn: "Government presents revised retrial bill to LDP — limits on court review period after prosecution appeals",
    summaryEn: "The government presented a revised version of its criminal procedure law amendment on retrial reform to LDP committees. The bill limits the court's review period when prosecutors appeal a retrial commencement decision. The revision reflects LDP calls for stricter limits, but stops short of a full ban on prosecution appeals demanded by many LDP members. Passage this Diet session remains uncertain.",
    tagEn: "Diet",
  },
  {
    date: "2026-04-13",
    time: "23:00",
    title: "米海軍、ホルムズ海峡の「逆封鎖」を開始　交渉決裂受けトランプ大統領が表明",
    summary: "交渉決裂を受けトランプ大統領はイランの港湾へ出入りする船舶を対象とした「逆封鎖」を表明し、米東部時間13日午前10時（日本時間同日午後11時）に米海軍が封鎖を開始した。原油価格が急騰し世界経済への打撃懸念が強まった。日本では精製所稼働率が急落し、高市政権は国家石油備蓄の追加放出を検討する方針を示した。",
    tag: "外交",
    tagColor: "#2b6cb0",
    titleEn: "US Navy begins 'reverse blockade' of Hormuz following collapse of Iran talks",
    summaryEn: "Following the breakdown of peace talks, President Trump announced a US Navy blockade targeting ships entering and leaving Iranian ports. The blockade began at 10:00 a.m. EDT on April 13 (11:00 p.m. JST). Crude oil prices surged amid growing fears of a global economic shock. Japan, which refines nearly 95% of its oil from Middle Eastern imports, saw refinery utilization rates plunge; the Takaichi government indicated it would consider releasing additional strategic petroleum reserves.",
    tagEn: "Diplomacy",
  },
  {
    date: "2026-04-13",
    time: "15:00",
    title: "高市首相、政府与党連絡会議で後半国会の重要法案審議への協力を要請",
    summary: "高市総理大臣は首相官邸で政府与党連絡会議を開催し、令和8年度予算成立後の後半国会に向けて与党に重要法案の審議への協力を要請した。国家情報局設置法案・防災庁設置法案・個人情報保護法改正案など複数の重要法案が議題。7月17日の会期末に向けた審議日程の確保が喫緊の課題となっている。",
    tag: "国会",
    tagColor: "#2d3748",
    titleEn: "PM Takaichi calls on ruling parties to cooperate on key bills in second half of Diet session",
    summaryEn: "Prime Minister Takaichi convened a government–ruling party liaison conference at the PM's office, requesting coalition support for key legislation in the Diet session's second half following the FY2026 budget passage. Bills on the agenda include the National Intelligence Agency Establishment Act, the Disaster Prevention Agency bill and the Personal Information Protection Law amendment. Securing debate time before the July 17 session deadline is an urgent priority.",
    tagEn: "Diet",
  },
  {
    date: "2026-04-12",
    time: "19:00",
    title: "バンス米副大統領、21時間の交渉後に合意なしとイスラマバードを離脱",
    summary: "バンス米副大統領は21時間にわたるイランとの協議が合意に至らなかったと発表し、イスラマバードを離脱。イランが核兵器を製造しないことを含む米側の条件をイランが拒否したと説明した。イランは「一回の協議で合意できると誰も期待していなかった」と反論。停戦の行方が不透明となり、エネルギー市場に動揺が広がった。",
    tag: "外交",
    tagColor: "#2b6cb0",
    titleEn: "Vance leaves Islamabad without a deal after 21 hours of talks with Iran",
    summaryEn: "US Vice President JD Vance announced that talks with Iran had failed after 21 hours of negotiations and departed Islamabad. He said Iran refused to accept US terms, including a fundamental commitment not to develop nuclear weapons. Iran countered that no one expected an agreement in a single round of talks. The breakdown cast doubt on the ceasefire and rattled global energy markets.",
    tagEn: "Diplomacy",
  },
  {
    date: "2026-04-12",
    time: "13:00",
    title: "自民党大会で高市首相「時は来た」　改憲発議を来年党大会までにめど",
    summary: "第93回自民党大会（東京・グランドプリンスホテル新高輪）で高市首相は「自主憲法制定は立党の精神。時は来た」と述べ、来年の党大会までに憲法改正の発議にめどをつける方針を表明した。2月の衆院選での大勝を踏まえ「選挙に勝ち続ける強い党をつくる」とも強調。2026年度の運動方針に衆参両院の憲法審査会での改正原案作成を明記した。",
    tag: "内政",
    tagColor: "#702459",
    titleEn: "Takaichi declares 'the time has come' at LDP convention; targets constitutional amendment proposal by spring 2027",
    summaryEn: "At the 93rd LDP annual convention in Tokyo, Prime Minister Takaichi declared 'drafting our own constitution is the founding spirit of this party — the time has come,' and pledged to reach a prospect for proposing a constitutional amendment by the party's next convention. Citing the party's landslide Lower House election win in February, she also vowed to build 'a strong party that keeps winning elections.' The 2026 operational policy calls for constitutional amendment draft committees to be established in both chambers' Constitutional Review Commissions.",
    tagEn: "Domestic Politics",
  },
  {
    date: "2026-04-10",
    time: "10:00",
    title: "イスラマバードで米・イラン最終和平交渉が開始",
    summary: "4月8日の停戦合意に基づき、パキスタン・イスラマバードで米・イランの最終和平交渉が開始された。ホルムズ海峡の恒久開放や核協議の再開が主な議題。2週間以内の合意達成を目指す。日本はエネルギー安全保障の観点から交渉の行方を注視している。",
    tag: "外交",
    tagColor: "#2b6cb0",
    titleEn: "US–Iran final peace talks open in Islamabad",
    summaryEn: "Under the April 8 ceasefire agreement, US–Iran final peace negotiations have begun in Islamabad, Pakistan. Permanent reopening of the Strait of Hormuz and resumption of nuclear talks are the main agenda items. The parties aim for an agreement within two weeks. Japan is closely watching the negotiations from an energy-security perspective.",
    tagEn: "Diplomacy",
  },
  {
    date: "2026-04-07",
    time: "14:30",
    title: "令和8年度本予算が参院本会議で可決・成立 — 一般会計122.3兆円で過去最大",
    summary: "参院本会議で令和8年度（2026年度）当初予算が与党・日本保守党などの賛成多数で可決、成立した。一般会計総額は122兆3092億円と過去最大。防衛力整備・子育て支援・科学技術投資を重点配分。高市首相は「中小企業の稼ぐ力を抜本強化する予算」と強調。年度内成立の目標より1週間遅れての成立となった。",
    tag: "予算",
    tagColor: "#e53e3e",
    titleEn: "FY2026 budget passes Upper House — record ¥122.3 trillion general account",
    summaryEn: "The FY2026 budget bill passed the House of Councillors by a majority including the ruling coalition and the Japan Conservative Party. The general account totals a record ¥122.3 trillion, with priority spending on defence, childcare and science and technology. PM Takaichi called it a 'budget to fundamentally strengthen the earning power of small businesses.' It passed one week later than the government had targeted.",
    tagEn: "Budget",
  },
  {
    date: "2026-04-05",
    time: "23:00",
    title: "京都府知事選 現職・西脇隆俊氏が3選、投票率37.43%",
    summary: "4月5日に投開票された京都府知事選で、自民・立憲・公明・国民・中道各党が推薦する無所属現職の西脇隆俊氏（70）が3回目の当選を決めた。新人2氏を破っての3選で、投票率は37.43%（前回比0.15ポイント減）。統一地方選前半戦の先行指標として与党は「信任」と評価した。",
    tag: "選挙",
    tagColor: "#805ad5",
    titleEn: "Kyoto governor election: incumbent Nishiwaki wins third term; turnout 37.43%",
    summaryEn: "In the Kyoto prefectural governor election held on April 5, incumbent Takatoshi Nishiwaki (70), backed by the LDP, CDP, Komeito, DPP and centrist parties, won a third term, defeating two challengers. Voter turnout was 37.43%, down 0.15 points from the previous election. The ruling coalition claimed the result as an endorsement ahead of the unified local elections.",
    tagEn: "Election",
  },
  {
    date: "2026-04-08",
    time: "22:00",
    title: "米・イランが2週間の即時停戦で合意、ホルムズ海峡全面再開へ",
    summary: "トランプ大統領とイランが即時停戦に合意（パキスタンが仲介）。ホルムズ海峡の安全な通航を2週間認め、米・イスラエルの軍事作戦を停止。10日からイスラマバードで最終合意に向けた交渉開始。日経平均は翌8日に2,879円高と歴代3位の急騰を記録。",
    tag: "外交",
    tagColor: "#2b6cb0",
    titleEn: "US and Iran agree on two-week ceasefire; Strait of Hormuz to fully reopen",
    summaryEn: "President Trump and Iran reached an immediate ceasefire agreement brokered by Pakistan. Iran will allow safe transit through the Strait of Hormuz for two weeks while the US and Israel halt military operations. Negotiations toward a final agreement begin in Islamabad on April 10. The Nikkei 225 surged 2,879 yen the following day — the third-largest single-day gain on record.",
    tagEn: "Diplomacy",
  },
  {
    date: "2026-04-07",
    time: "09:00",
    title: "トランプ大統領の対イラン猶予期限が到来、今後の対応に注目",
    summary: "トランプ大統領がイランに設定した猶予期限が4月6日夜（日本時間7日午前9時）に到来。ホルムズ海峡の全面再開は実現しておらず、米国の次の対応が焦点に。",
    tag: "外交",
    tagColor: "#2b6cb0",
    titleEn: "Trump's grace period for Iran expires; next US move in focus",
    summaryEn: "The grace period President Trump set for Iran expired on the night of April 6 (9:00 a.m. JST on April 7). A full reopening of the Strait of Hormuz has not been achieved, and attention now turns to the US response.",
    tagEn: "Diplomacy",
  },
  {
    date: "2026-04-07",
    time: "11:00",
    title: "与野党、4月〜6月に月1回の党首討論実施で合意",
    summary: "自民・梶山国対委員長と立憲・笠国対委員長が会談し、4月から6月にかけて月1回の党首討論を実施することで合意。予算成立後の重要法案審議に向けた与野党対話の枠組み。",
    tag: "国会",
    tagColor: "#e53e3e",
    titleEn: "Ruling and opposition parties agree to hold monthly leaders' debates from April to June",
    summaryEn: "LDP Diet Affairs chief Kajiyama and CDP counterpart Ryu met and agreed to hold party leaders' debates once a month from April through June, setting a framework for dialogue ahead of key legislative deliberations after the budget passes.",
    tagEn: "Diet",
  },
  {
    date: "2026-04-06",
    time: "14:00",
    title: "再審法改正案、4月7日の閣議決定を見送り",
    summary: "再審制度改正法案について、検察の即時抗告を全面禁止するか制限にとどめるかで与党内の意見が割れ、政府は4月7日予定の閣議決定を見送り。自民党内からは「全面禁止を求める声がほとんど」との指摘も。今国会中の成立を目指し調整継続。",
    tag: "法案",
    tagColor: "#38a169",
    titleEn: "Retrial law reform bill: cabinet decision on April 7 postponed",
    summaryEn: "With the ruling bloc split over whether to fully ban or merely restrict prosecutors' immediate appeals, the government postponed the cabinet decision on the retrial system reform bill planned for April 7. LDP members note that most voices favor a full ban. Coordination continues with the aim of passage this Diet session.",
    tagEn: "Legislation",
  },
  {
    date: "2026-04-05",
    time: "15:00",
    title: "ホルムズ海峡で15隻が通過、商船三井LNG船も確認",
    summary: "イランの許可を得て15隻がホルムズ海峡を通過。商船三井のLNG船「ソハール」の通過も確認された。ただし湾内にはなお約2,190隻が足止め状態。",
    tag: "外交",
    tagColor: "#2b6cb0",
    titleEn: "15 vessels pass through Strait of Hormuz, including MOL LNG carrier",
    summaryEn: "Fifteen vessels passed through the Strait of Hormuz with Iran's permission, including Mitsui O.S.K. Lines' LNG carrier 'Sohar.' About 2,190 ships remain stranded in the Gulf.",
    tagEn: "Diplomacy",
  },
  {
    date: "2026-04-04",
    time: "18:00",
    title: "イラン、日本・欧州船舶のホルムズ海峡通航を初めて許可",
    summary: "イランが封鎖開始後初めて日本と欧州の関係船舶のホルムズ海峡通航を認めた。米国と距離を置く国への便宜供与で国際社会の切り崩しを図る狙いとみられる。",
    tag: "外交",
    tagColor: "#2b6cb0",
    titleEn: "Iran permits Japanese and European ships through Strait of Hormuz for first time",
    summaryEn: "For the first time since the blockade began, Iran allowed Japanese and European affiliated vessels to transit the Strait of Hormuz, apparently aiming to split the international community by extending favors to countries keeping distance from the US.",
    tagEn: "Diplomacy",
  },
  {
    date: "2026-04-04",
    time: "11:00",
    title: "セクション301調査への政府対応方針を与党に説明　USTR期限は7月24日",
    summary: "3月11日に開始された米USTRのセクション301調査（日本含む16カ国対象）について、経済産業省が与党経済対策本部で対応方針を報告。枠組み合意に基づく15%関税の維持と追加関税回避が交渉の焦点。",
    tag: "政策",
    tagColor: "#d69e2e",
    titleEn: "Government briefs ruling parties on response to Section 301 probe; USTR deadline July 24",
    summaryEn: "METI reported its response strategy to the ruling parties' economic headquarters regarding the USTR Section 301 investigation launched March 11 covering 16 countries including Japan. Talks focus on maintaining the 15% tariff under the framework agreement and avoiding additional tariffs.",
    tagEn: "Policy",
  },
  {
    date: "2026-04-04",
    time: "08:00",
    title: "高校授業料無償化改正法が施行、新学期から全国で手続き本格化",
    summary: "4月1日施行の所得制限撤廃による私立高校授業料の実質無償化。各地の高校で新学期に合わせた手続きが本格化。約300万人の高校生が対象。",
    tag: "施行",
    tagColor: "#805ad5",
    titleEn: "High school tuition-free reform enacted; procedures begin nationwide with new term",
    summaryEn: "The amendment lifting income limits and effectively making private high school tuition free took effect April 1. Schools nationwide are now processing applications for the new school year, covering roughly 3 million high school students.",
    tagEn: "Enacted",
  },
  {
    date: "2026-04-04",
    time: "14:00",
    title: "令和8年度本予算、4月11日に自然成立の見通し",
    summary: "衆議院通過から30日ルールにより、参議院の議決がなくても4月11日に本予算が自然成立する。暫定予算は4月1日〜11日をカバー。",
    tag: "予算",
    tagColor: "#e53e3e",
    titleEn: "FY2026 main budget set to pass automatically on April 11",
    summaryEn: "Under the 30-day rule from Lower House passage, the main budget will automatically take effect on April 11 even without an Upper House vote. A provisional budget covers April 1 through 11.",
    tagEn: "Budget",
  },
  {
    date: "2026-04-04",
    time: "10:30",
    title: "経済安全保障推進法改正案、衆議院内閣委で質疑開始",
    summary: "3月19日に閣議決定された改正案について、重要企業の海外活動支援やサプライチェーン保護強化をめぐる質疑が行われた。",
    tag: "法案",
    tagColor: "#38a169",
    titleEn: "Economic Security Promotion Act amendment: questioning begins in Lower House Cabinet Committee",
    summaryEn: "Questioning began on the amendment approved by the cabinet on March 19, covering overseas activity support for critical companies and strengthened supply chain protection.",
    tagEn: "Legislation",
  },
  {
    date: "2026-04-03",
    time: "18:00",
    title: "4月1日から共同親権制度がスタート、家裁に相談相次ぐ",
    summary: "改正民法が施行され、離婚後の共同親権が選択可能に。77年ぶりの大改正で、各地の家庭裁判所に問い合わせが殺到。",
    tag: "施行",
    tagColor: "#805ad5",
    titleEn: "Joint custody system begins April 1; family courts flooded with inquiries",
    summaryEn: "The amended Civil Code took effect, allowing joint custody after divorce. It is the first major revision in 77 years, and family courts nationwide have been flooded with inquiries.",
    tagEn: "Enacted",
  },
  {
    date: "2026-04-03",
    time: "11:00",
    title: "「こども誰でも通園制度」本格開始、初日から申込み多数",
    summary: "3歳未満の未就園児が保育所を利用できる新制度が4月1日にスタート。子ども・子育て支援金の徴収も同日開始。",
    tag: "施行",
    tagColor: "#805ad5",
    titleEn: "'Childcare for All' system launches with many applications on day one",
    summaryEn: "A new system allowing unenrolled children under age 3 to use daycare facilities began on April 1. Collection of the child and child-rearing support levy also started the same day.",
    tagEn: "Enacted",
  },
  {
    date: "2026-04-02",
    time: "16:00",
    title: "国家情報局設置法案、衆院内閣委で参考人質疑",
    summary: "安全保障・インテリジェンスの専門家を招き、国家情報会議の権限と国会監視のあり方について意見聴取が行われた。",
    tag: "法案",
    tagColor: "#38a169",
    titleEn: "National Intelligence Bureau bill: expert hearings held in Lower House Cabinet Committee",
    summaryEn: "Security and intelligence experts were invited to testify on the powers of the National Intelligence Council and the form of Diet oversight.",
    tagEn: "Legislation",
  },
  {
    date: "2026-04-01",
    time: "15:30",
    title: "防衛特別法人税、本日より課税開始",
    summary: "防衛財源確保法（2023年成立）に基づく法人税の付加税がスタート。防衛費GDP比2%目標の安定財源として機能する。",
    tag: "施行",
    tagColor: "#805ad5",
    titleEn: "Special defense corporate tax begins today",
    summaryEn: "A corporate tax surcharge under the Defense Funding Act (enacted 2023) took effect, serving as a stable revenue source for the goal of defense spending at 2% of GDP.",
    tagEn: "Enacted",
  },
  {
    date: "2026-04-01",
    time: "10:00",
    title: "私立高校授業料の実質無償化、公立小学校の給食費無償化がスタート",
    summary: "教育費負担軽減策として、私立高校授業料の所得制限撤廃による実質無償化と、公立小学校の給食費無償化が4月1日より施行。",
    tag: "施行",
    tagColor: "#805ad5",
    titleEn: "Private high school tuition and public elementary school lunches become effectively free",
    summaryEn: "As measures to ease the education cost burden, effective tuition-free status for private high schools via removal of income limits, and free lunches at public elementary schools, took effect April 1.",
    tagEn: "Enacted",
  },
  {
    date: "2026-03-30",
    time: "17:00",
    title: "暫定予算（8.6兆円）が参議院で可決・成立",
    summary: "衆院選による審議の遅れで年度内の本予算成立が困難となり、4月1日〜11日の11日間をカバーする暫定予算が成立。11年ぶりの暫定予算編成。",
    tag: "予算",
    tagColor: "#e53e3e",
    titleEn: "Provisional budget of 8.6 trillion yen passes Upper House",
    summaryEn: "With the Lower House election delaying deliberations and making fiscal-year passage of the main budget difficult, a provisional budget covering the 11 days from April 1 to 11 was enacted — the first such budget in 11 years.",
    tagEn: "Budget",
  },
  {
    date: "2026-03-19",
    time: "10:00",
    title: "経済安全保障推進法改正案を閣議決定、国会提出へ",
    summary: "有識者会議の提言を踏まえ、重要物資のサプライチェーン強靱化や重要企業の海外展開支援を盛り込んだ改正案を閣議決定。",
    tag: "法案",
    tagColor: "#38a169",
    titleEn: "Cabinet approves Economic Security Promotion Act amendment for Diet submission",
    summaryEn: "Based on recommendations from an expert panel, the cabinet approved an amendment including supply chain resilience for critical materials and overseas expansion support for key companies.",
    tagEn: "Legislation",
  },
  {
    date: "2026-03-13",
    time: "16:30",
    title: "令和8年度予算案が衆議院を通過、参議院へ送付",
    summary: "一般会計総額122.3兆円の予算案が衆議院本会議で可決。審議時間は約59時間と過去20年で最短。参議院での審議入りへ。",
    tag: "予算",
    tagColor: "#e53e3e",
    titleEn: "FY2026 budget bill passes Lower House, sent to Upper House",
    summaryEn: "A general-account budget totaling 122.3 trillion yen passed the Lower House plenary. Deliberations lasted about 59 hours, the shortest in 20 years. The bill now moves to Upper House debate.",
    tagEn: "Budget",
  },
  {
    date: "2026-03-13",
    time: "11:00",
    title: "国家情報会議設置法案（国家情報局新設）を閣議決定",
    summary: "内閣情報調査室を改組し「国家情報局」を新設する法案を閣議決定。首相直属の国家情報会議を設置し、7月の発足を目指す。",
    tag: "法案",
    tagColor: "#38a169",
    titleEn: "Cabinet approves bill to create National Intelligence Council and Bureau",
    summaryEn: "The cabinet approved a bill to reorganize the Cabinet Intelligence and Research Office into a new 'National Intelligence Bureau.' A National Intelligence Council directly under the prime minister will be established, targeting a July launch.",
    tagEn: "Legislation",
  },
  {
    date: "2026-03-06",
    time: "10:00",
    title: "防災庁設置法案・関連法案を閣議決定",
    summary: "内閣府防災担当を独立した「防災庁」に格上げする法案を閣議決定。2026年秋の発足を目指し、国会審議へ。",
    tag: "法案",
    tagColor: "#38a169",
    titleEn: "Cabinet approves bill to establish Disaster Management Agency",
    summaryEn: "The cabinet approved a bill elevating the Cabinet Office's disaster management section into an independent 'Disaster Management Agency,' targeting a fall 2026 launch and moving to Diet deliberations.",
    tagEn: "Legislation",
  },
];
