// 政治ニュース タイムライン
// microCMS連携後はCMSから取得に切り替え可能

export interface PoliticsNewsItem {
  date: string;
  time: string;
  title: string;
  summary: string;
  tag: string;
  tagColor: string;
  source?: string;
  titleEn?: string;
  summaryEn?: string;
  tagEn?: string;
}

export const politicsNews: PoliticsNewsItem[] = [
  {
    date: "2026-05-01",
    time: "09:00",
    title: "高市首相、ベトナム・オーストラリア訪問へ出発　経済安保・FOIP強化が目的",
    summary: "高市早苗首相は1日、ベトナムとオーストラリアを歴訪するため出国した。2日にハノイでトー・ラム書記長（国家主席）らと会談し、日・ベトナム包括的戦略パートナーシップの強化や重要鉱物・エネルギー安保での連携を確認する予定。4日にはキャンベラでアルバニージー豪首相と会談し、日豪友好協力基本条約署名50周年に合わせた経済安全保障分野の共同宣言の発出を目指す。訪問中には「自由で開かれたインド太平洋（FOIP）」の深化に向けた外交演説も行う。",
    tag: "外交",
    tagColor: "#2b6cb0",
    source: "https://www.kantei.go.jp/jp/105/statement/2026/0501kaiken.html",
    titleEn: "PM Takaichi departs for Vietnam and Australia to strengthen economic security and FOIP",
    summaryEn: "Prime Minister Takaichi departed on the 1st for a diplomatic tour of Vietnam and Australia. On the 2nd in Hanoi she is scheduled to meet General Secretary and President To Lam and other officials to reaffirm the Comprehensive Strategic Partnership and cooperation on critical minerals and energy security. On the 4th in Canberra she will meet PM Albanese and aims to issue a joint declaration on economic security to mark the 50th anniversary of the Japan-Australia Basic Treaty. She will also deliver a foreign-policy speech on deepening the Free and Open Indo-Pacific (FOIP).",
    tagEn: "Diplomacy",
  },
  {
    date: "2026-04-23",
    time: "14:00",
    title: "国家情報局設置法案、衆院本会議で可決　参院審議へ",
    summary: "衆議院は23日の本会議で、内閣情報調査室を改組して「国家情報局」を新設する「国家情報会議設置法案」を、与党・日本維新の会・中道改革連合・国民民主党などの賛成多数で可決し、参議院に送付した。前日22日には衆院内閣委員会で可決されており、付帯決議ではプライバシー保護への十分な配慮を求めた。法案は首相を議長とする「国家情報会議」と、事務局となる「国家情報局」を設置する内容で、2026年7月の発足を目指す。日本共産党は情報機関の権限拡大への懸念から反対した。",
    tag: "安全保障",
    tagColor: "#744210",
    source: "https://www.jiji.com/jc/article?k=2026042300112&g=pol",
    titleEn: "National Intelligence Agency bill passes House of Representatives; sent to Upper House",
    summaryEn: "The House of Representatives on the 23rd passed the National Intelligence Council Establishment Bill — which reorganizes the Cabinet Intelligence and Research Office into a new National Intelligence Agency — by a majority including the ruling coalition, Nippon Ishin, the Centrist Reform Coalition and the DPP, and forwarded it to the House of Councillors. The bill cleared the lower house Cabinet Committee on the 22nd, with an attached resolution calling for full privacy protection. It would create a Prime Minister-chaired National Intelligence Council and a National Intelligence Agency secretariat, targeting a July 2026 launch. The JCP voted against due to concerns over expanding intelligence powers.",
    tagEn: "Security",
  },
  {
    date: "2026-04-17",
    time: "23:00",
    title: "イラン外相、ホルムズ海峡を全商船に「完全開放」と表明　米は港湾封鎖を継続",
    summary: "イランのアラグチ外相は17日、イスラエルとレバノンの停戦発効を受け、停戦期間中はすべての商船を対象にホルムズ海峡を完全開放すると表明した。トランプ大統領は謝意を示しつつも米軍によるイラン港湾封鎖は継続すると発表した。革命防衛隊は軍事関連を除く民間船舶のみ指定航路で通航可能と主張しており、通航量が戦闘前水準に戻るかは不透明。トランプ大統領は「1〜2日以内」に再協議を示唆し、4月19〜20日のパキスタンでの米・イラン協議再開を米メディアが報じている。",
    tag: "外交",
    tagColor: "#2b6cb0",
    source: "https://www.jiji.com/jc/article?k=2026041701173&g=int",
    titleEn: "Iran FM declares Hormuz 'fully open' to all commercial ships; US maintains port blockade",
    summaryEn: "Iranian Foreign Minister Araghchi announced on April 17 that all commercial vessels would be allowed to transit the Strait of Hormuz during the ceasefire period, following a ceasefire in Lebanon. President Trump expressed appreciation but said the US military blockade of Iranian ports would continue. Iran's Revolutionary Guard stipulated only civilian ships on designated routes, leaving it unclear whether traffic would return to pre-conflict levels. Trump suggested fresh talks 'within one to two days,' with US media reporting a possible April 19-20 resumption in Pakistan.",
    tagEn: "Diplomacy",
  },
  {
    date: "2026-04-16",
    time: "16:00",
    title: "柏崎刈羽原発6号機が14年ぶりに営業運転再開　東電、福島事故後初の本格稼働",
    summary: "東京電力は16日午後4時、原子力規制委員会から使用前確認証と使用前検査合格証の交付を受け、柏崎刈羽原子力発電所6号機の営業運転を再開した。2012年3月の停止以来14年ぶり。福島第一原発事故を引き起こした東電にとって事故後初の本格的な商業運転再開となる。中東情勢に伴うエネルギー供給懸念が再稼働の背景にある。再稼働後のトラブルで当初の2月26日予定から2度延期されていた。",
    tag: "その他",
    tagColor: "#553c9a",
    source: "https://news.web.nhk/newsweb/na/na-k10015100901000",
    titleEn: "Kashiwazaki-Kariwa Unit 6 resumes commercial operation for first time in 14 years",
    summaryEn: "Tokyo Electric Power Company resumed commercial operation of Kashiwazaki-Kariwa Nuclear Power Station Unit 6 at 4:00 p.m. on April 16, following issuance of pre-operation inspection certificates by the Nuclear Regulation Authority. It is the first commercial operation since March 2012 — and the first full commercial restart at a plant owned by TEPCO since the Fukushima accident. Energy security concerns linked to Middle East tensions are part of the backdrop. Post-restart malfunctions had caused the original February 26 launch date to be pushed back twice.",
    tagEn: "Other",
  },
  {
    date: "2026-04-16",
    time: "14:00",
    title: "衆院選挙制度協議が再開　自民党、定数削減を議題に含めるよう提案",
    summary: "衆参両院の選挙制度をめぐる与野党協議が4月16日に再開された。1月の衆議院解散に伴い昨年12月以来の再開で、森衆院議長のもとで新たな協議体が設置された。自民党は公約として掲げてきた衆院議員定数10%削減について、今国会に提出する関連法案施行後1年以内に結論を出す方向で議論に含めるよう提案した。",
    tag: "国会",
    tagColor: "#2d3748",
    source: "https://www.okinawatimes.co.jp/articles/-/1818628",
    titleEn: "Lower House election system talks resume; LDP proposes including seat reduction on agenda",
    summaryEn: "Cross-party consultations on the House of Representatives election system resumed on April 16 — the first time since December, after the January House dissolution — under a new council chaired by Speaker Mori. The LDP proposed including its campaign pledge of a 10% seat reduction in deliberations, with a target of reaching a conclusion within one year of enacting related bills submitted to the current Diet.",
    tagEn: "Diet",
  },
  {
    date: "2026-04-15",
    time: "15:00",
    title: "衆院議長、皇室典範改正を今国会で成立させたい意向　衆参全13会派が協議",
    summary: "安定的な皇位継承のあり方をめぐる衆参全13党派の国会協議が15日に開催された。森英介衆院議長は「立法府としての総意を早期にまとめ、今の国会で皇室典範改正案を成立させたい」と述べた。議長は中道改革連合に1か月以内に党見解を示すよう要請した。主要2案（女性皇族の皇籍保持と旧宮家男系男子の養子縁組容認）を軸に今後も協議を継続する。",
    tag: "国会",
    tagColor: "#2d3748",
    source: "https://news.web.nhk/newsweb/na/na-k10015100391000",
    titleEn: "Speaker calls for Imperial Household Law reform this Diet session; all 13 blocs convene",
    summaryEn: "A cross-party consultative meeting on stable imperial succession was held on April 15, attended by representatives of all 13 Diet blocs. Speaker Mori Hidesuke stated his intention to 'quickly forge a legislative consensus and pass an Imperial Household Law amendment in the current Diet session.' He asked the centrist Chudo Kaikaku Rengou to compile its party position within one month. Talks will continue around the two main proposals: retaining the princess' imperial status after marriage, and permitting the adoption of male-line males from former imperial family branches.",
    tagEn: "Diet",
  },
  {
    date: "2026-04-15",
    time: "21:00",
    title: "茂木外相、イラン外相と電話会談　米との早期合意と停戦維持を要請",
    summary: "茂木敏充外務大臣は15日夜、イランのアラグチ外相と約30分間の電話会談を行い、米国とイランとの戦闘終結に向けた協議が早期に最終合意に至ることへの「強い期待」を伝えた。また、ホルムズ海峡の安定回復が急務だとして、すべての船舶の自由で安全な航行が確保されるよう改めて求めた。米・イランの軍事衝突以降、両外相の会談は4回目。",
    tag: "外交",
    tagColor: "#2b6cb0",
    source: "https://news.infoseek.co.jp/article/yomiuri_20260415_gyt1t00373/",
    titleEn: "FM Motegi calls Iranian counterpart; urges early US-Iran deal and ceasefire maintenance",
    summaryEn: "Foreign Minister Toshimitsu Motegi held a roughly 30-minute phone call with Iranian FM Araghchi on the evening of April 15, conveying Japan's 'strong expectation' that US-Iran talks toward ending hostilities would yield a final agreement soon. He reiterated Japan's call for free and safe navigation for all vessels through the Strait of Hormuz, stressing that restoring stability in the strait is urgent. The call was the fourth between the two ministers since the US-Iran military confrontation began.",
    tagEn: "Diplomacy",
  },
  {
    date: "2026-04-15",
    time: "11:00",
    title: "再審法修正案、自民党審査で再び了承見送り　検察抗告禁止めぐり党内反発",
    summary: "刑事訴訟法改正案（再審制度見直し）の政府修正案を審査する自民党の部会が15日に開かれたが、検察の抗告権を全面禁止しない方針に出席議員から激しく反発する声が相次ぎ、了承を見送った。政府案は検察抗告後の審理期間を「1年以内」に制限する等9項目の修正を盛り込んでいるが、全面禁止を求める声が多数。今国会への提出は依然として不透明な情勢が続く。",
    tag: "国会",
    tagColor: "#2d3748",
    source: "https://www.jiji.com/jc/article?k=2026041501111&g=pol",
    titleEn: "Retrial law revision again stalls at LDP review; lawmakers oppose keeping prosecution appeals",
    summaryEn: "An LDP committee that reviewed the government's revised retrial reform bill on April 15 again deferred approval, after intense pushback from members who objected to leaving intact prosecutors' right to appeal retrial decisions. The government plan includes nine revisions — including capping the court review period after a prosecution appeal at one year — but most LDP voices demand a full ban. Submission to the Diet this session remains unclear.",
    tagEn: "Diet",
  },
  {
    date: "2026-04-14",
    time: "11:00",
    title: "政府、再審法改正の修正案を自民党に提示　検察抗告後の審理期間に制限",
    summary: "政府は再審制度見直しのための刑事訴訟法改正案の修正案を自民党の司法制度調査会などに提示した。検察が再審開始決定に抗告した場合、裁判所の審理期間に制限を設けることが柱。検察抗告の全面禁止を求める自民内の反発を受けた修正だが、禁止規定は盛り込まれておらず議論は継続。今国会での提出・成立は不透明な情勢。",
    tag: "国会",
    tagColor: "#2d3748",
    titleEn: "Government presents revised retrial bill to LDP — limits on court review period after prosecution appeals",
    summaryEn: "The government presented a revised version of its criminal procedure law amendment on retrial reform to LDP committees. The bill limits the court's review period when prosecutors appeal a retrial commencement decision. The revision reflects LDP calls for stricter limits, but stops short of a full ban on prosecution appeals demanded by many LDP members. Passage this Diet session remains uncertain.",
    tagEn: "Diet",
  },
  {
    date: "2026-04-13",
    time: "23:00",
    title: "米海軍、ホルムズ海峡の「逆封鎖」を開始　交渉決裂受けトランプ大統領が表明",
    summary: "交渉決裂を受けトランプ大統領はイランの港湾へ出入りする船舶を対象とした「逆封鎖」を表明し、米東部時間13日午前10時（日本時間同日午後11時）に米海軍が封鎖を開始した。原油価格が急騰し世界経済への打撃懸念が強まった。日本では精製所稼働率が急落し、高市政権は国家石油備蓄の追加放出を検討する方針を示した。",
    tag: "外交",
    tagColor: "#2b6cb0",
    titleEn: "US Navy begins 'reverse blockade' of Hormuz following collapse of Iran talks",
    summaryEn: "Following the breakdown of peace talks, President Trump announced a US Navy blockade targeting ships entering and leaving Iranian ports. The blockade began at 10:00 a.m. EDT on April 13 (11:00 p.m. JST). Crude oil prices surged amid growing fears of a global economic shock. Japan, which refines nearly 95% of its oil from Middle Eastern imports, saw refinery utilization rates plunge; the Takaichi government indicated it would consider releasing additional strategic petroleum reserves.",
    tagEn: "Diplomacy",
  },
  {
    date: "2026-04-13",
    time: "15:00",
    title: "高市首相、政府与党連絡会議で後半国会の重要法案審議への協力を要請",
    summary: "高市総理大臣は首相官邸で政府与党連絡会議を開催し、令和8年度予算成立後の後半国会に向けて与党に重要法案の審議への協力を要請した。国家情報局設置法案・防災庁設置法案・個人情報保護法改正案など複数の重要法案が議題。7月17日の会期末に向けた審議日程の確保が喫緊の課題となっている。",
    tag: "国会",
    tagColor: "#2d3748",
    titleEn: "PM Takaichi calls on ruling parties to cooperate on key bills in second half of Diet session",
    summaryEn: "Prime Minister Takaichi convened a government–ruling party liaison conference at the PM's office, requesting coalition support for key legislation in the Diet session's second half following the FY2026 budget passage. Bills on the agenda include the National Intelligence Agency Establishment Act, the Disaster Prevention Agency bill and the Personal Information Protection Law amendment. Securing debate time before the July 17 session deadline is an urgent priority.",
    tagEn: "Diet",
  },
  {
    date: "2026-04-12",
    time: "19:00",
    title: "バンス米副大統領、21時間の交渉後に合意なしとイスラマバードを離脱",
    summary: "バンス米副大統領は21時間にわたるイランとの協議が合意に至らなかったと発表し、イスラマバードを離脱。イランが核兵器を製造しないことを含む米側の条件をイランが拒否したと説明した。イランは「一回の協議で合意できると誰も期待していなかった」と反論。停戦の行方が不透明となり、エネルギー市場に動揺が広がった。",
    tag: "外交",
    tagColor: "#2b6cb0",
    titleEn: "Vance leaves Islamabad without a deal after 21 hours of talks with Iran",
    summaryEn: "US Vice President JD Vance announced that talks with Iran had failed after 21 hours of negotiations and departed Islamabad. He said Iran refused to accept US terms, including a fundamental commitment not to develop nuclear weapons. Iran countered that no one expected an agreement in a single round of talks. The breakdown cast doubt on the ceasefire and rattled global energy markets.",
    tagEn: "Diplomacy",
  },
  {
    date: "2026-04-12",
    time: "13:00",
    title: "自民党大会で高市首相「時は来た」　改憲発議を来年党大会までにめど",
    summary: "第93回自民党大会（東京・グランドプリンスホテル新高輪）で高市首相は「自主憲法制定は立党の精神。時は来た」と述べ、来年の党大会までに憲法改正の発議にめどをつける方針を表明した。2月の衆院選での大勝を踏まえ「選挙に勝ち続ける強い党をつくる」とも強調。2026年度の運動方針に衆参両院の憲法審査会での改正原案作成を明記した。",
    tag: "内政",
    tagColor: "#702459",
    titleEn: "Takaichi declares 'the time has come' at LDP convention; targets constitutional amendment proposal by spring 2027",
    summaryEn: "At the 93rd LDP annual convention in Tokyo, Prime Minister Takaichi declared 'drafting our own constitution is the founding spirit of this party — the time has come,' and pledged to reach a prospect for proposing a constitutional amendment by the party's next convention. Citing the party's landslide Lower House election win in February, she also vowed to build 'a strong party that keeps winning elections.' The 2026 operational policy calls for constitutional amendment draft committees to be established in both chambers' Constitutional Review Commissions.",
    tagEn: "Domestic Politics",
  },
  {
    date: "2026-04-10",
    time: "10:00",
    title: "イスラマバードで米・イラン最終和平交渉が開始",
    summary: "4月8日の停戦合意に基づき、パキスタン・イスラマバードで米・イランの最終和平交渉が開始された。ホルムズ海峡の恒久開放や核協議の再開が主な議題。2週間以内の合意達成を目指す。日本はエネルギー安全保障の観点から交渉の行方を注視している。",
    tag: "外交",
    tagColor: "#2b6cb0",
    titleEn: "US–Iran final peace talks open in Islamabad",
    summaryEn: "Under the April 8 ceasefire agreement, US–Iran final peace negotiations have begun in Islamabad, Pakistan. Permanent reopening of the Strait of Hormuz and resumption of nuclear talks are the main agenda items. The parties aim for an agreement within two weeks. Japan is closely watching the negotiations from an energy-security perspective.",
    tagEn: "Diplomacy",
  },
  {
    date: "2026-04-07",
    time: "14:30",
    title: "令和8年度本予算が参院本会議で可決・成立 — 一般会計122.3兆円で過去最大",
    summary: "参院本会議で令和8年度（2026年度）当初予算が与党・日本保守党などの賛成多数で可決、成立した。一般会計総額は122兆3092億円と過去最大。防衛力整備・子育て支援・科学技術投資を重点配分。高市首相は「中小企業の稼ぐ力を抜本強化する予算」と強調。年度内成立の目標より1週間遅れての成立となった。",
    tag: "予算",
    tagColor: "#e53e3e",
    titleEn: "FY2026 budget passes Upper House — record ¥122.3 trillion general account",
    summaryEn: "The FY2026 budget bill passed the House of Councillors by a majority including the ruling coalition and the Japan Conservative Party. The general account totals a record ¥122.3 trillion, with priority spending on defence, childcare and science and technology. PM Takaichi called it a 'budget to fundamentally strengthen the earning power of small businesses.' It passed one week later than the government had targeted.",
    tagEn: "Budget",
  },
  {
    date: "2026-04-05",
    time: "23:00",
    title: "京都府知事選 現職・西脇隆俊氏が3選、投票率37.43%",
    summary: "4月5日に投開票された京都府知事選で、自民・立憲・公明・国民・中道各党が推薦する無所属現職の西脇隆俊氏（70）が3回目の当選を決めた。新人2氏を破っての3選で、投票率は37.43%（前回比0.15ポイント減）。統一地方選前半戦の先行指標として与党は「信任」と評価した。",
    tag: "選挙",
    tagColor: "#805ad5",
    titleEn: "Kyoto governor election: incumbent Nishiwaki wins third term; turnout 37.43%",
    summaryEn: "In the Kyoto prefectural governor election held on April 5, incumbent Takatoshi Nishiwaki (70), backed by the LDP, CDP, Komeito, DPP and centrist parties, won a third term, defeating two challengers. Voter turnout was 37.43%, down 0.15 points from the previous election. The ruling coalition claimed the result as an endorsement ahead of the unified local elections.",
    tagEn: "Election",
  },
  {
    date: "2026-04-08",
    time: "22:00",
    title: "米・イランが2週間の即時停戦で合意、ホルムズ海峡全面再開へ",
    summary: "トランプ大統領とイランが即時停戦に合意（パキスタンが仲介）。ホルムズ海峡の安全な通航を2週間認め、米・イスラエルの軍事作戦を停止。10日からイスラマバードで最終合意に向けた交渉開始。日経平均は翌8日に2,879円高と歴代3位の急騰を記録。",
    tag: "外交",
    tagColor: "#2b6cb0",
    titleEn: "US and Iran agree on two-week ceasefire; Strait of Hormuz to fully reopen",
    summaryEn: "President Trump and Iran reached an immediate ceasefire agreement brokered by Pakistan. Iran will allow safe transit through the Strait of Hormuz for two weeks while the US and Israel halt military operations. Negotiations toward a final agreement begin in Islamabad on April 10. The Nikkei 225 surged 2,879 yen the following day — the third-largest single-day gain on record.",
    tagEn: "Diplomacy",
  },
  {
    date: "2026-04-07",
    time: "09:00",
    title: "トランプ大統領の対イラン猶予期限が到来、今後の対応に注目",
    summary: "トランプ大統領がイランに設定した猶予期限が4月6日夜（日本時間7日午前9時）に到来。ホルムズ海峡の全面再開は実現しておらず、米国の次の対応が焦点に。",
    tag: "外交",
    tagColor: "#2b6cb0",
    titleEn: "Trump's grace period for Iran expires; next US move in focus",
    summaryEn: "The grace period President Trump set for Iran expired on the night of April 6 (9:00 a.m. JST on April 7). A full reopening of the Strait of Hormuz has not been achieved, and attention now turns to the US response.",
    tagEn: "Diplomacy",
  },
  {
    date: "2026-04-07",
    time: "11:00",
    title: "与野党、4月〜6月に月1回の党首討論実施で合意",
    summary: "自民・梶山国対委員長と立憲・笠国対委員長が会談し、4月から6月にかけて月1回の党首討論を実施することで合意。予算成立後の重要法案審議に向けた与野党対話の枠組み。",
    tag: "国会",
    tagColor: "#e53e3e",
    titleEn: "Ruling and opposition parties agree to hold monthly leaders' debates from April to June",
    summaryEn: "LDP Diet Affairs chief Kajiyama and CDP counterpart Ryu met and agreed to hold party leaders' debates once a month from April through June, setting a framework for dialogue ahead of key legislative deliberations after the budget passes.",
    tagEn: "Diet",
  },
  {
    date: "2026-04-06",
    time: "14:00",
    title: "再審法改正案、4月7日の閣議決定を見送り",
    summary: "再審制度改正法案について、検察の即時抗告を全面禁止するか制限にとどめるかで与党内の意見が割れ、政府は4月7日予定の閣議決定を見送り。自民党内からは「全面禁止を求める声がほとんど」との指摘も。今国会中の成立を目指し調整継続。",
    tag: "法案",
    tagColor: "#38a169",
    titleEn: "Retrial law reform bill: cabinet decision on April 7 postponed",
    summaryEn: "With the ruling bloc split over whether to fully ban or merely restrict prosecutors' immediate appeals, the government postponed the cabinet decision on the retrial system reform bill planned for April 7. LDP members note that most voices favor a full ban. Coordination continues with the aim of passage this Diet session.",
    tagEn: "Legislation",
  },
  {
    date: "2026-04-05",
    time: "15:00",
    title: "ホルムズ海峡で15隻が通過、商船三井LNG船も確認",
    summary: "イランの許可を得て15隻がホルムズ海峡を通過。商船三井のLNG船「ソハール」の通過も確認された。ただし湾内にはなお約2,190隻が足止め状態。",
    tag: "外交",
    tagColor: "#2b6cb0",
    titleEn: "15 vessels pass through Strait of Hormuz, including MOL LNG carrier",
    summaryEn: "Fifteen vessels passed through the Strait of Hormuz with Iran's permission, including Mitsui O.S.K. Lines' LNG carrier 'Sohar.' About 2,190 ships remain stranded in the Gulf.",
    tagEn: "Diplomacy",
  },
  {
    date: "2026-04-04",
    time: "18:00",
    title: "イラン、日本・欧州船舶のホルムズ海峡通航を初めて許可",
    summary: "イランが封鎖開始後初めて日本と欧州の関係船舶のホルムズ海峡通航を認めた。米国と距離を置く国への便宜供与で国際社会の切り崩しを図る狙いとみられる。",
    tag: "外交",
    tagColor: "#2b6cb0",
    titleEn: "Iran permits Japanese and European ships through Strait of Hormuz for first time",
    summaryEn: "For the first time since the blockade began, Iran allowed Japanese and European affiliated vessels to transit the Strait of Hormuz, apparently aiming to split the international community by extending favors to countries keeping distance from the US.",
    tagEn: "Diplomacy",
  },
  {
    date: "2026-04-04",
    time: "11:00",
    title: "セクション301調査への政府対応方針を与党に説明　USTR期限は7月24日",
    summary: "3月11日に開始された米USTRのセクション301調査（日本含む16カ国対象）について、経済産業省が与党経済対策本部で対応方針を報告。枠組み合意に基づく15%関税の維持と追加関税回避が交渉の焦点。",
    tag: "政策",
    tagColor: "#d69e2e",
    titleEn: "Government briefs ruling parties on response to Section 301 probe; USTR deadline July 24",
    summaryEn: "METI reported its response strategy to the ruling parties' economic headquarters regarding the USTR Section 301 investigation launched March 11 covering 16 countries including Japan. Talks focus on maintaining the 15% tariff under the framework agreement and avoiding additional tariffs.",
    tagEn: "Policy",
  },
  {
    date: "2026-04-04",
    time: "08:00",
    title: "高校授業料無償化改正法が施行、新学期から全国で手続き本格化",
    summary: "4月1日施行の所得制限撤廃による私立高校授業料の実質無償化。各地の高校で新学期に合わせた手続きが本格化。約300万人の高校生が対象。",
    tag: "施行",
    tagColor: "#805ad5",
    titleEn: "High school tuition-free reform enacted; procedures begin nationwide with new term",
    summaryEn: "The amendment lifting income limits and effectively making private high school tuition free took effect April 1. Schools nationwide are now processing applications for the new school year, covering roughly 3 million high school students.",
    tagEn: "Enacted",
  },
  {
    date: "2026-04-04",
    time: "14:00",
    title: "令和8年度本予算、4月11日に自然成立の見通し",
    summary: "衆議院通過から30日ルールにより、参議院の議決がなくても4月11日に本予算が自然成立する。暫定予算は4月1日〜11日をカバー。",
    tag: "予算",
    tagColor: "#e53e3e",
    titleEn: "FY2026 main budget set to pass automatically on April 11",
    summaryEn: "Under the 30-day rule from Lower House passage, the main budget will automatically take effect on April 11 even without an Upper House vote. A provisional budget covers April 1 through 11.",
    tagEn: "Budget",
  },
  {
    date: "2026-04-04",
    time: "10:30",
    title: "経済安全保障推進法改正案、衆議院内閣委で質疑開始",
    summary: "3月19日に閣議決定された改正案について、重要企業の海外活動支援やサプライチェーン保護強化をめぐる質疑が行われた。",
    tag: "法案",
    tagColor: "#38a169",
    titleEn: "Economic Security Promotion Act amendment: questioning begins in Lower House Cabinet Committee",
    summaryEn: "Questioning began on the amendment approved by the cabinet on March 19, covering overseas activity support for critical companies and strengthened supply chain protection.",
    tagEn: "Legislation",
  },
  {
    date: "2026-04-03",
    time: "18:00",
    title: "4月1日から共同親権制度がスタート、家裁に相談相次ぐ",
    summary: "改正民法が施行され、離婚後の共同親権が選択可能に。77年ぶりの大改正で、各地の家庭裁判所に問い合わせが殺到。",
    tag: "施行",
    tagColor: "#805ad5",
    titleEn: "Joint custody system begins April 1; family courts flooded with inquiries",
    summaryEn: "The amended Civil Code took effect, allowing joint custody after divorce. It is the first major revision in 77 years, and family courts nationwide have been flooded with inquiries.",
    tagEn: "Enacted",
  },
  {
    date: "2026-04-03",
    time: "11:00",
    title: "「こども誰でも通園制度」本格開始、初日から申込み多数",
    summary: "3歳未満の未就園児が保育所を利用できる新制度が4月1日にスタート。子ども・子育て支援金の徴収も同日開始。",
    tag: "施行",
    tagColor: "#805ad5",
    titleEn: "'Childcare for All' system launches with many applications on day one",
    summaryEn: "A new system allowing unenrolled children under age 3 to use daycare facilities began on April 1. Collection of the child and child-rearing support levy also started the same day.",
    tagEn: "Enacted",
  },
  {
    date: "2026-04-02",
    time: "16:00",
    title: "国家情報局設置法案、衆院内閣委で参考人質疑",
    summary: "安全保障・インテリジェンスの専門家を招き、国家情報会議の権限と国会監視のあり方について意見聴取が行われた。",
    tag: "法案",
    tagColor: "#38a169",
    titleEn: "National Intelligence Bureau bill: expert hearings held in Lower House Cabinet Committee",
    summaryEn: "Security and intelligence experts were invited to testify on the powers of the National Intelligence Council and the form of Diet oversight.",
    tagEn: "Legislation",
  },
  {
    date: "2026-04-01",
    time: "15:30",
    title: "防衛特別法人税、本日より課税開始",
    summary: "防衛財源確保法（2023年成立）に基づく法人税の付加税がスタート。防衛費GDP比2%目標の安定財源として機能する。",
    tag: "施行",
    tagColor: "#805ad5",
    titleEn: "Special defense corporate tax begins today",
    summaryEn: "A corporate tax surcharge under the Defense Funding Act (enacted 2023) took effect, serving as a stable revenue source for the goal of defense spending at 2% of GDP.",
    tagEn: "Enacted",
  },
  {
    date: "2026-04-01",
    time: "10:00",
    title: "私立高校授業料の実質無償化、公立小学校の給食費無償化がスタート",
    summary: "教育費負担軽減策として、私立高校授業料の所得制限撤廃による実質無償化と、公立小学校の給食費無償化が4月1日より施行。",
    tag: "施行",
    tagColor: "#805ad5",
    titleEn: "Private high school tuition and public elementary school lunches become effectively free",
    summaryEn: "As measures to ease the education cost burden, effective tuition-free status for private high schools via removal of income limits, and free lunches at public elementary schools, took effect April 1.",
    tagEn: "Enacted",
  },
  {
    date: "2026-03-30",
    time: "17:00",
    title: "暫定予算（8.6兆円）が参議院で可決・成立",
    summary: "衆院選による審議の遅れで年度内の本予算成立が困難となり、4月1日〜11日の11日間をカバーする暫定予算が成立。11年ぶりの暫定予算編成。",
    tag: "予算",
    tagColor: "#e53e3e",
    titleEn: "Provisional budget of 8.6 trillion yen passes Upper House",
    summaryEn: "With the Lower House election delaying deliberations and making fiscal-year passage of the main budget difficult, a provisional budget covering the 11 days from April 1 to 11 was enacted — the first such budget in 11 years.",
    tagEn: "Budget",
  },
  {
    date: "2026-03-19",
    time: "10:00",
    title: "経済安全保障推進法改正案を閣議決定、国会提出へ",
    summary: "有識者会議の提言を踏まえ、重要物資のサプライチェーン強靱化や重要企業の海外展開支援を盛り込んだ改正案を閣議決定。",
    tag: "法案",
    tagColor: "#38a169",
    titleEn: "Cabinet approves Economic Security Promotion Act amendment for Diet submission",
    summaryEn: "Based on recommendations from an expert panel, the cabinet approved an amendment including supply chain resilience for critical materials and overseas expansion support for key companies.",
    tagEn: "Legislation",
  },
  {
    date: "2026-03-13",
    time: "16:30",
    title: "令和8年度予算案が衆議院を通過、参議院へ送付",
    summary: "一般会計総額122.3兆円の予算案が衆議院本会議で可決。審議時間は約59時間と過去20年で最短。参議院での審議入りへ。",
    tag: "予算",
    tagColor: "#e53e3e",
    titleEn: "FY2026 budget bill passes Lower House, sent to Upper House",
    summaryEn: "A general-account budget totaling 122.3 trillion yen passed the Lower House plenary. Deliberations lasted about 59 hours, the shortest in 20 years. The bill now moves to Upper House debate.",
    tagEn: "Budget",
  },
  {
    date: "2026-03-13",
    time: "11:00",
    title: "国家情報会議設置法案（国家情報局新設）を閣議決定",
    summary: "内閣情報調査室を改組し「国家情報局」を新設する法案を閣議決定。首相直属の国家情報会議を設置し、7月の発足を目指す。",
    tag: "法案",
    tagColor: "#38a169",
    titleEn: "Cabinet approves bill to create National Intelligence Council and Bureau",
    summaryEn: "The cabinet approved a bill to reorganize the Cabinet Intelligence and Research Office into a new 'National Intelligence Bureau.' A National Intelligence Council directly under the prime minister will be established, targeting a July launch.",
    tagEn: "Legislation",
  },
  {
    date: "2026-03-06",
    time: "10:00",
    title: "防災庁設置法案・関連法案を閣議決定",
    summary: "内閣府防災担当を独立した「防災庁」に格上げする法案を閣議決定。2026年秋の発足を目指し、国会審議へ。",
    tag: "法案",
    tagColor: "#38a169",
    titleEn: "Cabinet approves bill to establish Disaster Management Agency",
    summaryEn: "The cabinet approved a bill elevating the Cabinet Office's disaster management section into an independent 'Disaster Management Agency,' targeting a fall 2026 launch and moving to Diet deliberations.",
    tagEn: "Legislation",
  },
];
